### PR TITLE
Tweak tests a bit

### PR DESCRIPTION
**Pull request by fingolfin**
While working on removing GAPstones (see PR #1072), I made some tweaks and improvements to various tests, mainly to speed them up. I figured we might want to merge this workindependently of the GAPstones removal. In particular, it should be uncontroversial, which the removal of GAPstones might not be.

### CODE REVIEW

**Comment by fingolfin** [comment]
On #1072, @alex-konovalov mentioned that the new `testextra` dir could be hooked up to be run by `tst/teststandard.g`. Sure, that's easy to do.

As a matter of fact, I think we should rename the subdirs `testinstall`, `teststandard` to, say, `testquick` and `testslow` or so -- to emphasize that there is *not* a 1-to-1 correspondence between them, and the "testsuites". Already now, `teststandard.g` also runs the tests from `testinstall`. And `testtravis` runs a mishmash, too.

**Comment by markuspf** [comment]
I shuld probably mention #790, which was a (failed) attempt to do what you propose.

**Comment by fingolfin** [comment]
@markuspf Thanks for that pointer! Also https://github.com/gap-system/gap/wiki/Testing-methods-and-targets. I'll see what I can do.

**Comment by ChrisJefferson** [comment]
This is all totally fine. Will merge later unless anyone raises issues.

There are obvious followups to come -- but this can be merged as is for now.

**Comment by alex-konovalov** [comment]
> On #1072, @alex-konovalov mentioned that the new testextra dir could be hooked up to be run by tst/teststandard.g. Sure, that's easy to do.

But has not been done. I will do this now. I will make a direct commit to master branch since this is not covered by Travis CI anyway.

**Comment by alex-konovalov** [comment]
Done in 6c977335a587930a42e30d353a59d682c11f519e

**Pull request merged**
