### PR TITLE
WIP: Avoid the use of NEW_TYPE_READONLY

### PR DESCRIPTION
**Pull request by stevelinton**
This PR is just one commit, which tries to improve usage of the type cache by avoiding setting NEW_TYPE_READONLY to true. Instead we pass one more argument to NEW_TYPE.

### CODE REVIEW

**Comment by fingolfin** [comment]
Hmm, anybody know why travis failed here? I don't see a reason... Also, it seems to build GMP, isn't that supposed to be disabled (perhaps the HPCGAP build system needs to be told to use the system GMP somehow?)

**Comment by markuspf** [comment]
On Sun, Mar 29, 2015 at 07:56:19AM -0700, Max Horn wrote:
> Hmm, anybody know why travis failed here? I don't see a reason... Also, it
> seems to build GMP, isn't that supposed to be disabled (perhaps the HPCGAP
> build system needs to be told to use the system GMP somehow?)
> 

It is failing because it is missing the line containing "total" in the
testlog. The tests themselves didn't produce "Diffs".

It builds GMP, because I am missing GMP=system in the call to make.hpc. I'll
fix that right away.

**Comment by fingolfin** [comment]
Note that `lib/type1.g` is not used directly, only its compiled version `src/c_type1.c` is used -- one needs to run `etc/docomp` to regenerate the latter from the former. (We definitely should do that automatically from our build system, too!).

Overall, some things this patch does are unclear to me:

* I don't understand why it doesn't lead to an error when loading GAP see my comment on `type1.g`
* With it applied, I get segfaults all the time, e.g. when doing
`Test("tst/grppc.tst");`
* The NEW_TYPE method has a new `parent` parameter -- but this parameter gets ignored when doing the initial cache lookup. So how could it possible be correct, unless `parent = fail` holds?
* We could add a check for the cache lookup which ensures `parent = fail` holds, but then, wouldn't that leave us in the exact same situation we started with?

BTW, in an unrelated note, I wonder about `ConstructExtendedType` -- nothing seems to use it, and it doesn't exist in classic GAP. Can we remove it?

**Comment by markuspf** [comment]
The testing like it is is just incredibly fragile, I do not like it at all. I am basically holding back on doing anything on it until @ChrisJefferson has updated the testing setup.

**Comment by stevelinton** [comment]
The compiled version is only used if the embedded checksums tell GAP that the GAP version hasn't changed, so for development it's OK to just work on the GAP and recompile when things stabilise. There should be a warning message in this situation I think.

This clearly needs documenting in the code, but what is going on is the following:

The problem is that a few bits of GAP misuse the type to store not only official type data (which does form part of the definition of the type  and is used in cache lookup) but also other things that don't. I haven't tried to track down where this is used, but maybe we should do that and simply eradicate it.

Anyway, when making a subtype we need to copy that extra data from the parent type.

This was being done by forcing NEW_TYPE to return a writable type, letting Subtype modify it and then making it readonly later. This meant that the type was not looked up in the cache, which is bad,

What is now done is to pass in an extra argument <parent> which if not fail contains that extra non-defining data to be copied in.

**Comment by fingolfin** [comment]
You are, of course, correct on the CRC checksum bit, so the right code is used.

But it still seems to me as if the check is reversed: It only attempts to copy the `parent` data if it is `fail`, which of course would trigger an error.

Alas, `Subtype` is only rarely used: in the GAP library, exactly once in `lib/kbsemi.gi`, specifically the `ShallowCopy` method for Knuth Bendix rewriting systems. It seems to be (ab)used to set the `IsMutable` flag. Still, this is very rare, and I am pretty sure that is not the cause of any slowdowns. 
In the package distro, it is also used by RCWA and Resclasses, for the exact same purpose (setting IsMutable). Perhaps we can get those three thing using it to use some other mechanism, and then deprecate `Subtype`?

**Comment by fingolfin** [comment]
Besides, it seems to me `Subtype` might be buggy -- it takes a READ_LOCK, but never releases it (or rather, it pretends to do so -- *after* returnining, though... ;-).

Oh, and `SupType` is already never used by anything in the GAP library or package distro.

**Comment by fingolfin** [comment]
Aha, but `SupType2` and `Subtype2` are used by `SetFilterObj` and `ResetFilterObj` and hence more often than I thought *sigh*. So, that part of my previous comments can be ignored (though we still might want to get rid of their 3-argument and varadic siblings, which are indeed rarely used).

The segfault, and the fact that the cache seems (?) to ignore the new `parent` parameter, are still there, though.

**Comment by stevelinton** [comment]
YOu are correct about cache ignoring parent, but that is what happened before. Subtype2 copies extra values from the parent type into the subtype after the subtype has been created and therefore after the cache lookup. I can only assume that these extra values are always just convenience data not do not define which type it is.

**Comment by fingolfin** [comment]
But the cache lookup returns, so with this patch, the code copying values from the parent type into the subtype is never reached. Otherwise, it would trigger an error, wouldn't it? To quote:
```
    if IS_IDENTICAL_OBJ(parent,fail) then
        for i in [ POS_FIRST_FREE_TYPE .. LEN_POSOBJ( parent ) ] do
            if IsBound( parent![i] ) and not IsBound(type[i]) then
                type[i] := parent![i];
            fi;
        od;
    fi;
```
So only if `parent = fail` do we execute this code... ?!

**Comment by alex-konovalov** [comment]
The travis test fails because the test doesn't reach the end so this is a genuine problem. For now, the way to detect it is to grep for the word "total" at the end of the log file. Apparently there are segmentation faults at `matrix.tst` and `bugfix.tst`.

**Comment by stevelinton** [comment]
Commit 596499c should have fixed the main problems. 
I've accidentally done a merge instead of a rebase though.

**Comment by stevelinton** [comment]
Replaced by #142

**Pull request closed without merging**
