### PR TITLE
lib/string.gi: add \+ method for strings which concatenates its inputs

### PR DESCRIPTION
**Pull request by fingolfin**
This is an alternative to PR #1314, which instead prints an error message.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
While I agree this is inefficient, I believe it should be merged for ease of use. There are many ways in GAP of writing inefficient code, and this is a natural thing many users want to write.

**Comment by markuspf** [comment]
I am also in favour of merging this functionality.

**Comment by alex-konovalov** [comment]
Me too. As I said elsewhere, I expect that those cases where `\+` will be used to concatenate more than two strings will mainly be used to assemble some output before displaying it. In such situation, the inefficiency will be unnoticeable, since output is relatively slow anyway.

**Comment by james-d-mitchell** [comment]
I'm also in favour of this.

**Comment by alex-konovalov** [comment]
After discussion at https://mail.gap-system.org/pipermail/gap/2017-May/000887.html I suggest to close this in favour of #1314.

**Comment by ChrisJefferson** [comment]
Closed, as #1314 was merged instead

**Pull request closed without merging**
