### PR TITLE
Shared region for OPERATIONS and WRAPPER_OPERATIONS

### PR DESCRIPTION
**Pull request by alex-konovalov**
This fixes issue #215. However, I was unable to rebuild `src/c_oper1.c` with 
```bin/current/gac -C -o src/c_oper1.c lib/oper1.g```
because  some parts of the GAP code caused an error 
```CANNOT COMPILE STATEMENT OF TNUM 80;```
@rbehrends, could you have a look, please?

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I did work on re-enabling the compiler, and it doesn't support all atomic functionality.

**Comment by ChrisJefferson** [comment]
The missing part is I'm sure 'atomic readwrite' and 'atomic readonly'. The easiest option would be to lift the two methods with 'atomic' into 'oper.g', so they don't get compiled. It probably wouldn't be that much work to add atomic to the compiler, but I'd prefer not to if I don't have to!

**Comment by rbehrends** [comment]
You can work without `atomic` by using `WRITE_LOCK()` or `READ_LOCK()` instead. Note that unlike `LOCK()`, these functions will raise an error if they can't acquire a lock. So, for example:

```
atomic readwrite OPERATIONS_REGION do
    ...
od;
```

becomes:

```
lk := WRITE_LOCK(OPERATIONS_REGION);
...
UNLOCK(lk);
```

Similarly for `atomic readonly` and `READ_LOCK()`.

**Comment by alex-konovalov** [comment]
@rbehrends Thanks, that helps! Updated the PR with the new version.

**Pull request merged**
