### PR TITLE
FIX: Maximal subgroups will work also if no tomlib available

### LINKED ISSUE #3498: Three more failures in the master branch when GAP started with `-r -A` options: it hangs forever on
Made the comment a separate issue so that one can close without closing top issue

There are also three more failures that I observe in Jenkins in the master branch when GAP started with `-r -A` options: it hangs forever on
-  `tst/teststandard/twocohom.tst`
- `tst/testextra/perfect.tst`
- testing manual examples from Chapter 47

_Originally posted by @alex-konovalov in https://github.com/gap-system/gap/issues/3496#issuecomment-501388527_

### PR DESCRIPTION
**Pull request by fingolfin**
This extracts a commit from PR #3494 by @hulpke

Fixes #3498

### CODE REVIEW

**Comment by fingolfin** [comment]
Perhaps this also fixes #3496?

**Comment by alex-konovalov** [comment]
One manual example is affected: https://travis-ci.org/gap-system/gap/jobs/545707527

**Comment by alex-konovalov** [comment]
This fix will still break `testextra`, but at least will not cause timeout and may be fixed later:
```
########> Diff in /Users/alexk/GITREPS/gap/tst/testextra/grpperm.tst:266
# Input is:
p:=List(p,x->Image(IsomorphismPermGroup(x)));
# Expected output:
[ <permutation group with 13 generators>,
  <permutation group with 13 generators>,
  <permutation group with 13 generators>,
  <permutation group with 13 generators> ]
# But found:
[ <permutation group with 13 generators>, 
  <permutation group with 13 generators>, 
  <permutation group with 13 generators>, 
  <permutation group with 13 generators> ]
########
```
Look identical, eh? The diff is in a space after the comma. Cf. the idea of comparing output up to trailing whitespaces from #697.

**Comment by fingolfin** [comment]
Are you sure that breakage in `tst/testextra/grpperm.tst:266` is caused by this PR, and not rather by some other change, and only uncovered by this PR fixing the timeout in `tst/testextra/grpperm.tst`? Because I don't see how this PR could possible cause that diff.

Those spaces at the end of the lines really should be there, so it seems more likely to me that this was already broken when the test was added in commit 97711e4ba2d6171d035b7cf52e61f1eedc8290c5 / PR #3451. I've now fixed this via another commit in this PR.

**Comment by alex-konovalov** [comment]
Thanks @fingolfin !

**Comment by alex-konovalov** [comment]
And yes, I agree with your analysis @fingolfin (hence rebase and merge is OK for this PR). When the test run out of time, `tst/testextra/grpperm.tst` was never reached at all.

**Pull request merged**
