### PR TITLE
FIX: Remove immediate methods to transfer mapping information.

### LINKED ISSUE #565: SemidirectProduct Embedding does not return the proper subgroup?
According to the manual, ````SemidirectProduct```` ````Embedding```` should return the embeddings of the normal subgroup and the complement. This is indeed the case for the following semidirect product of S_4, and the embedding does not give the whole group:
````
gap> N := Group((1,2)(3,4), (1,3)(2,4));; H := AutomorphismGroup(N);;
gap> G := SemidirectProduct(H, N);;
gap> Size(Image(Embedding(G, 2)))=Size(N);
true
gap> Size(Image(Embedding(G, 1)))=Size(H);
true
gap> Image(Embedding(G, 1))=G;
false
````
However, for the semidirect product of A_6 with its automorphism group ````Embedding```` 1 gives the whole group:
````
gap> N := AlternatingGroup(6);; H := AutomorphismGroup(N);;
gap> G := SemidirectProduct(H, N);;
gap> Size(Image(Embedding(G, 2)))=Size(N);
true
gap> Size(Image(Embedding(G, 1)))=Size(H);
false
gap> Image(Embedding(G, 1))=G;
true
````
Apparently, up to A_20, there is no problem, except for A_6.
Am I missing something trivial here or is this a bug?

### PR DESCRIPTION
**Pull request by hulpke**
These immediate methods try to transfer information from an inverse general
mapping to the original. However these inverses may not be defined on the
range (but only on the image), so doing so is invalid.

This fixes #565.

### CODE REVIEW

**Comment by fingolfin** [comment]
Huh? But shouldn't  Range(map) = Source(Inverse(map)) always hold? If not, then I'd say the inverse mapping is wrong in the first place.

(I vaguelly recall mentioning a couple months ago that I was concerned about an inverse mapping violating this -- and here we see a reason why)

**Comment by hulpke** [comment]
Not for permutation group mappings (it has been this way since 1997 or so).
I suspect action homomorphisms that are not made surjective will suffer from the same issue.

What the code implicitly uses is an `RestrictedInverseMapping` which we have not declared.

**Comment by fingolfin** [comment]
Upon consulting the manual, let me correct that: I believe we always should have `Range(map) = Source(InverseGeneralMapping(map))`, and vice-versa. See chapter 32.

**Comment by fingolfin** [comment]
Then we have a serious problem, as the mapping code is inconsistent with itself and with its documentation :/

**Comment by fingolfin** [comment]
In any case, I disagrew with the change in this pull request. *If* we decide to go that route, we should at the very least also adjust the documentation of `InverseGeneralMapping`, and possibly (though maybe later) search for other places that relay on this guarantee.

I am also somewhat concerned about other peoples code being broken by this change (in fact, I am pretty sure some of my own code will be broken by this, but will have to test).

**Comment by fingolfin** [comment]
BTW, the `InverseGeneralMapping` contains at least one incorrect statment anyway. It says: "If `map` knows to be bijective its inverse general mapping will know to be a mapping. In this case also `Inverse( map )` works." -- this is not actually true, it only works for endomaps (there are probably good reasons for that; anyway, documentation and code contradict each other here, too).

**Comment by hulpke** [comment]
Yes, the mappings code needs cleanup, both in documentation and in the code. Neither is something we can achieve just before a release.

What we therefore need is a short-term bandage that removes the bug in #565 and a longer term work on cleaning up the homomorphisms code.

My favorite way to this second goal would be to separate the homomorphism *mechanism* (how it computes images) from its declaration (what source and range are). This would also make it easier to deal with restrictions and corestrictions.

If there is interest I'd be willing to propose a rough description of the commands I envision we will need for such a change.

**Comment by fingolfin** [comment]
I am quite interested in such a proposal / description. Separating the mechanism from source/range considerations though interesting.

My concern with merging this change as a band-aid now is that we'd then have to be super-careful about merging stable into master, else we introduce this into master, too. And in the meantime, master and stable have diverging behavior.

OTOH, if this bug has been around for 16 years, as it sounds, it may not be that urgent to get it fixed now -- it might be sufficient to document it for now, warning users about it in the release notes, and informing them that proper fix is coming up?

**Comment by hulpke** [comment]
@fingolfin 

I will try to write up a draft of how I would change group homomorphisms.

Concerning the bug at hand, let me add a bit more detail: While it happens with an automorphism group it already happens in the "nice" permutation image, it has nothing to do with nice monomorphism.
It is triggered by a homomorphism being constructed as `GroupHomomorphismByImages' (without NC), the test for `IsMapping' constructs the inverse map (for permutation groups this test is to check the cokernel of the inverse map) only on the image (which is not proper with the definition but was the natural thing to do in the permutation context). As this inverse is total, the immediate method translates that the original is surjective.

All of the relevant code is from the '90s. I wonder whether the recent changes for homomorphisms uncovered it, so I would not just push it aside as rare.

What can we do:

a) Nothing. Not good, as the wrong 'onto' implication can have other consequences.

b) Document. I can't see how, unless we want to disclaim correctnes.ss of 'surjective' and related operations for anything that might touch permutation groups.

c) Work around the known issues for the moment. My change is to only remove (or if someone wants: Disable) immediate methods that are only there for convenience implications (The rule for immediate methods is that code must run correctly, though maybe slower, even without them).
If it propagates in the master it is harmless.
Admittedly this is not guarantee to fix all ramifications, but it would allow us to release a version in which all known bugs are fixed.

d) Delay the release and try to fix it more generally. This will take longer and could accidentally impact the performance of permutation group homomorphisms. It will not address the underlying issues with restrictions.

**Comment by fingolfin** [comment]
Note that the bug in #565  already existed in GAP 4.4.12 and 4.5.3. 

So, while I agree this is not good, I don't think it's something new. Hence, while it definitely should be fixed, I don't think it's that urgent -- it waited already for at least a 8 years (4.4.12 is from December 2008).

That said, what you say about immediate methods of course has merit. I'd still feel marginally bettter about this if instead of removing the immediate methods, we'd comment them out, and added a comment before them which points to this pull request as explanantion why the code is commented out.

**Comment by hulpke** [comment]
If it already was in 4.4 I can live with leaving it alone, as long as I don't have to write a description of known bugs in the release.

I'd also be happy with commenting the immediate methods out instead. Should I do this change?

**Comment by fingolfin** [comment]
@hulpke If removing / commenting the homs out does indeed workaround the bug, and since we are reasonably hopeful that it won't introduce regressions: Sure, if you can spare the time, that is.

**Comment by hulpke** [comment]
I've replaced the removal with a commenting-out and added explanation. also added a test to bugfix.

**Comment by alex-konovalov** [comment]
Is this PR supposed to go to GAP 4.8.2? In this case, I recommend to set a milestone so we will keep it in mind while planning the release. There is already a milestone for GAP 4.8.3, if this needs more testing.

**Comment by hulpke** [comment]
My intention was for this to go into 4.8.2, but as this might be a controversial change I should not be the one who decides on it.

**Pull request merged**
