### PR TITLE
Display git hash

### LINKED ISSUE #229: Git-SHA in GAP banner
It would be nice to have the short Git-SHA displayed in the banner.

### PR DESCRIPTION
**Pull request by markuspf**
This Closes #229

### CODE REVIEW

**Comment by alex-konovalov** [comment]
I should be able to adjust release wrapping tools to replace
```
KERNEL_INFO().KERNEL_SHA,
```
by the hardcoded string. But is is true that `mkshaheader.sh` is going to be also called when GAP is installed from the source code archive and no revision history is present?

**Comment by markuspf** [comment]
At the moment the GAP_SHA will just be empty then.

It's a bit silly though, because the source code archive is hopefully also made from a well-defined git SHA, and should contain that SHA as well. I'll have to think about this.

**Comment by alex-konovalov** [comment]
Empty GAP_SHA  should be fine then. Of course, the source code distro is made from a particular revision, and it is documented in the release wrapping logs. I can update https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/updateversioninfo script to find it and replace `KERNEL_INFO().KERNEL_SHA` with the exact value.

**Comment by markuspf** [comment]
I *really* don't like this replacing text in (source) files.

I think what we should do is make some way to ship the source distribution so that `mkshaheader.sh` produces the header that just contains the SHA of the commit that was used for the release.
If there's a way to know that we are configuring a source release, we can just execute a different script, otherwise I'd prefer the `mkshaheader.sh` script to be replaced in source distributions.

**Comment by alex-konovalov** [comment]
Fine - we know when we are wrapping a source release, and can add additional steps to that - for example, to replace `mkshaheader.sh`.

**Comment by hulpke** [comment]
The code seems fine, but it is not clear to me why this should be printed in the banner and not simply be made available as part of GAPInfo?

**Comment by markuspf** [comment]
@hulpke The idea was that when one is developing and starting GAP one can see right away which commit the current binary was build from. This helps debugging.

One can also detect mismatches between the binary's SHA and the currently checked out SHA.

The info is available as part of GAPInfo.KernelInfo too.

**Comment by rbehrends** [comment]
This does not seem to work when compiling from a tarball?

**Comment by alex-konovalov** [comment]
@rbehrends Do you mean the archive when one clicks on the "Download ZIP" link on GitHub?

**Comment by markuspf** [comment]
I made mkshaheader work when building outside of the git repository. This is still not ideal since at the moment the SHA will be set to "none", and we should really be putting the tag and SHA of the version that the archive was made from somewhere.

I think we should be putting a file somewhere, or set an environment variable that contains this information that mkshaheader.sh can use.

**Comment by alex-konovalov** [comment]
Do we want a warning when the binary's SHA differs from the currently checked out? Of course, there is no need to rebuild the binary if no kernel files were changed, so it is up to a developer whether to ignore the warning or not. 

OTOH, switching branches would almost certainly require to rebuild the binary. Will it make sense to also track the branch name in addition to SHA? Branch names are usually more readable than SHA hashes, so this will make the banner more understandable - if I will see the wrong branch in the banner, I will figure that out immediately without looking at SHA.

**Comment by markuspf** [comment]
This addresses #230 in the sense that the information displayed in the banner is not bogus anymore. There is still some code that checks that the versions of the library and the kernel binary coincide which have to be fixed before all `"4.dev"` instances can be removed.

**Pull request merged**
