### PR TITLE
Merge First with FirstOp, Filtered with FilteredOp, etc.

### PR DESCRIPTION
**Pull request by fingolfin**
This pull request deals with `First`, `Number`, `ForAll`, `ForAny`, `Filtered` and their undocumented "Op" variants `FirstOp` and so on. To keep things simple, I'll just refer to `First` from now on.

Previously, `First` was a global function, which checked if its first argument had the TNUM of an internal list, and if yes, applied certain code to it; if not, it delegated to the `FirstOp` operation. This setup was introduced by Thomas Breuer in March 1998 (the commit also dealt with `Sum`, `Product`, and `List`, but I do not). No reason was given, but I assume it was to speed up things.

Fast forward today. For the datastructure package, we'd like to use `First` in a single-argument version, so I looked into turning `First` into an operation. This lead to me discovering the situation I just described. Curious, I tested what happend if I merged `First` and `FirstOp`. I wanted to know how much slower it really made things.

To my surprise, the change made no difference. Moreover, when I applied a similar change to `Number`, things actually got _faster_, at least in the micro benchmark I used! This lead to a lot more research and testing... I discovered the following:
- the method dispatch creates no measurable overhead. Or perhaps it is measurable with a far more elaborate setup, but for me it was basically drowned out in the noise generated by garbage collection and other outside factors
- the following two loops seemingly do the same thing, but in reality, they (a) do not and (b) perform quite differently, depending on the input:

```
# Loop 1
for x in C do
  ...
od;
# Loop 2
for i in [1..Length(C)] do
  x := C[i];
  ...
od;
```

But these are not at all equivalent. For starters, loop 2 only works correctly for dense lists, but let's ignore that for the moment. But in reality, the first loop actually corresponds more closely to this (as is explained in the manual entry for the `for` loop):

```
# Loop 3
i := 1;
while i <= Length(C) do
  x := C[i];
  i := i + 1;
  ...
od;
```

Now, for internal lists (such as plists, blists, ranges, strings), loop 1 is always the fastest. But for non-internal lists (such as 8-bit compressed vectors), the second loop is faster -- because it does not constantly recompute the list length. While doing that is fast, if you have millions of iterations, the overhead adds up. (The explicit loop 3 is always slowest, by the way).

On the other hand, for non-dense loops, loop 1 is always fastest, since adding calls to `IsBound` to loop 2 slows it down tremendously. This leads to the bizarre situation that for optimal performance, one wants to use loop 1 for the generic case, but not for dense lists, _except_ those dense lists also are internal... :). This PR does just that, which means that despite the simpler structure of the code, it actually is a little bit faster in many cases. I performed quite some benchmarking, and will attach some results as well as my benchmark code (yay, to GitHub for introducing that feature today :-). The test took varous short (ca 5 element) and longer (ca 5*1024 elements) lists, and applied the relevant functions / operations, once with `ReturnFalse` and once with `ReturnTrue`. Well, not just once, many times; then repeated this, and compute the avarages of the runs (it even prints the standard deviation ;-). All times are in milliseconds.
- Before: [filtered-bench-res-master.txt](https://github.com/gap-system/gap/files/3010/filtered-bench-res-master.txt)
- After: [filtered-bench-res-first-last.txt](https://github.com/gap-system/gap/files/3011/filtered-bench-res-first-last.txt)
- Here is the code to generate those numbers: [filtered-bench.g.txt](https://github.com/gap-system/gap/files/3012/filtered-bench.g.txt)

To ensure backwards compatibility, I made `FirstOp` a synonym of `First`, etc. This ensures that the packages `cvec`, `fr` and `resclasses` keep working, as they install some methods for the "Op" variants (these were the only packages I could find doing so).

Finally, the fact that loop 1 corresponds to loop 3, but not to loop 2, means that strictly speaking the different methods have slightly different semantics. Consider this code snippet:

```
list := ... some list, internal or external ...;
Number( list,  function(x)  Add(list, x); return true; end);
```

If `list` is a dense non-internal list, or if it is empty, this returns the length of `list`; otherwise, it runs into an endless loop.

But this is existing behavior, so I don't feel bad about it. And anyway, if a user does something like this, it's their own fault... ;-). But perhaps we should document that `First` and friends assume that the list is not modified while they run.

### CODE REVIEW

**Comment by frankluebeck** [comment]
Just a quick note. Of course, there is a reason why First, ForAll, and quite a few siblings are functions and no operations. And this should not be changed currently. The last case I remember was that we have changed 'Reversed' from an operation to a function.
 
The problem is that when you call an operation then GAP wants to know the type of all arguments. 
When such an argument is a long nested (internal) list, then computing its type can be very expensive and lead to severe performance problems  (unfortunately, lists do not store their type and part of the type (like homogeneity) can only be determined by traversing the whole data structure). 

It is a long standing plan to change this setup somehow such that the type of lists becomes cheap to compute (or is somehow stored). But as long as this is not done, the functions discussed in this proposal should stay functions which delegate to the corresponding operations for non-internal lists and other data structures. This way  the (irrelevant) type computations of internal lists are bypassed.

**Comment by stevelinton** [comment]
Just to expand slightly, the problem with lists is in the case of long list containing mutable objects. In that case since the list has no way of being alerted when one of its (recursive) entries is mutated, it cannot remember very much about its type. So when any Operation is called on it, it has to decide its type, for which purpose it needs to traverse the list (and recursively any other lists with mutable subobjects). This is linear-time, but still expensive compared to just looking up a type.

To get out of this we have to do one of two things, neither of them easy:

1. Set up some kind of notification mechanism, so that the list can provisionally remember its type, and be notified when any subobject mutates so that it can adjust or forget the type. This is fiddly low-level code that risks slowing down all object access.

2. Redefine the promises about what type information will be available for lists, so that method selection can be done without traversing the list (so the list will have some very weak type). This will involve installing a lot of methods for such untraversed lists all over the library. 

2 is probably the better solution, especially now we have vector objects which should be prefered for one use case of plain lists anyway, but it's a lot of work.

**Comment by fingolfin** [comment]
@frankluebeck @stevelinton Thanks a lot for the explanation, that makes a lot of sense.

So it seems to be a major project to "fix" (or rather: improve) this. I guess I should then make a simple PR, where I just change the function "First" to also accept a single argument, and delegate to FirstOp in that situation, too. I guess I can also try to get some of the speed improvements backported, too.

I'll leave this PR open for a bit, to remind me of the above.

**Comment by fingolfin** [comment]
Note to self: That future PR should also a comment (or multiple) explaining the issue

**Pull request closed without merging**
