### PR TITLE
Library: Fix iterator printing

### PR DESCRIPTION
**Pull request by markuspf**
* The description function should only be used if the iterator is
  in IsIteratorByFunctions
* As pointed out by @stevelinton in his comments on #114 for
  IsIterator it is not possible to know whether the iterator is
  even a component object

### CODE REVIEW

**Comment by fingolfin** [comment]
So this would only work for iterators that have a `description` component? Do any existing iterators have that right now?

In that case, what's the plan with this? Are you also adding descriptions for existing iterator implementations?

And: If we add this, shouldn't there be documentation going along with it? (I am always worried about adding such things undocumented -- there are tons of abandonded, rarely-to-never used things in the GAP library which were once added with good intentions, and now just rot :/).

**Comment by markuspf** [comment]
I added documentation, and will go over the library to add the description function, or at least a string that is more descriptive than `<iterator>`.

**Comment by markuspf** [comment]
As another justification and aside: Enumerators have a PrintObj component. I will have a look at how to make this a bit more uniform.

**Comment by markuspf** [comment]
See #212

**Pull request closed without merging**
