### PR TITLE
GHBI: verify that image of a map is contained in its range (version AH)

### PR DESCRIPTION
**Pull request by hulpke**
This is a pull request, based on stable-4.8 that contains #401 and adds commands that make testinstall.g run on assertion level 2 without infinite recursion problems.

The same changes also need to go into master, though this is probably beyond my skills

### CODE REVIEW

**Comment by fingolfin** [comment]
Thanks! Will take a second look at it tomorrow, and then w can merge it.

Once that is done, we'll also merge it into master -- but that's then actually quite easy, we'll just do this:
```
git checkout master
git merge stable-4.8
```
:-).

**Comment by hulpke** [comment]
testbugfix found a number of similar further issues, Travis integration now works. 
test standard did not terminate overnight, I'll investigate.

**Comment by fingolfin** [comment]
I will also run the standard tests now.

**Comment by fingolfin** [comment]
It seems grplatt.tst is hanging? Or at least it takes a looong time for. To find out where, I did this:
```
gap> Test("tst/teststandard/grplatt.tst", rec(showProgress:=true));
# line 12, input:
START_TEST("grplatt.tst");
# line 13, input:
g:=PerfectGroup(IsPermGroup,95040);;
# line 14, input:
l:=ConjugacyClassesSubgroups(g);;
# line 15, input:
li:=List(l,i->[Size(Representative(i)),Size(i)]);;
# line 16, input:
Sort(li);
# line 17, input:
Length(li);
# line 19, input:
Print(List(li,i->i),"\n");
# line 49, input:
LatticeSubgroups(Group((1,2,3,4,5,6)));;
# line 50, input:
g:=WreathProduct(g,TransitiveGroup(6,13));;
# line 51, input:
l:=MaximalSubgroupClassReps(g);;
```
And there it hangs. But if I do the relevant computation manually, it seems to work:
```
gap> g:=WreathProduct(g,TransitiveGroup(6,13));;
gap> g:=PerfectGroup(IsPermGroup,95040);;
gap> g:=WreathProduct(g,TransitiveGroup(6,13));;
gap> l:=MaximalSubgroupClassReps(g);; time;
21317
```
I notice that it causes atlasrep and tomlib to be loaded if not present. Perhaps this is related

**Comment by fingolfin** [comment]
Weird. If I run the test "by hand", it works:
```
gap> g:=PerfectGroup(IsPermGroup,95040);;
gap> l:=ConjugacyClassesSubgroups(g);;
───────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  AtlasRep 1.5.0 (An Atlas of Group Representations)
by Robert A. Wilson (http://www.maths.qmw.ac.uk/~raw),
   Richard A. Parker (richpark@gmx.co.uk),
   Simon Nickerson (http://web.mat.bham.ac.uk/S.Nickerson),
   John N. Bray (http://www.maths.qmw.ac.uk/~jnb), and
   Thomas Breuer (http://www.math.rwth-aachen.de/~Thomas.Breuer).
Homepage: http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep
───────────────────────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  CTblLib 1.2.2 (The GAP Character Table Library)
by Thomas Breuer (http://www.math.rwth-aachen.de/~Thomas.Breuer).
Homepage: http://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib
───────────────────────────────────────────────────────────────────────────────────────────────────────────
+-----------------------------------+
| SpinSym 1.5 (The SpinSym Package) |
| Try '?SpinSym package' for help.  |
+-----------------------------------+
───────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  TomLib 1.2.5 (The GAP Library of Tables of Marks)
by Götz Pfeiffer (goetz.pfeiffer@nuigalway.ie).
Homepage: http://schmidt.nuigalway.ie/tomlib
───────────────────────────────────────────────────────────────────────────────────────────────────────────
gap> li:=List(l,i->[Size(Representative(i)),Size(i)]);;
gap> Sort(li);
gap> Length(li);
147
gap> Print(List(li,i->i),"\n");
[ [ 1, 1 ], [ 2, 396 ], [ 2, 495 ], [ 3, 880 ], [ 3, 1320 ], [ 4, 495 ], [ 4, 1320 ], [ 4, 1485 ],
  [ 4, 1485 ], [ 4, 1980 ], [ 4, 2970 ], [ 5, 2376 ], [ 6, 1320 ], [ 6, 2640 ], [ 6, 2640 ], [ 6, 3960 ],
  [ 6, 3960 ], [ 6, 7920 ], [ 8, 495 ], [ 8, 495 ], [ 8, 495 ], [ 8, 495 ], [ 8, 990 ], [ 8, 1485 ],
  [ 8, 1485 ], [ 8, 1485 ], [ 8, 2970 ], [ 8, 2970 ], [ 8, 2970 ], [ 8, 2970 ], [ 8, 2970 ], [ 8, 2970 ],
  [ 8, 2970 ], [ 9, 220 ], [ 9, 220 ], [ 9, 1760 ], [ 10, 2376 ], [ 10, 2376 ], [ 10, 2376 ], [ 11, 1728 ],
  [ 12, 1320 ], [ 12, 1320 ], [ 12, 1980 ], [ 12, 1980 ], [ 12, 2640 ], [ 12, 3960 ], [ 12, 3960 ],
  [ 12, 7920 ], [ 16, 495 ], [ 16, 1485 ], [ 16, 1485 ], [ 16, 1485 ], [ 16, 1485 ], [ 16, 1485 ],
  [ 16, 1485 ], [ 16, 2970 ], [ 16, 2970 ], [ 16, 2970 ], [ 16, 2970 ], [ 16, 2970 ], [ 18, 220 ],
  [ 18, 220 ], [ 18, 2640 ], [ 18, 2640 ], [ 18, 5280 ], [ 20, 2376 ], [ 20, 2376 ], [ 20, 2376 ],
  [ 24, 1320 ], [ 24, 1980 ], [ 24, 1980 ], [ 24, 1980 ], [ 24, 1980 ], [ 24, 1980 ], [ 24, 1980 ],
  [ 24, 1980 ], [ 24, 1980 ], [ 24, 3960 ], [ 27, 880 ], [ 32, 495 ], [ 32, 495 ], [ 32, 1485 ],
  [ 32, 1485 ], [ 32, 1485 ], [ 32, 1485 ], [ 32, 1485 ], [ 36, 660 ], [ 36, 660 ], [ 36, 1320 ],
  [ 36, 1320 ], [ 36, 1320 ], [ 40, 2376 ], [ 48, 495 ], [ 48, 1980 ], [ 48, 1980 ], [ 48, 1980 ],
  [ 48, 1980 ], [ 54, 880 ], [ 54, 880 ], [ 54, 880 ], [ 55, 1728 ], [ 60, 396 ], [ 60, 792 ], [ 60, 792 ],
  [ 60, 1584 ], [ 64, 1485 ], [ 72, 220 ], [ 72, 220 ], [ 72, 660 ], [ 72, 660 ], [ 72, 660 ], [ 72, 660 ],
  [ 72, 1320 ], [ 96, 495 ], [ 96, 495 ], [ 96, 495 ], [ 96, 495 ], [ 108, 880 ], [ 120, 396 ],
  [ 120, 396 ], [ 120, 396 ], [ 120, 792 ], [ 120, 792 ], [ 144, 660 ], [ 144, 660 ], [ 192, 495 ],
  [ 192, 495 ], [ 216, 220 ], [ 216, 220 ], [ 240, 396 ], [ 360, 66 ], [ 360, 66 ], [ 432, 220 ],
  [ 432, 220 ], [ 660, 144 ], [ 660, 144 ], [ 720, 66 ], [ 720, 66 ], [ 720, 66 ], [ 720, 66 ],
  [ 720, 66 ], [ 720, 66 ], [ 1440, 66 ], [ 1440, 66 ], [ 7920, 12 ], [ 7920, 12 ], [ 95040, 1 ] ]
gap> LatticeSubgroups(Group((1,2,3,4,5,6)));;
gap> g:=WreathProduct(g,TransitiveGroup(6,13));;
gap> l:=MaximalSubgroupClassReps(g);;
gap> time;
23466
```

If I load it via `Test` (as described in previous comment), it seems to hang forever. In the same GAP session.  I can even alternate between them: Run the test, then abort it after some minutes (w/o quitting GAP), then run the test sequence manually, and it works; run `Test` again and it hangs; etc.

Huh?!?

**Comment by hulpke** [comment]
When you run by hand, is the assertion level set to 2?

Alexander

**Comment by fingolfin** [comment]
Aaahhh, good point, I forgot about that. With the assertion level set to 2, my manual computation also takes forever.

Perhaps the assertions take an exorbitant amount of time to verify homomorphism properties? Here is a backtrace, obtained with Ctrl-C ;-)
```
ImageSiftedBaseImage( stb, OnTuples( iter!.bimg, stb.labels[k] ), iter!.img * stb.labelimages[k], OnRight
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ghomperm.gi:142 called from
sch <> One( sch ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ghomperm.gi:980 called from
IsMapping( hom ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ghom.gi:447 called from
GroupHomomorphismByImagesNC( G, h, GeneratorsOfGroup( G ), List( GeneratorsOfGroup( G ), function ( i )
        return ();
    end ) ) at /Users/mhorn/Projekte/GAP/gap.github/lib/factgrp.gi:1283 called from
oper( Parent( D ), D ) at /Users/mhorn/Projekte/GAP/gap.github/lib/domain.gd:449 called from
attr( sub ) at /Users/mhorn/Projekte/GAP/gap.github/lib/domain.gd:437 called from
NaturalHomomorphismByNormalSubgroupNCOrig( G, N
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ghom.gd:339 called from
NaturalHomomorphismByNormalSubgroupNC( G, DerivedSubgroup( G )
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grp.gi:638 called from
MaximalAbelianQuotient( G ) at /Users/mhorn/Projekte/GAP/gap.github/lib/factgrp.gi:726 called from
SmallerDegreePermutationRepresentation( H
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grpfp.gi:4029 called from
IsomorphismPermGroupOrFailFpGroup( gp ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grpfp.gi:218 called from
FPFaithHom( fam ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grpfp.gi:250 called from
FpElmEqualityMethod( FamilyObj( left )
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grpfp.gi:165 called from
sch <> One( sch ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ghomperm.gi:980 called from
IsMapping( hom ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ghom.gi:447 called from
GroupHomomorphismByImagesNC( f, fp, fgens, GeneratorsOfGroup( fp )
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/gpfpiso.gi:335 called from
IsomorphismFpGroupByChiefSeriesFactor( M, "x", N
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grplatt.gi:2046 called from
NormalSubgroups( PerfectResiduum( G )
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grplatt.gi:2216 called from
Socle( q ) at /Users/mhorn/Projekte/GAP/gap.github/lib/maxsub.gi:795 called from
<function "DoMaxesTF">( <arguments> )
 called from read-eval loop at line 1 of *errin*
brk>
```

Ah, my dreaded frenemy `SmallerDegreePermutationRepresentation` shows up... :)

**Comment by fingolfin** [comment]
We also see that at least two recursive `IsMapping` calls occur. Bingo... Hm, so what do w do about that? Should we simply set the assertion level used by the new checks to 3?

**Comment by hulpke** [comment]
I think the second `IsMapping` is actually a different map than the first one. What is happening is that the maximal subgroup (or for that matter subgroup lattice) computations construct homomorphisms onto finitely presented factor groups (which will be used for complement calculations). Is these homomorphisms are checked by assertions, GAP tries to construct faithful permutation representations for the (sometimes quite large) factor groups, and these again undergo the assertion testing.

This is similar to the issues before, and I have resolved it in the same way by adding :noassert comments that have only the effect to not do the assertion testings for the homomorphisms constructed within.

With these changes `grplatt.tst` runs in decent time.

There seems to be a similar issue in `gripper.tst` -- I investigate.

**Comment by hulpke** [comment]
Now `teststandard.g` also completes without errors or infinite delay.

**Comment by fingolfin** [comment]
Thanks. Regarding `SmallerDegreePermutationRepresentation`: I know the reasoning, but for every case where it is beneficial, I run into a case where it hurts me. E.g. just two days ago, we discovered a computatio running for minutes -- once we passed `cheap`, to turn of `SmallerDegreePermutationRepresentation`, it complete in under 5 seconds. So sometimes it helps, sometimes it hurts...

Which is why I refer to it as my "frenemy" ;-).

**Comment by fingolfin** [comment]
Anyway: I think this is basically ready for merging, thank you!

Though perhaps you want to run one last interactive rebase, to fix minor cosmetic issues with the commit messages? (typos "honmomorphism", "peroperty"; and the first line of the penultimate commit is a bit too long; shortening "Do not assertion test homomorphism ..." to "Do not test homomorphism..." would resolve that (and IMHO be nicer anyway).

If you don't want to do that, we'll just merge it as-is.

**Comment by hulpke** [comment]
@fingolfin I did a rebase -i, edited typos (I want to keep ``assertion test'' in, as it is not the regular test)  and pushed (--force) the branch. Two similar commits were unified into one -- thus one commit less.
Tests ran again. I think its ready now.

**Comment by fingolfin** [comment]
Beautiful. Thank you *very much* for all your efforts, I appreciate it a lot.

**Comment by hulpke** [comment]
@fingolfin Thank you very much. What about getting the changes into the master branch? Do we simply wait for the merge of `stable-4.8', or should there be a separate pull request?

**Comment by fingolfin** [comment]
I just performed that merge, so master should be fine now, too.

**Pull request merged**
