### PR TITLE
fix a regression in `Test`

### LINKED ISSUE #5552: strange behaviour of `Test` in the master branch
Consider the following two test files.

**file test1.tst**
```
gap> SizeScreen( [ 72 ] );;
gap> START_TEST("test1.tst");;
gap> SizeScreen()[1];
72
gap> true;  # a test that passes
true
gap> SizeScreen()[1];
72
gap> STOP_TEST("test1.tst");;
```

**file test2.tst**
```
gap> SizeScreen( [ 72 ] );;
gap> START_TEST( "test2.tst" );;
gap> SizeScreen()[1];
72
gap> true;  # a test that fails
false
gap> SizeScreen()[1];
72
gap> STOP_TEST( "test2.tst" );;
```

In GAP 4.12.2, we get the following.
```
gap> Test("test1.tst");
test1.tst                           
msecs: 0
true
gap> Test("test2.tst");
########> Diff in test2.tst:5       
# Input is:
true;  # a test that fails
# Expected output:
false
# But found:
true
########
test2.tst
msecs: 0
false
```
This is fine: No error is reported for `test1.tst`, and the failing test is reported for `test2.tst`.

The current master branch behaves differently:
```
gap> Test("test1.tst");
test1.tst                           
msecs: 0
true                                
gap> Test("test2.tst");
########> Diff in test2.tst:5       
# Input is:
true;  # a test that fails
# Expected output:
false
# But found:
true
########
########> Diff in test2.tst:7       
# Input is:
SizeScreen()[1];
# Expected output:
72
# But found:
80
########
test2.tst                           
msecs: 1
false
```

Here the failure in `test2.tst` is reported, which is good.
However, afterwards the line length has apparently been set to 80. Why?

Note that the effect is that after this first failed test, failures will be reported for all outputs that depend on the line length, no matter whether these outputs are correct (w.r.t. the intended line length) or not.

I think the behaviour in GAP 4.12.2 was better.

### PR DESCRIPTION
**Pull request by ThomasBreuer**
After reporting a difference,
reset the line length to the previous value not to the default value.

resolves #5552

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Fine by me. Would be good if @ChrisJefferson had another look, though.

**Comment by fingolfin** [comment]
Actually there is also PR #5549 which seems to be about the same issues, more or less, but a bit differently. (I asked @ChrisJefferson to review that, too, some time ago...). It would be good if you three (@ThomasBreuer @zickgraf @ChrisJefferson could figure out which way to go...)

**Comment by ThomasBreuer** [comment]
Thanks @fingolfin .
As far as I see, #5549 and #5553 do the same:
- There is a linelength before the tests, after the tests, and while printing differences. It is called `size` in #5549 and `startsize` in #5553.
- There is a linelength during the tests.  It is called `current_size` in #5549 and `size` in #5553.
- There is a default linelength that is set at the beginning of the tests. It is called `testsize` in both cases. (This variable is used only once, we could also get rid of it.)

**Comment by zickgraf** [comment]
I also think that both PRs do the same. Since I was not fully convinced by the variable name `current_size` I used in #5549, I'm totally fine with using #5553 :-)

**Comment by ThomasBreuer** [comment]
Thanks @zickgraf.
I have now added a commit to remove the unnecessary local variable `testsize`; all we need is to set the linelength once before starting the tests, and later to switch between the linelengths outside the tests and inside the tests.
@ChrisJefferson ?

**Comment by ChrisJefferson** [comment]
Looks good to me, I'll just let the tests all cycle, then I'm happy to merge (or someone else can hit the button before me)

**Review by ChrisJefferson — APPROVED** [review]

**Pull request merged**
