### PR TITLE
WIP clean dev/ directory

### PR DESCRIPTION
**Pull request by markuspf**
This is an attempt at getting rid of various files which look out of date or not necessary.
Also I will try moving some files to more appropriate locations.

Some of the files that I do remove in this pull-request contain information that I think is quite valuable, so I will try to consolidate it in some appropriate way, for example in documentation.

Please comment on any objections or suggestions, and don't merge before there is a go from me, and no major objections.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
These seems reasonable to me!

**Comment by alex-konovalov** [comment]
Fine with me for all 11 files with various historical notes. What about timers.g by @stevelinton - this is the code listed at [GAP Language Routines](http://www.gap-system.org/Packages/Contrib/contrib.html) on the GAP website.

**Comment by alex-konovalov** [comment]
Regarding further cleanup in this directory - I will take care of `wininst` and `hudson` subdirectories, and also of `dist45`and `PackageAdmin` from `DistributionUpdate/`. `rsyncserv` is maintained by @frankluebeck. Furthermore, `LinksOfAllHelpSections` is needed for GAP website maintenance.

**Comment by alex-konovalov** [comment]
I am now happy for the following subdirectories of `dev` to be deleted as well: `hudson`, `DistributionUpdate/dist45` and `DistributionUpdate/PackageAdmin`.

**Comment by markuspf** [comment]
I think we should rather merge this and resurrect files if they are missed by someone instead of waiting, becuase this would become a never-ending PR then. We can always make new removal PRs or just remove things (and maybe add the DELETED file with a comment in anywhere)

**Comment by alex-konovalov** [comment]
This PR is merged but I do not delete "WIP" from its title - further cleanup is needed. There are some other PR which seem to be merged and closed but contain "WIP" or even "WIP (do not merge)" in their title - these perhaps should be renamed...

**Pull request merged**
