### PR TITLE
Comment out assertion as the homomorphism it not well-constructed.

### PR DESCRIPTION
**Pull request by hulpke**
and assertion now runs into error.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@hulpke thanks - I guess this fixed the diff reported yesterday.

BTW, writing commit messages in Git it is recommended to stick to the convention of keeping the first line of the commit no longer than 50 characters (see [here](http://chris.beams.io/posts/git-commit/) and use it for a short summary, Then if you need more space to explain further details, leave line 2 blank and add them starting from line 3. Otherwise we can see e.g. this:

```
Comment out assertion as the homomorphism it uses is only storage and…
… not

well-constructed.
```
A useful trick is `git commit --amend`, which you may use if you just made a commit (but haven't pushed it elsewhere) and then decided to rewrite commit message or to add more files to that commit.

**Comment by fingolfin** [comment]
Another remark: If you plan to merge a pull request immediately after creating it, then there is no point in creating the pull request in the first place; you could just push the change directly.

**Comment by alex-konovalov** [comment]
@fingolfin pushing directly is fine for small obviosly correct changes, but for something non-trivial the usefulness of making a PR is that it will be tested with Travis CI...

**Comment by hulpke** [comment]
> Another remark: If you plan to merge a pull request immediately after creating it, then there is no point in creating the pull request in the first place; you could just push the change directly.
> 
> 
Yes. Doing it as a pull request gives me an automatic test (which I don’t have to run myself) and the ability to see exactly what (including which commit messages) will be transferred. I’m worried (in particular after prior experience) that a push would include other  commit messages in the same branch.

**Comment by fingolfin** [comment]
Good points!

**Pull request merged**
