### PR TITLE
Dense FILTERS

### PR DESCRIPTION
**Pull request by stevelinton**
The list FILTERS had a few holes which arose from filters declared in the kernel but never 
"ratified" by DeclareXXXXKernel calls. The PR fixes this by deleting IS_MACFLOAT (never used) and 
uncommented a DeclarePropertyKernel call for IsNSortedList (used in a few places).

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Looks good to me.

**Comment by fingolfin** [comment]
Hm, note that the OpenMath package uses `IS_MACFLOAT` -- so I guess this change may have broken it? @alex-konovalov may know more about that...

(When removing seemingly unused symbols, I always try to first grep the collection of all packages distributed in GAP, plus all my clones of GAP packages)

**Comment by stevelinton** [comment]
Ahh thanks. I’ll look closer.

**Comment by alex-konovalov** [comment]
@fingolfin @stevelinton no problem - that was some legacy code, I will try to get rid of it and release new version today.

**Pull request merged**
