### PR TITLE
Fix Mersenne Twister on 64 bit system

### LINKED ISSUE #423: Strange behaviour of IsMersenneTwister
In commit https://github.com/gap-system/gap/commit/dd4ba8ff8d156b95f1882a6ae8dcb3060603e8b3 @frankluebeck added the following example:
```
gap> mysource := RandomSource(IsMersenneTwister, 42);;
gap> Random(mysource, 1, 10^60);
474943581767832038339909502952186501785153672757525589711853
```
It happened however that this example is reproducible only in 64-bit build with GMP.

In all of the three other configurations (32-bit builds with/without GMP and 64-bit build without GMP) the result of `Random` is 
```
999331861769949319194941485000557997842686717712198687315183
```

First I thought that this is related to building GMP with c++ support, added in #399, but then I've checked that the same happens in the stable-4.7 branch. This must be just the new example that revealed this behaviour, which has been here before.

One could certainly adjust the example to run in the same way everywhere. For example replacing 10^60 by 10^30 helps. But I am also worried that this may point to a more serious problem and should be investigated. And if there is no bug here, then we should be aware that the output of randomised algorithms may also depend on the way how GAP was compiled.

### PR DESCRIPTION
**Pull request by fingolfin**
On 64bit systems, we would sometimes pull more random bits from
the Mersenne Twister than were strictly needed. For example, when
asked for 200 random bits, on a 32bit system we generated 7 * 32 = 224
bits of randomness, and discarded 24 of these. On a 64 bit system,
we generated 4 * 64 = 256 bits of randomness, and discard 56 of them.

This commit fixes it, and also unifies the 32bit and 64bit code paths,
resulting in somewhat easier to understand code.

Fixes #423

### CODE REVIEW

**Comment by fingolfin** [comment]
I just updated the PR to avoid over long lines...

**Comment by markuspf** [comment]
I have done the same debugging as Max did, and came to the same conclusions. Unfortunately I cannot test on a 32bit system. This fix looks good to me. Maybe @frankluebeck can comment as well?

Maybe there is there a way to test this sensibly, like generating a couple of random numbers and checking that they yield the same results. It would be good to catch errors that stem from refactoring integer code or just updating GMP and whatnot.

**Comment by alex-konovalov** [comment]
@markuspf tested this with 32 bits and the fix also works. @stevelinton, @frankluebeck, @ChrisJefferson - could any of you say if you agree with the fix and we may merge it, please?

**Comment by ChrisJefferson** [comment]
Looks good to me, the code is quite a bit simpler now, which is nice.

**Pull request merged**
