### PR TITLE
JenningsLieAlgebra

### PR DESCRIPTION
**Pull request by willemdegraaf**
Fixed a bug in JenningsLieAlgebra, reported by Laurent Bartholdi. 
Here is an example of the correct behaviour:
```
gap> g := Group((1,10)(2,9)(3,11)(4,12)(5,15)(6,16)(7,13)(8,14)(17,21)(18,22)*
> (19,24)(20,23)(25,27)(26,28)(29,30)(33,51)(34,52)(35,49)(36,50)(37,54)(38,53)*
> (39,55)(40,56)(41,61)(42,62)(43,64)(44,63)(45,57)(46,58)(47,60)(48,59), 
> (1,19)(2,20)(3,17)(4,18)(5,22)(6,21)(7,23)(8,24)(9,29)(10,30)(11,32)(12,31)*
> (13,25)(14,26)(15,28)(16,27)(33,42)(34,41)(35,43)(36,44)(37,47)(38,48)(39,45)*
> (40,46)(49,53)(50,54)(51,56)(52,55)(57,59)(58,60)(61,62), 
> (1,37)(2,38)(3,40)(4,39)(5,33)(6,34)(7,36)(8,35)(9,43)(10,44)(11,41)(12,42)*
> (13,46)(14,45)(15,47)(16,48)(17,58)(18,57)(19,59)(20,60)(21,63)(22,64)(23,61)*
> (24,62)(25,50)(26,49)(27,51)(28,52)(29,55)(30,56)(31,53)(32,54));
<permutation group with 3 generators>
gap> L:= JenningsLieAlgebra(g);
<Lie algebra of dimension 13 over GF(2)>
gap> List(Basis(L),PthPowerImage);
[ 0*v.1, v.6, 0*v.1, v.7, v.8, v.9, 0*v.1, v.10, v.11, v.12, 0*v.1, v.13, 
  0*v.1 ]
gap> LieLowerCentralSeries(L);
[ <Lie algebra of dimension 13 over GF(2)>, 
  <Lie algebra of dimension 3 over GF(2)>, 
  <Lie algebra of dimension 0 over GF(2)> ]
```

### CODE REVIEW

**Comment by markuspf** [comment]
Without knowing what's going on, could you add a test, please? (For example testing the above example, feel free to add more ;))

**Comment by willemdegraaf** [comment]
Hi,

I tried to add a test in the commit message. Don't know how to add one
otherwise.
In any case, here it is:

gap> g :=
Group((1,10)(2,9)(3,11)(4,12)(5,15)(6,16)(7,13)(8,14)(17,21)(18,22)*
>
(19,24)(20,23)(25,27)(26,28)(29,30)(33,51)(34,52)(35,49)(36,50)(37,54)(38,53)*
> (39,55)(40,56)(41,61)(42,62)(43,64)(44,63)(45,57)(46,58)(47,60)(48,59),
>
(1,19)(2,20)(3,17)(4,18)(5,22)(6,21)(7,23)(8,24)(9,29)(10,30)(11,32)(12,31)*
>
(13,25)(14,26)(15,28)(16,27)(33,42)(34,41)(35,43)(36,44)(37,47)(38,48)(39,45)*
> (40,46)(49,53)(50,54)(51,56)(52,55)(57,59)(58,60)(61,62),
>
(1,37)(2,38)(3,40)(4,39)(5,33)(6,34)(7,36)(8,35)(9,43)(10,44)(11,41)(12,42)*
>
(13,46)(14,45)(15,47)(16,48)(17,58)(18,57)(19,59)(20,60)(21,63)(22,64)(23,61)*
> (24,62)(25,50)(26,49)(27,51)(28,52)(29,55)(30,56)(31,53)(32,54));
<permutation group with 3 generators>
gap> L:= JenningsLieAlgebra(g);
<Lie algebra of dimension 13 over GF(2)>
gap> List(Basis(L),PthPowerImage);
[ 0*v.1, v.6, 0*v.1, v.7, v.8, v.9, 0*v.1, v.10, v.11, v.12, 0*v.1, v.13,
  0*v.1 ]
gap> LieLowerCentralSeries(L);
[ <Lie algebra of dimension 13 over GF(2)>,
  <Lie algebra of dimension 3 over GF(2)>,
  <Lie algebra of dimension 0 over GF(2)> ]

All the best,

Willem

**Comment by alex-konovalov** [comment]
@willemdegraaf you can add a test file to the [`tst/testbugfix`](https://github.com/gap-system/gap/tree/master/tst/testbugfix) directory - see some of the most recent test files there as an example what to put there and how to name the test files.

**Comment by willemdegraaf** [comment]
Sorry for my ignorance: hoow do I add a file to that directory?

Willem

**Comment by alex-konovalov** [comment]
@willemdegraaf are you using GitHub's web-interface, or working in a local clone of the repository with git?

**Comment by willemdegraaf** [comment]
Until now I was using the web interface.

**Comment by alex-konovalov** [comment]
@willemdegraaf then go to the branch corresponding to this pull request in your fork, and navigate there to the directory where you want to create the file - that is given by this link: https://github.com/willemdegraaf/gap/tree/Laurent/tst 

Now there is a "create new file" button there, click on it, specify the file name, enter the content of the file, then the text of the commit message, and click on "Commit new file" button at the bottom of this page.

**Comment by willemdegraaf** [comment]
Fixed that. Also noted that the same error happens in PCentralLieAlgebra; fixed that as well.
Next I hope to add a test file.

**Comment by willemdegraaf** [comment]
OK. Did that. Do I now need to do another pull request?

**Comment by alex-konovalov** [comment]
@willemdegraaf you don't need another PR: because the file was added in the branch from which this PR has been submitted, this PR is now updated automatically.

When this PR will be ready, one should perhaps "squash and merge" this to have all changes in a single commit.

**Comment by alex-konovalov** [comment]
@willemdegraaf ... hmm... your new test file will not be picked up by tests, because it is not in the right location - I've overlooked that, because your fork is our of sync, and it does not have the latest state of the `tst` directory, which has a separate subdirectory for bugfix tests. But first let's see how the currently running Travis CI tests will go.

Will you be able to use `git` on your local machine instead of the web interface? That may be more efficient in the long run.

**Comment by willemdegraaf** [comment]
Yes, I can use git. But it would take some time to learn how to work with
that...

**Comment by alex-konovalov** [comment]
@willemdegraaf will be time well invested - better than spending time on trying to use the web interface. Hopefully some of us here may help. To start with, you may try to follow https://github.com/gap-system/gap/blob/master/CONTRIBUTING.md

**Comment by willemdegraaf** [comment]
Good, thank you! I will look at it one of these days.

**Comment by alex-konovalov** [comment]
P.S. If this is a bugfix, perhaps it should be submitted to stable-4.9 branch. One could edit PR using GitHub web interface to change where it is submitted.

**Comment by fingolfin** [comment]
This PR is based on 534315038f25f83488a5b9cea5c6d8d8bce441f5 from April 2015 (!), i.e. 2.5 years ago.

I'll make a new PR with the changes in here, in a single commit and all the problems @alex-konovalov mentioned corrected.

**Comment by alex-konovalov** [comment]
Closed as replaced by #2085.

**Pull request closed without merging**
