### PR TITLE
Add optimised INT_STRING, to turn strings into ints

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This patch simplifies and improves how we turn ints into strings. The implementation could be further optimised (this code is lifted from how the parser parses int), but I didn't want to write separate GMP and non-GMP code.

There are some weird strings we now reject we used to accept. The new rules match the regexp:

`-*[0-9]+`

So string begins with any number of '-', if there is an odd number the string is negative. Then there are a series of digits expressing the number. Everything else returns fail.

The main things we now reject we used to accept are:

* `Int("")` and `Int("-")` used to return `0`, they now return `fail`.
* Some long weird strings were accepted, now they are rejected.

### CODE REVIEW

**Comment by hulpke** [comment]
Thank you! Should the return of `fail' for invalid strings be part of the (guaranteed) documented behavior?

**Comment by ChrisJefferson** [comment]
Yes, I will tweak the documentation to say we return fail (which we mostly did anyway, so this is just clarifying behaviour)

From: Alexander Hulpke
Sent: Wednesday 6 January 21:38
Subject: {Disarmed} Re: [gap] Add optimised INT_STRING, to turn strings into ints (#435)
To: gap-system/gap
Cc: Christopher Jefferson

Thank you! Should the return of `fail' for invalid strings be part of the (guaranteed) documented behavior?

-

**Comment by stevelinton** [comment]
Is there an easy way to avoid duplication of code between this and the scanner?

**Comment by stevelinton** [comment]
We also discussed in issue #181 getting rid of non-GMP long integers after 4.8 which might speakj for shifting to a GMP based solution.

**Comment by fingolfin** [comment]
While we indeed plan to get rid of non-GMP integers eventually, I don't think there is a need to hold back this PR because of that. When we remove the non-GMP integers, we can still rewrite this function. (If somebody is concerned about us "forgetting" to do that, we can file an issue for this once this PR has merged)

**Comment by alex-konovalov** [comment]
I agree with @fingolfin, so I've set GAP 4.8.2 milestone for this. Let's wait till @ChrisJefferson will update the documentation and then merge it.

**Comment by ChrisJefferson** [comment]
Now with some merging of duplicated code, I think this is ready to commit.

We should be sure to put this exists in the release notes, as it might break some people's number parsing (altough they were doing weird things). I might also put this in stable-4.7, if we plan on making another release.

**Comment by alex-konovalov** [comment]
No need to put it into stable-4.7, but it should be cherry-picked on stable-4.8.

We don't plan 4.7.10. In fact, release wrapping already switched to wrap minor releases for 4.8.X from stable-4.8 and major for 4.9.Y from master branch. The quality of the 2nd beta (i.e. GAP 4.8.1) is comparable with the public release, and it's only our wait for packages which were given a window until February 1st which holds the release at the moment. I hope to have it very quickly in February.

To put this in release noted: @ChrisJefferson, please edit https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.7-and-GAP-4.8 and put there the text you like.

**Pull request merged**
