### PR TITLE
Fix unexpected error when doing certain calculations in a fitting-free group acting intransitively on its socle factors

### PR DESCRIPTION
**Pull request by hulpke**
If a fitting-free group acts intransitively on it's socle factors,  it could lead to the calculation being stopped by an error trap. (Could not lead to false results.,)
This was reported in a support email by Sumi Toshio.
<s>
Also minor changes:

- Small speedup for double cosets in large groups
- Avoid pcgs computation if the index is small and it will not help.
- Delete accidentally surviving debug trap and force parent for improved performance
- A fix for #5525 -- overlooked special case in MTC to cyclic subgroup that would result in an error message.

##Release Notes

If a fitting-free group acts intransitively on it's socle factors,  it could lead to the calculation being stopped by an error trap. (Could not lead to false results.)
</s>

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Be good to have some tests that cover the change in behaviour @hulpke

**Comment by hulpke** [comment]
> Be good to have some tests that cover the change in behaviour @hulpke

Easier said than done. This was implemented to get a huge calculation finish in a fewer days. I fear this is one of the cases where it is not reasonable to expect a specific test example.

**Comment by james-d-mitchell** [comment]
Ah, that's a shame @hulpke, if the input to the huge calculation isn't too big maybe it could be added as a comment in the code, for posterity?

**Comment by dimpase** [comment]
With this change, computing `StructureDescriiption` for `H` in question does not seem to work well, it gets stuck in a seemingly endless loop (I waited for 15 min of wall clock)
```
gap> StructureDescription(H);
^CError, user interrupt in
  S := rec(
    labels := arg[1],
    genlabels := [  ],
    generators := [  ],
    identity := arg[2] ); at /mnt/opt/gap/lib/stbc.gi:1190 called from 
EmptyStabChain( S.labels, S.identity, b ) at /mnt/opt/gap/lib/stbc.gi:812 called from
StabChainSwap( S ) at /mnt/opt/gap/lib/stbc.gi:785 called from
StabChainForcePoint( S, new ) at /mnt/opt/gap/lib/stbc.gi:1113 called from
ChangeStabChain( GG, [ a ], false ); at /mnt/opt/gap/lib/stbcbckt.gi:490 called from
Suborbits( E, rbase.base{[ 1 .. tra - 1 ]}, fpt, Omega ) at /mnt/opt/gap/lib/stbcbckt.gi:2055 called from
...  at *stdin*:6
you can 'return;'
brk> 
```

OTOH, `MaximalNormalSubgroups(H)` amost instantly return the subgroups, of index 2 and 3.
 `StructureDescription` for the index 2 one is very quick (and actually allows to get an answer for `H`, manually) , but for the index 3 one `StructureDescription` seems to be getting stuck, too.

**Comment by hulpke** [comment]
> With this change, computing `StructureDescriiption` for `H` in question does not seem to work well, it gets stuck in a seemingly endless loop (I waited for 15 min of wall clock)

I think this is a fundamental flaw in how `StructureDescription` works. If you look further down the backtrace, one sees that `ConjugacyClassesSubgroups` got called:

Instead of going for a subdirect product decomposition, it tries semidirect products, but `SemidirectDecompositionsOfFiniteGroup` then calls for the full lattice because the group has nonsolvable normal subgroups with nonsolvable factor groups. Clearly this will take very long with existing code.

The obvious fix would be to have `StructureDescription` to try subdirect products first.

**Comment by fingolfin** [comment]
I've pulled out the unrelated changes into separate PRs and merged them. (Because that makes my life quite a bit easier for doing releases, and also for tracking down regressions, reverting or adjusting commits that introduce regressions etc.).

I also changed the test added by this PR to match exactly what was reported -- the alternate shorter example previously in this PR did not trigger the error for me at all on an unpatched GAP.

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
