### PR TITLE
Remove use of "fail" as local variable

### PR DESCRIPTION
**Pull request by markuspf**

### CODE REVIEW

**Comment by fingolfin** [comment]
Ouch! Nice catch!

So using `true` and `false` as a local variable raises an error, but `fail` does not?  Indeed, `GAPInfo.Keywords` lists the former, but not the latter... Should we change things so that `fail` used a local trigger an error in the future?

**Comment by ChrisJefferson** [comment]
Technically, `true` and `false` are keywords, while `fail` is just a global variable. You can see this by checking things like `IsBound(true)` (which doesn't parse as `true` is a keyword) and `IsBound(fail)` is true (as `fail` is just a variable).

We could in principle make `fail` a true keyword like `true` and `false`. It would be lots of little changes but I don't think anything too serious.

**Comment by markuspf** [comment]
I was going to open an issue asking whether `fail` should be a keyword, but was still thinking about it, as it'd possibly break some legacy code.

I have a patch almost ready to do this.

(I have discovered a few more syntactic oddities while writing an alternative implementation of GAP, some of which might pop up as issues here soon).

**Comment by frankluebeck** [comment]
I cannot see any problem with the current behaviour. 

Of course, if you use `fail` as local variable then you cannot use the global `fail` within that function; but you probably don't want to use it anyway. 

The same is true with any global variable, e.g.,
```
f := function() local Size; Size:=2; return 2*Size; end;
f();
```
So, what is the problem with
```
f := function() local fail; fail:=2; return 2*fail; end;
f();
```
???

**Comment by ChrisJefferson** [comment]
@frankluebeck : It is a bit weird that true, false and fail aren't all handled in a consistent manner, but I'm not sure if users will actually notice.

**Comment by frankluebeck** [comment]
@ChrisJefferson: Indeed, it is difficult/impossible to understand why `fail` and `true` behave differently.

But I would consider the behaviour with respect to `true` and `false` as "weird". These are the only keywords which just evaluate to objects. Instead of making "fail" another keyword I would rather remove `true` and `false` from the list of keywords. Wouldn't this simpliy the parser?

Or is there any advantage in `true` and `false` being keywords which I overlook?

**Comment by fingolfin** [comment]
Changing the values of `true` and `false` leads to code that is very hard to debug. Suddenly, statements like `if a = true then` and `if a then` are non-equivalent. I would count "preventing programmer from writing unmaintainable code" an important advantage.

**Comment by markuspf** [comment]
`fail` is read-only, so that's a non-issue in a way.

By the way I just tried in python 2.7:
```
>>> False
False
>>> type(False)
<type 'bool'>
>>> False = 7
>>> False
7
```
and 3.5
```
>>> False
False
>>> False =7
  File "<stdin>", line 1
SyntaxError: can't assign to keyword
```

So this speaks for leaving at least `true` and `false` as keywords. I think of them rather like integer literals for example.

One advantage of having them as keywords is saving one global variable lookup per use (though I don't think there'd be a massive performance impact).

I do agree that having `true` and `false` as variables could lead to subtle bugs (though fail seems to be much more susceptible to misuse to me).

**Comment by ChrisJefferson** [comment]
I am happy too, but let's wait until tomorrow / later today when my mess has got cleaned up and calmed down.

**Pull request merged**
