### PR TITLE
Ongoing corrections to go in the next minor release

### PR DESCRIPTION
**Pull request by hulpke**
This corrects reported errors.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I am happy with all of these except the middle one (FIX: Use workaround for (currently only) PSL only if group is simple.). I don't doubt it's right, I just don't have the confidence to have an opinion on it :)

**Comment by markuspf** [comment]
@ChrisJefferson it is a correct (stopgap) fix. Could we maybe add one or two tests that exercise the branches of this function though?

**Comment by hulpke** [comment]
@markuspf A test for 2 branches (the third is a worst-case fallback that will be expensive...) is part of an enhancement that I committed today (so will go into master, not stable).

**Comment by alex-konovalov** [comment]
@hulpke Since this PR now merged, could you please add to [this Wiki page](https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.7-and-GAP-4.8) the text to include in the changes manual and the next minor release announcement?

**Pull request merged**
