### PR TITLE
Remove more StabChainMutable

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This continues to remove references to StabChainMutable.

The big change here is making sure wherever we create a StabChainMutable, we also create a StabChainImmutable. This allows us to switch all uses of HasStabChainMutable to HasStabChainImmutable.

There is a helper function SetStabChain, which always sets StabChainImmutable, and sets StabChainMutable if the given chain is mutable.

In some places calls to SetStabChainMutable are moved. That is because we now never set the StabChain until we have finished building it.

### CODE REVIEW

**Comment by fingolfin** [comment]
I did not test these changes, but I read through them, and they make sense to me. Moving towards immutable stab chains seems like a good idea.

However, I do not know enough about the existing stab chain code to judg whether this might have hidden impacts I am not aware of. I wonder whether @hulpke or @frankluebeck have any insights on that?

**Comment by ChrisJefferson** [comment]
I believe none of these changes should be expensive, except in some cases we will now store an ImmutableStabChain and MutableStabChain, whereas previously we just had a MutableStabChain.

**Comment by fingolfin** [comment]
I see no good reason to delay this further... if there are regressions, we'll deal with them appropriately.

**Comment by alex-konovalov** [comment]
There are new diffs in manual examples:
```
============================================================
########> Diff in [ "./../../lib/object.gd", 664, 671 ]
# Input is:
KnownAttributesOfObject(g);
# Expected output:
[ "Size", "OneImmutable", "NrMovedPoints", "MovedPoints", 
 "GeneratorsOfMagmaWithInverses", "MultiplicativeNeutralElement", 
 "HomePcgs", "Pcgs", "GeneralizedPcgs", "StabChainMutable", 
 "StabChainOptions" ]
# But found:
[ "Size", "OneImmutable", "NrMovedPoints", "MovedPoints", 
 "GeneratorsOfMagmaWithInverses", "MultiplicativeNeutralElement", 
 "HomePcgs", "Pcgs", "GeneralizedPcgs", "StabChainMutable", 
 "StabChainImmutable", "StabChainOptions" ]
########
########> Diff in [ "./../../lib/attr.gd", 62, 89 ]
# Input is:
KnownAttributesOfObject(g);
# Expected output:
[ "OneImmutable", "LargestMovedPoint", "NrMovedPoints", 
 "MovedPoints", "GeneratorsOfMagmaWithInverses", 
 "MultiplicativeNeutralElement", "StabChainMutable", 
 "StabChainOptions" ]
# But found:
[ "OneImmutable", "LargestMovedPoint", "NrMovedPoints", 
 "MovedPoints", "GeneratorsOfMagmaWithInverses", 
 "MultiplicativeNeutralElement", "StabChainMutable", 
 "StabChainImmutable", "StabChainOptions" ]
########
########> Diff in [ "./../../lib/attr.gd", 62, 89 ]
# Input is:
KnownAttributesOfObject(g);
# Expected output:
[ "Size", "OneImmutable", "LargestMovedPoint", "NrMovedPoints", 
 "MovedPoints", "GeneratorsOfMagmaWithInverses", 
 "MultiplicativeNeutralElement", "StabChainMutable", 
 "StabChainOptions" ]
# But found:
[ "Size", "OneImmutable", "LargestMovedPoint", "NrMovedPoints", 
 "MovedPoints", "GeneratorsOfMagmaWithInverses", 
 "MultiplicativeNeutralElement", "StabChainMutable", 
 "StabChainImmutable", "StabChainOptions" ]
########
=========OUTPUT END: testmanuals with autoloaded packages=========
```
As @ChrisJefferson explained, "except in some cases we will now store an ImmutableStabChain and MutableStabChain, whereas previously we just had a MutableStabChain" so I will just update these examples to match the new output.

**Pull request merged**
