### PR TITLE
Backport more HPC-GAP `src` changes

### PR DESCRIPTION
**Pull request by fingolfin**
This is based on PR #232, and backports many more changes, reducing the inter-branch diff for the `src` directory.

This is not quite yet finished!

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Travis build fails...
```
gcc -I. -I../.. -DCONFIG_H   -Wall -g -O2  -g -O2  -o objfgelm.o -c ../../src/objfgelm.c
../../src/objfgelm.c: In function ‘Func8Bits_HeadByNumber’:
../../src/objfgelm.c:407:5: error: expected ‘;’ before ‘,’ token
```

**Comment by fingolfin** [comment]
Yeah, as I said, its not quite finished yet, I just wanted to already push it up, so it's visible. I'll fix the error and push more soon. For now, I'd like to get the TLS branch merged.

**Comment by markuspf** [comment]
I went through the commits, and I don't see anything blatantly wrong with them, except for some formatting details (and the comments I made).

**Comment by fingolfin** [comment]
I fixed the NOOP bit (i.e. it's left in system.h). For ffdata.h I'd prefer to do that in a separate cleanup later, just as with code formatting issues.

Otherwise, I think this is ready to merge.

**Comment by markuspf** [comment]
I'll take the plunge and merge then.

**Pull request merged**
