### PR TITLE
Hpcgap lib merge 1

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This patch merges some files in hpcgap/lib. It also makes a wide selection of strings which GAP creates immutable -- in many cases if these strings were edited bad things would happen, so making them immutable shouldn't break anything.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This has been rebased on top of #1333  (MakeImm and Imm), and that is used to do some more simple merging.

**Comment by ChrisJefferson** [comment]
It also requires #1334 as well (sorry)

**Comment by fingolfin** [comment]
OK, #1334 is in -- please rebase this PR so that we can merge it.

**Comment by fingolfin** [comment]
Or wait, I'll just do it

**Comment by fingolfin** [comment]
Ah well, seems we both did it... also fine :-)

**Pull request merged**
