### PR TITLE
Remove experimental do/od syntax; cleanup reader for functions

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Two commits have `tile` instead of `tilde` (I don't know how to comment on commit messages.

**Comment by ChrisJefferson** [comment]
Apart from that it's fine, but I would have prefered to just review a commit removing do/od, 90% of this commit was unrelated stuff that doesn't really need going into 4.9 (while I think we really want to get do/od out, before people find it and maybe start using it). However, unless anyone else complains it may as well go in now.

**Comment by fingolfin** [comment]
@ChrisJefferson I added PR #1932 containing just the do/od removal.

**Comment by fingolfin** [comment]
Also rebased this PR on the new one, and fixed the `tile` commit messages.

**Pull request merged**
