### PR TITLE
Changebag fix

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This fixes a number of issues with missing 'CHANGED_BAG' calls (and an assignment which needs splitting), which were discovered using a new gasman checking branch I created.

These should also be put in stable-4.8. Should I make the pull request there, or do the commit here then get them picked into 4.8?

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Since this PR is already made anyway, let's fist merge it here and then cherry-pick after another round of nightly testing (which will also include compiler warnings - good thing to do for changes touching the kernel). One should only keep an eye to remember to cherry-pick it.

**Comment by stevelinton** [comment]
Thanks for finding and fixing these. Were all the bugs in oper.c or can we expect more PRs for other files?

**Comment by ChrisJefferson** [comment]
There are some other PRs now arriving. I think that's everything (at least, everything I find in the process of GAP starting, plan to look functions invoked during testing next).

**Comment by alex-konovalov** [comment]
I suggest to merge this, see how it passes tests in master (e.g. if it compiles with `-Werrro`) and then cherry=pick onto stable-4.8.

**Comment by fingolfin** [comment]
@alex-konovalov The problem with that is still that somebody needs to remember doing that! I could merge this PR right now, but I don't want to be the one responsible for cherry-picking its changes to stable in the future.

So, either we get a new PR against stable-4.8, then I"d be happy to merge it; or else somebody else merges this and takes responsibility for the cherry picking later :)

**Comment by alex-konovalov** [comment]
I will take the responsibility, since we spoke with @ChrisJefferson about this particular PR last week, and I've promised to do this. But in general I suggest that "obvious" changes should go to the stable branch first, as it's easy to forget about cherry-picks.

**Comment by alex-konovalov** [comment]
Now cherry-picked onto stable-4.8

**Pull request merged**
