### PR TITLE
travis: abort ci.sh as soon as there is an error

### PR DESCRIPTION
**Pull request by fingolfin**
This PR sets the `-e` flag for `etc/ci.sh`, causing the script to abort as soon as any command in it fails. This way, if a build is broken due to outside circumstances (e.g. because gap-system.org it failed to download bootstrap packages), it doesn't blindly plunge ahead, but rather stops immediately.

This just affected me: Travis failed to download stuff from St Andrews:
```
The command "make -j4" exited with 0.
$ make bootstrap-pkg-full
--2016-12-21 16:23:55--  http://www.gap-system.org/pub/gap/gap4pkgs/bootstrap-pkg-full.tar.gz
Resolving www.gap-system.org (www.gap-system.org)... 138.251.206.223
Connecting to www.gap-system.org (www.gap-system.org)|138.251.206.223|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://palain.cs.st-andrews.ac.uk/pub/gap/gap4pkgs/bootstrap-pkg-full.tar.gz [following]
--2016-12-21 16:23:56--  https://palain.cs.st-andrews.ac.uk/pub/gap/gap4pkgs/bootstrap-pkg-full.tar.gz
Resolving palain.cs.st-andrews.ac.uk (palain.cs.st-andrews.ac.uk)... 138.251.206.223
Connecting to palain.cs.st-andrews.ac.uk (palain.cs.st-andrews.ac.uk)|138.251.206.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-21 16:23:57 ERROR 404: Not Found.
tar (child): ../bootstrap-pkg-full.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make: *** [bootstrap-pkg-full] Error 2
The command "make bootstrap-pkg-full" exited with 2.

318.73s$ bash etc/ci.sh
```
At this point, I would have expected Travis to stop anyway, but apparently it doesn't (see also https://github.com/travis-ci/travis-ci/issues/1066 ), and just plows ahead:
```
etc/ci.sh: line 22: cd: pkg/io*: No such file or directory
checking for gcc... gcc
checking whether the C compiler works... yes
...
```
At this point, you can see that a `cd` command in `etc/ci.sh` fails, but it goes on anyway. With this PR, it would have aborted at that point. The great advantage of that is that it becomes easier to figure out what went wrong -- in the current setup lots and lots of additional error messages follow, and if you start reading the log at the bottom, you have to wade through irrelevant errors.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin are you sure that this will not terminate the script, if there are diffs when the test is called line 30:
```
echo "Read(\"tst/${TEST_SUITE}.g\"); quit;" |\
```
We still want to do the postprocessing in this case.

**Comment by markuspf** [comment]
What postprocessing are you referring to?

**Comment by fingolfin** [comment]
@alex-konovalov You are right, that might be a problem (and hey, that's why I asked for a review instead of pushing it directly ;-). I did not really look at `etc/ci.sh` closely when making this PR.

Now that I do, I am somewhat puzzled... the test suite main files all end with a force quit. So why do we call GAP in this complicated way, instead of just this:
```
     sh bin/gap.sh tst/${TEST_SUITE}.g
```

**Comment by fingolfin** [comment]
@markuspf I guess the creation of the coverage data... Although, now that I think about it: That is for codecov only, isn't it? And that won't run if the build failed anyway...

**Comment by fingolfin** [comment]
Actually, come to think we use `etc/ci.sh` only for travis, right? So, looking at `.travis.yml`, it contains this:
```
script:
  - ./configure --with-gmp=system
  - make config
  - make -j4
  - make bootstrap-pkg-full
  - bash etc/ci.sh
```
Perhaps we should move the configure & make stuff into `etc/ci.sh`? That way, if any of them fails, we'd abort immediately. Drawback: It would be harder to customize builds, if we ever wanted to do so... but that's hypothetical, it's not as if we could undo this at any time.

**Comment by alex-konovalov** [comment]
Careful - the plan was to use `ci.sh` from more than one CI tool (e.g. AppVeyor too). 

The postprocessing is what happening in `ci.sh` after running `echo "Read(\"tst/${TEST_SUITE}.g\"); quit;" |` - that's exactly preparing coverage reports as @fingolfin said and grepping to count the number of diffs.

Suggestion to use `sh bin/gap.sh tst/${TEST_SUITE}.g` sounds good to me. I think the current code may be a relic from the previous test suite which had to be compatible with GAP 4.7.

**Comment by fingolfin** [comment]
@alex-konovalov the results of the post processing are not used when the build fails, though, are they?

**Comment by markuspf** [comment]
Codecov does not analyse code coverage unless tests pass though, so that is irrelevant.

**Comment by alex-konovalov** [comment]
@markuspf I am not so sure - recently someone overlooked merge conflict and pushed code with `>>>>>` marks. Then codecov reported something like the code coverage dropped from 50 to 10 percents. 

But indeed this is up to us to control, and it makes sense to report coverage only if the test passes. The tests in the master branch are not rotting, so it a test fails, that would be clearly PRs fault.

**Comment by alex-konovalov** [comment]
@fingolfin wrote:
>Perhaps we should move the configure & make stuff into etc/ci.sh?

Note: one of the ideas behind `etc/ci.sh` was to provide the script which one could run locally and still have the setup maximally close to the one on Travis CI. So changes in `etc/ci.sh` should not increase this distance.

Of course, because `make bootstrap-pkg-full` is called outside this script, and, moreover, `bin/BuildPackages.sh` is not called at all (only IO and profiling are built), this is not giving 100% authentic experience. But OTOH I am not convinced that `etc/ci.sh` will be used often locally, if each time it will try to download and build packages...

**Comment by fingolfin** [comment]
Hmm, weird, it seems this change does not have the effect I thought it would have: Consider the failure (due to Travis not being able to download some files): https://travis-ci.org/gap-system/gap/jobs/185820171
Looking at it, it seems `etc/ci.sh` was *not* aborted early... I'll look into it

**Comment by fingolfin** [comment]
@alex-konovalov OK, I was not aware of that... if only this was documented, say, in a comment at the top of the script that explains this intention... :-)

**Comment by fingolfin** [comment]
The problem was that we run the script via "bash etc/ci.sh", which ignores flags set in the shebang. So I just set them explicitly. Also added a comment, and changed how GAP are worked. A test verified that Travis now properly aborts the build early. I now removed the HACK commit used to trigger the early test failure, and the regular test suite is running now.

**Comment by fingolfin** [comment]
You can see the correct early abort for example here: https://travis-ci.org/gap-system/gap/jobs/186010965

Note that it ended after less than 2 minutes, while in the past failed build went on, and took 6-7 minutes until they reported a failure, with tons of distracting output after the real problem; see e.g. here: https://travis-ci.org/gap-system/gap/jobs/186010965

**Comment by fingolfin** [comment]
Tests failed because our code for grepping for the test suite totals was broken (and must have been broken for a long time without anybody noticing... another benefit of setting the `-e` flag. Oh, and without `-x` it would have taken me much longer to figure out WTF happened).

Which leads me to wonder: What is the purpose of this line in `etc/ci.sh`:
```
( ! grep "########> Diff" testlog.txt )
```
Perhaps it is there to highlight any diffs that were found? But why is there a `!` ?

**Comment by markuspf** [comment]
The ! is there to make the script return a non-zero exit code if grep *found* a diff. This is probably all leftovers from the old hacky travis.yml setup.

**Comment by fingolfin** [comment]
@markuspf I see.. and why does it run in a subshell?
Perhaps it would be cleaner then to write
```
grep "########> Diff" testlog.txt || echo "No diffs found"
```

**Comment by markuspf** [comment]
In my shell that does not return a non-zero exit code if something *is* found. It doesn't need to go in a subshell, but one has to invert the return codes either way.

**Comment by fingolfin** [comment]
Actually, with the changes in this PR, if the test suite ends with an error, it'll exit with a non-zero exit code -- and `etc/ci.sh` will terminate, and this line is never executed. So, it only gets executed if there are no diffs. Ergo, we can just as well remove it... Right?

**Comment by markuspf** [comment]
Does GAP quit with a non-zero exit code when tests diff? I didn't think it did.

One big goal I had with the `ci.sh` script was that I didn't have to keep poking travis all the time, beacuse thats incredibly time consuming. Admittedly I didn't really follow through on this.

**Comment by fingolfin** [comment]
@markuspf It does, thanks to @ChrisJefferson 

However, I just tested, and the fact that we pipe its output into other commands masks the failure... Argh.

**Comment by fingolfin** [comment]
OK, simply *not* grepping for diffs allowed to get rid of the `tee` calls and the piping, and thus bash now catches non-zero exit codes caused by diffs... so the end result is much simpler, at the loss of coloring diffs... but since we only colored a very small part of that, I don't consider this a loss... I always use my browser's search feature to find "####> Diff" anyway (or simply scroll through the logs).

I also squashed all changes into a single commit.

**Comment by markuspf** [comment]
This is of course fine by me, @alex-konovalov might have objections to removing the colouring, but we wanted to address the issue of better reports on test failures anyway, so I am game.

**Comment by alex-konovalov** [comment]
It wasn't me who added the colouring, and I don't have any objections if it will disappear. So, seems like we're ready to merge this?

BTW, there is a comment: "`CoverToJson` is only here temporarily until its functionality has been published as part of the profiling package" - is this still the case?

**Comment by markuspf** [comment]
Current version of `profiling` has `OutputJsonCoverag` function that does what `CoverToJson` does.

**Comment by markuspf** [comment]
Shall we go for merging this then?

**Pull request merged**
