### PR TITLE
Fix some inconsistency of manual entries

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This commit fixes some of the inconsistency in the manual pointed out in
Issue #538.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@james-d-mitchell thanks! Travis test failed because `make manuals` results in errors - could you please check and fix that?

**Comment by james-d-mitchell** [comment]
Yes, looking into it now.

**Comment by james-d-mitchell** [comment]
I think I fixed it.

**Comment by alex-konovalov** [comment]
Thanks - it builds now. Looks good to me (and as soon as #538 will be merged, we may run such test easier and clean up the rest).

Maybe one minor remark: to use consistent style, use capital letter in `Synonym` instead of
```
<Filt Name="IsReesMatrixSubsemigroup" Arg="R" Type="synonym" />
```
to maintain consistent style. The GAPDoc manual says "The `Type` attribute can be any string, but it is thought to be something like `"Category"` or `"Representation"`, and in other places this field is started from a capital letter, as, for example, in
``` 
<Filt Name="IsTransformationCollection" Arg="obj" Type="Category"/>
```

**Comment by james-d-mitchell** [comment]
I've changed "synonym" to "Synonym" in 4 places. Please let me know if I should do anything further!

**Comment by alex-konovalov** [comment]
@james-d-mitchell thanks - there are also occurrences in monoid.gd and semigrp.gd, maybe forgot to add file before `git commit --amend`?

**Comment by james-d-mitchell** [comment]
Ooops, missed those ones. Changed them now.

**Comment by alex-konovalov** [comment]
@james-d-mitchell thanks - looks good now!

**Pull request merged**
