### PR TITLE
Add RegisterTNUM functionality (wip, HPC-GAP)

### PR DESCRIPTION
**Pull request by markuspf**
This is a port of @fingolfin's code for GAP in #19. @rbehrends could you have a quick look as to whether we'll need more thread safety (and how to achieve it)?
The code as is could register a TNUM and it could be used without the tables being filled in another thread.

### CODE REVIEW

**Comment by markuspf** [comment]
This breaks  HPC-GAP on startup at the moment, so I will investigate.

**Comment by markuspf** [comment]
There was an overlap in TNUMs that I introduced by overlooking quite a lot of them from HPC-GAP. I hope this is the correct behaviour, but maybe @rbehrends or @fingolfin could have a look whether it actually is.

**Comment by alex-konovalov** [comment]
I've just submitted PR #216 - this will unblock this issue, making possible to document this properly in the Development manual, keeping that in a single PR.

**Comment by alex-konovalov** [comment]
@markuspf shall this be merged now, too?

**Comment by markuspf** [comment]
If someone enlightens me about the purpose of the list functions that I have removed in my last commit, then we can merge this now.

**Comment by fingolfin** [comment]
@markuspf Not sure what you are talking about, and what your "last commit" exactly is. Can you provide a SHA-1 and/or explain what you mean?

**Comment by markuspf** [comment]
@fingolfin I mean what I did in 07da28ae

**Comment by fingolfin** [comment]
Ah, I see. Well, `IsbbListFuncs` etc. were added to help implement support for arbitrary index objects for `[]` and `[]:=`. But they turned out to be superfluous, and were later removed. (BTW, git pro hint: with `git log -G IsbbListFuncs` on the master branch, you can quickly find the commit they were originally removed by me, namely 1485ae9ef8bd7025e7e6da444328335c561a6bc1 -- and if you do this on the old repository, you can even see the commit Steve add this -- sometimes in 1999... it just took us 16 years to complete that feature, I guess :).

**Comment by markuspf** [comment]
@fingolfin thanks for both the clarification and the git pro tip, I'll keep that in mind. I'll merge this now then.

**Pull request merged**
