### PR TITLE
use early methods for tag based operations

### PR DESCRIPTION
**Pull request by ThomasBreuer**
This is a follow-up of #5344, according to a comment in #4398.

### CODE REVIEW

**Comment by fingolfin** [comment]
The documentation test fails in the line
```gap
d1:= DiagonalMatrix( GF(9), [ 1, 2 ] * Z(3)^0 );
```
Both @ThomasBreuer and me had trouble reproducing this, so I went and did exactly what the CI does for testing the manuals (i.e. following the steps in `dev/ci.sh` for the `testmanuals` test suite...

... and the problem seems to be caused by saving and restoring workspaces:
```
$ ./gap -b -A
gap> SaveWorkspace("testmanuals.wsp");
true
gap> QUIT;
$ ./gap -b -L testmanuals.wsp
gap> d1:= DiagonalMatrix( GF(9), [ 1, 2 ] * Z(3)^0 );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `DiagonalMatrix' on 3 arguments at /Users/mhorn/Projekte/GAP/gap/lib/methsel2.g:250 called from
DiagonalMatrix( DefaultMatrixRepForBaseDomain( R ), R, vector
```
I've not yet dug deeper from here, I first need some sleep.

**Comment by ChrisJefferson** [comment]
The workspace issue is fixed (hopefully!) in #5400

**Comment by ThomasBreuer** [comment]
@ChrisJefferson Thanks a lot for the fix.
As far as I understand, the manual tests are currently the only place where GAP workspaces are exercised.
Would it make sense to add a test that first creates a workspace and then runs the tests from `testinstall` and `teststandard` with this workspace?

**Comment by fingolfin** [comment]
@ThomasBreuer Yes that would make sense.

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
