### PR TITLE
Remove primgrp, smallgrp, transgrp from required packages

### PR DESCRIPTION
**Pull request by fingolfin**
This starts work on issue #2434. Let's see what breaks, if anything.

Though we may not see any breakage without dedicated tests, at least in packages...

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin thanks - just to let you know I've seen this and will run extended tests of PR using my parametrised Jenkins build - I'm specifying the number of the PR, and then id does the same as in 
 the nightly build for master or stable, but for this PR.

The changes are obviously correct, it's the impact of them that we need to estimate and report to authors of affected packages.

**Comment by alex-konovalov** [comment]
Observed problems are of different kinds:

* Tests calling functions from these packages, e.g.

    List(AllSmallGroups(60), g -> Size(FrattiniSubgroup(g)));

2. Tests calling library functions relying on these packages, e.g.

```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pull-request-quickt\
est/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/install/label/kovacs/GAP-pull-reques\
t-snapshot/tst/testinstall/opers/MaximalNormalSubgroups.tst:32
# Input is:
SortedList(List(MaximalNormalSubgroups(D2), StructureDescription));
# Expected output:
[ "C18", "D18", "D18" ]
# But found:
Error, the Small Groups identification is required but not installed
########
```

3. Side effects e.g.:

```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pull-request-quickt\
est/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/install/label/kovacs/GAP-pull-reques\
t-snapshot/tst/testinstall/ctblmono.tst:117
# Input is:
TestMonomial( chi );
# Expected output:
rec( comment := "degree is index of Hall subgroup", isMonomial := true )
# But found:
rec( comment := "codegree is prime power", isMonomial := true )
########
```

4. Warnings and break loops when packages are loaded

5. Manual examples 

6. An of course, default tests of GAP packages specified in their `PackageInfo.g` files.

I think one of the first modifications of this PR would be to add these three packages to the set of packages loaded by default: 

https://github.com/gap-system/gap/blob/42789e61c61440f24663e08731b5351ef1ae2b6b/lib/package.gi#L1751

**Comment by alex-konovalov** [comment]
@fingolfin ping?

**Comment by fingolfin** [comment]
Updated as requested

**Comment by alex-konovalov** [comment]
The number of diffs is still overwhelming. I would prefer to deal with this one by one. Either there should be three separate PRs, or you can try now to remove only PrimGrp and see what happens. The majority of diffs are coming from SmallGrp, and we need to discuss how to deal with that.

**Comment by fingolfin** [comment]
To be honest, I am not sure it's worth the bother, so I don't intend to do anything about this PR. It really was meant more as a reminder; for now I think there are far more important issues to think about.

**Comment by alex-konovalov** [comment]
Fine, so the summary is that many problems show up, they are classified as below, and we need to discuss how to deal with them and in which priority.

1. Tests calling functions from these packages
2. Tests calling library functions relying on these packages
3. Side effects (diffs when the test does not call a function from a package explicitly - less obvious)
4. Warnings and break loops when packages are loaded
5. Manual examples (now they run without diffs with default packages, but with errors when those three packages are missing)
6. Default tests of GAP packages specified in their PackageInfo.g files.

The complexity for untangling this for each package may be different.

**Comment by fingolfin** [comment]
This PR has no chance to be merged anytime soon, if ever, and at the same time is trivial, so I don't see a point in keeping this open.

**Pull request closed without merging**
