### PR TITLE
Rearrange test files into directories

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This looks like a large patch, but all it does is rearrange the test files into directories.

The main advantage of this (to my mind) is that it removes various pieces of "magic", like hard-wiring which tests are in certain files, or looking for the hard-coded string "to be run in testinstall.g", which is missing from several files which should probably have it.

There are still a number of bits of the test suite which can be improved, but this patch should do the heavy lifting.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
It looks good to me. I've also experimented with this PR in a local clone. It may be a good time to merge this now, since nightly tests are in a good stable state. For a clean testing, better not to merge any other PRs closely to merging this PR, to avoid them interfering with each other.

**Comment by ChrisJefferson** [comment]
I'll just give it another 24 hours in case anyone else wants to comment (as it's a fairly major shift), then merge it if no-one complains.

I imagine there will be some fall-out, but we'll get to that!

**Comment by alex-konovalov** [comment]
So far everything goes well after this merge, with Friday nightly tests and with weekly wrapping of the release candidates. Thank you @ChrisJefferson for making this transition so smooth. I had only to make two small commits to fix one `make` target and also to change the location of the piece of the manual contained in `teststandard.g`.

One more minor thing: I've observed that `ctbl.tst` is not part of `testinstall`, but it requires GAP Character Table library. That "broke" the following scenario: there is a test to check that GAP compiles without warnings. It compiles it with `-Werror` option and then runs `testinstall.g`. It uses a lightweight archive with only the GAPDoc package, and no other packages, to reduce the network traffic. Of course, now it reports fails because of `ctbl.tst`.

Possible options to fix this may include:
1) Moving `ctbl.tst` out of `testinstall`.
2) Not running `testinstall.g` as a part of the compiler test. If the resulting GAP build would not be runnable, we would detect it elsewhere anyway.
3) Reorganising tests further and keep tests that require packages separately.

Any preferences?

**Comment by ChrisJefferson** [comment]
We should move ctbl.tst out of testinstall. I put some things in there
that seemed very fast. Obviously there was a good reason that one was not
in testinstall!

Longer term, we might want to further sort by package requirements.

Chris

**Comment by alex-konovalov** [comment]
Thanks. For now, I've moved ctbl.tst to teststandard.

**Pull request merged**
