### PR TITLE
Disallow transitive group of degree 1

### LINKED ISSUE #797: TransitiveGroup(1,1) fails
### Observed behaviour
```
gap> NrTransitiveGroups(1);
1
gap> TransitiveGroup(1,1);
Error, List Element: <list>[1] must have an assigned value in
  l[5] := BlistStringDecode( l[5], TRANSPARTNUM[deg] - 1 ); at /Users/caj/reps/gap/gap/trans/trans.grp:323 called from
TRANSProperties( deg, num ) at /Users/caj/reps/gap/gap/trans/trans.grp:355 called from
<function "TransitiveGroup">( <arguments> )
 called from read-eval loop at *stdin*:10
you can 'return;' after assigning a value
```

### Expected behaviour
I get the transitive group on one point (the identity group), or return `fail` for NrTransitiveGroups(1)
### Copy and paste GAP banner (to tell us about your setup)
 GAP v4.8.3-643-g3460711-dirty of 2016-05-11 09:25:22 (BST)

This at least hasn't worked since 4.7.2

### PR DESCRIPTION
**Pull request by hulpke**
This fixes #797

### CODE REVIEW

**Comment by markuspf** [comment]
Do you mean "degree 1" though?

**Comment by hulpke** [comment]
Yes, I mean 1.

**Comment by alex-konovalov** [comment]
@ChrisJefferson since #797 submitted by you, are you happy to merge this?

**Comment by ChrisJefferson** [comment]
Yup, looks good.

**Pull request merged**
