### PR TITLE
Add PushPlist helper

### PR DESCRIPTION
**Pull request by fingolfin**
I have a few more commits with this prepared, but they are bigger, so I'd rather get this PR merged first, and then submit the other changes as separate PRs.

### CODE REVIEW

**Comment by fingolfin** [comment]
Note that there is already a kernel function `AddPlist` which however performs extra checks I'd like to avoid here.

Also, I was wondering whether to rename this to `PUSH_PLIST` or `PushPlist`, as it really only allows adding to the end of a plist (in contrast to `Add` on the GAP level, which takes an optional position argument).

In that case, I'd be tempted to also add  `POP_PLIST` and `POP0_PLIST` (resp. `PopPlist`/`Pop0Plist`), which remove the last element (and differ as usual in what they do when the given list is empty)

**Comment by ChrisJefferson** [comment]
I wonder if this should be PushPlist instead, mainly because the ALL_CAPS functions never seem to call `CHANGED_BAG` themselves`

**Comment by ChrisJefferson** [comment]
Of course, there might well be some ALL_CAPS functions which do called CHANGED_BAG, I'm not claiming this is a strict rule, but my experience (as the ALL_CAPS functions, until recently, were mostly single line macros).

**Comment by fingolfin** [comment]
@ChrisJefferson updated. better?

**Comment by ChrisJefferson** [comment]
Looks good now, will just wait for tests to cycle.

**Pull request merged**
