### PR TITLE
Remove template for GitHub pull requests

### PR DESCRIPTION
**Pull request by fingolfin**
Please make sure that this pull request:

- [ ] is submitted to the correct branch (the stable branch is only for bugfixes)
- [ ] contains an accurate description of changes for the release notes below
- [X] provides new tests or relies on existing ones
- [ ] correctly refers to other issues and related pull requests

### Tick all what applies to this pull request

- [X] Adds new features
- [X] Improves and extends functionality
- [X] Fixes bugs that could lead to crashes
- [X] Fixes bugs that could lead to incorrect results
- [X] Fixes bugs that could lead to break loops

### Write below the description of changes (for the release notes)

This PR removes our template for GitHub PRs. I find that template useless, and always remove it when submitting a PR. This one is an exception, to demonstrate what the template looks like, and also to remind of the fact that information in it need not be accurate anyway: You must check whether a branch was submitted to the right branch anyway -- if we want to keep track of that, let's use a label. Most other checkboxes can also be handeled by labels.

And finally, if information is missing in a PR, we just ask for it (if we keep asking the same questions, we can start using "Saved Replies", see https://help.github.com/articles/working-with-saved-replies/

### CODE REVIEW

**Comment by alex-konovalov** [comment]
I am perfectly happy with people just removing the template text and starting to write their own description. But I do think that the template is useful, especially for new contributors, and for changes that are worth describing in release notes, so I don't want to see it gone completely. I've used it myself in #1144 and find it helpful.

However, I agree that it's annoying that it is too long, and it will be useful to squeeze it. For example:

```
**This is just a reminder, feel free to delete it**: Please make sure to submit pull request 
to the correct branch (the stable branch is only for bugfixes) and provide tests.

**Only for changes to be listed in release notes**: give an accurate description and tick all what applies:
 -- [ ] Adds new features
 -- [ ] Improves and extends functionality
 -- [ ] Fixes bugs that could lead to crashes
 -- [ ] Fixes bugs that could lead to incorrect results
 -- [ ] Fixes bugs that could lead to break loops
```

**Comment by fingolfin** [comment]
I don't think that second section is useful at all. First off, it requires the submitter to know (or decide?) whether the PR should be listed in the releases notes. This is already where it goes wrong, IMHO.
Next, the information therein could be collected via labels, and IMHO better, because labels are searchable. E.g. there could be an "add-to-release-notes" label; then it'd become trivial to list all merged PRs that have this label. As for the other checks, we already have labels for "new feature", "enhancement", "bug", "crashes", "wrong result", "unexpected error".

Of course these are not applied consitently -- just as those checkbox are not consistently checked.

**Comment by alex-konovalov** [comment]
OK, the 2nd section addresses the following problem: when there is a time to collate all descriptions for the release announcement, many of them are either missing or written informally, and it requires more efforts to put them together than it should be. An alternative is to drop that completely, and refer to the list of issues/PRs under release milestone, but that would contain a lot of noise (see e.g. [here](https://github.com/gap-system/gap/pulls?q=is%3Apr+milestone%3A%22GAP+4.9.0%22+is%3Aclosed) for coming GAP 4.9). 

I agree with the argument that it may be not known to the submitted in advance. So asking for a description and checkboxes could be moved to one of the "saved replies" to be asked later. The label "for-release-notes" sounds like a good alternative idea.

So, shall we then reduce the template to have a last-minute  reminder about correct branch and also about tests?
```
**This is just a reminder, feel free to delete it**: Please make sure to submit pull request 
to the correct branch (the stable branch is only for bugfixes) and provide tests.
```
If there is a strong support for deleting this template completely, please go ahead - I will not merge this myself though ;-)

**Comment by hungaborhorvath** [comment]
I used the template exactly once, and I recall that it took too much time (relatively) to fill it out. In all other cases I just got annoyed and removed all text.

**Comment by alex-konovalov** [comment]
So, shall we leave just this text then?
```
**This is just a reminder, feel free to delete it**: Please make sure to submit pull request 
to the correct branch (the stable branch is only for bugfixes) and provide tests.
```

**Comment by markuspf** [comment]
To be completely honest, I am still in favour of just removing the template entirely.

**Comment by alex-konovalov** [comment]
Ok, fine. We can always restore it if need be. But we do must keep some checklist and maintain discipline while merging PRs: branch, tests, description, closing related issues, etc.

**Pull request merged**
