### PR TITLE
Replaced ReadTest by Test in the dev manual

### PR DESCRIPTION
**Pull request by alex-konovalov**
I've started revision of the GAP Development manual - at the moment with a small change and a pull request, mainly to advertise this task in the TODO list and solicit contributions.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This something that I still want and intend to do. Assigned to myself and set milestone 4.9.0.

**Comment by fingolfin** [comment]
@alex-konovalov ping?

**Comment by fingolfin** [comment]
This needs to be rebased now, and then we can merge it, I think.

**Comment by alex-konovalov** [comment]
@fingolfin rebased!

**Comment by alex-konovalov** [comment]
The rest of this file is outdated - please don't merge, I will clean it up a bit more.

**Pull request merged**
