### PR TITLE
Hpcgap merge nov25

### PR DESCRIPTION
**Pull request by ChrisJefferson**
New mega-merge for HPC-GAP.

EDIT: Now passing all tests (hopefully)

The biggest issue is that the new Timeout functionality doesn't work. I haven't investigated at all how hard it would be to fix it, but by "luck", as HPC-GAP doesn't use configure, it compiles as disabled so users can't call it anyway.

### CODE REVIEW

**Comment by rbehrends** [comment]
With regard to `CallWithTimeout()`, I discussed the details [here](https://github.com/gap-system/gap/pull/331#issuecomment-154221726). I'm currently a bit busy with trying to get generational GC to work with HPC-GAP, so I don't have the time to dig into the `CallWithTimeout()` issues myself at the moment.

**Comment by alex-konovalov** [comment]
@ChrisJefferson thanks - seems to me that `CallWithTimeout` is the only thing that fails Travis tests. I am inclined to merge this anyway while it's fresh, and maybe fix or exclude the test temporarily from HPC-GAP until timeouts will be enabled.

**Comment by ChrisJefferson** [comment]
The timeout stuff now hopefully fixed (by being siabled, so the functions always fail)

**Comment by rbehrends** [comment]
To clarify something else: HPC-GAP does use configure, but the one in `hpc/configure`, which doesn't generate a Makefile. This is not a happy solution (because `hpc/configure` is manually generated by simply removing the `ln -sf ... Makefile` line from the original configure), but HPC-GAP still depends on and uses the configure script. The generation of `hpc/configure` could in principle be automated via:

```sh
egrep -v '^ln -sf .* Makefile$' configure > hpc/configure
```

or something similar.

**Comment by ChrisJefferson** [comment]
Actually, please just wait a while before merging -- I used some new software and the history looks horrible.

**Comment by fingolfin** [comment]
> I'm currently a bit busy with trying to get generational GC to work with HPC-GAP [...]

That's pretty cool, actually :). Will this be usable together with `malloc` allocation?

**Comment by rbehrends** [comment]
> That's pretty cool, actually :). Will this be usable together with malloc allocation?

It is still using the Boehm GC (which does have a generational API), so, yes. I have no idea yet what this will give us in terms of performance, though. I'm nowhere near the point where it is ready for testing.

**Comment by alex-konovalov** [comment]
@ChrisJefferson is this ready to merge now? Seems like you've managed to squeeze all similarly looking "imerge" commits.

**Comment by ChrisJefferson** [comment]
Yep, this is good (I hope!). I have made issue #377 to represent the unimplemented timeout functionality.

**Pull request merged**
