### PR TITLE
Print issue tracker, maintainers and contributors in package banners

### PR DESCRIPTION
**Pull request by fingolfin**
If available, print the issue tracker URL as part of the default package banner. Also, if the list of package maintainers is non-empty and different from the list of package authors, always print it. Both changes are meant to help users to identify whom to contact about issues.

Finally, any people in the person record who are neither author nor maintainer are listed under "with contributions by". This matches what GitHubPagesForGAP does, and how various packages seem to use these fields. It means that we now really list all people in the persons record at least once in the default package banner.

Some examples:

### All persons are both author and maintainer: no change
```
Loading  AutoDoc 2018.09.20 (Generate documentation from GAP source code)
by Sebastian Gutsche (http://wwwb.math.rwth-aachen.de/~gutsche/) and
   Max Horn (http://www.quendi.de/math).
Homepage: https://gap-packages.github.io/AutoDoc
Report issues at https://github.com/gap-packages/AutoDoc/issues
```

### List of authors and maintainers differ
```
Loading  AutPGrp 1.10 (Computing the Automorphism Group of a p-Group)
by Bettina Eick (http://www.icm.tu-bs.de/~beick) and
   Eamonn O'Brien (http://www.math.auckland.ac.nz/~obrien).
maintained by:
   Bettina Eick (http://www.icm.tu-bs.de/~beick) and
   Max Horn (http://www.quendi.de/math).
Homepage: https://gap-packages.github.io/autpgrp/
Report issues at https://github.com/gap-packages/autpgrp/issues
```
```
Loading  AtlasRep 1.5.1 (An Atlas of Group Representations)
by Robert A. Wilson (http://www.maths.qmw.ac.uk/~raw),
   Richard A. Parker (richpark@gmx.co.uk),
   Simon Nickerson (http://nickerson.org.uk/groups),
   John N. Bray (http://www.maths.qmw.ac.uk/~jnb), and
   Thomas Breuer (http://www.math.rwth-aachen.de/~Thomas.Breuer).
maintained by:
   Thomas Breuer (http://www.math.rwth-aachen.de/~Thomas.Breuer).
Homepage: http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep
```
```
Loading  IO 4.5.4 (Bindings for low level C library I/O routines)
by Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef).
maintained by:
   Max Horn (http://www.quendi.de/math).
Homepage: https://gap-packages.github.io/io
Report issues at https://github.com/gap-packages/io/issues
```

### Packages "with contributions by"

Some packages have "contributors", e.g. in Homalge (ping to @mohamed-barakat). I think this change would also allow `semigroups`, `recog` and `xmod` to switch to the default package banner.
```
Loading  HomalgToCAS 2018.06.15 (A window to the outer world)
by Thomas Bächler (http://wwwb.math.rwth-aachen.de/~thomas/),
   Mohamed Barakat (http://www.mathematik.uni-kl.de/~barakat/),
   Simon Görtzen (http://wwwb.math.rwth-aachen.de/~simon/),
   Sebastian Gutsche (http://wwwb.math.rwth-aachen.de/~gutsche/), and
   Vinay Wagh (http://www.iitg.ernet.in/vinay.wagh/).
with contributions by:
   Thomas Breuer (http://www.math.rwth-aachen.de/~Thomas.Breuer/) and
   Frank Lübeck (http://www.math.rwth-aachen.de/~Frank.Luebeck/).
maintained by:
   Mohamed Barakat (http://www.mathematik.uni-kl.de/~barakat/) and
   Simon Görtzen (http://wwwb.math.rwth-aachen.de/~simon/).
Homepage: http://homalg-project.github.io/homalg_project/HomalgToCAS/
```

```
Loading  Digraphs 0.13.0 (Digraphs - Methods for digraphs)
by Jan De Beule (http://homepages.vub.ac.be/~jdbeule/),
   Julius Jonusas (http://www-groups.mcs.st-andrews.ac.uk/~julius/),
   James Mitchell (http://goo.gl/ZtViV6),
   Michael Torpey (http://www-groups.mcs.st-andrews.ac.uk/~mct25/), and
   Wilf Wilson (http://wilf.me).
with contributions by:
   Stuart Burrell (sb235@st-andrews.ac.uk),
   Luke Elliott (le27@st-andrews.ac.uk),
   Christopher Jefferson (http://caj.host.cs.st-andrews.ac.uk),
   Markus Pfeiffer (https://www.morphism.de/~markusp/),
   Christopher Russell (cr66@st-andrews.ac.uk), and
   Finn Smith (fls3@st-andrews.ac.uk).
maintained by:
   James Mitchell (http://goo.gl/ZtViV6).
Homepage: https://gap-packages.github.io/Digraphs
Report issues at https://github.com/gap-packages/Digraphs/issues
```

```
Loading  Guarana 0.96.1 (Applications of Lie methods for computations with infinite polycyclic groups)
by Björn Assmann (bjoern@mcs.st-and.ac.uk).
with contributions by:
   John McDermott (jjm@mcs.st-and.ac.uk).
maintained by:
   The GAP Team (support@gap-system.org).
Homepage: https://gap-packages.github.io/guarana/
Report issues at https://github.com/gap-packages/guarana/issues
```

### CODE REVIEW

**Comment by ssiccha** [comment]
@fingolfin @ThomasBreuer I'ld suggest that we use the way package banners are printed like in this PR as the default. They provide useful information to people that are not that familiar with GAP.

OTOH there could be a `UserPreference` that tells GAP to print compact banners instead. That would then be another issue.

**Comment by stevelinton** [comment]
In the Jupyter (and any similar) interfaces, it would be nice to "fold" this information away by default, so that what printed was a link you could click on to expand the details in some way.

While that obviously goes beyond the scope of this PR, are there any considerations in the _way_ it is implemented that might make that easier in the future? @markuspf?

**Comment by fingolfin** [comment]
@frankluebeck I have now updated and extended the banner tests.

@ThomasBreuer @ssiccha I agree that an option / user preference to get compact banners would be useful (of course it'd only affect packages using the default banner -- and this PR is hopefully going to allow a few more packages to switch to the default banner). I'd be happy to review such a PR!

**Comment by ThomasBreuer** [comment]
@ssiccha I disagree.
When a user --in particular a user who is not familiar with GAP-- just wants to load a package
and gets several screens full of banners from this package and its needed and suggested packages
then I regard this neither as useful nor as information.
Altogether one line of version info for all the packages that got loaded would be more reasonable.

I like the idea of @stevelinton to show the long version of a package banner on demand.
In a classical GAP session, a function that shows the full banner could do that job.

**Comment by ssiccha** [comment]
@ThomasBreuer Ah, one could do something like print the compact banner per default and have a line like `For information where to send bug reports and questions see NotSoCompactPackageBanner("pkgname");`. That's what I meant with "useful information", whom to contact.

Would that step on any package authors, maintainers, or contributors' toes since then their names won't be printed when loading a package?

**Comment by alex-konovalov** [comment]
@ssiccha I think this is too radical reduction which is on the other side of the scale, opposite to @fingolfin's suggestion. To make it shorter, perhaps we can print people's names but not their homepage URLs? While shortening, we should remember that `Homepage` and `Report issues` are very important, and do not throw them away.

**Comment by ChrisJefferson** [comment]
I also think this might make input too long.

As a practical example, at the moment loading digraphs is 21 lines -- quite a lot of screen but at least I can still see what I was typing. With this PR it becomes 37 lines, scrolling whatever I was doing way off the top of the terminal.

**Comment by alex-konovalov** [comment]
@ChrisJefferson just title/version results in people sometime asking questions all over the internet, but not in the right place, or googling and discovering outdated pages hosted elsewhere, but not latest package pages. That's why I said that we should remember that `Homepage` and `Report issues` are very important, and do not throw them away.

**Comment by ChrisJefferson** [comment]
I will cope with displaying information about packages which a user explicitly loaded. DIsplaying it for required packages doesn't sound useful -- If a user of semigroups finds a bug, how are they supposed to know if they should report it at the bug tracker of semigroups, digraphs, GRAPE, genss, orb, IO or GAP?

**Comment by sebasguts** [comment]
I think this output is probably too long. When some packages from the homalg project are loaded, they might as well load 20 packages with them (I know, this is a different problem). Adding more information to the banners makes it harder to find information in the output for those who want to find, say, loaded package versions. Other people might just be overwhelmed by all the information and might never look at it either.

Furthermore, I think @alex-konovalov has a point that when an error occurs, it is unclear to which issue tracker a bug report has to be send, as there might be several to choose from.

@stevelinton : In Jupyter folding could be done by returning the banner strings as HTML, probably using the `<details>` tag.

**Comment by ThomasBreuer** [comment]
I think that we have two issues.
First, we need something like a *full package banner*,
will all information that may be of interest, preferably with clickable links.
Second, we have to decide what should be shown by default as a side-effect
when a package gets loaded;
the ongoing discussion indicates that this should not be the full package banner.

Could we merge the current pull request,
which deals with the improvement of the full package banner,
and open a new issue for discussing the question about the default
side-effect when a package gets loaded?

**Pull request merged**
