### PR TITLE
[WIP] Accessing list entries and record components of expressions 

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Implementing the original requirements from #457.

### CODE REVIEW

**Comment by fingolfin** [comment]
So, what is the status of this? Any particular known issues? Anything missing? Apart from documentation for this new feature.

If not, I am all for merging it -- though I am a bit scared of "forgetting" to document this new feature. And announcing it to people once 4.9 is released. Do we have a good scheme for taking care of that already? If not, we should think about setting one up. Perhaps @alex-konovalov can comment?

**Comment by alex-konovalov** [comment]
@fingolfin: I've created a new Wiki page for the overview of changes between GAP 4.8. and 4.9: https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.8-and-GAP-4.9. On that page we should collect important changes which should be included in the release overview. If you don't have time to polish formulations, or even to write several sentences, just put a number of an issue or a pull request under one of the appropriate headings on that page, so this information will be remembered and you or someone else may improve the description later.

**Comment by markuspf** [comment]
I think we should add documentation and merge this. I'd hit the merge button right now, but I do agree with Max that we'd end up with yet another undocumented feature.

**Comment by ChrisJefferson** [comment]
I can't decide where to put documentation for that.. I mean we never really clearly list anywhere we can / can't index the results of function calls, etc.

We should be sure to mention it in release notes, for existing GAP users.

**Comment by frankluebeck** [comment]
I would say that an explicit documentation is not needed in this case. It is more that this nice pull request makes things work which some people from time to time expected to work anyway.

Maybe an entry in a CHANGES file which gives a few examples of code that now works would be appropriate?

**Pull request merged**
