### PR TITLE
Method for PositionsProperty on non-dense Lists

### PR DESCRIPTION
**Pull request by sebasguts**

### CODE REVIEW

**Comment by sebasguts** [comment]
@fingolfin Did so, do I get my bonus points ;)?

**Comment by fingolfin** [comment]
@sebasguts sure, and a pony and a rainbow!

**Comment by alex-konovalov** [comment]
@sebasguts bonus points are awarded only if you will help to fix (50% points if at least identify the reason) of the failure of your newly submitted test when all available packages are loaded: https://travis-ci.org/gap-system/gap-docker-master-testsuite/jobs/316407774

**Comment by sebasguts** [comment]
Cause QPA has an installation of the function that is installed for arbitrary lists, but does not work on lists with holes. I will provide them a patch.

**Comment by fingolfin** [comment]
That patch would consist of them removing their `PositionsProperty`, right? Because it seems to offer nothing beyond what the built-in `PositionsProperty` does?

Also, unless they release a fixed version quickly, we could raise the rank of our `PositionsProperty` artificially.

**Comment by sebasguts** [comment]
Yep, did a PR to remove the functions from QPA.

**Pull request merged**
