### PR TITLE
kernel: tweak transformations & partial perms code

### PR DESCRIPTION
**Pull request by fingolfin**
* correct some comments
* remove some dead code
* get rid of EqPermTrans22 and EqPermTrans44
* make IdentityTrans internal
* use IS_* macros in FuncOnTuples and FuncOnSets

### CODE REVIEW

**Comment by fingolfin** [comment]
@wilfwilson if you have any questions about any bits in this PR, even basic ones, feel free to ask, I'll try my best to explain

**Comment by wilfwilson** [comment]
Thanks @fingolfin. Actually, looking at it again, and looking at the surrounding code a bit more for context, I think I understand it all. All looks good to me.

**Comment by markuspf** [comment]
@wilfwilson are you running the semigroups tests with gap `master`? Could you have an eye out for breakages, please?

**Comment by wilfwilson** [comment]
@markuspf yes Semigroups is tested against GAP `master` and `stable-4.10` and `stable-4.9`. All seems fine

**Pull request merged**
