### PR TITLE
kernel: add docs for GAP_EvalString

### PR DESCRIPTION
**Pull request by fingolfin**
I wrote this a long time ago as part of a different branch that I never finished, but I figure this one is useful on its own. It addresses issue #2864 at least partially. Perhaps @dimpase is interested in reviewing it?

### CODE REVIEW

**Review by dimpase — CHANGES_REQUESTED** [review]
It's not clear from the description whether side effects of the statements are ignored, or the statements are executed sequentially.

**Comment by fingolfin** [comment]
What you mean with "ignoring side effects of statements "? The whole purpose of statements are their side effects. The only way to suppress them is to not execute them

**Review by dimpase — COMMENTED** [review]
Say, if statement number N wasn't successfully executed, does this mean that statements number N+1, N+2, etc will fail (or even left unevaluated) ?

**Comment by dimpase** [comment]
This differs from the usual interactive use, where a failure to execute a statement brings one into a `brk` loop, right?

**Comment by fingolfin** [comment]
@dimpase edited the comment a bit.

**Review by dimpase — APPROVED** [review]
Thanks. One may wonder why bother to proceed executing commands after an error (but that's for another PR/issue).

**Comment by fingolfin** [comment]
I agree the interface is a bit strange and we could do better these days, but in its defense, back when Markus wrote it, things in the GAP kernel were a lot more tangled up so it wasn't clear how. Also, this interface was originally created for use in Jupyter notebooks, and apparently (??) it was deemed "sensible" to do it that in that situation... though I don't know how much was intention and how much was "we need to wrangle this into something sensible and this it the best we can achieve for now"...

Anyway, for now, I only want to document the status quo :-).

**Pull request merged**
