### PR TITLE
kernel: fix syntax error not being reported on REPL

### LINKED ISSUE #4188: REPL silently accepts garbage input
Look at this: notice the two typos in the first input; the first (in PseudoRandom) I fix, but the `:` instead of `;` is left -- and bam, I get no syntax error (but GAP also doesn't do anything).

```
gap> List([1..300], i->Order(PseudoRanom(grp))):
Syntax warning: Unbound global variable
List([1..300], i->Order(PseudoRanom(grp))):
                        ^^^^^^^^^^^
Error, Variable: 'PseudoRanom' must have an assigned value in
  return Order( PseudoRanom( grp ) ); at *stdin*:45 called from
func( C[i] ) at /Users/mhorn/Projekte/GAP/gap.github/lib/coll.gi:665 called from
<function "List">( <arguments> )
 called from read-eval loop at *stdin*:45
type 'quit;' to quit to outer loop
brk> quit;
Syntax error: ; expected
List([1..300], i->Order(PseudoRanom(grp))):
                                          ^
gap> List([1..300], i->Order(PseudoRandom(grp))):
gap>
```

This doesn't happen in GAP 4.11.0, so I suspect this is caused by one of my interpreter refactoring sprints.

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #4188

### CODE REVIEW

**Comment by fingolfin** [comment]
Unfortunately this revives another bug:
```
# Input is:
obj := """
# Expected output:
Syntax error: String must end with """ before end of file in stream:2
# But found:
Syntax error: String must end with """ before end of file in stream:2
Syntax error: ; expected in stream:2
```

**Comment by wilfwilson** [comment]
> Unfortunately this revives another bug, see `tst/testinstall/kernel/scanner.tst`:
> 
> ```
> # Input is:
> obj := """
> # Expected output:
> Syntax error: String must end with """ before end of file in stream:2
> # But found:
> Syntax error: String must end with """ before end of file in stream:2
> Syntax error: ; expected in stream:2
> ```

Is this a bug? I looks to me like both syntax warnings are valid.

**Comment by fingolfin** [comment]
It's not really a bug; it's a extraneous warning; but after thinking again about it, it's there because the invalid input `"""`  actually ends with a new line, so, yeah, it's OK.

So from my POV this could be merged.

**Review by wilfwilson — APPROVED** [review]
I agree.

**Pull request merged**
