### PR TITLE
HPC-GAP: components of CYCLOTOMIC_FIELDS cache are in the wrong region

### PR DESCRIPTION
**Pull request by fieker**
there still is a problem when run twice, but that shows already in
 normal gap

### CODE REVIEW

**Comment by stevelinton** [comment]
Can you at least say which cache?

**Comment by alex-konovalov** [comment]
I'd like to see if this could be fixed without locking `CYCLOTOMIC_FIELDS`. The latter is a list such that in the `n`-th cyclotomic field is stored at position `n`, so perhaps there is no need to lock it around the lines where components of `B` are set. Instead, just making those components immutable may be the solution, if they are not modified in the future. @fieker, could you please provide an example to try?

**Comment by alex-konovalov** [comment]
I have a fix locally - will submit another PR shortly.

**Comment by alex-konovalov** [comment]
thanks @fieker - I've submitted the new fix in PR #86

**Pull request closed without merging**
