### PR TITLE
Remove unused lvars a files

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR removes all declared but unused local variables in the files in the library starting with the letter "a", and removes tabs from one of these files again. 

## Text for release notes

None

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]

**Comment by ChrisJefferson** [comment]
Out of interest, was this done by some kind of script, or hand-checking?

**Comment by james-d-mitchell** [comment]
Done using `gaplint` with a config file that disables all rules except the one that analyses local variables:

https://github.com/james-d-mitchell/gaplint

**Comment by fingolfin** [comment]
Off-topic, but: we could easily add code to the GAP kernel which issues a warning about unused locals. If someone is interested in that, just open an issue to remind us about it; I might work on it (or can leave some hints how to do it).

**Comment by james-d-mitchell** [comment]
@fingolfin good idea, although it would likely generate a very large number of such warnings. This is probably a better approach than the one using gaplint.

**Comment by fingolfin** [comment]
@james-d-mitchell yeah I definitely would want there to be an option to turn off that warning. Then people can work on fixing the warning in the GAP library, and eventually in packages.

**Comment by fingolfin** [comment]
I don't understand what's going on. I've closed and reopened this PR; I've even rebased & force pushed its content. Each time the same CI job ends up as "cancelled". Why?!?

**Comment by fingolfin** [comment]
OK, this time it seems I managed to get it started properly. We'll see

**Pull request merged**
