### PR TITLE
RootFFE for discrete logarithm in finite fields, Updates to magma converter

### PR DESCRIPTION
**Pull request by hulpke**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This is a version of #415 with fixed GAPDoc syntax. My immediate comments are that:
* PR made from the master branch and it mixes two different pieces of functionality
* no tests are provided, neither in the form of manual examples or examples in some test file
* the ManSection is not linked from the main manual, so even though it's added and checked for GAPDoc syntax, it will not appear in the documentation.

**Comment by fingolfin** [comment]
Why was this merged?

This contains dozens of commits, many unrelated. At the very least, this should have been rebased on current master before merging...

**Comment by frankluebeck** [comment]
@hulpke said:
> (The operation is needed for translating a lot of the magma matrix group code and it seemed general enough to merit inclusion in the library.)

Yes, I guessed that this is related to the magma translation. But I do not agree that it is wise to commit such unsatisfactory code to the GAP library.

How about the following strategy: You keep such "first make it work at all" code with your magma translation code. Then you can run the translated code and find out with tests which functions which are missing in the GAP library are performance critical. I'm pretty sure that the equivalent of `RootFFE` is very well implemented in magma, and that this function is indeed performance critical. 

This way you can produce a TODO list of important functions to be thoroughly implemented in the GAP library to get a reasonable performance of the translated code. 

That is better than having bad performing methods in the GAP library which later nee to be rediscovered as culprits of disappointing performance of the translated matrix group code.

**Comment by hulpke** [comment]
@fingolfin 

I was under the assumption it had two commits in 3 files. I am still severely struggling with git and it is possible I have made mistakes. 
I also have to admit that with these problems (and overall negative reaction I am getting to any changes) I am close to throwing in the towel!

**Comment by hulpke** [comment]
@frankluebeck I'm happy to keep the implementation in a ``temp fix'' file as part of the converted code. However the declaration ought to be in the library, I think as it is likely that there will be multiple packages using such a function.

**Comment by markuspf** [comment]
I reverted the merge . I'll help taking it apart into well-defined pieces.

**Comment by fingolfin** [comment]
@hulpke Well, if you scroll up on the GitHub web page for your pull request (i.e. #416 ), then you can see that you just merged some dozens of commits. Though I also vaguely recall that there used to be fewer commtis on this PR. Perhaps you accidentally pushed more changes to the master branch of your fork on github? This causes the pull request to automatically update. If you want the pull request to stay stable, first create a separate branch for it.

This is an important feature of GitHub, not a bug, and a direct corollary of the idea that one should implement new features on branches. I could elaborate, but perhaps here is not the right place for it?

Anyway, let me emphasis that I don't view your changes negative, and value your contributions highly; I am sure others have a similar view. But we are indeed quite frank with feedback here ;-), and try to establish high standards. I think it would be important for you to invest a little (!) more time into learning the basics of git; this of course requires an investment of time on your part, but I think it will pay off on the long run. It should also help to reduce your level of frustration greatly. 

Working with git without learning it properly is a lot like working with a sophisticated mathematical theory without learning it properly: You can do a surprising lot without that, but without proper understanding, you'll run into issues that are incomprehensible to you, simply because you are not aware of some basic assumptions or lemma or fact. And disaster can strike...

So, I renew my offer to help you with learnign more. Be it by suggesting stuff to read on it; answering your questions; skyping with your to explain things; etc.

Finally, as I suggested to you earlier: It might be easier for you to develop that magma conversion code in a separate repository; that way, you don't have to worry about interfering with regular GAP codes, and you don't have to cope with people complaining about that code -- and we don't wouldn't have to review it (well, probably nobody does that right now). That said, this is just a suggestion -- I don't really mind much if you keep developing it the way you do it right now.

**Pull request merged**
