### PR TITLE
Improve transformations code and tests

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This pull requests contains many minor improvements in the transformations code and its tests. It does not contain any changes in functionality except where this involved fixing a bug.

This came out of wanting to remove the randomness in the test file `trans/testinstall/trans.tst`, and to get `trans/testinstall/trans.tst` to run in a more reasonable amount of time (as mentioned in Issue #573). In the process of doing this I rewrote some of the C functions for transformations to improve their complexity, reduce the length of the code, and to make them more robust (by checking their arguments more thoroughly). I also removed several C/GAP functions that weren't used or documented, cleaned up the whitespace is `src/trans.c`, `lib/trans.gi`, and `lib/trans.gd`, reorganised `src/trans.c` and added more comments, and fixed some bugs and inconsistencies.

The file `trans/testinstall/trans.tst` now runs in about 600ms (on my laptop), and tests almost all of the code in `src/trans.c` and `lib/trans.gi`, and doesn't contain any randomness, except to test the function `RandomTransformation`.

The whitespace changes are separate from the other changes. I realise that there are a large number of commits in this PR, I'm happy to rebase this to whatever anyone wants.

### CODE REVIEW

**Comment by markuspf** [comment]
If this is not just a bugfix (and with 68 commits, I daresay it isn't), this should go against `master` not `stable-4.8`.

**Comment by james-d-mitchell** [comment]
Maybe, but I can't get the Semigroups package tests to run against master, so I did against stable-4.8 so that I could check that the changes don't mess anything up.

**Comment by james-d-mitchell** [comment]
I'm just going to let travis finish, then I'll update the PR so that it is against the master branch.

**Comment by james-d-mitchell** [comment]
Hmm, do I have to make another pull request to change this from stable-4.8 to master?

**Pull request closed without merging**
