### PR TITLE
Remove undocumented & unused AgemoAbove

### PR DESCRIPTION
**Pull request by fingolfin**
Last caller was removed 2000-05-23

### CODE REVIEW

**Review by hulpke — COMMENTED** [review]
It is clearly not used. But in general code for `Omega` and `Agemo` was (at least 10 years ago) somewhat haphazard. So this might have been a relic of trying to do it better.

**Review by ThomasBreuer — COMMENTED** [review]
Perhaps we are almost sure that nobody uses the function `AgemoAbove`, but why don't we just move it to `lib/obsolete.gi`?

**Comment by fingolfin** [comment]
@hulpke it definitely was used before the date I listed, but that was when during a rewrite the last caller to it was removed.

@ThomasBreuer well it is a completely undocumented function (not even a code comment hinting at what it does) with trivial code, and no package or GAP library code uses it (and if anything external were to use it, (a) its their fault, and (b) it'd be trivial for them to repair it). As such I see little benefit in putting this into `obsolete.gi`, where it would just keep sitting indefinitely?

**Review by ThomasBreuer — APPROVED** [review]

**Review by james-d-mitchell — APPROVED** [review]
Seems safe to remove this based on what @fingolfin has written

**Pull request merged**
