### PR TITLE
Some more HPC-GAP syncing

### PR DESCRIPTION
**Pull request by fingolfin**
By now, most low-hanging fruits are gone... from now on, for most syncing we likely will have to start adding code to the GAP kernel, too. In this PR this mostly amounts to copying code from the HPC-GAP kernel to the GAP kernel, wrapping the code in `#ifdef HPCGAP` / `#endif` as appropriate.

### CODE REVIEW

**Comment by fingolfin** [comment]
This is contains PR #1228 as a subset, as that is needed to avoid some warnings.

**Comment by markuspf** [comment]
Except for having one commit that syncs two files that seem very unrelated (`finfield.c` and `iostream.c`) this looks good to me. (And the test failure is because of coverage, which for this type of PR isn't really relevant)

**Comment by ChrisJefferson** [comment]
I'll just wait while the travis backlog clears to be on the safe side, then merge this.

**Comment by markuspf** [comment]
We should probably merge this before I complete/redo #1224 (sometime later today), otherwise there'd be conflicts.

**Comment by fingolfin** [comment]
@ChrisJefferson Travis is idle :)

**Pull request merged**
