### PR TITLE
Manual76

### PR DESCRIPTION
**Pull request by cdwensley**
Edits are made to Chapter 76 of the reference manual, "Using and Developing GAP Packages", with two aims in mind: (a) clarify the meaning in places; (b) split 76.2.1, "LoadPackage", into two subsections, with material on automatic loading in a new 76.2.2.

### CODE REVIEW

**Comment by fingolfin** [comment]
Actually, ignore the instructing using `git rebase` I just posted, they won't work with your branch, as it has too many conflicts, being based on an ancient version of the repository. I updated my instructions using `git reset --mixed`, and verified that this works.

**Comment by cdwensley** [comment]
This is clearly an experiment which has not worked, due to my inexperience with GitHub  I have no idea where all these old commits have come from.  As far as I was concerned I was starting from gapdev as of today (not an ancient version); made a new branch, Manual76; edited two files; committed them; copied this to https://github.com/cdwensley/; and issued a PR.  Surely the best thing to do is to close #1862 and start again some time in the future?  But, should I decide to start another branch some time, will the same thing happen?  If so, how to get rid of these old commits?

**Comment by fingolfin** [comment]
As to "will the same thing happen" -- it depends on what exactly you did. Clearly something went wrong. Looking at the history of this PR, I think what happened is that the `master` you started from is *not* the latest `master` branch, but rather a branch you have locally which contains local changes. You can check this by doing `git log --decorate --oneline master` and looking at the output. The output should look something like this:
```
631fdddaf (HEAD -> master, origin/master, origin/HEAD) HPC-GAP manual cleanup
0b21f5a13 Fixed documentation for MakeConstantGlobal and memory_allocated
67dc403d7 Merge pull request #1809 from hulpke/additions
...
```
Note the first line, which says, amongst other things, `master, origin/master` which means that both the `master` branch (on your computer) as well as `origin/master` (i.e. the master on `github/gap-system`.

Anyway, I suspect on your system these differ, and hence `master` and `origin/master` will appear on different lines for you.

To fix this, do this (warning, this wipes out any uncommitted changes): `git checkout master && git reset --hard origin/master`.

To fix your pull request, you can now do this:
```sh
git checkout manual76 # go to your branch
git reset --hard origin/master # reset it to master
git cherry-pick 6db8490a13394a5caa20c2c9dd1cb91df2ab3a8b
```
The last command takes the one change from your "bad" branch and re-applies it.

**Comment by cdwensley** [comment]
Well I have done all of that, but ... 
The command:  git log --decorate --oneline master  initially gave: 
6b1d22c9f (HEAD -> master, origin/master, origin/HEAD, manual76) Merge branch 'master' of https://github.com/gap-system/gap
631fdddaf (upstream/master) HPC-GAP manual cleanup
0b21f5a13 Fixed documentation for MakeConstantGlobal and memory_allocated
... 
After completing the instructions above, the output is: 
6b1d22c9f (origin/master, origin/HEAD, master) Merge branch 'master' of https://github.com/gap-system/gap
631fdddaf (upstream/master) HPC-GAP manual cleanup
0b21f5a13 Fixed documentation for MakeConstantGlobal and memory_allocated
... 
But my gapdev fork at:  https://github.com/cdwensley/gap  still has the message: 
This branch is 23 commits ahead, 1 commit behind gap-system:master, 
while the manual76 branch in the same place has: 
This branch is 24 commits ahead, 1 commit behind gap-system:master. 
At least the one extra commit looks to be correct. 
Perhaps the simplest thing is to delete this fork and my clone of it and start again?

**Comment by cdwensley** [comment]
This PR clearly misconceived, so closed.

**Comment by fingolfin** [comment]
Aha, my mistake, I blindly assumed you had cloned gap-system/gap (and thus ˋoriginˋ would refer to that), but you cloned your own repo (so origin refers to that, and ˋupstreamˋ refers to the official GAP repository.

With that in mind, your output confirms my theory: upstream/master is different from your local master as well as origin/master.

To fix this, you'll have to ˋgit reset --hard upstream/masterˋ your local master; I'd also recommend to change it to pull from upstream, not origin

**Comment by cdwensley** [comment]
It was obviously a big mess.  I have closed the PR; deleted all copies of gapdev; made a new fork and cloned that; and added gapsystem/gap as upstream (hopefully that's the correct procedure).  Only problem is getting the packages working.  It would be useful if either (a) it was possible (i.e. if I knew how) to keep packages in one folder which could be accessed from both gap4r8 and gapdev, or (b) if the downloads page of the GAP website had a packages download option (because I run into the wget problem if I try "make bootstrap-pkg-full").  But I'm sure I can copy the packages over from gap4r8 and get them installed.

**Comment by alex-konovalov** [comment]
@cdwensley for master branch, do not use packages from GAP 4.8. Download this instead: 

* http://www.gap-system.org/pub/gap/gap4pkgs/packages-master.tar.gz

It included latest packages that were picked up for the redistribution and passed internal Jenkins tests, and includes in particular new PrimGrp, SmallGrp and TransGrp packages. This is the very archive that `make bootstrap-pkg-full` tries to get in the master branch.

What is the wget problem that you have?

**Comment by cdwensley** [comment]
Thanks - now downloaded (foolishly, I assumed this archive would create the pkg/ directory). 
I see from the web that wget is not included in OS X on Macs: 
ChristoleysiMac:gapdev christopherwensley$ make bootstrap-pkg-full
/bin/sh: wget: command not found
make: *** [bootstrap-pkg-full] Error 127

**Comment by fingolfin** [comment]
Right. That command should learn to use `curl` instead if `wget` is not available.

**Comment by fingolfin** [comment]
Filed as issue #1866.

**Pull request closed without merging**
