### PR TITLE
Remove Test mode

### PR DESCRIPTION
**Pull request by markuspf**
It didn't seem to be used

Please make sure that this pull request:

- [x] is submitted to the correct branch (the stable branch is only for bugfixes)
- [x] contains an accurate description of changes for the release notes below
- [x] provides new tests or relies on existing ones
- [x] correctly refers to other issues and related pull requests

### Tick all what applies to this pull request

- [x] Removes unused features/code
- [ ] Adds new features
- [ ] Improves and extends functionality
- [ ] Fixes bugs that could lead to crashes
- [ ] Fixes bugs that could lead to incorrect results
- [ ] Fixes bugs that could lead to break loops

### Write below the description of changes (for the release notes)

Test Input and Output facilities were removed.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Good find, looks confusing, and totally unused. is this not quite finished (you've added an `#if 0` somewhere, which I imagine you might want to clean up at some point).

**Comment by markuspf** [comment]
Yeah, I was waiting for the tests to go through before I clean up. There is also some leftover documentation still in there.

**Comment by fingolfin** [comment]
This was used by the old test code; then @frankluebeck wrote the new, much better `Test`, and finally @alex-konovalov removed READ_TEST etc. in d3ef24b36230e0743f809cf17efb4c73f087796d

**Comment by alex-konovalov** [comment]
@fingolfin yes. There are still packages calling `ReadTest` which now delegates to 
```
Test( <filename>, rec( compareFunction := "uptowhitespace" ) )
```
and also displays the message:
```
#I  ReadTest is no longer supported. Please use more robust and flexible
#I  Test. For backwards compatibility, ReadTest(<filename>) is replaced
#I  by Test( <filename>, rec( compareFunction := \"uptowhitespace\" ))
```
I support this PR then.

**Comment by alex-konovalov** [comment]
P.S. "Merging #1107 into master will decrease coverage by 6.13%" ??? How so?

**Comment by fingolfin** [comment]
@alex-konovalov That's a fluke, and caused by codecov receiving incomplete coverage data (probably due to a canceled Travis or AppVeyor build), hence it reports a too low coverage percentage. It should be fixed once the currently running CI builds complete.

**Comment by fingolfin** [comment]
You still have a "DO NOT MERGE!" label on this. Intentionally?

**Pull request merged**
