### PR TITLE
Merge from master to hpcgap-default

### PR DESCRIPTION
**Pull request by alex-konovalov**
This large merge synchronises HPC-GAP with developments happening in the master branch since March 2015.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Travis CI tests seem to be unstable, I will try to restart them to see if the problem persists. I've tested it manually on OS X and Ubuntu Linux - `test{install/travis/bugfix}.g work well, and there are only problems (or two instances of the same problem) in `grpperm.tst` and `grpconst.tst`, both seen before.

I suggest then to merge this (after giving some window to contributors to master branch to revise their code in this PR) in order to test on a wider range of machines using Jenkins.

**Comment by markuspf** [comment]
I am a bit worried about these really big merges. This compiled on my machine, and it passes most of the tests.
I suggest to merge it now, but we have to find a way to merge things, or otherwise we'll break HPCGAP in all the ways that are not fun to debug.

**Comment by alex-konovalov** [comment]
@markuspf I totally agree. We should get into a habit of doing this regularly in small batches, either by merging or cherry-picking. Perhaps at least for each minor release, but in practice this should be even more often. OTOH, we survived some large merges like that in the past :)

**Comment by markuspf** [comment]
I will just hit the button now. No risk, no progress.

**Comment by alex-konovalov** [comment]
Nothing too dramatic detected in Jenkins yet, but new test `listindex.tst` fails in the background thread. Not surprising - new code, not adapted to HPC-GAP. I will try to look tonight.

**Comment by alex-konovalov** [comment]
Just to document how to reproduce this to return later: start HPC-GAP, `!sh` to switch to another thread, then enter:
```
r := NewCategory("ListTestObject",IsList and HasLength and HasIsFinite);
InstallMethod(\[\],[r,IsObject],function(l,ix) return ix; end);
```
and get
```
[5] gap> 
[5] Error, Attempt to read object 4322912432 of type list (plain,hom) without havin\
[5] g read access in
[5]   <compiled or corrupted statement>  called from 
[5] <compiled or corrupted statement>  called from
[5] <function "local function">( <arguments> )
[5]  called from read-eval loop at line 2 of stream
[5] brk> 
```
Then in thread zero:
```
--- Switching to thread 0
gap> OBJ_HANDLE(4322912432);
[ <Operation "IsPNilpotent">, <Operation "IsPSolvable">, <Operation "PCentralSeries">, 
  <Operation "PRump">, <Operation "PCore">, <Operation "SylowSubgroup">, 
  <Operation "SylowComplement">, <Operation "HallSubgroup">, <Operation "InducedPcgs"> ]
```
what looks like some list related to key-dependent attributes.

**Comment by alex-konovalov** [comment]
This should be related to Enhanced list indexing: https://github.com/gap-system/gap/pull/192/files. If I will not find a quick fix, I will create a new issue, since this PR is already merged.

**Comment by alex-konovalov** [comment]
Next step. Rebuilt HPC-GAP with make.hpc debug, now the break loop is more informative:
```
--- Switching to thread 5
[5] gap> r := NewCategory("ListTestObject",IsList and HasLength and HasIsFinite);
InstallMethod(\[\],[r,IsObject],function(l,ix) return ix;[5] <Category "ListTestObject">
 end);[5] gap> 
[5] Error, No read access to object 4348424608 of type list (plain,hom)
[5] in gen/c_oper1.c, line 1929, function HdlrFunc6(), accessing t_2 in
[5]   <compiled or corrupted statement>  called from 
```

**Comment by alex-konovalov** [comment]
Aha, so the inaccessible object is `WRAPPER_OPERATIONS` in the compiled version of the following code from `oper1.g`:
```
# Signal a warning if the operation is only a wrapper operation.
      if opr in WRAPPER_OPERATIONS then
        INFO_DEBUG( 1,
              "a method is installed for the wrapper operation ",
              NAME_FUNC( opr ), "\n",
              "#I  probably it should be installed for (one of) its\n",
              "#I  underlying operation(s)" );
      fi;
```

**Pull request merged**
