### PR TITLE
Fix the build when off_t is 64 bits, but Int is 32 bits.

### PR DESCRIPTION
**Pull request by markuspf**
This was submitted in #171

### CODE REVIEW

**Comment by stevelinton** [comment]
Should we give a more appropriate error in this case if the user tries to call StringFile on a file which is too long to be stored in a string in the 32 bit workspace? It's just about believable that someone would
have a 4G+ data file and accidentally try and read it into a 32 bit GAP.

**Comment by markuspf** [comment]
In principle yes, but what is the size that we cannot (or do not want to) fit?

**Comment by stevelinton** [comment]
It's whenever (off_t)(Int)fstatbuf.st_size isn't equal to fstatbus.st_size. 

In  that case odd things could happen, like StringFile returning just 1GB of a 5GB file, or a negative argument to read.

If the coercions haven't changed the value then StringFile might still fail because it can't allocate memory for the string, but that is what is meant to happen

**Comment by fingolfin** [comment]
From my point of view, this looks good and should be merged.

**Pull request merged**
