### PR TITLE
Add command line option --bare to start GAP without any packages

### PR DESCRIPTION
**Pull request by markuspf**
This requries (and includes) #2950.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
While it's yet another .travis.yml line, do we want to test GAP works with `--bare`? (how well does it work? Does it pass testinstall for example?)

**Comment by markuspf** [comment]
Not all tests work (but a suprising number does!). I'll look at adding a "testbare" target.

**Comment by hulpke** [comment]
What is the difference between --bare and -N (for noautoload)?

**Comment by markuspf** [comment]
@hulpke `-N` disables hidden implications, I assume you mean `-A` (no autoloading of suggested packages? `--bare` does not load *any* packages, in particular it does not load `GAPDoc` which is currently the only `NeededPackage`.
Did `-N` use to do something different from what it does now?

**Comment by alex-konovalov** [comment]
If you will look at "testbare" target, you may also start GAP there with `-O` to disable loading obsoletes. This will help to check they are not reappearing in the GAP library.

**Comment by stevelinton** [comment]
What is the reasoning for this? If a package is "needed" GAP is allowed to fail arbitrarily badly without it, including not loading the library. If you need to start GAP without GAPDoc for some reason, then maybe GAPDoc is not needed, just recommended for interactive sessions or something?

**Comment by stevelinton** [comment]
I'm fine with this, but as @wilfwilson says, it should *not* be user-facing, and for the same reason should not be part of the tests that get run automatically on Pull Requests unless we want to change the rules on what it means for a package to be needed. This is a specialist feature for debugging aspects of library and package loading.

**Comment by wilfwilson** [comment]
@stevelinton would you feel if the text describing the `--bare` option (currently `Start GAP without loading any packages`) included some kind of disclaimer? For example:

> Start GAP without loading any packages (experimental)

Or something of that kind?

**Comment by stevelinton** [comment]
Something of the kind. `experimental` suggests that it might be something we plan to roll out though. How about

`Attempt to start GAP without even needed packages (developer tool)`

**Comment by wilfwilson** [comment]
I prefer that, I've made the change.

**Comment by wilfwilson** [comment]
@wucas I think so. I would recommend using the title of this PR (which I just updated) as the text for the release notes.

**Pull request merged**
