### PR TITLE
Speed up recursion checking

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This PR does two things:

1) Removes 579456e2 (except the tests which still pass). This reintroduces #1286, but at preent I cannot find a way of fixing that issue which does not produce an unacceptable speed loss.

2) Performs a simple optimisation to CheckRecursionBefore, which speeds up it's usage, and improves the performance of code which recurses. This can lead to a 6% improvement in very trivial functions (too trivial to do anything useful...)

### CODE REVIEW

**Comment by fingolfin** [comment]
Could you explain the motivation for this? It seems to be related to speed, but you never quite say how so?

**Comment by ChrisJefferson** [comment]
Sorry, the motivation is that #3577 observed that a number of fairly simple pieces of GAP code have gotten significantly slower than they were in 4.10. On profiling investigation, the code to check the recursion depth show up much higher than they used to do, to the point where in some cases they are over 50% of the profile, given very small functions.

579456e introduced many more increments and decrements of the recursion depth, to try to catch more places where we could enter an infinite loop. While it fixed a bug, it turns out to be quite expensive, so I think for now we should consider reverting the commit.

While profiling this code I found an easy wasy of speeding up the recursion depth check, which I also put in this PR.

**Comment by fingolfin** [comment]
There are some further test failures in `tst/testspecial/stack-depth-rec.g` and `tst/testspecial/copy-weakpointerobj.g`

**Comment by ChrisJefferson** [comment]
I've broken this PR while fiddling with it. Will report back once I've fixed it.

**Comment by ChrisJefferson** [comment]
Now working.

I have disabled a test I previously wrote. On deep inspection, with this PR it ends up always failing, as a value ends up left on the stack which stops GASMAN collecting a particular bag. While I could poke the test until randomly changes in the stack made it pass again, I decided it was easier to just remove it. This test tested what happened when an operation occurred mid-GC.

If we decided we really cared about this, having a more reliable way of forcing a GC to occur at a particular time, and clean up particular bags.

**Comment by fingolfin** [comment]
You say that you disabled "a test", but two tests were removed. I just wanted to double check that was intentional then, and you meant that you had removed two tests?

**Comment by ChrisJefferson** [comment]
So, I think there are two different test removals.

The first commit removes a test which has been around for a long time, but kept failing with this PR. The PR isn't directly related to this test, it just caused random stack fluctuations which caused the test to fail.


When reverting the old commit at the end of the PR, two of the tests are removed as this unmerging broke them.

**Pull request merged**
