### PR TITLE
Fix `Orbits` when called with a range as seeds

### LINKED ISSUE #5056: Using ranges for seeds in Orbits
Please use the following template to submit an issue
(you may delete lines which are not used). Thank you!

### Observed behaviour
```
gap> act := function(omega,g) return PowerModInt(omega,Int(g),15); end;
gap> ugrp := Units(ZmodnZ(Phi(15)));
gap> orbs := Orbits(ugrp,[1..5],act);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `[]:=' on 3 arguments
The 2nd argument is 'fail' which might point to an earlier problem
 at /Users/morse/gap-4.12.0/lib/methsel2.g:249 called from
PositionCanonical( D, o ) at /Users/morse/gap-4.12.0/lib/oprt.gi:1694 called from
op( G, D, gens, gens, act ) at /Users/morse/gap-4.12.0/lib/oprt.gd:654 called from
<function "Orbits for a group, a domain or list, and a function">( <arguments> )
 called from read-eval loop at *stdin*:3
type 'quit;' to quit to outer loop
```

### Expected behaviour
#Same as
```
gap> orbs := Orbits(ugrp,[1,2,3,4,5],act);
[ [ 1 ], [ 2, 8 ], [ 3, 12 ], [ 4 ], [ 5 ] ]
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin21-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.4, AutoDoc 2022.07.10, AutPGrp 1.11, Browse 1.8.14, 
             CaratInterface 2.3.4, CRISP 1.4.5, Cryst 4.1.25, CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.8, GAPDoc 1.6.6, genss 1.6.7, IO 4.7.2, IRREDSOL 1.4.3, LAGUNA 3.9.5, orb 4.8.5, 
             Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.2, RadiRoot 2.9, recog 1.3.2, ResClasses 4.7.3, 
             SmallGrp 1.5, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, utils 0.76
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #5056

### CODE REVIEW

**Comment by hulpke** [comment]
Is there a test example?

**Comment by fingolfin** [comment]
Yes but I forgot to `git add` it 😕. Will do once I am back at a computer

**Comment by fingolfin** [comment]
@hulpke example added

**Review by danielrademacher — APPROVED** [review]

**Comment by fingolfin** [comment]
Backported to stable-4.12 via commit 0a20c1b21

**Pull request merged**
