### PR TITLE
Assorted cleanup, e.g. removes SharedType alias for DataType; documents polycylic specific kernel code

### PR DESCRIPTION
**Pull request by fingolfin**
These are just some cleanup commits, best to look at each commit individually.

[ Procedural note: From a pure point of view, I perhaps should submit three PRs for this. But that seems silly for what amounts to trivial cleanups... For the same reason, I kind of wonder if we should "rebase" this, instead of merging... the only information the "merge" adds is a pointer to the pull request; but for trivial cleanup changes, does that provide any actual benefit? ]

### CODE REVIEW

**Comment by markuspf** [comment]
This looks good to me.

I agree that these trivial cleanups can be rebased, or in some cases even committed directly to `master`, though with due care, etc.

**Comment by fingolfin** [comment]
I added some more changes. One drawback of having all of these in a single PR is that perhaps few people consider themselves able to evaluate each commit in here... So perhaps I should split it into multiple PRs again?

Then again, if people were to just say "commits A, B, C look fine; D is wrong because...; and I can't say anything about the rest", that woud also be helpful :)

That said, I have been using these commits on my system for quite some time, so I am hopeful that they are safe... :)

**Comment by ChrisJefferson** [comment]
I've read all these commits, they look fine and uncontroversial to me.

**Comment by markuspf** [comment]
Yep, once the tests go through I can either merge or rebase, whatever the preference is.

**Comment by fingolfin** [comment]
I certainly prefer rebase for this, but, whatever... :)

**Pull request merged**
