### PR TITLE
Remove zoo related stuff

### PR DESCRIPTION
**Pull request by fingolfin**
The website mostly doesn't mention the `zoo` format anymore; most young people won't even know what it is. And I don't think anybody uses it.

### CODE REVIEW

**Comment by frankluebeck** [comment]
I agree that the zoo-format is no longer needed for the distribution. 

I didn't follow in detail how these scripts (which I wrote quite a few years ago) were changed over time. But originally I used the zoo-format archive as master archive which contained the information about which files are text and which are binary. For UNIX this is not relevant, but maybe still for Windows zip-files?
If yes, be careful that you don't throw away useful information by this change.

**Comment by alex-konovalov** [comment]
Please be careful - we still provide for download GAP 3.4.4 archives in zoo format: http://www.gap-system.org/Gap3/Download3/download.html

**Comment by dimpase** [comment]
it would be good to move zoo to GAP3 section of the GAP website...

**Comment by fingolfin** [comment]
@frankluebeck I carefully verified before making this pull request that nothing inside the `gap` and `gap-distribution` code uses the zoo tool. You are right about the zoo format being historically used for detecting text files, and the function `TextFilesInZooArchive` still exists, but the code calling it is commented out.

@alex-konovalov @dimpase Did you actually look at the download page? :-) Because it already provides the unzoo tool. So, I don't think we have to bundle it with GAP4

**Comment by alex-konovalov** [comment]
@fingolfin fine w/me then. I didn't scroll long enough :)

@frankluebeck BTW, the same page says that you "created an executable of the currently released version of GAP 3.4.4 for Linux on i686 machines" but the link to http://www.math.rwth-aachen.de:8001/~Frank.Luebeck/gap/GAP3/ does not work.

The text/binary classification is done by tools from gap-distribution repository so there is no risk of making a harm to those. I've looked at all suggested changes - happy for them to be merged.

**Comment by dimpase** [comment]
On 28 January 2016 at 10:33, Max Horn <notifications@github.com> wrote:

> @frankluebeck <https://github.com/frankluebeck> I carefully verified
> before making this pull request that nothing inside the gap and
> gap-distribution code uses the zoo tool. You are right about the zoo
> format being historically used for detecting text files, and the function
> TextFilesInZooArchive still exists, but the code calling it is commented
> out.
>
> @alex-konovalov <https://github.com/alex-konovalov> @dimpase
> <https://github.com/dimpase> Did you actually look at the download page?
> :-) Because it already provides the unzoo tool. So, I don't think we have
> to bundle it with GAP4
>

now I am looking; e.g. this one
http://www.gap-system.org/Gap3/Download3/readzoo.html
with Netscape screenshot...
And the one where "Binaries for 68k MACs" are mentioned.

IMHO it's safe to keep the source only. Chances that these binaries work
anywhere are approachi

**Comment by fingolfin** [comment]
Well, actually many modern day "swiss army knife" decompressing tools actually still support .zoo -- E.g. I am on Mac OS X and am using the free tool "The Unarchiver". I just downloaded one of GAP 3.4 .zoo files, and was able to extract it by simply double clicking it. Debian has a `zoo` package. The unzoo and zoo sources can also be found via the Wikipedia page https://en.wikipedia.org/wiki/Zoo_%28file_format%29

All in all, I am not worried :)

**Comment by frankluebeck** [comment]
Yes, it is still no problem to uncompress zoo-files. The version of `unzoo` on the GAP web pages was a hacked version that knew about the `!TEXT!` comments (again, only really relevant for non-UNIX systems). 

@alex-konovalov: please, change the link you mention above to
 http://www.math.rwth-aachen.de/~Frank.Luebeck/gap/GAP3/

**Comment by alex-konovalov** [comment]
@frankluebeck thanks - done in https://github.com/gap-system/GapWWW/commit/93e8d81ddba8d6492f002303e6d533e7a01e0085. Will appear online after next pull from the repository.

**Comment by alex-konovalov** [comment]
I think this is ready to merge. In the unlikely event of needed anything back we can always restore it. I will let someone else press the "Merge" button just in case.

**Pull request merged**
