### PR TITLE
Type inspection tools

### PR DESCRIPTION
**Pull request by markuspf**
This branch will build up to contain the type-system introspection tools I wrote during the OpenDreamKit WP6 workshop. I appreciate input on which functionality is desirable, and how to implement it to be useful for as many people as possible.

I will have a look at what is already there, for example in `ApplicableMethods` to integrate these functions in a useful way.

Please do not merge this branch yet, it is just here for better visibility.

I plan to add
* functions that can iterate over filters, categories, properties, and attributes,
* some functions to deduce relationships between filters, categories, properties and attributes
* I also have functions that can print all installed methods for an operation.
* the output of `ViewString` for types and families is not very nice yet

### CODE REVIEW

**Comment by frankluebeck** [comment]
Are you aware of `BrowseGapMethods`? For example, with
```
BrowseGapMethods([Size]);
```
you get information about all installed methods of the operation `Size`, type `sr` for "select row" to easily read the corresponding source code for each method.

And an unrelated comment: Some time ago I suggested a utility function which does the same as the method selection when an operation is called with some arguments, but which returns the method instead of calling it (note that `ApplicableMethod` is very slow).

**Comment by markuspf** [comment]
Good that you bring that up!

I discovered `BrowseGapMethods` when I was working on the types export at the workshop (and had forgotten about it again by now).

It's a very good example of the kind of tool I'd like. In the Jupyter frontend, I'd like to be able to do context-sensitive help/"tab"-completion based on this kind of information.

**Comment by markuspf** [comment]
Incidentally, I think we should always print the file and line number of where a method is installed in the output of `ApplicableMethod`.
The suggested utility function to return a method instead of running it, I will put on the list of things to do.

**Comment by ChrisJefferson** [comment]
I would personally like a "compact description", which (where possible) remove any results of `InstallTrueMethods` (for example), so (hopefully) the resulting list is shorter and easier to understand.

**Comment by fingolfin** [comment]
Nice project.

**Comment by markuspf** [comment]
Please disregard most of the hackery I did in this branch to collect information about GAPs runtime state, I'll surely clean this up, but we needed a prototype.

**Comment by markuspf** [comment]
I will make more smaller PRs to get this moving forward more smoothly.

**Pull request closed without merging**
