### PR TITLE
Update GMP to version 6.0.0a

### PR DESCRIPTION
**Pull request by markuspf**
This is an attempt at updating the default GMP to 6.0.0a. 

We'll have to make sure that all tests pass, and that windows still works with this change.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thanks. Travis tests use `./configure --with-gmp=system` so this will not be checked. I think it's fine to merge if this works locally for you. Anyhow to test on wider platforms including Windows we have to merge this first.

**Comment by markuspf** [comment]
I have tested this on my machines, which is not very representative since they all run the same system. Should I try and merge this for tests to be run by other people? What fallout would we expect?

We can always revert after all.

**Comment by alex-konovalov** [comment]
Yes, please - then it will be picked up by Jenkins test at 6pm today.

**Comment by ChrisJefferson** [comment]
I have been running 6.0.0 on a few apps (including GAP), hopefully it should just be a drop-in replacement, except for one function (  mpn_bdivmod ), which we don't use.

**Comment by alex-konovalov** [comment]
BTW, answering an earlier question about possible fallout: besides broken test which use test files and manual examples, other things that may happen are appearing of new compiler warnings and possibly breaking some packages. For example, Float package requires that GAP is compiled with GMP support, and some other package(s) requiring GMP for their external binaries may automatically choose GAP's GMP instead of the system one (to ease their installation on system where there is no system-wide GMP installation).

**Comment by stevelinton** [comment]
The release announcement for 6.0.0a mentions some problems on various older FreeBSD and other operating systems

https://gmplib.org/list-archives/gmp-announce/2014-March/000042.html

We should probably at least include a note with GAP that users of such systems should install gap 5 and then user —with-gmp=system.

	Steve

**Comment by alex-konovalov** [comment]
@markuspf this went well - perhaps we don't have to keep the extern/gmp-5.0.5 tar.gz archive in the repository any more?

**Comment by alex-konovalov** [comment]
BTW, GMP 6.1.0 was announced on Nov 1st 2015: https://gmplib.org/gmp6.1.html

**Comment by fingolfin** [comment]
And I have seen several reports regarding crashes and rregressions with it, so I'd recommend staying with GMP 6.0.0a for the time being...

**Comment by markuspf** [comment]
On Mon, Dec 14, 2015 at 05:50:17AM -0800, Max Horn wrote:
> And I have seen several reports regarding crashes and rregressions with it, so
> I'd recommend staying with GMP 6.0.0a for the time being...

Can someone enlighten me again, why we are shipping our own GMP? (If only for
purposes of this being publically documented.

**Comment by alex-konovalov** [comment]
Because this is the version of GMP that we are testing carefully in all regression tests, so we may guarantee that all works with this version of GMP as expected.

**Comment by stevelinton** [comment]
A couple of reasons:

1. Windows, Mac and some Linux users may not have the skills  (or even the permissions) to install GMP for themselves.

2. Many combinations of GMP versions and C compiler versions are broken (or possibly reveal subtle errors in the way we are using their APIs). Using a system GMP of unknown version has (or at least had) a bad habit of producing strange errors.

	Steve

**Pull request merged**
