### PR TITLE
Added suggestion to call ?cite to the GAP startup screen

### PR DESCRIPTION
**Pull request by alex-konovalov**
This pull request should promote good software citation practices, suggesting to look for the `Cite` function that will generate sample citation for the version being used, in several formats.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This looks like a reasonable change to me. We could make some other, later changes (in particular, I've never noticed that the output of `?help` is very long and confusing!)

**Comment by alex-konovalov** [comment]
@ChrisJefferson yes, that seemed like an easy change that can be done immediately. It came from the suggestion by James Davenport at the panel discussion at the [Collaborations Workshop 2016](www.software.ac.uk/cw16) this morning. The line with these suggestions has some space to accommodate these extra characters, so why not?

**Comment by frankluebeck** [comment]
Of course, suggesting `?cite` is fine.

Concerning `?help`: it would indeed be better to suggest `??help` because the appropriate sections of the reference manual do not start with the word "help".

**Comment by alex-konovalov** [comment]
@frankluebeck thanks for pointing out about `??help` - I've updated this PR, so it's ready to be merged.

**Pull request merged**
