### PR TITLE
Collection of small corrections

### PR DESCRIPTION
**Pull request by hulpke**
Next attempt...

Branches alone do not resolve the issue but in fact it seems to be important where the branch is put on (as anything before gets inherited). This should contain only 4 minor changes (that fix reported errors) and one file removal.

### CODE REVIEW

**Comment by hulpke** [comment]
This fixes #420 and #413 as well as the error reported in a comment for #401

**Comment by fingolfin** [comment]
Looks essentially good to me, though I wonder about the same thing as alex: Shouldn't the LoadPackage call in line 2716 also be updated? (The one in 842 OTOH seems fine).

There is also a typo in the commit message of the last commit ("... cannot me faked as ...") which could be fixed with a `git commit --amend`, but if you do not feel comfortable messing with the repository history, then just leave it.

**Comment by hulpke** [comment]
@alex-konovalov 
 8ffc77d also adds a test for `fail' from the factor -- if there is no Hall subgroup in the factor.

I will add a check for loading tomlib to go in the next fix batch. (At some point in the not-so-far past tomlib was always installed)
I dislike issuing warnings for not installed packages-- the code will run into the generic cyclic extension routine and someone running without tomb might it fact have done so deliberately and would get annoyed by repeated warning to install the package.

**Comment by alex-konovalov** [comment]
@hulpke thanks. Indeed, TomLib became a proper package in GAP 4.5 (see [here](http://www.gap-system.org/Manuals/doc/changes/chap4.html#X7E24E9DE7CADD1B7)).

**Comment by alex-konovalov** [comment]
@hulpke thanks - I've cherry-picked this into the new `stable-4.8` branch so this will appear in GAP 4.8.2.

**Pull request merged**
