### PR TITLE
kernel: merge GMP_REDUCE into GMP_NORMALIZE

### PR DESCRIPTION
**Pull request by fingolfin**
Old patch I wrote a couple years ago as part of another bigger change (which is still incomplete, but I figured this bit could be merged now...).

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Can you say a few words about the rationale for this change?

**Comment by fingolfin** [comment]
We always calls `GMP_NORMALIZE` then `GMP_REDUCE`. There are zero places left that only call one of them. And they must be called in the right order.

**Comment by james-d-mitchell** [comment]
Ah ok, I see, I somehow failed to read the word "merge" in the title and commit message. This looks like a good change to me!

**Review by ChrisJefferson — APPROVED** [review]
Looks good to me, and neither function is used by any package, so it can't break anything else.

**Comment by fingolfin** [comment]
> Looks good to me, and neither function is used by any package, so it can't break anything else.

Just to say, it was used by the `float` package for a long time, even for the one distributed with GAP 4.11 -- since then a patch of mine to remove its usage there was merged, which is why we can now finally apply this patch :-).

**Pull request merged**
