### PR TITLE
Collection of Fixes

### PR DESCRIPTION
**Pull request by hulpke**
Two fixes for the stable version

### CODE REVIEW

**Comment by fingolfin** [comment]
Looks good to me, but I see an update was just pushed, so I'll wait for the tests

**Comment by alex-konovalov** [comment]
Thanks @hulpke - just to questions:
- could you add a test for #869 as well, please?
- where did the report by Dimitry Savchuk appeared (useful to know for changes overview)

**Comment by hulpke** [comment]
@alex-konovalov 
Test for 869 is added.
Dmytro told me in person.

**Comment by alex-konovalov** [comment]
@hulpke thanks, looks good to me too now.

**Pull request merged**
