### PR TITLE
Fix/master/findall doc

### PR DESCRIPTION
**Pull request by Spamakin**
The documentation for both [40.9-4 GQuotients](https://docs.gap-system.org/doc/ref/chap40_mj.html#X790C261184EEAB94) and [40.9-5 IsomorphicSubgroups](https://docs.gap-system.org/doc/ref/chap40_mj.html#X83B417BE7C508DC4) document an option `findall` which is by default true but can be set to false. However there is, at least as far as I could find, **any** portion of in the nearby documentation showing how to set such a value. I know it is contained in [other portions](https://docs.gap-system.org/doc/ref/chap4_mj.html#X867D54987EF86D1D) but I think it is nice to have this additional example.

The only thing I am a little iffy about are the inline comments stating that the first results has `findall:=true` by default. I think it's nice but it is a bit superfluous. If someone wants to get rid of these, go for it.

## Text for release notes

none

### CODE REVIEW

**Comment by Spamakin** [comment]
The testmanuals test is giving me trouble. I'm not sure how to run it locally but also I swear I am running the code in the interpreter just pasting it in as an example. However, if I run it multiple times then I do get different outputs
```
gap> g:=Group((1,2,3),(1,2),(4,5,6),(4,5));
Group([ (1,2,3), (1,2), (4,5,6), (4,5) ])
gap> h:=Group((1,2,3),(1,2));
Group([ (1,2,3), (1,2) ])
gap> quo:=GQuotients(g,h); # findall:=true by default
[ [ (1,3)(4,5,6), (2,3)(4,6) ] -> [ (1,2), (2,3) ], [ (1,3)(4,5,6), (2,3)(4,6) ] -> [ (1,2,3), (2,3) 
     ] ]
gap> quo:=GQuotients(g,h); # findall:=true by default
[ [ (1,2,3)(4,5), (2,3)(4,6,5) ] -> [ (2,3), (1,2,3) ], [ (1,2,3)(4,5), (2,3)(4,6,5) ] -> 
    [ (1,2,3), (2,3) ] ]
gap> quo:=GQuotients(g,h); # findall:=true by default
[ [ (2,3)(4,6,5), (1,3)(5,6) ] -> [ (1,2), (2,3) ], [ (2,3)(4,6,5), (1,3)(5,6) ] -> [ (1,2,3), (2,3) 
     ] ]
gap> quo:=GQuotients(g,h); # findall:=true by default
[ [ (1,2,3)(4,6), (1,3)(5,6) ] -> [ (1,2), (2,3) ], [ (1,2,3)(4,6), (1,3)(5,6) ] -> [ (1,2,3), (2,3) 
     ] ]
gap> quo:=GQuotients(g,h); # findall:=true by default
[ [ (1,2,3)(5,6), (1,2)(4,5) ] -> [ (1,2), (2,3) ], [ (1,2,3)(5,6), (1,2)(4,5) ] -> [ (1,2,3), (2,3) 
     ] ]
```
Not sure how to fix this since the algorithm to my understanding does use a bit of randomness.

**Comment by fingolfin** [comment]
These tests depend on randomized algorithms, which can thus produce different (but correct) results each time. One way to fix this is to look at the test logs, which show the outputs it expected, and to copy them from there into your pull request.

Another fix is to make the test independent of randomized results, by hiding outputs that differ based on random choices (e.g. by using `;;` instead of `;` to end lines, to suppress output) and then instead test structural properties (such as:
```
gap> Length(emb);
2
```
and similar

**Comment by Spamakin** [comment]
Hm I'm thinking maybe close this PR then since 1: it's not a big deal to have this and 2: dealing with the randomization seems like too big a hassle. `IsomorphicSubgroups` is randomized so the test logs wouldn't necessarily produce the same output each time right? I don't see how copying from the logs would fix this.

**Comment by ChrisJefferson** [comment]
Many many functions in GAP use GAP's random generator. We try hard while running tests to regenerate random outputs the same way (fixing random seeds, and also taking algorithms which involve time and removing time-based variance from them), so you (should) find you always get the same output from running the manual tests.

**Pull request closed without merging**
