### PR TITLE
kernel: port HVARs from HPC-GAP to GAP

### PR DESCRIPTION
**Pull request by fingolfin**
This is mostly untested as of now. In particular, I wonder if it has any performance impact (in either direction). If somebody wants to come up with some micro benchmarks and test this, be my guest :-P.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This crashes, I have a fix for it.

**Comment by ChrisJefferson** [comment]
Fix, and a simple test, on caj/hvars at chrisjefferson/gap.

This test also serves as a micro-benchmark. There seems to be no measurable difference (but maybe there is a better benchmark)

**Comment by fingolfin** [comment]
You should be able to directly push to my branch, if you want.

**Comment by fingolfin** [comment]
Seems workspaces are (still) broken.

**Comment by ChrisJefferson** [comment]
Now fixed (although it looks moderately horrible, I don't think it can improved)

**Comment by fingolfin** [comment]
Looks good to me.

I guess it's up to @markuspf to merge this :-)

**Comment by fingolfin** [comment]
I rebased this, squashed two of @ChrisJefferson's commits, cleaned up the `InitGlobalBag` calls, and applied the changes to `hpcgap/src/vars.c`, too, so that we don't desync again.

**Comment by fingolfin** [comment]
Rebased again

**Comment by markuspf** [comment]
This looks mostly good to me, I am just wondering whether the functions we introduce here anyway should be `clang-format`ted? For instance

```C
static inline void MakeHighVars( Bag bag ) {
  while (bag && TNUM_OBJ(bag) == T_LVARS) {
    RetypeBag(bag, T_HVARS);
    bag = ADDR_OBJ(bag)[2];
  }
}
```

is currently formatted as

```C
static inline void MakeHighVars(Bag bag)
{
    while (bag && TNUM_OBJ(bag) == T_LVARS) {
        RetypeBag(bag, T_HVARS);
        bag = ADDR_OBJ(bag)[2];
    }
}
```

(so a newline after function definition, and 4 space indent).

**Comment by fingolfin** [comment]
I tried very hard (and sometimes unsuccessfully) to refrain from doing any code formatting in my merges, as one quickly opens an unending pit of troubles when doing that...

That said, I have no problem in reformatting that function, or other parts of the patches, if that is preferred. I could try to use `git-clang-format` for that.

**Pull request merged**
