### PR TITLE
Fix for computing quotients of certain algebra modules

### PR DESCRIPTION
**Pull request by fingolfin**
The issue was originally reported by Rudolf Tange on the GAP support mailing list.

### CODE REVIEW

**Comment by fingolfin** [comment]
This is the error on HPC-GAP:
```
gap> V:=DirectSumOfAlgebraModules(s);
# Expected output:
<35-dimensional left-module over <Lie algebra over GF(5), with 3 generators>>
# But found:
Error, Atomic List Element: <pos>=2 is an invalid index for <list>
```

If somebody wants to look into it, be my guest...

**Comment by fingolfin** [comment]
There was an alternative fix suggested by Willem De Graaf on the mailing list. At least one of them should be in GAP 4.9.

**Comment by markuspf** [comment]
This needs fixing for HPC-GAP (and probably a rebase).

**Comment by alex-konovalov** [comment]
For the record, Willem's reply is in his email "[GAP Support] BUG in DirectSumOfAlgebraModules or inquotient-module function?" on 14/09/2017.

**Comment by fingolfin** [comment]
I updated this PR to use the fix proposed by Willem instead of my original fix, as his fix corrects additional problems -- one is that `IsCanonicalBasis` did not terminate if called on a basis of a sparse row spaces; that problem persisted with my fix, but is corrected by Willem's more fundamental fix.

I also tracked down and corrected the problem on HPC-GAP, and added another commit which very slightly improves performance for `\in` on enumerators-by-basis.

**Pull request merged**
