### PR TITLE
HPC-GAP fix for #44

### PR DESCRIPTION
**Pull request by markuspf**
@james-d-mitchell do you want to make the function names more uniform, the partial permutation code does the initialisation in ResizeTmpPperm?

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Hmm, I'm not sure that I would have made this change like this. You say:

"Otherwise if the TmpTrans was not initialised for the current thread we
get a segfault as reported in issue #44"

Isn't the trouble that the variable `TmpTrans` is not assigned to a value, not that it is assigned but not initialised to 0? If you look at the functions using `ResizeTmpTrans`, the values in `TmpTrans` are always assigned (and not always to 0). 

This change means that the values in `TmpTrans` are are initialised twice in every function where you replaced `ResizeTmpTrans` by `ResizeInitTmpTrans`.

Another thing: I can't see how this would actually fix the problem reported by Wilf, the first 3 lines of code in `ResizeInitTmpTrans` are identical to those in `ResizeTmpTrans`, so whatever the problem is with `ResizeTmpTrans` the same problem exists in `ResizeInitTmpTrans`. 

I think this requires more thought.

**Comment by markuspf** [comment]
I updated the PR to just do the necessary allocation if TmpTrans is null now.

@james-d-mitchell I believe you are looking at trans.c in `master`, in `hpcgap-default` the two functions differed, and it was even my fault because I changed ResizeInitTmpTrans before, but not ResizeTmpTrans.

**Comment by james-d-mitchell** [comment]
Ok, I was only looking at the commits (on github) in the pull request. So, `ResizeTmpTrans` will not be removed?

**Comment by markuspf** [comment]
No, I changed to allocate if ResizeTmpTrans is called, and allocate and initialise if ResizeInitTmpTrans is called, to avoid initialising twice.

If course I could also go through and refactor it a bit if you prefer that.

**Comment by james-d-mitchell** [comment]
If `ResizeTmpTrans` is not removed, then I am happy. Thanks!

**Pull request merged**
