### PR TITLE
Cleanup ZmodnZ code

### PR DESCRIPTION
**Pull request by fingolfin**
This cleans up the ZmodnZ code a bit. In particular, we used to store the modulus `n` in three places: 

1. in the type(s) via `DataType`,
2. in the family as `fam!.modulus`, and
3. in the family in the attribute `Characteristic(fam)`.

The last commit in this PR unifies this to the third variant. For now, the first variant is also retained (i.e. we still store the modulus in the type) becaues the Browse package accesses it there, like this:
```String( DataType( TypeObj( m[1][1] ) ) ) )```
This code should be changed to
```String( Characteristic( m[1][1] ) ) )```
or
```String( ModulusOfZmodnZObj( m[1][1] ) ) )```
then it'll work with both old and new GAP versions, and then we could get rid of this usage of DataType. 

There is only one other use of `DataType` in the GAP library: Generalized mapping use it store source and range; they do this because the underlying representation / implementation could be a positional object, so we cannot rely on attribute storage.

Outside the library, the `cvec` package is the only other user I am aware of. I am hopeful it could be refactored to not use `DataType`, too, though, but I did not look closely.

### CODE REVIEW

**Comment by stevelinton** [comment]
This is great. The use of DataType is not as big a deal as the use of the next entry in the type to cache the default type for new elements, which is why Subtype has to do all the horrible stuff it does. I can see no use of that in packages or anywhere else, but I'm not certain.

**Comment by fingolfin** [comment]
That would be `fam!.typeOfZmodnZObj` resp. `fam!.typeOfZmodnZObj![ ZNZ_PURE_TYPE ]` -- this PR does not do anything about those, but now that you mention it... I'll try to see later today if I can do something about that, too.

**Comment by stevelinton** [comment]
Great

**Comment by stevelinton** [comment]
One more thought. We should check this cleanup for any serious performance regressions. Replacing direct lookup in the type with attribute access in the family is adding significant indirection.

**Comment by fingolfin** [comment]
Indeed, I was wondering about that, too. Places that did `fam!.modulus` now do `Characteristic(fam)`, and I thought that should be fine because this should amount to the kernel getter... but I should test that. And perhaps write `fam!.Characteristic`, that ought to have the same speed, right?

It is unclear to me how `DataType( TypeObj( x ) )` and `Characteristic( FamilyObj( x ) )` resp. `FamilyObj( x )!.Characteristic` compare -- i.e. I need to look at the code for types and families to refresh my memory about this :). But performance tests should be done anyway.

**Comment by fingolfin** [comment]
So I wrote some tests, and indeed, this PR slows things a little bit down. With current master:
```
zmodnz.tst
GAP4stones: 460000
Tests took 49 ms

R = (Integers mod 126750):
Testing with 30000000 repetitions
Characteristic(R) 1865 ms
Characteristic(x) 6067 ms
Characteristic(FamilyObj(x)) 2811 ms
FamilyObj( x )!.Characteristic 1552 ms
DataType( TypeObj( x ) ) 2749 ms
summing x up: 9318 ms
```
With the PR as it is right now:
```
zmodnz.tst
GAP4stones: 383333
Tests took 45 ms

R = (Integers mod 126750):
Testing with 30000000 repetitions
Characteristic(R) 1838 ms
Characteristic(x) 6055 ms
Characteristic(FamilyObj(x)) 2896 ms
FamilyObj( x )!.Characteristic 1919 ms
DataType( TypeObj( x ) ) 2787 ms
summing x up: 10163 ms
```

So, it seems `FamilyObj( x )!.Characteristic` is the fastest way to get the modulus, and I have a local patch which changes most stuff to use that. Result:
```
zmodnz.tst
GAP4stones: 383333
Tests took 49 ms

R = (Integers mod 126750):
Testing with 30000000 repetitions
Characteristic(R) 1839 ms
Characteristic(x) 6006 ms
Characteristic(FamilyObj(x)) 2897 ms
FamilyObj( x )!.Characteristic 1711 ms
DataType( TypeObj( x ) ) 2780 ms
summing x up: 9475 ms
```

So we are almost back to speed... but only almost... This confused me, and I finally tracked it down to this behavior, measured in current master:
```
gap> x:=ZmodnZObj(22, 126750);
ZmodnZObj( 22, 126750 )
gap> fam := FamilyObj(x);
NewFamily( "Zmod126750", [ 1111 ], [ 35, 82, 83, 84, 85, 100, 103, 107, 111, 115, 119, 122, 125, 129, 133, 152, 155, 159, 1111,
  1112 ] )
gap> n:=10^7;
10000000
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
495
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
514
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
517
gap> Unbind(fam!.modulus);
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
570
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
595
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
607
gap> fam!.modulus:=126750;
126750
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
492
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
488
gap> for i in [1..n] do c := FamilyObj( x )!.Characteristic; od; time;
499
```

So the mere presence of the `modulus` key in the family object makes things *faster*, even though it is not used. I have not yet looked deeped (and need to leave now), but my guess is that this is somehow due to the way access to component objects works. In any case, I find that a bit disturbing to find such a large deviation. :-/

**Comment by stevelinton** [comment]
The only reason not to merge this is that there might be an extension to also get rid of the ZNZ_PURE_TYPE discussed above, which would be very helpful for HPCGAP and that might somehow have knock-on implications for the rest of the PR

**Comment by fingolfin** [comment]
... and ZNZ_PURE_TYPE is gone :). Turned out to be quite easy. I run a lot of tests to verify this is correct, in particular, I had an augmented version where in all places where ZNZ_PURE_TYPE was used, I had an Assert that compared it to Fam!.typeOfZmodnZObj  (and also to the type of the object it self). No mismatches for the former! For the latter, the expected ones: E.g. an object that has the `IsOne` flag set has a different type *sigh*.

I also run the following sophisticated benchmark:
```
x:=ZmodnZObj(22, 126750);; sum:=x;; for i in [1..10^7] do sum := sum + x; od; time; sum;
```
Before this PR, this takes about 3.1 secs on my system, with this PR this goes down to 2.9 -- i.e. we get a small speedup.

There is still a slowdown in this microbenchmark:
```
x:=ZmodnZObj(22, 126750);; fam := FamilyObj(x);; for i in [1..10^8] do c := fam!.Characteristic; od; time;
```
This goes up from 3.7 secs to 4.0 secs for me. The reason is in the binary search algorithm used for the record lookup, I think: In master, the family contains the `modulus` attribute, and a total of 13 attributes, with `Characteristic` in position 11. In this branch, there are only 12 attributes. When you do the math, it turns out that in master, the right entry is found after two loop iterations (lo..hi = 1..13 -> look at pos 7 ; no match -> lo..hi = 8..13 -> look at pos 11 ; MATCH), while in the branch, we get four iterations (lo..hi = 1..12 -> look at pos 6 ; no match -> lo..hi 7..12 -> look at pos 10 ; no match -> lo..hi = 11..12 -> look at pos 12 ; no match -> lo..hi = 11.11 -> look at pos 11; MATCH).

While I could leave in the modulus field to avoid this slow down, this feels just wrong. And this seems to have no practical impact, so I feel it is safe to ignore this.

**Comment by alex-konovalov** [comment]
Just for the record, I have discovered that this also broke my code from the OpenMath package which encodes ZmodnZ objects as follows: 
```
gap> OMPrint(ZmodnZObj(2,6));
<OMOBJ>
	<OMA>
		<OMS cd="integer2" name="class"/>
		<OMI>2</OMI>
		<OMI>6</OMI>
	</OMA>
</OMOBJ>
```
It accesses necessary data as `x![1]` and `FamilyObj( x )!.modulus`:
```
gap> x:=ZmodnZObj(2,6);
ZmodnZObj( 2, 6 )
gap> [ x![1], FamilyObj( x )!.modulus ];
[ 2, 6 ]
```
It's an easy fix for me, since I have only to replace `FamilyObj( x )!.modulus` by `Characteristic(FamilyObj( x ))`.

**Comment by fingolfin** [comment]
@alex-konovalov Well, strictly speaking OpenMath was relying on undocumented behavior, so I'd say this is a bug in it... Indeed, I'd also consider using `x![1]` a bug -- it relies on a specific representation. Better would be to use `Int(x)` or `ExtRepOfObj(x)`.

That said, of course I do not want to break existing packages (which is why I left DataType support in  for now, to support the `Browse` package). But to stay compatible with the old OpenMath, we'd have to add the DataType back in, which would be kind of sad... So, Alex, if you could make a new release of OpenMath with this changed, that would be awesome :)

**Comment by alex-konovalov** [comment]
Of course I will update OpenMath, no doubts...

**Pull request merged**
