### PR TITLE
miscellaneous library cleanup

### PR DESCRIPTION
**Pull request by fingolfin**
This is a grab bag of minor tweaks of the library, which mostly came up while looking at differences between master and hpcgap-default. I decided to import some sensible changes from HPC-GAP to master. However, all these changes IMHO have merit of their own, i.e. I do not just propose them in order to reduce diffs between the branches.

### CODE REVIEW

**Comment by frankluebeck** [comment]
This looks mostly fine to me. I'm only unsure about making the variables `SNMAXPRIMS`, `ANMAXPRIMS`, `NUMBER_SMALL_RINGS` and `SMALL_RINGS_DATA` immutable. These cache data up to some bound and maybe they should be extendable by future functions or packages? Does @hulpke have an opinion on these cases?

**Comment by fingolfin** [comment]
I thought about this, too, but decided to go ahead with the change based on the following thinking: These variables are undocumented internals. So if they are extended in the future, then there are two possibilities:

1. The extension is part of the library. In that case, whoever needs that change can make those variables mutable again as part of their changes.
2. The extension is part of a package. Then accessing internal undocumented library variables is a bad idea, and IMHO a bug. The correct solution would likely be to move those variables to the package; or to document them; or perhaps something else. In any case, I'd consider it a feature that they are immutable, thus preventing silent "tampering" -- forcing whoever makes the changes to discuss and coordinate this with the GAP team.

**Comment by ChrisJefferson** [comment]
These changes all look uncontroversial and fine to me

**Comment by hulpke** [comment]
I don't have a problem with making SNMAXPRIMS etc. immutable, as an extension would be either in place or a package could overwrite the variable with a larger list.

**Pull request merged**
