### PR TITLE
Refactor polycyclic collectors (WIP, do not merge) -- version for HPC-GAP

### PR DESCRIPTION
**Pull request by fingolfin**
This is a variant of PR #69, rebased on the hpcgap-default, with some additional changes: First off, the "stacks" use by the collector are now stored in TLS (thread local storage). Secondly, some HACK commits which are part of my ongoing attempts to actually make things work across thread.

Not yet ready for merging.

### CODE REVIEW

**Comment by fingolfin** [comment]
Things seem to work across threads now, at least in some simple tests, e.g. 
```gap
G:=AbelianGroup([100,99]);
g:=Random(G);
```
Then switch to another thread and try to look at more group elements, multplying them with each other and with g, etc. -- in my tests that seemed to work now.

Tests also seem to run fine. However, the following snippet takes more than twice as long with HPC-GAP than with GAP master (36 sec vs 16 sec)
```gap
for tst in ["grppc.tst","grppcnrm.tst","rwspcgrp.tst","rwspcsng.tst"] do
    f := Filename( DirectoriesLibrary( "tst" ), tst );
    Test(f);
od;
```

**Comment by fingolfin** [comment]
So, any feedback on the last two "HACK" commits would be appreciated. Some specific questions:

* I made lots of stuff read-only (as I wasn't sure how to move it to the public region; not that I even am sure it would be correct to move it there...?). Note that backtick is not enough, see issue #75. Anyway, does that seem plausible? 

* I am using `FuncMakeReadOnlyObj` in the C code to mark the group elements as readonly (they are "data objects", i.e. T_DATOBJ). Is there a better way? Is this even the right thing to do?

* Actually, this should probably also be extended and make arbitrary associative words in syllable format read-only. Currently they are not and hence end up thread-local, too:
```
gap> F:=FreeGroup(IsSyllableWordsFamily, 2);
<free group on the generators [ f1, f2 ]>
gap> RegionOf(F.1);
<region: thread region #0>
```
However, I am not completely certain if that is safe to do, i.e. whether or not anything ever modifies these.

**Comment by alex-konovalov** [comment]
@fingolfin: regarding your last remark on associative words in syllable format - they may be made read-only:
```
gap> MakeReadOnly(F.1);
f1
gap> RegionOf(F.1);
<region: read-only region>
```
but that does not happen automatically. I've resurrected my earlier attempt to fix this by introducing `IsReadOnlyDataObjectRep`, and you may see it here: https://github.com/alex-konovalov/gap/commit/8b1d5bbea68f7822a60366e99043d105b2267073

However, it does not work as expected - the object reports its `IsReadOnlyDataObjectRep` but is still thread-local:
```
gap> F := FreeGroup(IsSyllableWordsFamily, 2 );
<free group on the generators [ f1, f2 ]>
gap> RepresentationsOfObject(F.1);
[ "IsDataObjectRep", "IsReadOnlyDataObjectRep", "IsSyllableAssocWordRep", "Is8BitsAssocWord" ]
gap> RegionOf(F.1);
<region: thread region #0>
```
As we discussed with @stevelinton and @rbehrends, this is related to the fact that the types of most data objects aren't set via `Objectify`, but in the kernel. What needs to be done is to replace these direct assignments to `ADDR_OBJ(obj)[0]` with function calls that take care of the region logic.

**Comment by fingolfin** [comment]
This PR is no in sync with PR #69, but the last four commits are unique to HPC-GAP. The first of those moves the collection stacks into TLS variables. Unfortunately, that comes with a performance penalty: I repeatedly run the following code:
```
for tst in ["grppc.tst","grppcnrm.tst","rwspcgrp.tst","rwspcsng.tst"] do
    f := Filename( DirectoriesLibrary( "tst" ), tst );
    Test(f);
od;
```
In classic GAP, this takes about 16 seconds on my system. In HPC-GAP master, it is about 24 seconds (50% longer). Here are some more timings after various commits (in each case I run the tests at least twice):

With commit 3b0c4cdcb80bfbd0f8b3decfb21c3d26969a973f... pc collector: cleanup some code in Solution()
Time: 23929 ms & 24083 ms

With commit 2ba9f8345e70f39b731a6900ce733bd18b7de198... pc collector: replace per-collector stacks by shared global stacks
Time: 24456 ms &  24307 ms

With commit cc7d6568d91df42c999d4010ff55973289f85e5e... pc collector: store stacks etc. in TLS vars
Time: 26759 ms &  26862 ms

With commit 491ac9789f24f93ed1388901d7c8f3668d3057e2... make free group elements in IsSyllableWordsFamily read-only
Time: 26616 ms & 26738 ms

With commit 33e0fd9fdd89634ceb78cdae286bd4d1082e4a5f     pc collector: make collectors used by a group read-only
        and e2853ae6a59738080c4c7b0a05a9c486d09ac595     ensure ElementByRws returns immutable objects
Time: 26821 ms, 26850 ms, 26729 ms, 26712 ms


So already moving the stacks out of the collectors lost half a second -- likely because going through `VAL_GVAR` is a little bit slower than reading data from the collector object (which we need to access anyway). But the conversion to TLS vars costs more than two extra seconds.

Is there is a faster / better way than going through `ValGVarTL`? Note that those variables don't strictly need to be accessible from the interpreter. In fact not exposing them there would have the added benefit that user's can't shoot themselves in the foot by accidentally unbiding those vars. (Though we may want to add a `FlushPCCollectorStacks` command if we make the stacks inaccesible from the interpreter.)

**Comment by ChrisJefferson** [comment]
From Reimer, look at `AllocateExtraTLSSlot()` and `TLS->Extra` (or just go and put your variable directly in the thread-local storage, where all GAP's other global variables went).

If you need it, there is also `void InstallTLSHandler(void (*constructor)(),void (*destructor)())`, to set up a constructor and destructor for your new variables.

**Comment by stevelinton** [comment]
Does it make sense to have a thread-local version of InitCopyGVar?

**Comment by rbehrends** [comment]
The way that (GAP-level) thread-local variables are implemented is that they are represented as a list of T_PREC objects (one per thread). The main overhead in accessing them comes from the binary search that is being used (plus a bit more because of multiple indirections). I would in general look at replacing the record implementation with, say, a custom hash table in order to speed that up, which should minimize the overhead).

**Comment by rbehrends** [comment]
> Does it make sense to have a thread-local version of InitCopyGVar?

In general, we should already use the `GVarDescriptor` functions to access global variables, and it would be a good idea to have something similar for thread-local variables. This would probably go hand in hand with a replacement for the T_PREC implementation (so that they actually stay in the same memory location).

**Comment by fingolfin** [comment]
Ahem... I don't even know what a `GVarDescriptor` is... besides what I can guess from the name and its entry in gvars.h... Anyway, I prefer if the code does not diverge too much between the two PRs. I'll look into `AllocateExtraTLSSlot` and `InstallTLSHandler` (hmmm, though `AllocateExtraTLSSlot` is apparently only defined but never used in HPC-GAP...?)

**Comment by rbehrends** [comment]
> though AllocateExtraTLSSlot is apparently only defined but never used in HPC-GAP...?

That's because it's specifically meant for packages. Kernel code can add thread-local C variables directly to tls.h.

**Comment by fingolfin** [comment]
I'll merge the branch as-is for now so that others can see its effects on tests, and will follow up with a fix for the performance regression.

**Pull request merged**
