### PR TITLE
GHBI: verify that image of a map is contained in its range

### LINKED ISSUE #396: The image of a map is not contained in its range?
It is possible to do the following:
```
gap> phi:=GroupHomomorphismByImages(Group((1,2)),Group((2,3)),[(1,2)],[(1,2)]);
[ (1,2) ] -> [ (1,2) ]
gap> Image(phi,GeneratorsOfGroup(Source(phi))[1]) in Range(phi);
false
gap> Image(phi,GeneratorsOfGroup(Source(phi))[1]);
(1,2)
gap> Range(phi);
Group([ (2,3) ]
```
When we were looking at this earlier, we had to wait for the polycyclic package to be updated in order to provide the fix that performs the membership test for generator images being in the range with an NC method which doesn't.

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #396

### CODE REVIEW

**Comment by fingolfin** [comment]
Please do not merge yet, I think something might be wrong...

**Comment by fingolfin** [comment]
@alex-konovalov @hulpke Does that seem OK to you?

**Comment by alex-konovalov** [comment]
@fingolfin yes, thanks - it activates earlier prepared chunk of code by uncommenting it and removing a synonym declaration. This follows the plan that was discussed formerly as mentioned in #396.

**Comment by hulpke** [comment]
@fingolfin Looks fine to me.

should GHBINC then also cal GGMBINC (rather than GGMBI)?

Also (as this can be a source of weird bugs), should GHBINC have an assertion that still tests?

**Comment by fingolfin** [comment]
@hulpke all good points, I'll think about them and try to augment this PR. Might also add some more tests.

**Comment by fingolfin** [comment]
Hmm, with this PR, we get this:
```
gap> phi:=GroupHomomorphismByImages(Group((1,2)),Group((2,3)),[(1,2)],[(1,2)]);
Error, images must lie in range group
gap> phi:=GroupHomomorphismByImages(Group((1,2)),Group((1,2,3)),[(1,2)],[(1,2,3)]);
fail
```
So in one case, we get an error, in one case, we get fail. That seems like a potential source of confusion, and somewhat arbitrary. BTW, the manual entry for GHBI says this:
```
If gens does not generate G or if the mapping of the generators does not extend to a homomorphism (i.e., if mapping the generators describes only a multi-valued mapping) then fail is returned.
```
So the above behavior does not contradict the manual. But I still wonder: Maybe we should return `fail` here, too, instead of producing an error? Or conversly, change the documented behavior to generate an error, instead of returning `fail`? That would be risky, as it might break existing code (though not silently so), but arguably would make for easier to debug errors, as `fail` does not give a hint on the source of the failure.

If we were to replace the new errors with `return fail;` we probably should at least add `Info` messages that explain the failure, to ease debugging.

**Comment by hulpke** [comment]
@fingolfin I suggest to leave this current (somewhat inconsistent) behavior at the moment as the immediate bug fix.

Then lets look separately at this and related issues with mappings (e.g. restriction and co-restriction, dealing with maps that are not total) and get constant definitions for functions to create maps, the tests to be done (this does not only apply to creating maps, but also whether to test that an element to be mapped is in the domain, which can be costly), behavior for invalid input, and how to do validity tests within code without triggering an error.

I suspect that this might involve changes that could cause slight incompatibilities and therefore needs to be done more slowly.

**Comment by alex-konovalov** [comment]
@fingolfin shall we merge now to include into the 2nd beta of GAP 4.8?

**Comment by alex-konovalov** [comment]
I suggest that we should merge this for the 2nd beta of GAP 4.8. The above mentioned difference in the behaviour (break loop vs returning fail) does not contradict to the documentation, and if the change will break anything then it will be for a good cause since it would discover some hidden errors.

Furthermore, the distinction between two cases (returning fail or entering a break loop) makes sense to me. When `fail` is returned, it's potentially an expensive check whether the mapping of the generators extends to a homomorphism. In the other case, mapping generators to something that does not belong to the image looks like a real error in the input.

**Comment by fingolfin** [comment]
@alex-konovalov I do not understand you point about performance: The two kinds of checks you mention (whether the mapping of the generators extends to a homomorphism; and whether the images are contained in the range group) can be equally hard; indeed, I can construct examples were one is trivial, the other is extremly hard. So neither is "easier" or "harder" than the other in general.

But that's irrelevant, anyway: What @hulpke said is the real important bit: For now, we should not change the behavior, thus the existing code returning "fail" should stay as it is.

On the long run, neither returning fail nor running `Error` are IMHO great solutions; what I'd really would like to have for things like this is something like C++ exceptions -- i.e. normally, there would be an error; but if the caller "knows what he is doing", it should be possible to suppress the error and get fail as return value (e.g. so that one can try another algorithm)... I believe something like this already exists partially, via options... 

Anyway, but that's all hypothetical and for the future. For now, I'll add some asserts, and look at the other comands @hulpke made

**Comment by fingolfin** [comment]
The test failed due to the asserts I added. I think this means they caught an actual error in the lifting code:
```
gap> SetAssertionLevel(2);
gap> g:=PerfectGroup(IsPermGroup,960,1);;
gap> ns:=NormalSubgroups(g);
Error, Assertion failure in
  Assert( 2, IsMapping( hom ) ); at /Users/mhorn/Projekte/GAP/gap.github/lib/ghom.gi:440 called from
GroupHomomorphismByImagesNC( G, fp, Concatenation( qreps, pcgs ), GeneratorsOfGroup( fp )
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/gpfpiso.gi:563 called from
LiftFactorFpHom( l!.lattfpres, l, M, N, mpcgs
 ) at /Users/mhorn/Projekte/GAP/gap.github/lib/grplatt.gi:2178 called from
<function "NormalSubgroupsCalc">( <arguments> )
 called from read-eval loop at line 11 of *stdin*
you may 'return;'
brk> G;
A5 2^4
brk> H;
<fp group on the generators [ f1, f2 ]>
brk> gens;
[ (2,14,9,13,15)(3,4,6,7,16)(5,11,12,10,8), (2,6,4,13,10)(3,11,5,7,15)(8,9,14,12,16) ]
brk> imgs;
[ f1, f2 ]
brk> Size(G);
960
brk> Size(H);
60
brk> Size(Group(gens));
60
brk> IsTotal(hom);
false
```

**Comment by hulpke** [comment]
Thanks for spotting this.

The error occurs in code that builds homomorphisms to fp groups by layers. When doing so for a factor group it only uses the partial information — that is generator representatives for the factor group and their images. But as a homomorphism this will not neccessarily be total.

I will correct this so it is a proper homomorphism.

Since this is map only exists within the routine (and there is used for bookkeeping only) and is never moved out of the function this should not have caused actual calculation errors.

**Comment by fingolfin** [comment]
Once #421 has been merged, we can rerun the tests on this PR, and if they pass, should be ready to merge this.

**Comment by fingolfin** [comment]
To be clear: Once #421 is merged, I would simply rebase this PR, to trigger the test rerun, and also because the resulting history is easier to understand :)

**Comment by alex-konovalov** [comment]
@hulpke: as it was remarked by @fingolfin, now #421 is merged, so if you could rebase this PR to trigger a new Travis test, that would be great. Thanks

**Comment by hulpke** [comment]
> On Jan 6, 2016, at 12:36 PM, Alexander Konovalov <notifications@github.com> wrote:
> 
> @hulpke: as it was remarked by @fingolfin, now #421 is merged, so if you could rebase this PR to trigger a new Travis test, that would be great. Thanks

I have no idea how to do this. Sorry!

  Alexander

**Comment by alex-konovalov** [comment]
@hulpke in the simplest case, checkout the branch you'd like to rebase and call `git rebase master`.
But I've just realised that this PR has been submitted by @fingolfin so my request should be addressed to him and not to you - sorry for the misleading comment.

**Comment by alex-konovalov** [comment]
@fingolfin Travis tests fail after rebase - do you know what happens?

**Comment by hulpke** [comment]
I've looked at the test failures. What is happening is that some calculations with nice monomorphism want to write an equivalent homomorphism as GHBI (e.g. to construct an inverse, or to write down an object representing nice monomorphism in the first place).

This construction process now is instrumented with an assertion that tests membership (or checks that the map indeed is a mapping), and these trigger membership tests in the group that is handled by the nice monomorphism, leading to the infinite recursion.

A similar issue happens with subgroups of fp groups that are represented as pre-images under a homomorphism. Here the homomorphism is used for membership testing etc, and so we cannot test this when constructing the homomorphism.

I have fixes for these (essentially to skip the assertions if things go wrong) with which the tests go through

**Comment by hulpke** [comment]
There is a fix for the problems I described in hulpke/gap ghbifix

**Comment by fingolfin** [comment]
This has been superseded by PR #472.

**Pull request closed without merging**
