### PR TITLE
Prof improve weird lines

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This will hopefully deal with some weird lines appearing in profiles from variables not being correctly reset (going to look at the result of this PR)

### CODE REVIEW

**Comment by fingolfin** [comment]
Unfortunately Codecov did not add a coverage report comment here. Nor did it for PR #3023. This may be Codecov being flaky again as usual; or perhaps there is still something flaky with coverage uploading from Travis to Codecov ... but then again,  https://codecov.io/gh/gap-system/gap/commit/2820560658a999701014792d75130da307972086/build  shows Travis and AppVeyor data just fine, and we can see coverage for this PR on https://codecov.io/gh/gap-system/gap/tree/2820560658a999701014792d75130da307972086

Judging from that, the spurious code markers in comments are gone.

There are still `fi;` lines marked as "code that was not executed, though. See e.g. https://codecov.io/gh/gap-system/gap/src/2820560658a999701014792d75130da307972086/lib/memusage.gd#L46 and https://codecov.io/gh/gap-system/gap/src/2820560658a999701014792d75130da307972086/lib/random.g#L71 -- but I assume those are simply not in scope for this PR.

**Comment by ChrisJefferson** [comment]
Yup, I'll look at those `fi;` seperately. In general those just have to be special-cased, because in GAP those types of things often are technically read but never "executed", but that obviously isn't helpful :)

**Comment by fingolfin** [comment]
Well, it would also be perfectly fine to me if `fi` was simply "gray", i.e., not considered to be code. But marking it as unexecuted code is annoying.

**Comment by ChrisJefferson** [comment]
Oh I agree, it needs fixing. Just need to decide which way to handle it, write some tests, that kind of thing :)

**Comment by alex-konovalov** [comment]
@ChrisJefferson I am puzzled that the label backport-4.10 has been removed, but this is still assigned to the milestone 4.10.1. I think that the initial intention was to backport it, but then it was decided to not to do it - in this case, both the label and the milestone should be updated.

**Pull request merged**
