### PR TITLE
Add make check-manuals to makemanuals Travis test

### PR DESCRIPTION
**Pull request by alex-konovalov**
This continues #3105 and #3112. After partial clean up of types of ManSections (#3105) and fixing all `<Ref>` elements to ensure that they refer to an item properly mentioning its type, derived from the type of the ManSection for the corresponding item (#3112), the next step is to extend the `makemanuals` test in Travis to ensure that we maintain the reference manual in this state. Also, the log, a fragment of which is below, will be accessible on Travis, to provide a list of ManSections having no examples.

```
****************************************************************
*** Looking for ManSections having no examples 
****************************************************************
./help.xml:193 : SetHelpViewer
./../../lib/pager.gd:21 : Pager
./run.xml:578 : SaveWorkspace
./../../lib/system.g:552 : ARCH_IS_UNIX
...
./integers.xml:144 : \mod
./../../lib/zmodnz.gd:159 : ZmodnZ
./../../lib/zmodnz.gd:30 : IsZmodnZObj
./../../lib/random.gd:20 : IsRandomSource
./../../lib/random.gd:147 : IsMersenneTwister
./../../lib/bitfields.gd:19 : MakeBitfields
./../../lib/numtheor.gd:38 : InfoNumtheor
./../../lib/combinat.gd:294 : Combinations
./../../lib/combinat.gd:408 : Arrangements
./../../lib/combinat.gd:479 : UnorderedTuples
./../../lib/combinat.gd:510 : NrUnorderedTuples
./../../lib/combinat.gd:593 : Tuples
./../../lib/combinat.gd:623 : EnumeratorOfTuples
...
****************************************************************
*** Doc coverage report 
****************************************************************
2856 mansections 
1318 with examples 
1538 without examples 
****************************************************************
*** Checking types in ManSections 
****************************************************************
./../../lib/magma.gd:673 : Centralizer uses Attr instead of Oper
./../../lib/grp.gd:3538 : GrowthFunctionOfGroup uses Oper instead of Attr
./../../lib/oprt.gd:1243 : Orbit uses Oper instead of Func
./../../lib/oprt.gd:1281 : Orbits uses Oper instead of Attr
./../../lib/oprt.gd:1306 : OrbitsDomain uses Oper instead of Attr
./../../lib/oprt.gd:1357 : OrbitLength uses Oper instead of Func
./../../lib/oprt.gd:1378 : OrbitLengths uses Oper instead of Attr
./../../lib/oprt.gd:1400 : OrbitLengthsDomain uses Oper instead of Attr
./../../lib/oprt.gd:1431 : OrbitStabilizer uses Oper instead of Func
./../../lib/oprt.gd:1035 : SparseActionHomomorphism uses Oper instead of Func
./../../lib/oprt.gd:
1037 : SortedSparseActionHomomorphism uses Oper instead of Func
./../../lib/oprt.gd:1992 : CycleLengths uses Oper instead of Func
./../../lib/oprt.gd:1696 : IsTransitive uses Oper instead of Prop
./../../lib/oprt.gd:1517 : Transitivity uses Oper instead of Attr
./../../lib/oprt.gd:1844 : RankAction uses Oper instead of Attr
./../../lib/oprt.gd:1780 : IsSemiRegular uses Oper instead of Prop
./../../lib/oprt.gd:1807 : IsRegular uses Oper instead of Prop
./../../lib/oprt.gd:1670 : Earns uses Oper instead of Attr
./../../lib/oprt.gd:1731 : IsPrimitive uses Oper instead of Prop
./../../lib/oprt.gd:1552 : Blocks uses Oper instead of Func
./../../lib/oprt.gd:1554 : Blocks uses Attr instead of Func
./../../lib/oprt.gd:1596 : MaximalBlocks uses Oper instead of Func
./../../lib/oprt.gd:1598 : MaximalBlocks uses Attr instead of Func
./../../lib/oprt.gd:
1634 : RepresentativesMinimalBlocks uses Oper instead of Func
./../../lib/oprt.gd:
1637 : RepresentativesMinimalBlocks uses Attr instead of Func
./../../lib/oprt.gd:1148 : ExternalSet uses Oper instead of Attr
./../../lib/oprt.gd:1199 : ExternalSubset uses Oper instead of Func
./../../lib/oprt.gd:1221 : ExternalOrbit uses Oper instead of Func
./../../lib/oprt.gd:1453 : ExternalOrbits uses Oper instead of Attr
./../../lib/oprt.gd:1479 : ExternalOrbitsStabilizers uses Oper instead of Attr
./../../lib/ratfun.gd:1378 : Discriminant uses Oper instead of Attr
./../../lib/tom.gd:1506 : CyclicExtensionsTom uses Oper instead of Attr
./../../lib/ctbl.gd:1110 : IsAlmostSimple uses Prop instead of Oper
./../../lib/ctbl.gd:1114 : IsMonomial uses Prop instead of Oper
./../../lib/ctbl.gd:1115 : IsNilpotent uses Prop instead of Oper
./../../lib/ctbl.gd:1116 : IsPerfect uses Prop instead of Oper
./../../lib/ctbl.gd:1117 : IsSimple uses Prop instead of Oper
./../../lib/ctbl.gd:1118 : IsSolvable uses Prop instead of Oper
./../../lib/ctbl.gd:1119 : IsSporadicSimple uses Prop instead of Oper
./../../lib/ctbl.gd:1120 : IsSupersolvable uses Prop instead of Oper
./../../lib/ctbl.gd:2469 : DecompositionMatrix uses Oper instead of Attr
./../../lib/ctbl.gd:3824 : CharacterTableIsoclinic uses Oper instead of Attr
./../../lib/ctblmaps.gd:
584 : FusionConjugacyClassesOp uses Oper instead of Attr
./../../lib/ctblmono.gd:607 : TestMonomial uses Oper instead of Attr
./../../lib/ctblmono.gd:609 : TestMonomial uses Oper instead of Attr
./../../lib/ctblmono.gd:762 : TestRelativelySM uses Oper instead of Attr
./../../lib/ctblmono.gd:764 : TestRelativelySM uses Oper instead of Attr
****************************************************************
*** Checking types in cross-references 
****************************************************************
Found 7574 Ref elements including 7502 within the Reference manual
****************************************************************
Selected 3742 ManSections of the following types:
Attr - 753
Fam - 8
Filt - 358
Func - 1373
InfoClass - 21
Meth - 68
Oper - 894
Prop - 223
Var - 44
Found 47 errors in ManSection types 
Selected 6229 Ref elements referring to ManSections 
Found 0 errors and 0 warnings in Ref elements 
****************************************************************
```

### CODE REVIEW

**Comment by fingolfin** [comment]
So I run `make check-manuals` on master last night, and got this output:
```
$ wc dev/log/check_manuals_2018-12-29-17-42
    1620    5099   74038 dev/log/check_manuals_2018-12-29-17-42
```

Do we really want to add 1620 lines of output to those Travis log files? I have not yet quite understood what we'd gain by it, as we'd not be checking that output in any way. So the only benefit is that a manual inspecting of that output could be performed. And to be frank, I don't believe anybody other than @alex-konovalov would ever do that. That does not mean it might not be useful -- but then I'd still like to understand in which way resp. under which circumstances this might be useful.

Now, if we performed some kind of automatic check with that data, which would lead to a build failure if, say, additional failures occurred, that might be different (e.g. naively, one could store the pairs of `filename:error` (sans the the line number, which changes too often) in a reference file, and then if there is any difference, fail; thus there'd be a failure if new issues were introduced, and also if any old ones get fixed; in both cases, the reference file would have to be updated in order to pass (but hopefully, in the case of a new issue being introduced, it'd be fixed instead)

**Comment by ChrisJefferson** [comment]
I'd prefer to avoid making travis outputs no longer, as I find travis seems to frequently freeze / mess up webbrowsers as I scroll through long outputs.

**Comment by alex-konovalov** [comment]
I usually do not experience difficulties while jumping to the end of Travis logs, and these 1620 extra lines do not force Travis to hide the log and suggest that it should be downloaded separately, so I thought it may be fine. But if this may cause difficulties for someone - thanks for the feedback, I will be happy to adapt this PR. The long log is mainly due to 1538 lines reporting mansections without  examples - I can make that optional (as a tool that will be mainly used by myself). I also think that the test script could know a list of exceptions for orbitish and in-parent operations - then I can reduce to zero the number of reports of mis-typed mansections as well.

**Comment by ChrisJefferson** [comment]
Coming back to this PR, I may have misunderstood it. Can it "fail" if someone breaks the manual? I (think) I agree with Max, that a test which can't fail isn't useful (as no-one is going to check the output manually)

**Comment by alex-konovalov** [comment]
@ChrisJefferson You're right, this was not clearly expressed above. The test output consists of two parts:
- part 1 is long list of mansections without examples. It does not fail anything, and can be used for reference purposes. I agree with Max that it has limited interest and should be removed. I have just force-pushed an update of this PR which does this.
- part 2 is short. It **fails** it there are errors and warnings in Ref elements. It also prints the lost of 47 questionnable ManSections, which are "somehow" correct (they are exceptions). At the moment the test does not know the list of exceptions. Still, I think we can merge this and work on these exceptions later - because this test **will fail** if someone breaks the manual (i.e. by not using correct tags. I will make some more commits which break the manual to check and demonstrate this.

**Comment by alex-konovalov** [comment]
@ChrisJefferson See build https://travis-ci.org/gap-system/gap/jobs/487162696 - broken XML fails the build. Will now force-push again to remove that commit.

**Pull request merged**
