### PR TITLE
src/hpc/aobjects.c: define and use enums for atomic policies

### PR DESCRIPTION
**Pull request by fingolfin**
This should be "just" some cleanup to the code, but I wonder if I missed something subtle and/or undocumented, so please review it carefully.

### CODE REVIEW

**Comment by fingolfin** [comment]
@rbehrends Does this PR look OK?

**Comment by rbehrends** [comment]
This looks good to me. I think this may have a performance impact, but the impact should be minuscule and rather offset by the readability. I'd actually be in favor of giving the various modes more descriptive names in the long term.

**Comment by fingolfin** [comment]
Performance impact? How so? At least on x86, I don't see that; but OK, perhaps on an arch that has dedicated instructions for comparison against 0; but on x86, any small immediate should be fine, no? What am I missing?

**Comment by rbehrends** [comment]
Performance impact: a compiler can roll a set of comparisons vs. >0, <0 and ==0 into a single test and multiple jumps (depending on flags). To compare ==1, ==-1, and ==0 requires multiple tests. Note that I said that the performance impact is likely to be minuscule, if it's measurable at all.

**Pull request merged**
