### PR TITLE
Add TraceAllMethods, UntraceAllMethods, and filename/line info to traces

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This improves tracing by adding two new methods TraceAllMethods and UntraceAllMethods (which are documented, but whose meaning is I hope obvious), and also add filename/line number info to trace calls where possible, to show the location of the called function.

Unfortunately this isn't mergable yet, as the tests don't pass (as traces now have filenames) and can't be fixed (as the filenames are computer specific). However, posting for any comment while I think about the best fix.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Looks useful. Which tests would fail if this will be merged?

**Comment by ChrisJefferson** [comment]
The tests for 'TraceMethod' mainly, which show an example trace (which now has filenames and line numbers. But on my computer those filenames are /Users/caj/..., which would still not match other people's computers)

**Comment by alex-konovalov** [comment]
Can't see where these tests are - none in `tst` uses `TraceMethod`. Are they in the manual?

**Comment by ChrisJefferson** [comment]
Yes, in the manual section for TraceMethod, there is an example trace.

**Comment by alex-konovalov** [comment]
Then it is trivial - just use Log elements instead of Example

**Comment by stevelinton** [comment]
Maybe make that manual section non-testable and add a test file that just checks that TraceMethod can run without crashing.

**Comment by alex-konovalov** [comment]
@ChrisJefferson Now I see what you mean after this PR has been merged and tested using Jenkins CI:
```
============================================================
########> Diff in [ "./opers.xml", 355, 363 ]
# Input is:
g:= Group( (1,2,3), (1,2) );;  Size( g );
# Expected output:
#I  Size: for a permutation group
#I  Setter(Size): system setter
#I  Size: system getter
#I  Size: system getter
6
# But found:
#I  Size: for a permutation group at /mnt/disk2/hudson-slave/workspace\
/GAP-dev/GAPCOPTS/32build/GAPGMP/gmp/GAPTARGET/manuals/label/64bit/GAP\
-git-snapshot/lib/grpperm.gi:487
#I  Setter(Size): system setter
#I  Size: system getter
#I  Size: system getter
6
########
########> Diff in [ "./opers.xml", 370, 393 ]
# Input is:
Size( g );
# Expected output:
#I  Size: for a permutation group
#I  immediate: IsNonTrivial
#I  immediate: Size
#I  immediate: IsFreeAbelian
#I  immediate: IsTorsionFree
#I  immediate: IsNonTrivial
#I  immediate: GeneralizedPcgs
#I  Setter(Size): system setter
#I  Size: system getter
#I  immediate: IsPerfectGroup
#I  Size: system getter
#I  immediate: IsEmpty
6
# But found:
#I  Size: for a permutation group at /mnt/disk2/hudson-slave/workspace\
/GAP-dev/GAPCOPTS/32build/GAPGMP/gmp/GAPTARGET/manuals/label/64bit/GAP\
-git-snapshot/lib/grpperm.gi:487
#I  immediate: IsNonTrivial
#I  immediate: Size
#I  immediate: IsFreeAbelian
#I  immediate: IsTorsionFree
#I  immediate: IsNonTrivial
#I  immediate: GeneralizedPcgs
#I  Setter(Size): system setter
#I  Size: system getter
#I  immediate: IsPerfectGroup
#I  Size: system getter
#I  immediate: IsEmpty
6
########
```
- these two examples could be converted to `Log` elements to avoid diffs.

**Comment by alex-konovalov** [comment]
@ChrisJefferson I've just pushed a commit which excludes example for TraceMethod from the test of manual examples.

**Pull request merged**
