### PR TITLE
Remove MPI support

### PR DESCRIPTION
**Pull request by fingolfin**
In PR #1486 I fix some issues with the MPI code in GAP, but even with those, that code is currently completely broken in GAP.
So I wondered there whether it would be better to just remove it.... well, this PR does just that (though I may have missed some parts of it).

If we were tomerge this (which should only happen after discussing this on the gap mailing list), we should probably also remove the pargap package from distribution.

### CODE REVIEW

**Comment by stevelinton** [comment]
What strikes me about this PR is how small the diff is outside of gapmpi.c. So with a very small number of hooks (which could probably be made generally useful) all the kernel parts of pargap/mpi could be moved into the package, using just general purpose, documented, hooks into the kernel. Then anyone who wishes to update/maintain the package can do so independently.

**Comment by fingolfin** [comment]
@stevelinton On making those hooks "generally useful": sure, we could invent something, but I am sceptical it would be actually useful without an actual use case beyond `pargap`! "Code you write but don't use is usually incorrect", after all: we'd spent time coming up with a generalized interface, and then the first time somebody actually wants to use it, they'd most likely find out it is missing some important bits they use.

Or, in short: I don't believe in generalizing something for which one has only a single example ;-).

That said, `pargap` always had a very small integration footprint, and most of the kernel parts of pargap/mpi always *were* inside of pargap. It was the HPC-GAP project which decided to move that code directly into the GAP kernel, and this PR kind of reverts to the old state of things.

But unfortunately, pargap right now is completely broken by the kernel changes in the past year (e.g. the `READ_ERROR` -> `TRY_READ` refactoring). It shouldn't be too hard to fix that, but `pargap` resp. `gapmpi` touches some very deep internal parts of GAP, so I am sure it'll be broken again in the future. Thus we'd either need an active `pargap` package maintainer, or an active`gapmpi` maintainer (working on the kernel)... or if nobody volunteers for either, we should consider abandoning `pargap`.

In closind, I'd be happy to give advice to anybody who wants to fix `pargap` and/or the `gapmpi`code (see also PR #1486 for a start of the latter). But I am really interested in doing it myself.

**Comment by alex-konovalov** [comment]
I am for recommending to use SCSCP instead of ParGAP. I am nominally a maintainer for ParGAP fpr very cosmetic changes, but I am not volunteering for more substantial changes. Instead, I am very keen on improving SCSCP functionality (see `ParListWithSCSCP` in https://gap-packages.github.io/scscp/doc/chap8.html). It has a number of benefits comparatively to ParGAP.

**Comment by markuspf** [comment]
Which hooks are we talking about?

**Comment by stevelinton** [comment]
> Which hooks are we talking about?

I wasn't thinking very specifically, but pargap certainly used to have code in the kernel to run initialisation functions quite early in boot-up, strip out MPI-specific command line options before GAP saw them, running a bespoke main loop and similar.  Now I think more carefully the startup stuff would be tricky to handle via an API that package kernel code could use, simply because the system wouldn't have started to load packages by that point, you would need a whole other mechanism for getting a C library loaded much earlier, which is obvious overkill.

**Comment by markuspf** [comment]
Should we merge this then?

**Comment by fingolfin** [comment]
I have rebased this now, so that tests are run again (a lot of time passed, so while I think a problem is unlikely, better be safe than sorry).

I am fine with merging this, though I think we should perhaps send one last warning to the lists: I.e. write a reply to my email there, say that we got no responses at all from people using ParGAP, and that we will remove it, say, "by the end of this week" ?

Or, if you think we waited enough, then at the very least send a reply to the email (sent to gap@gap and forum) indicating that we are now removing builtin MPI support from GAP, as nobody expressed any interest in it; and that ParGAP may be removed from the GAP package distribution in 4.9.

Finally, we should propose on the gap@ mailing list to remove ParGAP and Linboxing from the distribution in GAP 4.9, as they are unmaintained and do not compile (but of course they can be added back if a maintainer steps up). We can then (if necessary) debate this during GAP days.

**Comment by markuspf** [comment]
I am happy with sending an email again and waiting until Friday to hit the merge button.

**Comment by fingolfin** [comment]
Then please do so :-)

**Pull request merged**
