### PR TITLE
Add rewriteToFile to TestDirectory

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This adds an option `rewriteToFile` to `TestDirectory`. This just provides an easy-to-use access to `rewriteToFile` from `Test`.

This lets you run `TestDirectory(".", rec(rewriteToFile := true))` in a directory, which will run all the tests and replace all outputs with GAP's current outputs. This will hopefully make fixing tests faster.

### CODE REVIEW

**Comment by stevelinton** [comment]
I'd be happier if this wrote the modified files into a different directory, encouraging the user to look over them and check them. For me, this change as is makes it just a bit to easy to capture erroneous behaviour in a test.

**Comment by markuspf** [comment]
I think that, since mostly one keeps testfiles in a git repository one has to explicitly commit changes (and hence look at a diff, ideally in a pull request). In my opinion this is more convenient than having a separate directory and diff manually.

**Comment by fingolfin** [comment]
I agree with @markuspf here. Though I guess it might be useful to allow to override this somehow, though I am not completely sure how to do that. Perhaps if `rewriteToFile` is set to a string or a `Directory` object, then write all new files into that dir. But this needs some care if inputs include both `tst/foo.tst` and `tst/subdir/bar.tst` -- you probably will want `outdir/foo.tst` and `outdir/subdir/bar.tst` as output.

So while it might be nice for somebody, I wouldn't want to delay this PR over it; esp. since I am never going to use this variant (I'll always overwrite the input files, and then use `git diff` to analyze the changes). Rather, if somebody actually requests this (maybe @stevelinton?) via an issue, we can work on that in a separate PR..

**Comment by stevelinton** [comment]
Fine. No objections.

**Pull request merged**
