### PR TITLE
Add more examples into the manual for StructureDescription

### PR DESCRIPTION
**Pull request by hungaborhorvath**
Further, correct the old examples from #763.
Add some extra tests.
Remove InfoPerformance from tst files as per 392ad821fd.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thanks @hungaborhorvath - looks obviously ok to me, and tests passed. Will rebase it now.

**Comment by alex-konovalov** [comment]
@hungaborhorvath there are further issues with `StructureDescription` - I am now seeing this in `make testinstall` log in the master branch when GAP runs without packages:
```
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/teststandard/bugfix.t\
st:1081
# Input is:
StructureDescription(testG(8,2));
# Expected output:
"((C8 x C2) : C2) : C2"
# But found:
"QD16 : C4"
########
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/teststandard/bugfix.t\
st:1085
# Input is:
StructureDescription(testG(8,4));
# Expected output:
"((C16 x C2) : C2) : C2"
# But found:
"(C8 . D8 = C4 . (C8 x C2)) : C2"
########
```

**Comment by hungaborhorvath** [comment]
@alex-konovalov Thank you, I did not catch this previously. At first I thought that we should simply use the "nice" option here, because that would give stable output: ````"(C8 x C4) : C2"```` in the first case, ````"(C16 x C4) : C2"```` in the second case.

_However_, using the "nice" option reveals a bug somewhere. I am not entirely sure where, yet. It seems to be with nice monomorhpisms of which I have no idea about. I am debugging this, but it might take some time. 

Should these tests be commented out until I figure out the problem, or shall we leave them? Or should I open an issue with this?

**Comment by hungaborhorvath** [comment]
@alex-konovalov Ok, so I have reported it in #973, and I have no idea how to resolve this. It involves that GAP (using the presentation of these groups) cannot decide if a list of subgroups is already an element of a set or not.

**Comment by alex-konovalov** [comment]
Thanks @hungaborhorvath - let's continue discussion in #973. I though about opening a new issue myself, but decided to wait until you'll confirm that there is no straightforward fix.

**Pull request merged**
