### PR TITLE
lib/string.gi: add \+ for strings, shows more helpful error

### PR DESCRIPTION
**Pull request by fingolfin**
This is an alternative to PR #1313, which instead actually concatenates its inputs.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
At least this alternative seems uncontroversial and makes GAP more user-friendly.

**Comment by ChrisJefferson** [comment]
Maybe add some tests to this, just for sanity, then I think we should merge it.

**Comment by alex-konovalov** [comment]
Indeed, a test as @ChrisJefferson may have sense (for example, if a package will appear, which installs a method for `\+` to concatenate strings. Then I suggest to merge this a solution that is not changing the existing functionality, but makes GAP more user-friendly.

**Comment by fingolfin** [comment]
I will not add tests to this, but anybody else is of course welcome to

**Pull request merged**
