### PR TITLE
Fix broken shebang

### PR DESCRIPTION
**Pull request by fingolfin**
Oops!

Motivated by https://src.fedoraproject.org/rpms/gap/blob/rawhide/f/gap.spec#_233 by @jamesjer

### CODE REVIEW

**Review by ChrisJefferson — APPROVED** [review]
Woops indeed!

**Comment by ChrisJefferson** [comment]
Out of interest, were you just having a look at the fedora packaging, or was this pointed out to us?

**Comment by fingolfin** [comment]
I got this from looking at the Fedora package myself in this case, but in general @jamesjer is very good about upstreaming his patches; after we released 4.12.0 he made a ton of PRs for various packages to fix issue here and there; and also PR #5027 here.

**Comment by fingolfin** [comment]
Backported to stable-4.12 via commit 03ddf4d33

**Pull request merged**
