### PR TITLE
Merge stable-4.8 into master branch

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This is a technical merge - most if not all of these commits are already in master and were cherry-picked onto stable-4.8. So while they appear in the list above, the merge will show no changes for them.

**Comment by fingolfin** [comment]
Yes, this is a technical merge, but we need it, because there is a merge conflict, which this resolves. I could have done it directly, but I went via github to get the tests running.

Once this has been merged, future merges of stable-4.8 into master (we probably will need to do a couple) should again be conflict-free (and thus can be done via github again).

And the commented you marked as "duplicating" some other commit is already in stable-4.8.

**Comment by alex-konovalov** [comment]
@fingolfin yes, it's useful - I haven't mean anything else by "technical" except that doing it is a part of the periodic check that two branches are in the consistent state. Now Travis validated it, I will leave merging to you.

@fingolfin, do you think we should encourage that changes for stable-4.8 should be done in stable and then propagated to master via such "technical" merges to avoid too many cherry-picks?

**Comment by fingolfin** [comment]
@alex-konovalov Good question, I am not quite sure. In principle, it would be OK if we only cherry-picked stuff from master to stable. But I am concerned about people making changes to stable only, without putting them into master -- as has already happened. So, doing periodic merges from stable into master ensures we don't "loose" any change. But other than that, I don't think it's a superior solution (but perhaps I am missing something...)

**Comment by alex-konovalov** [comment]
@fingolfin in mercurial times, we did technical merges regularly, so I think we should continue with them. Just in case, which particular changes do you mean in "people making changes to stable only, without putting them into master -- as has already happened" ? I think that there were none, because what appeared in stable was a result of my cherry-picking.

This shows that cherry-picking in general makes history very convoluted... I agree with @markuspf telling me in another "ear" that in theory we should add bug fixes that apply to stable to stable first. With new features, I think the way is to create branches off stable-4.8, if one wishes fir them to go into the stable branch...

**Comment by fingolfin** [comment]
@alex-konovalov actually, my mistake, the reverse happened: a commit namely 5534b1bea04) was applied to master, but not to stable-4.8. This wouldn't have mattered, but another, prior commit touching the same lines in the same files *was* cherry picked. The result, then is a merge conflict between the two branches. This could have been avoided by cherry picking 5534b1bea04 (which I basically did, from a functional point of view, except that I was not aware of 5534b1bea04 and thus applied the required changes manually). But this can happen again in the future, and is difficult to avoid with cherry picking alone.

But again, cherry picking is not bad. We just should perform a merge of stable into master afterwards (not necessarily after each cherry pick, but still regularly).

We probably should not continue this discussion here, though, but rather move this to the gap mailing list, so that others are aware of it... and/or, create a Wiki page where we summarize "best practices using our git repository" ?!?

**Comment by alex-konovalov** [comment]
@fingolfin in the long run, we need this on Wiki. BTW, any reasons why you're not merging this just now?

**Pull request merged**
