### PR TITLE
Add ReturnFirst and ReturnNothing

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This adds two new functions, ReturnNothing and ReturnFirst, similar in spirit to ReturnTrue and ReturnFalse. I find these functions often arise in practice.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Is `ReturnFirst` a good demo case for the new variadic functions? If this will be `function(a,arg)` returning `a` then it will automatically check the right number of arguments.

**Comment by ChrisJefferson** [comment]
I was going to use variadic functions, but they currently always print a warning when used. Once that warning gets disabled (and I think we want to wait until a later beta for that, to give package authors a chance to see the warning), we can switch over.

**Comment by ChrisJefferson** [comment]
Bah, the main reason I wrote these was so I could use them in thread1.g, but this file is included after thread1.g, so I can't. So I can either put them in the C level (and then I have to decide what file to put them in), put them in thread1.g (which seems weird), make a new library file that gets included first.. or just not use them. Bah.

**Comment by fingolfin** [comment]
@ChrisJefferson Actually ID_FUNC, ReturnTrue, ReturnFail, ReturnFalse are all implemented on the C level.

**Comment by ChrisJefferson** [comment]
Yep, I'm just doing C implementations of returnfirst and returnnothing, just so I can also not worry about re-arranging the order of files. Seems like overkill, but at least it is consistent.

**Comment by ChrisJefferson** [comment]
Now with C implementations (mainly so I can use them in HPCGAP Backports

**Comment by alex-konovalov** [comment]
Merged this. New functionality, should not break anything existing, and now permits merging #231.

**Pull request merged**
