### PR TITLE
Avoid a crash when isatty(x) is true but ttyname(x) is NULL.

### PR DESCRIPTION
**Pull request by jamesjer**

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Sorry this has sat for a while.

The 'isatty' patch can in straight away in my opinion.

The 'fstatbuf.st_size' I would like to check for 2GB overflow. Just an 'ErrorMayQuit' is sufficient I think.

The longlong seems reasonable, but does it have a use (and more seriously, do we have any way of testing it's correctness at the moment?)

**Comment by alex-konovalov** [comment]
Thanks Chris. It would be a good practice not to mix several patches in one PR - would be easier to merge then...

**Comment by markuspf** [comment]
I applied the isatty patch just now, the other two patches I separated as to not muddle together separate issues.

**Comment by markuspf** [comment]
I will close this pull request, because it conflates multiple patches. I made new pull requests #178 and #179 which separate the patches.

**Pull request closed without merging**
