### PR TITLE
Add appropriate code coverage for commit diffs to code review checklist

### PR DESCRIPTION
**Pull request by alex-konovalov**
This is a trivial one line change in PR template (which nobody seem to use though).

### CODE REVIEW

**Comment by fingolfin** [comment]
Yeah, I am not using that template. The first thing when I open a new PR is to delete it; and I never read it in PRs other submit. To be honest, to me it feels more like a nuisance than being helpful; though I don't mind much, as ignoring it is not much of a hassle. I also am familiar with the suggestions it contains, so I realize that it may be more helpful for others.

All in all, though, this means that I don't feel comfortable reviewing this PR.

**Comment by alex-konovalov** [comment]
Fine w/me. Just to add that If you're familiar with the reviewer checklist, but are an author of the PR, than the list meant to be for others. I am going to merge this, since the checklist surely should contain code coverage, with understanding that the practical use of the checklist remain low.

**Comment by stevelinton** [comment]
The phrasing of the new line isn't really clear, at least to me. I'm not sure what is appropriate, or what "code coverage for commit diffs" actually means. Do you mean "make sure that the lines changed in your commits are covered by the tests"?

**Comment by alex-konovalov** [comment]
@stevelinton I mean exactly that. The wording is based on what Codecov website says. I liked it since its one line only. Thanks for suggestion - what about `lines changed in commits are sufficiently covered by the tests` then?

**Comment by stevelinton** [comment]
yes. I’d be fine with that.

	Steve

**Comment by alex-konovalov** [comment]
@stevelinton done. Need at least one approved review to squash and merge.

**Comment by alex-konovalov** [comment]
Thanks @DominikBernhardt. Of course, suggestions how to rewrite it will be most appreciated!

**Pull request merged**
