### PR TITLE
Fix IsGeneratorsOfSemigroup

### PR DESCRIPTION
**Pull request by james-d-mitchell**
The property `IsGeneratorsOfSemigroup` was used inappropriately in the library files invsgp.g* and in
semigrp.g*.

This commit includes refactored versions of the functions `Semigroup`,
`Monoid`, `InverseSemigroup`, and `InverseMonoid`. Some unnecessary code was
removed, and some changes, described below, were introduced.

In invsgp.g* `IsGeneratorsOfSemigroup` was used as a filter for the methods
`InverseSemigroupByGenerators` and `InverseMonoidByGenerators`. But since
collections are often not attribute storing, it was not possible to
enter any of these methods except with a collection in
`IsAssociativeElementCollection`. Note that since matrices are not in
`IsAssociativeElementCollection`, there are instances when the methods
should have applied but did not.

In semigrp.g*, `IsGeneratorsOfSemigroup` was checked for every one of the
arguments to the function `Semigroup`, and `Monoid`, but not to the final
list of generators obtained. For example, a collection of matrices of
different dimensions each individually satisfy `IsGeneratorsOfSemigroup`
but collectively do not. This commit introduces checks for the final
list of generators inside the functions `Semigroup` and `Monoid`.

Some minor adjustments were made to other methods which these changes required.

### CODE REVIEW

**Comment by markuspf** [comment]
What happened to the removal of the implication `IsAssociativeElementCollection -> IsGeneratorsOfSemigroup`? Or do I misremember what we agreed was the best course of action (or did you find a problem with that approach)?

**Comment by james-d-mitchell** [comment]
You remember correctly, but I decided not to go with that solution in the end. The reason being that removing the implication `IsAssociativeElementCollection -> IsGeneratorsOfSemigroup` means that a method has to be installed for `IsGeneratorsOfSemigroup` for every type of semigroup element in the library. Like this the change is smaller, and consistent with the existing documentation. 
Previously, the only existing examples of elements in `IsAssociativeElementCollection` not satisfying `IsGeneratorsOfSemigroup` were bipartitions in the Semigroups package. These also did not meet the manuals definition of `IsAssociativeElementCollection` (it was not always possible to multiply them, for example, if they had different degrees it was not possible). So, I changed bipartitions, rather than changing GAP.

**Comment by alex-konovalov** [comment]
I suggest not to merge this until GAP 4.8.2 will be out.

**Comment by alex-konovalov** [comment]
I am happy to merge this now subject to reviews.

**Comment by markuspf** [comment]
This looks good to me. @james-d-mitchell explained why he took a different approach, so I'll merge.

**Pull request merged**
