### PR TITLE
Add ViewString for Families and Types

### PR DESCRIPTION
**Pull request by markuspf**
This adds some code that gives much more verbose (and in my opinion useful) information about types and families.

I am happy to adjust what is printed and in which ways, for instance I have code that stores the location (filename, line number) where a filter was declared.

### CODE REVIEW

**Comment by fingolfin** [comment]
That seems like a useful addition!

Though right now, the view method is quite verbose, while the display method remains rather short. Perhaps they should be switched? It might be annoying for some people if families printed verbosely by default... (I am not yet sure for myself whether I'd like or dislike that... gotta try it during actual work to get a feeling for it).

For those curious about the effect of this PR, here is a brief example:
```
gap> F:=FreeGroup(2);
<free group on the generators [ f1, f2 ]>
gap> FamilyObj(F);
name:
    CollectionsFamily(...)
required filters:
    IsCollection
implied filters:
    IsListOrCollection
    IsCollection
    IsExtLElement
    CategoryCollections(IsExtLElement)
    IsExtRElement
    CategoryCollections(IsExtRElement)
    CategoryCollections(IsMultiplicativeElement)
    CategoryCollections(IsMultiplicativeElementWithOne)
    CategoryCollections(IsMultiplicativeElementWithInverse)
    IsOddAdditiveNestingDepthObject
    CategoryCollections(IsAssociativeElement)
    IsGeneratorsOfMagmaWithInverses
    Tester(IsGeneratorsOfMagmaWithInverses)
    IsGeneratorsOfSemigroup
    Tester(IsGeneratorsOfSemigroup)
    CategoryCollections(IsWord)
    CategoryCollections((IsWord and IsAssociativeElement))
    CategoryCollections(((IsWord and IsAssociativeElement) and (IsWord and IsMultiplicativeElementWithOne)))
    CategoryCollections(((IsWord and IsAssociativeElement) and (IsWord and IsMultiplicativeElementWithInverse)))
gap> FamilyObj(F.1);
name:
    FreeGroupElementsFamily
required filters:
    IsMultiplicativeElementWithInverse
    IsAssociativeElement
    IsWord
implied filters:
    CanEasilyCompareElements
    Tester(CanEasilyCompareElements)
    CanEasilySortElements
    Tester(CanEasilySortElements)
    IsExtLElement
    IsExtRElement
    IsMultiplicativeElement
    IsMultiplicativeElementWithOne
    IsMultiplicativeElementWithInverse
    IsAssociativeElement
    IsWord
gap> Display(FamilyObj(F));
NewFamily( "CollectionsFamily(...)", [ 57 ], [ 56, 57, 120, 121, 123, 124, 127, 131, 135, 139, 154, 515, 516, 553, 554, 1174,
  1180, 1181, 1182 ] )
gap> Display(FamilyObj(F.1));
NewFamily( "FreeGroupElementsFamily", [ 134, 153, 1173 ], [ 83, 84, 85, 86, 120, 123, 126, 130, 134, 153, 1173 ] )
```

**Comment by markuspf** [comment]
You're quite right, `View` should be short, `Display` should be more verbose, and `Print` can be what it is right now (if the code is copy-and-pasteable, I haven't tried that). I will adapt the PR accordingly.

There are more things that could be done, but I figure an incremental approach to this is better than trying to collect everything in one PR that never gets merged and bitrots.

**Comment by markuspf** [comment]
I updated the code to install `ViewString` and `DisplayString` methods.

For reference this is how the example above now behaves:
```
gap> F := FreeGroup(2);
<free group on the generators [ f1, f2 ]>
gap> FamilyObj(F);
<Family: "CollectionsFamily(...)">
gap> Display(FamilyObj(F));
name:
    CollectionsFamily(...)
required filters:
    IsCollection
implied filters:
    IsListOrCollection
    IsCollection
    IsExtLElement
    CategoryCollections(IsExtLElement)
    IsExtRElement
    CategoryCollections(IsExtRElement)
    CategoryCollections(IsMultiplicativeElement)
    CategoryCollections(IsMultiplicativeElementWithOne)
    CategoryCollections(IsMultiplicativeElementWithInverse)
    IsOddAdditiveNestingDepthObject
    CategoryCollections(IsAssociativeElement)
    IsGeneratorsOfMagmaWithInverses
    Tester(IsGeneratorsOfMagmaWithInverses)
    IsGeneratorsOfSemigroup
    Tester(IsGeneratorsOfSemigroup)
    CategoryCollections(IsWord)
    CategoryCollections((IsWord and IsAssociativeElement))
    CategoryCollections(((IsWord and IsAssociativeElement) and (IsWord and IsMultiplicativeElementWithOne)))
    CategoryCollections(((IsWord and IsAssociativeElement) and (IsWord and IsMultiplicativeElementWithInverse)))
gap> FamilyObj(F.1);       
<Family: "FreeGroupElementsFamily">
gap> Display(FamilyObj(F.1));
name:
    FreeGroupElementsFamily
required filters:
    IsMultiplicativeElementWithInverse
    IsAssociativeElement
    IsWord
implied filters:
    CanEasilyCompareElements
    Tester(CanEasilyCompareElements)
    CanEasilySortElements
    Tester(CanEasilySortElements)
    IsExtLElement
    IsExtRElement
    IsMultiplicativeElement
    IsMultiplicativeElementWithOne
    IsMultiplicativeElementWithInverse
    IsAssociativeElement
    IsWord
```

I have some ideas as to making the filter-names clickable or hoverable in the Jupyter interface. That will of course probably be a Jupyter-specific View/Display.

**Comment by markuspf** [comment]
Incidentally the `Print` method does not at all output GAP-parseable output.

**Pull request merged**
