### PR TITLE
<ignore, for testing>

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This is just for @chrisjefferson to test how coverage is generated. Please ignore.

### CODE REVIEW

**Comment by markuspf** [comment]
Can we close this again?

**Comment by ChrisJefferson** [comment]
I'd prefer to keep it around. Continue ignoring it :) I want to see if recent changes have removed issues with coverage wobbling.

**Comment by fingolfin** [comment]
Coverage wobble still happens :-(

**Comment by fingolfin** [comment]
This seems to be obsolete (if not: sorry! please reopen)

**Comment by ChrisJefferson** [comment]
closing and reopening seems to have confused coverage. Closing again.

**Pull request closed without merging**
