### PR TITLE
Remove cooperman permutation code

### PR DESCRIPTION
**Pull request by markuspf**
Please make sure that this pull request:

- [x] is submitted to the correct branch (the stable branch is only for bugfixes)

- [x] contains an accurate description of changes for the release notes below

- [x] provides new tests or relies on existing ones

- [x] correctly refers to other issues and related pull requests

### Description of changes (for the release notes)

This PR removes Code from `permutat.c` that implements supposedly better methods for permutation operations. Since this code was neither tested, nor hooked up anywhere, it is removed here.
We should possibly resurrected it as a package such as https://github.com/markuspf/permutat and supply appropriate benchmarks.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
FYI this is the reference to the paper which describes this algorithm: Gene Cooperman and Xiaoqin Ma. 2002. Overcoming the memory wall in symbolic algebra: a faster permutation multiplication. SIGSAM Bull. 36, 4 (December 2002), 1-4. DOI=http://dx.doi.org/10.1145/641239.641241

**Comment by markuspf** [comment]
The obvious second option is to hook up and test the cooperman multiplication, if it has obvious benefits for general use (which I could do in a different PR).

**Comment by fingolfin** [comment]
I conducted some experiments on 2^16+1 and 2^24+1 points (i.e. generate a symmtric group, take two random elements, then multiply them with each method).
I also tried various values of the (under-documented...) `logBucketSize` parameter -- I tried 1, 10, 20, 30.

For 2^16+1, it seems the Cooperman-Ma method is always slower -- at least I wasn't able to find a `logBucketSize` value where it wasn't.

For 2^24+1, it seems `logBucketSize=20` is more or less the "sweet spot". With that setting, the Cooperman-Ma method was a bit faster -- 10 multiplications wnet from 2.5 to 2.2 seconds. That's far from the factor 3.4 speed up described in the paper.

Perhaps this was all my fault, for not using optimal `logBucketSize` settings or something -- but that's irrelevant, as it is not documented how to use it "properly", and so everybody would have the same problem, I guess.

Based on this, I agree it seems sensible to remove this.

**Comment by markuspf** [comment]
I can't get it to run faster on basically any randomly generated examples either. 

There's of course the issue that it was designed for the memory characteristics that existed in 2002 (or 2007, which is when the code was added). 

This methods performance depends on the structure of the permutations involved: if the points are not moved very far away, locality is not too much of a problem.

Maybe it'd be a nice internship project to do some experimentation with this method (and potential parallelisation of this multiplication?)

**Comment by markuspf** [comment]
So, update: I ran some benchmarks on permutations on 2^26 + 1 points ranging the bucket size from 2^8 to 2^24, and for 2^22 I got a 20% speedup over the builtin multiplication:

```
builtin: 30.573363736
cooperman:
bucketsize: 256 116.045106934
bucketsize: 512 98.45345511799999
bucketsize: 1024 67.598786178
bucketsize: 2048 62.255970987
bucketsize: 4096 60.711272484
bucketsize: 8192 58.39647240400001
bucketsize: 16384 48.839939593
bucketsize: 32768 45.779925407
bucketsize: 65536 45.346617859
bucketsize: 131072 45.85771512800001
bucketsize: 262144 46.38302097299999
bucketsize: 524288 43.90982119
bucketsize: 1048576 35.82537564100001
bucketsize: 2097152 29.37108889300001
bucketsize: 4194304 23.894643344
bucketsize: 8388608 24.412840362
bucketsize: 16777216 25.852806242
```

**Comment by fingolfin** [comment]
I still think removing this is the right step... But perhaps @stevelinton , @frankluebeck @hulpke have another oppinion?

**Comment by stevelinton** [comment]
I'm fine for this to be removed. I wrote it baically as an experiment and committed it for some reason I can no longer rmemeber, but it never produced a useful speedup.

**Comment by ChrisJefferson** [comment]
Just to chime in, I also tried playing with this. If anyone ever wanted to use this in general, they would have to do extensive testing. I did come up with a tuning which lead to ~30% speed improvements, but found that configuration slowed down another (32-bit intel CPU) by ~40%. If we wanted to start using things like this, I think we'd have to introduce machine-specific automatic CPU tuning, which while fun would also be a major undertaking.

**Comment by frankluebeck** [comment]
Years ago I have done similar tests with this code as described above, and I came to the same results (at best a little bit faster on certain degree ranges but similar or slower as the standard code in other ranges).

I'd say it is save to remove that code.

**Pull request merged**
