### PR TITLE
Remove group presentation from tst/testinstall/opers/Socle.tst

### PR DESCRIPTION
**Pull request by hungaborhorvath**
Tried to remove all group presentations from Socle.tst.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@hungaborhorvath - thanks, looks good to me!

**Comment by alex-konovalov** [comment]
@hungaborhorvath I've merged this, but it crashes in the `make testinstall` call:
```
########> Diff in /Volumes/hudson-fs/workspace/GAP-dev/GAPCOPTS/64build/GAPGMP\
/gmp/GAPTARGET/install/label/fruitloop/GAP-git-snapshot/tst/testinstall/opers/\
Socle.tst, line 45:
# Input is:
Socle(D) = ClosureSubgroup(TrivialSubgroup(D), Union(Set(MinimalNormalSubgroup\
s(D), GeneratorsOfGroup)));
# Expected output:
true
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```
`make testinstall` starts GAP with `-m 100m -o 1g` so it could happen that that runs for you with default `-o 2g` option, but fails in test setting, or that it actually points to some regression - anyhow, this needs an investigation.

**Comment by hungaborhorvath** [comment]
@alex-konovalov What other options are used? This runs fine for me: 

````
ghorvath@SamsungLaptop:~/work/gap$ bin/gap.sh -m 100m -o 1g
 ┌───────┐   GAP v4.8.1-278-g51bbf2f of 2016-01-25 23:34:17 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, 
             CRISP 1.4.1, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, 
             FactInt 1.5.3, FGA 1.3.0, GAPDoc 1.5.1, IO 4.4.4, IRREDSOL 1.2.4, 
             LAGUNA 3.7.0, Polenta 1.3.2, Polycyclic 2.11, RadiRoot 2.7, 
             ResClasses 3.4.0, Sophus 1.23, SpinSym 1.5, TomLib 1.2.5
 Try '?help' for help. See also  '?copyright' and  '?authors'
gap> Test("tst/testinstall/opers/Socle.tst");
Socle.tst
GAP4stones: 13
true
gap> 
````

**Comment by alex-konovalov** [comment]
The full list of options can be seen in `Makefile.in`
```
TESTGAP = ./bin/gap-$(CONFIGNAME).sh -b -m 100m -o 1g -A -q -x 80 -r $(GAPARGS)
TESTGAPauto = ./bin/gap-$(CONFIGNAME).sh -b -m 100m -o 1g -q -x 80 -r $(GAPARGS)
```
Only `-m` and `-o` are memory related. Try also `-A` to disable packages - it could happen that with `-A` some package that extends the functionality is missing, and the built-in code runs out of memory. To reproduce exactly the setting of the test in which I am observing this, call
```
make testinstall
```
and then inspect log files `testinstall1...` and `testinstall2...` that will appear in `dev/log` directory. `1` stands for the test with `-A` option, and `2` for the test when all packages are loaded.

**Comment by hungaborhorvath** [comment]
@alex-konovalov Thanks, I managed to reproduce it. Removed the MinimalNormalSubgroups line, now it runs without any packages with the memory settings. I issued the PR: #534

Sorry for the problem, I did not check it without packages and with this memory limit. 

Maybe the line could be added to teststandard?

**Comment by alex-konovalov** [comment]
> Maybe the line could be added to teststandard?

No, it will fail in the same way there because of the same `-o 1g` used there.

**Pull request merged**
