### PR TITLE
Random cleanup, and remove StringAndFilter from kernel

### PR DESCRIPTION
**Pull request by fingolfin**
This is just a bunch of random cleanup which reduces the diffs to HPC-GAP a little bit.

Also, I removed `StringAndFilter` from the kernel, addressing #977

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Looks good to me.

**Comment by fingolfin** [comment]
I am going to add some more stuff to this, so please don't merge for now

**Comment by fingolfin** [comment]
This is now ready to go from my POV (assuming tests pass)

**Comment by hulpke** [comment]
All uncontroversial with me, but again the caveat that the primitive groups library is becoming a package and thus changes therein need to be shadowed in the package.

**Comment by fingolfin** [comment]
@hulpke I am not quite sure what your comment is trying to say. Is this a reminder to your and/or whoever is working on moving primitive groups into a package? Or is there something else it implies, which I am not catching? Is it an objection to this PR being merged, or just a tangential comment?

BTW, I think it's great that prim and trans (and perhaps also small?) are moving into packages, and it has my full moral support. But there wasn't any public communication on this so far, was there? I only saw github projects being created for them some months ago, and epxected some heads up on the mailing list or somewhere, but I don't recall any... given that there was so little communication on these, I am not sure how you can expect anybody to take this into consideration when making changes... after all, I can't take something into consideration I don't really know anything about...

More specifically, I have no idea what the exact plans for making these data libraries into packages are... who is supposed to do the work? What is the transition strategy? (I assume there is one, at least -- right now, having those packages present in my `pkg` dir causes GAP to spew errors when loading, even I assume that'll be fixed?) What is the intended timeframe? Etc.

**Comment by markuspf** [comment]
Moving prim, trans, and smallgrp, into packages is a long-standing plan which has been asked for (and communicated by) @alex-konovalov quite a few times.

There actually is https://github.com/gap-packages/smallgrp already, I just have to find the time to complete it. This has been discussed with Bettina and Eamonn in Edinburgh this year.

Any further discussion we should do maybe on the mailing list. I assume we wanted to make an announcement once the packages are reasonably done.

**Comment by fingolfin** [comment]
@markuspf I know that this is a long standing plan, it has been mentioned for years and years. I am talking about the recent activities towards this -- I am not aware of any communication by @alex-konovalov on that matter, or by anybody else. My point was that I am surprised that the fact that apparently now the stakeholders in the various libs have decided to actually moved foward has not been communicated on the mailing list.

**Comment by hulpke** [comment]
@fingolfin 
My remark is not an objection to merging, but to make sure that the changes concerning prim will also go in the package at
https://github.com/gap-packages/primgrp
and not get lost.

There similarly is a package for the transitive groups at
https://github.com/hulpke/transgrp

There is already setup in the library that, if these packages are available, they get loaded in preference over the prim/trans folders of the main system. Also the main system will run if neither packages, nor folders are available (but of course then some tests fail as they cannot form the groups).

I was working under the assumption that 4.9 would remove the prim and trans folders and instead rely on the packages, but probably @alex-konovalov can comment better on timeline and transition.

**Comment by fingolfin** [comment]
@hulpke Thanks, that clarifies things quite a bit.

So if even you are a bit in the dark about the timeline and transition, I really think it would be important to communicate this better. Either via the mailing list, or perhaps via an issue here which outlines the plan, and tracks its progress (and what needs to be done -- that way, others could help with it, too).

**Comment by alex-konovalov** [comment]
@fingolfin @hulpke actually, if you will look at Milestone GAP 4.9 at https://github.com/gap-system/gap/milestone/4 then you will see there issues #791 and #792 for making packages for transitive and primitive groups library. The only reason why there is no issue for Small Groups there was that these two issues were created before it was discussed with Bettina and Eamonn in Edinburgh in summer 2016. Perhaps @markuspf would be the best person to create such issue, as he already did major part of work for converting it into a package.

**Pull request merged**
