### PR TITLE
Use `Pluralize` to give correct pluralization in many GAP library methods

### PR DESCRIPTION
**Pull request by wilfwilson**
This PR was originally part of #3992, so it has already been discussed there.

This PR uses the `Pluralize` function in many locations in the GAP library, so that GAP produces more grammatically correct strings - such as `<magma with 1 generator>` rather than `<magma with 1 generators>`. There is also a follow-up PR #4343.

This PR affects the `ViewString` of many objects, and so this will cause the tests/manual examples for many packages to fail. Therefore this cannot be merged until those tests/examples are adjusted, and new package versions are released. I will use this description to keep track of what needs to be done for that, initially copied from https://github.com/gap-system/gap/pull/3992#issuecomment-626346932.

### Open PRs

None.

### Pending release

None.

### Resolved

- [x] anupq – fixed in v3.2.3 (via https://github.com/gap-packages/anupq/pull/46)
- [x] circle – fixed in v1.6.4 (via https://github.com/gap-packages/circle/pull/9)
- [x] crime
- [x] crisp – incorrect pluralisations only occur in a `.tex` file
- [x] cubefree – fixed in v1.19 via https://github.com/gap-packages/cubefree/pull/5
- [x] ctbllib-1.3.2 - incorrect pluralisations only occur in `doc2/ambigfus.xml`, and the relevant test does not appear in a test file. So I don't think that merging this will cause its tests to fail.
- [x] digraphs – fixed in v1.2.1
- [x] fining – I'm pretty sure that the manual example output is automatically generated and not used in tests; test files are not affected by this PR (I ran `tst/testall.g` with this PR)
- [x] forms – one instance, but doesn't seem to affect tests
- [x] fr – one manual example affected, but those seem not to be used in tests.
- [x] laguna – fixed in v3.9.4 (via **https://github.com/gap-packages/laguna/pull/20)
- [x] lpres
- [x] nilmat – fixed in v1.4.1 via https://github.com/gap-packages/nilmat/pull/4
- [x] nq
- [x] NumericalSgps – might want to use `Pluralize` in the future
- [x] qpa-version – uses it in manual examples, but those are manually formatted anyway and not used in tests?
- [x] rds – fixed in v1.8 via https://github.com/gap-packages/rds/pull/1
- [x] RepnDecomp – fixed in v1.2.0 via https://github.com/gap-packages/RepnDecomp/pull/10
- [x] semigroups – fixed initially in v3.3.1 and again in v3.4.1
- [x] singular – fixed in v2020.12.18
- [x] SmallGrp – fixed in v1.4.2
- [x] smallsemi – fixed in v0.6.13 via https://github.com/gap-packages/smallsemi/pull/18
- [x] sonata – fixed in v2.9.2 via https://github.com/gap-packages/sonata/pull/19
- [x] sophus
- [x] spinsym
- [x] walrus – fixed in v0.9991 via https://github.com/gap-packages/walrus/pull/33
- [x] wedderga – fixed in v4.10.1 via https://github.com/gap-packages/wedderga/pull/85
- [x] xgap – one place uses (four times) `<matrix group with 1 generators>` but it seems to be done manually and not tested
- [x] XMod – fixed in v2.82
- [x] XModAlg – fixed in v1.18

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@wilfwilson I merged in Circle, LAGUNA and Wedderga - will try to make releases after switching them to GitHub actions for CI.

**Comment by fingolfin** [comment]
With the switch to the new package distro, we can merge this! (Well, ideally, we'd first run all package tests against this, using either the CI @wilfwilson set up at https://github.com/gap-infra/integration or the ones at https://github.com/gap-system/PackageDistro . But we don't have the tooling for that set up yet... but hopefully soon!

**Review by alex-konovalov — APPROVED** [review]
Indeed, all checkboxes for GAP packages are now ticked.

**Comment by fingolfin** [comment]
@wilfwilson this PR still has a "do not merge" label. Can it be removed?

**Comment by wilfwilson** [comment]
Please do @fingolfin!

**Comment by fingolfin** [comment]
Unfortunately this broke the QPA tests, see https://github.com/gap-system/PackageDistro/runs/7161848758?check_suite_focus=true -- on the positive, side, it *only* broke those. Reported at https://github.com/gap-packages/qpa/issues/71

**Comment by wilfwilson** [comment]
I'm amazed it broke so little! Thank you for reporting that @fingolfin.

**Pull request merged**
