### PR TITLE
Reverting nested alarms in the stable-4.8 branch

### PR DESCRIPTION
**Pull request by alex-konovalov**
This reverts the following commits:
53e0a18c662c4189edbc4e8dd53894342da6ffe8
b8f10919355305e9f76456ba06a8495ecc8234a4
96c7532d8db5b576bfe52a99ea87941d909a60de
ce694b2ba66451673434c721db5034d73ebbb945

since this code is not yet ready for the release.

### CODE REVIEW

**Comment by markuspf** [comment]
If you hold back on this for a while, I think I know what is going wrong here.

**Comment by markuspf** [comment]
Mhm, actually the code checks these conditions.  I'll have to look more closely which implementation of the timers is actually used and why wrong values are passed.

**Comment by alex-konovalov** [comment]
@markuspf any hope, or should we merge this and retry this after 4.8.3?

**Comment by alex-konovalov** [comment]
@markuspf achieved some progress in PR #672 submitted to the master branch, but to keep with the release schedule, I am going to merge this and revert nested alarms in the stable-4.8 branch. We may attempt to introduce them in GAP 4.8.4.

**Pull request merged**
