### PR TITLE
Add tests for Backtraces

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Please make sure that this pull request:

- [X] is submitted to the correct branch (the stable branch is only for bugfixes)
- [X] contains an accurate description of changes for the release notes below
- [X] provides new tests or relies on existing ones
- [X] correctly refers to other issues and related pull requests

### Tick all what applies to this pull request

- [X] Adds new features

### Write below the description of changes (for the release notes)

This adds a new type of test, which allows testing the exact output of GAP. This is useful for testing GAP's break loop and backtraces in particular.

Run `run_error_tests.sh` to run all tests. They are not (yet) linked into being run all the time.

This is a necessary part of my planned improvements to GAP's reporting on what line caused problems when entering the break loop.

### CODE REVIEW

**Comment by markuspf** [comment]
I'm being slow again: the `semigroups` project seems to be testing `Error` messages already today, what does this do differently?

**Comment by ChrisJefferson** [comment]
I should be more exact!

They aren't testing the backtraces (which they don't care about), and the `in x[y] at file.g:12` type statements. That's what I want to test. I've editted the title of the patch.

**Comment by alex-konovalov** [comment]
@ChrisJefferson yes, I see what you mean. In `.tst` we test only the initial part of the error message, without backtraces. This therefore seems useful. Did someone try to run these tests on another machine?

**Comment by markuspf** [comment]
I did, so I am going to merge this now.

**Comment by alex-konovalov** [comment]
@ChrisJefferson: I think to start with, one should call GAP with -r -A here. I've tried to run it and all tests failed, but diffs are not displayed - hard to find out what's going on here...

**Comment by alex-konovalov** [comment]
@ChrisJefferson: I've added `-r -A` option in https://github.com/gap-system/gap/commit/0b2747bd60255047a1f1c4e4a034dcb9ca5b1d78. Can't see why the test does not pass: where does `>` come from?

```
$ ./run_error_tests.sh 
1c1
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
---
> Error, no method found! For debugging hints type ?Recovery from NoMethodFound
bad-add.g failed
1c1
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
---
> Error, no method found! For debugging hints type ?Recovery from NoMethodFound
bad-array-double-1.g failed
1c1
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
---
> Error, no method found! For debugging hints type ?Recovery from NoMethodFound
bad-array-int-0.g failed
1c1
Error, List Element: <list> must be a list (not a integer) in
---
> Error, List Element: <list> must be a list (not a integer) in
bad-array-int-1.g failed
1c1
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
---
> Error, no method found! For debugging hints type ?Recovery from NoMethodFound
bad-array-string.g failed
1c1
Error, Variable: 'l' must have an assigned value in
---
> Error, Variable: 'l' must have an assigned value in
bad-array-undef-0.g failed
1c1
Error, Variable: 'm' must have an assigned value in
---
> Error, Variable: 'm' must have an assigned value in
bad-array-undef-1.g failed
1c1
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
---
> Error, no method found! For debugging hints type ?Recovery from NoMethodFound
bad-minus.g failed
```

**Pull request merged**
