### PR TITLE
Correct typo in COPYRIGHT

### PR DESCRIPTION
**Pull request by Joseph-Edwards**
This PR corrects a typo in the COPYRIGHT file.

## Text for release notes

None

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thanks, but it seems it was correct: https://dictionary.cambridge.org/dictionary/english/nee

**Comment by Joseph-Edwards** [comment]
I think née is used when women change their names, and né for men. I realise this is quite pedantic though!

**Comment by olexandr-konovalov** [comment]
@Joseph-Edwards oh, I see! This is not even in Cambridge Online, but mentioned in https://en.wikipedia.org/wiki/Birth_name. Let's ask @mtorpey to review!

**Comment by mtorpey** [comment]
I love that this has come up.  It's very pedantic, but indeed, *née* is feminine.  I sometimes use *né* myself, as in my Slack profile:

image

*né* isn't widely used in English, but of course this is because men so rarely change their surnames.

I support the PR.  But if something less quirky is called for, then "formerly" or "aka" would do.

**Review by mtorpey — APPROVED** [review]

**Pull request merged**
