### PR TITLE
Split some lines which can cause issues if garbage collection occurs

### LINKED ISSUE #501: Random corrupt saved workspace leading to segfault
Saved workspaces are randomly (but rarely) corrupt; SaveWorkspace can also segfault sometimes. Seems to rely on memory layout and can be triggered by randomly fiddling with gap memory pool size and environment variables. The following script generally leads to at least one segfault before running to completion:
~~~~bash
#!/bin/sh
GAPDIR=/tmp/gap-test/gap4r8
GAP=$GAPDIR/bin/x86_64-pc-linux-gnu-gcc-default64/gap

for i in `seq 0 100`
do
    for MEM in `seq 5 20`
    do
        echo "MEM = ${MEM}000k"
        echo 'SaveWorkspace("workspace");' | $GAP -r -A -m ${MEM}000k -l $GAPDIR > /dev/null
    	echo 'Basis(GF(2)^1);' | $GAP -q -r -A -l $GAPDIR -L workspace
	if [ $? -ne 0 ]; then
            echo "Error - workspace corrupt?"
            exit 1
        fi
    	echo 'Irr(CharacterTable(GL(2,7)));' | $GAP -r -A -l $GAPDIR -L workspace | grep Error
    done

    echo "Setting env, loop $i"
    for j in `seq 0 10`
    do 
        newvar=`mktemp -u tmpenvXXXXXXXXXXXXX`
    	newval=`mktemp -u tmpvalueXXXXXXXXXXXXXXXXXXX`
        export "$newvar=$newval"
    done
done
~~~~
Partial output showing a segfault:
~~~~
MEM = 20000k
CanonicalBasis( ( GF(2)^1 ) )
Setting env, loop 55
MEM = 5000k
CanonicalBasis( ( GF(2)^1 ) )
MEM = 6000k
CanonicalBasis( ( GF(2)^1 ) )
MEM = 7000k
CanonicalBasis( ( GF(2)^1 ) )
MEM = 8000k
CanonicalBasis( ( GF(2)^1 ) )
MEM = 9000k
./makeenv: line 11: 13719 Done                    echo 'SaveWorkspace("workspace");'
     13720 Segmentation fault      (core dumped) | $GAP -r -A -m ${MEM}000k -l $GAPDIR > /dev/null
~~~~
This is present in Gap-4.8.1 but has been there since at least 4.5.7 (issue ported from redmine http://tracker.gap-system.org/issues/224)

### PR DESCRIPTION
**Pull request by ChrisJefferson**
We need to split ```  ENVI_FUNC(func) = INTOBJ_INT( RNamObj(name) );``` into 
```  rnam = INTOBJ_INT( RNamObj(name) );
    ENVI_FUNC(func) = rnam;```, because as a single line C can (and in the case of gcc, does) compile the code to:

* evaluate `ENVI_FUNC(func)` - get pointer to where we are writing
* do `RNamObj(name)`, which causes a garbage collection (and moves `ENVI_FUNC(func)`!)
* Do `INTOBJ_INT`, then write the result to the old location of `ENVI_FUNC(func)` (corruption occurs).

While I was around I did some other changes which may not be necessary, but don't hurt (avoid calling CSTR_STRING on strings that might also get garbage collected before usage).

This (hopefully) fixes #501

### CODE REVIEW

**Comment by vbraun** [comment]
Good catch, the evaluation order in the assignment is unspecified.

**Comment by markuspf** [comment]
Another reason to love C! Thanks for debugging this.

**Comment by ChrisJefferson** [comment]
This has acquired another patch, which fixes a similar issue.

**Comment by markuspf** [comment]
@ChrisJefferson I wonder whether you could rebase this on stable-4.8, because these fixes should go into stable. Otherwise we should not forget to cherry pick this.

**Comment by ChrisJefferson** [comment]
Now rebased onto stable-4.8

**Comment by markuspf** [comment]
Looks like something went wrong with the rebase there?

**Comment by ChrisJefferson** [comment]
Oh wow, yes. Sorry. Will fix (stupid git)

**Comment by ChrisJefferson** [comment]
Moved to #519 , as I can't change the branch I'm applying the patch to (to stable-4.8).

**Pull request closed without merging**
