### PR TITLE
Adjust julia gc to `jl_gc_new_weakref` no longer being exported

### PR DESCRIPTION
**Pull request by lgoettgens**
As discussed in https://github.com/oscar-system/GAP.jl/issues/1032#issuecomment-2435216269. cc @fingolfin 

## Text for release notes

not needed

### CODE REVIEW

**Comment by fingolfin** [comment]
You'll need this at the top of the file:
```C
#include <julia_threads.h>    // for jl_get_ptls_states

#if JULIA_VERSION_MAJOR == 1 && JULIA_VERSION_MINOR == 7
// workaround issue with Julia 1.7 headers which "forgot" to export this
// function
JL_DLLEXPORT void * jl_get_ptls_states(void);
#endif

```

**Review by fingolfin — APPROVED** [review]

**Comment by fingolfin** [comment]
Still crashes :-(

**Comment by fingolfin** [comment]
We really should ask the Julia folks to add `jl_gc_new_weakref` back to headers given that `jl_gc_new_weakref_th` existed in older version but wasn't in the headers (and was it *exported*?)

**Comment by lgoettgens** [comment]
> Still lots of compiler warninga in the bundled GAP. And it compiles GAP twice, gotta look into that

The double compilation is due to the way that `setup_override_dir.jl` works. It expects gap to already be compiled the usual way, then replaces two files and re-compiles but this time with julia gc.

**Comment by fingolfin** [comment]
Julia PR was merged so we can close this. Thanks for the effort, @lgoettgens !

**Pull request closed without merging**
