### PR TITLE
Fix bug in compiler, and add tests

### LINKED ISSUE #1781: Compiler emits call to InfoDecision but symbol is defined `static` in intrprtr.c
With a fresh checkout of master, the compiling the snippet
```gap
SomeFunc := function(a, b)
    Info(InfoWarning, 1, "foo");
    return a+b;
end;
```
produces a module that fails to load:
```
LoadDynamicModule("libtest.la.so");
#W dlopen() error: dlopen(libtest.la.so, 9): Symbol not found: _InfoDecision
  Referenced from: libtest.la.so
  Expected in: flat namespace
 in libtest.la.so
```

It seems that `InfoDecision` is declared in compiled.h, but has no non-static definition. I fixed this locally with the following trivial diff:
```diff
diff --git a/src/intrprtr.c b/src/intrprtr.c
index fc1bc9576..c08153f56 100644
--- a/src/intrprtr.c
+++ b/src/intrprtr.c
@@ -4533,7 +4533,7 @@ void            IntrInfoBegin( void )
 
 }
 
-static Obj InfoDecision;
+Obj InfoDecision;
 static Obj InfoDecisionFast;
 static Obj IsInfoClassListRep;
```

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This patch fixes #1781 (which was easy, as there was a fix already in that PR!), but more usefully adds a simple testing infrastructure for the GAP->C compiler, and adds some simple tests (including for the fixed bug).

Obviously, the number of tests here is very small, but it provides a basic sanity check and a place for people to add more tests if they want.

### CODE REVIEW

**Comment by fingolfin** [comment]
Instead of renaming .out to .output, you could also just adjust the rule in `.gitignore`... :-) E.g. replacing it by this:
```
/doc/*/main.out
/log/*.out
```

**Comment by ChrisJefferson** [comment]
Touching the `.gitignore` seems to lead to bikesheding, so I thought it was easier to just rename the files intead...

**Comment by fingolfin** [comment]
@ChrisJefferson not sure why you think changing entries in `.gitignore` leads to bike shedding? Those entries all are there to hide build artifacts. In some cases, they are pretty generic, for simplicity; but we can always replace a relatively "general" entry with more specialized ones, as is needed here. I see no room for bikeshedding whatsoever.

And even if, then we should actively combat that, instead of avoiding to make certain changes.

That said, if you prefer `.output` over `.out`, that's of course also OK, but I will now change the `.gitignore` rule for `.out` anyway...

**Comment by fingolfin** [comment]
Specifically, I already change `.gitignore` in PR #1780

**Comment by fingolfin** [comment]
@ChrisJefferson I am sorry but this now conflicts :/. Would you terribly mind updating it, then we can merge it ASAP.

**Pull request merged**
