### PR TITLE
Include random.gd before coll.gi

### PR DESCRIPTION
**Pull request by fingolfin**
This way, we can move the definition of GlobalMersenneTwister from
coll.gi to random.gd, and will be able to use InstallMethodWithRandomSource
inside of coll.gi

This implements a change I suggested on #2204 -- if @ChrisJefferson likes it, also feel free to cherry-pick this into your PR, and then we just test and merge your PR and we close this. Or we merge this first. Or we discard this PR if people hate it, and do something completely different ;-).

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This seems like a reasonable change, but it's entirely incompatible with my PR, so we could merge this, then I throw my PR away and start again.

**Comment by fingolfin** [comment]
If you are willing to do that: fine by me, thanks, and sorry for the extra work

**Comment by fingolfin** [comment]
BTW, I don't think it is *that* incompatible: the first commit of your PR should not conflict at all, and the second just needs the "a (finite) collection" method installation moved back to `coll.gi`, no?

I could also do that, and add your commits to this PR, then you have no further work. Just let me know what you prefer (i.e. either merge this PR then rebase yours, or tell me to merge your work into this PR).

**Comment by ChrisJefferson** [comment]
I'll merge this and fix, my PR has other problems (some infinite loop is happening)

**Pull request merged**
