### PR TITLE
Improve Test and TestDirectory, sync more HPC-GAP test files

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This patch looks fine. I can't figure out why it is breaking the manuals however.

**Comment by fingolfin** [comment]
Problem is with the tests for `Test()`. The diffs look as if there was no actual diff. Problem is that while this is true visually, it isn't true on the byte level: one of the things I added is code which shows where in the test we currently are at. I made this the new default. Some ways to fix this issue:
* turn the new code off by default
* as above, but turn it on only within `TestDirectory`
* modify the problematic test(s) to explicitly set `showProgress:=false`
* teach the diff code some basics about matching things based on their visual appearance, e.g. about \c and \r (I am not fond of this idea, but it is a possibility, so I list it)
* .... ?

**Comment by ChrisJefferson** [comment]
I'm still confused -- were these tests always failing we just weren't showing the failure?

Also, are these tests run with ignorewhitespace? We could certainly make ignore whitespace understand \c and \r

**Comment by alex-konovalov** [comment]
Diffs are puzzling from a first glance, but then I realised that we are testing how diffs are reported by `Test`. So we have "nested diffs":
 
```
########> Diff in /home/travis/build/gap-system/gap/doc/ref/../../lib/test.gi:
262 (/home/travis/build/gap-system/gap/tst/testmanuals/chapter7.tst:67)
# Input is:
Test(ss);
```
Expected output is
```
########> Diff in test stream, line 8:
# Input is:
a := 13+29;
# Expected output:
41
# But found:
42
########
false
```
But found:
```
########> Diff in test stream, line 8:
# Input is:
a := 13+29;
# Expected output:
41
# But found:
42
########
false
```
Next, we have
```
########> Diff in /home/travis/build/gap-system/gap/doc/ref/../../lib/test.gi:
262 (/home/travis/build/gap-system/gap/tst/testmanuals/chapter7.tst:81)
# Input is:
Test(ss, rec(reportDiff := Ignore, rewriteToFile := ftmp));
# Expected output:
false
# But found:
false
########
```
and
```
########> Diff in /home/travis/build/gap-system/gap/doc/ref/../../lib/test.gi:
262 (/home/travis/build/gap-system/gap/tst/testmanuals/chapter7.tst:83)
# Input is:
Test(ftmp);
# Expected output:
true
# But found:
true
########
```
Because we have exact comparison, maybe there is some whitespace symbol. Can you add `compareFunction:="uptowhitespace"` to the options record and see if this will gone?

**Comment by alex-konovalov** [comment]
Also, I've missed when option "some" was introduced (https://github.com/gap-system/gap/pull/1207/commits/b120c0d89855ad86d7a55e28f16e643745dbc6cc) - what does it mean? Finally, https://github.com/gap-system/gap/pull/1207/commits/2b675eafa70438e43ef1410d29b73c76ec9664e5 adds a new file, but the commit message says that tests were removed. This may be hard to understand when looking at this commit in the future.

**Comment by fingolfin** [comment]
First off, I should have mentioned that this PR changes Test and TestDirectory, and that these changes should be documented - I just didn't want to invest time into writing documentation before the feature is not finalized - and indeed, as I learned from the tests, they need more work.

The "some" variant for showProgress only displays the line number of the next line `Test` is going to read. This is helpful for long .tst files, as you can see which lines take a long time, or possibly hang. Now, to do that, it constantly overwrites the last terminal line. The result is an "animated" line number display. And if no test errors occur, this output is overwritten again at the end. Just try running `testinstall` with this branch to see it in action.

So the tests for `Test` itself really do produce a diff now, and with more than just whitespace as difference: all those line numbers are in it! But ifnyou print the diffnon a terminal, this is not visible.

**Comment by fingolfin** [comment]
In particular, Travis emulates enough of a terminal to hide the diff. I bet it would be visible on AppVeyor.

**Comment by fingolfin** [comment]
To be even more explicit: the output of `Test` now is something like this:
```
Testing file xyz.tst
\r# Line 1\c\r# Line 2\c\r# Line 3\c... and so on...
```

**Comment by fingolfin** [comment]
Rebased; also I dropped the changes to `Test` for now -- while I think this is useful, it should be in its own PR instead of holding this one back. I'll resubmit it eventually.

Also, I followed @alex-konovalov's feedback and reworded one commit message, see 775fa6acf2728e89b10742d8bf9495c59ba7b23c

**Pull request merged**
