### PR TITLE
kernel: move most system #includes out of common.h

### PR DESCRIPTION
**Pull request by fingolfin**
... and into the files that actually need them. That minimizes the risk of header conflicts, and also may be desirable for who code linking against GAP which may for some reason or another not want to #include certain system headers.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This should be checked it doesn't break any packages which are assuming those headers are included by gap?

**Comment by fingolfin** [comment]
That's among the things Travis tests for

**Comment by fingolfin** [comment]
So at the very least, the `io` and `profiling` packages are affected by this, both are in need of an `#include <stdio.h>`

**Comment by fingolfin** [comment]
I added a HACK commit to workaround the issue by adding `#include <stdio.h>` into `src/compiled.h`. This shouldn't be merged as is, but will allow me to find out which others packages might be affected.

**Comment by ChrisJefferson** [comment]
Will merge when conflicts are fixed.

**Comment by fingolfin** [comment]
Done, but let's see if tests still pass

**Pull request merged**
