### PR TITLE
FreeMonoid(0) is a monoid, not a group

### PR DESCRIPTION
**Pull request by markuspf**
Please make sure that this pull request:

- [x] is submitted to the correct branch (the stable branch is only for bugfixes)
- [x] contains an accurate description of changes for the release notes below
- [x] provides new tests or relies on existing ones
- [x] correctly refers to other issues and related pull requests

### Tick all what applies to this pull request

- [x] Improves and extends functionality

### Write below the description of changes (for the release notes)

`FreeMonoid(0)` was previously inferred to be a group which meant that code for monoids needed to be special cased. See also #673.

### CODE REVIEW

**Comment by markuspf** [comment]
Of course this breaks all semigroup tests.

**Comment by markuspf** [comment]
@james-d-mitchell any input on how your preferred fix looks like?

**Comment by james-d-mitchell** [comment]
Will have a look later today. I recall trying to fix this previously and
not finding a good solution.

**Comment by james-d-mitchell** [comment]
I think the changes you've made are correct, and are the ones I would have made had I had more courage. 

The diffs in the tests look pretty harmless to me, I'm going to try running the Semigroups package tests with your changes to see if anything more serious comes up. I'll report when I've done that.

**Comment by james-d-mitchell** [comment]
@markuspf I ran the Semigroups tests and this does not break anything seriously there (somethings are broken but they are all like the failures in the tests here). I think you should rewrite the test output so that the test don't fail, and press ahead with this.

**Comment by markuspf** [comment]
I will fix this soon.

**Comment by markuspf** [comment]
Now this of course begs the question what to do about things like

```
gap> S := Semigroup(PartialPerm([1]));
<trivial partial perm monoid of rank 1 with 1 generator>
```

Why does this produce a monoid, not a semigroup?

**Comment by james-d-mitchell** [comment]
Because it is a monoid :) Is this related to the current issue? The
Semigroup function makes a monoid out of any generating set which contains
the One of its generators.

**Comment by markuspf** [comment]
But is that not the same kind of cleverness that we are just trying to fix?

**Comment by james-d-mitchell** [comment]
Yes, this was probably a mistake, which I'd like to rectify at a later point.

**Comment by alex-konovalov** [comment]
@markuspf as you likely know - with all packages loaded we now have:
```
########> Diff in /home/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build\
/GAPTARGET/install/label/graupius/GAP-master-snapshot/tst/testinstall/semigrp.\
tst:290
# Input is:
S := Semigroup(PartialPerm([1]));
# Expected output:
<trivial partial perm monoid of rank 1 with 1 generator>
# But found:
<trivial partial perm group of rank 1 with 1 generator>
########
########> Diff in /home/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build\
/GAPTARGET/install/label/graupius/GAP-master-snapshot/tst/testinstall/semigrp.\
tst:300
# Input is:
S := Semigroup(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
########> Diff in /home/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build\
/GAPTARGET/install/label/graupius/GAP-master-snapshot/tst/testinstall/semigrp.\
tst:309
# Input is:
S := Monoid(PartialPerm([1]));
# Expected output:
<trivial partial perm monoid of rank 1 with 1 generator>
# But found:
<trivial partial perm group of rank 1 with 1 generator>
########
########> Diff in /home/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build\
/GAPTARGET/install/label/graupius/GAP-master-snapshot/tst/testinstall/semigrp.\
tst:311
# Input is:
S := Monoid(PartialPerm([1]));
# Expected output:
<trivial partial perm monoid of rank 1 with 1 generator>
# But found:
<trivial partial perm group of rank 1 with 1 generator>
########
########> Diff in /home/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build\
/GAPTARGET/install/label/graupius/GAP-master-snapshot/tst/testinstall/semigrp.\
tst:317
# Input is:
S := Monoid(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
```

**Comment by markuspf** [comment]
Most of this is of course @james-d-mitchell's fault and a bug in the semigroups package.

(The other is the documentation not being updated)

**Comment by james-d-mitchell** [comment]
I don't know if it's my fault, but certainly I am preparing a new version of Semigroups to deal with these changes.

**Pull request merged**
