### PR TITLE
Changed  inequality to strict in documentation of Jennings series

### PR DESCRIPTION
**Pull request by grouptheoryenthusiast**
Please make sure that this pull request:

- [ ] is submitted to the correct branch (the stable branch is only for bugfixes)

- [ ] contains an accurate description of changes for the release notes below

- [ ] provides new tests or relies on existing ones

- [ ] correctly refers to other issues and related pull requests

### Description of changes (for the release notes)
Fixed the issue raised by Benjamin Sambale about the documentation of the Jennings Series. The documentation had incorrectly used `\geq` and this has now been changed to a strict inequality, `>`.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
While I believe this is right, I don't suppose you could also add a small test, to verify the new documentation (and mainly to make sure no-one breaks it in future!). Either a manual example, or a '.tst' file would be fine.

This isn't a requirement, but it would be nice to have.

**Comment by grouptheoryenthusiast** [comment]
@ChrisJefferson  I was also thinking this, I was trying to find the `.tst` file that tests other p-group series and couldn't find such a place.  I could make a file called `pgroup.tst` , into while I would add tests for the Jennings Series and tests for currently untested p-group functions could be added in here?

**Comment by hungaborhorvath** [comment]
Currently there exists a  ````tst/testinstall/pgroups.tst````, maybe it could go in there?

**Comment by grouptheoryenthusiast** [comment]
@hungaborhorvath  Thanks! I can't believe I didn't see that :) !

**Comment by ChrisJefferson** [comment]
This looks good. I'll just give it a day or so in case anyone wants to comment (I can't imagine they will), and then merge it.

**Pull request merged**
