### PR TITLE
Fix a bug in JenningsLieAlgebra and PCentralLieAlgebra

### PR DESCRIPTION
**Pull request by fingolfin**
Fix a bug reported by Laurent Bartholdi.

This is a rebased, squashed and slightly improved version of PR #2079

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin `START_TEST` does some things which in particular help to tests reproducibility:

https://github.com/gap-system/gap/blob/286b995f3d4e0f0e41b15ce0ce2319d6edad0d49/lib/profile.g#L1027-L1034 

Keeping calls to `START_TEST` in test files and not e.g. in `TestDirectory` allows to test a single testfile with `Test` and still have a setting close (of course, to some extent) to the one which will be used when running the full test suite (barring memory settings, packages loaded etc).

(IIRC there was a Wiki page "How to add a test to GAP", but can't seem to be able to find it now).

If you want to keep it in testinstall, I suggest to name it `liealgebras.tst` or so, as the obvious place where to put more tests for Lie algebras (and maybe @willemdegraaf would be interested to add some while starting to work with git?). `jennings` IMHO is too narrow for a test in testinstall (but would be fine for a test in testbugfix).

**Comment by fingolfin** [comment]
Alex, I know all that about START_TEST but fail to see the relevance of any of that in this particular case.
I also don't really "want" to keep that test fil anywhere. I just want to be done with this, and move on to things I care about.

I have now moved the .tst file to testbugfix.

**Comment by alex-konovalov** [comment]
OK, then please just rename it to `2018-01-15-jennings.tst` to follow the naming convention for the [`testbugfix` directory](https://github.com/gap-system/gap/tree/master/tst/testbugfix) and that will be it.

**Comment by fingolfin** [comment]
Done

**Comment by alex-konovalov** [comment]
Added to release notes for GAP 4.10 at https://github.com/gap-system/gap/wiki/Release-notes-for-GAP-4.10. I've checked what happens in GAP 4.8.10:
```
gap> g := Group((1,10)(2,9)(3,11)(4,12)(5,15)(6,16)(7,13)(8,14)(17,21)(18,22)*
> (19,24)(20,23)(25,27)(26,28)(29,30)(33,51)(34,52)(35,49)(36,50)(37,54)(38,53)*
> (39,55)(40,56)(41,61)(42,62)(43,64)(44,63)(45,57)(46,58)(47,60)(48,59), 
> (1,19)(2,20)(3,17)(4,18)(5,22)(6,21)(7,23)(8,24)(9,29)(10,30)(11,32)(12,31)*
> (13,25)(14,26)(15,28)(16,27)(33,42)(34,41)(35,43)(36,44)(37,47)(38,48)(39,45)*
> (40,46)(49,53)(50,54)(51,56)(52,55)(57,59)(58,60)(61,62), 
> (1,37)(2,38)(3,40)(4,39)(5,33)(6,34)(7,36)(8,35)(9,43)(10,44)(11,41)(12,42)*
> (13,46)(14,45)(15,47)(16,48)(17,58)(18,57)(19,59)(20,60)(21,63)(22,64)(23,61)*
> (24,62)(25,50)(26,49)(27,51)(28,52)(29,55)(30,56)(31,53)(32,54));
<permutation group with 3 generators>
gap> L:= JenningsLieAlgebra(g);
<Lie algebra of dimension 13 over GF(2)>
gap> List(Basis(L),PthPowerImage);
[ 0*v.1, v.3, 0*v.1, v.1, v.2, v.3, 0*v.1, v.10, v.11, v.12, 0*v.1, v.12, 
  0*v.1 ]
gap> LieLowerCentralSeries(L);
[ <Lie algebra of dimension 13 over GF(2)>, 
  <Lie algebra of dimension 3 over GF(2)> ]
```
so this is classified as a bug that can lead to incorrect results.

**Pull request merged**
