### PR TITLE
WIP Allow lists to be indexed by multiple values

### PR DESCRIPTION
**Pull request by stevelinton**
This PR provides kernel support for giving multiple indices to lists. 

m[1,2] is translated into m[[1,2]] although there is scope to do more for the special case of two arguments.

assignment, unbind and isbound are all supported.

It lacks testing, any library functionality and it depends on a pending PR from @fingolfin so it should not be merged as is.

### CODE REVIEW

**Comment by stevelinton** [comment]
Tried to rebase this onto current master. Clearly I messed up horribly. Can anyone advise?

**Comment by markuspf** [comment]
Hi Steve,

not entirely sure what you did there. It looks like the patches are applied twice, so maybe you tried rebasing and then merging?

I think I fixed it in https://github.com/markuspf/gap/tree/rebase-pr-83 by first resetting to f4aed5e and then rebasing on master.

There were three small confilcts, two in src/vars.c and one in src/code.c).

@fingolfin might give more insight into what actually happened.

Not sure whether I should open a new PR or overwrite this one...

**Comment by fingolfin** [comment]
Woah, that's quite a mess :-).

This looks indeed as if there were both merges and rebases, possibly even across multiple branches. If you then do a plain rebase, things get messy, simply because git cannot possible read your mind and know what exactly you want to rebase where (this is maybe one point where the Mercurial branch system can be helpful -- there, each commit in a hg branch is "colored" (i.e. the name of that branch is integral part of the commit record, unlike git, where branch names are just ephermal labels pointing to a single commit at the tip of a branch). Thus it "knows" what is part of that branch and what was merged into that branch from elsewhere. Of course that still doesn't make everything work magically, but, well...

@stevelinton To really figure out what happens, we'd have to know the precise steps you followed over time, when working with that branch...

**Comment by fingolfin** [comment]
BTW, the rebased version Markus created looks fine to me.

@stevelinton To recover, you coud first fetch Markus work into your clone. Then you can reset your messed up branch to that:
```
git checkout sl/multi-index
git fetch https://github.com/markuspf/gap rebase-pr-83
git reset --hard FETCH_HEAD
```

**Pull request closed without merging**
