### PR TITLE
Converted INSTALL to INSTALL.md and cleaned up

### PR DESCRIPTION
**Pull request by alex-konovalov**
This was long intended, and recently was reminded to myself when @markuspf was looking at removing details on building with/without GMP from INSTALL in the master branch. The plan is therefore first to convert INSTALL to INSTALL.md in the stable-4.8 branch, them merge it into master, and then remove non-GMP specifics.

Now the file should look better when it's rendered in Markdown e.g. on GitHub. However, I took care of not making any further dramatic changes which will decrease readability of the text version. I also replaced version numbers by 4.X.Y to avoid the necessity of updating them for each subsequent release.

This is work in progress - I'd like to clean up details about alternative distributions and expert install on Windows. But it's a good opportunity to revise the rest of the test, so if you have suggestions regarding other sections, please comment here or wait till it's merged and edit the file yourself.

BTW,  this quote from INSTALL file is relevant to the recent emails to GAP Support: **If you unpack the archive as root user under UNIX, make sure that you issue the command umask 022 before, to ensure that users will have permissions to read the files.** I wish I reread that a week ago ;-)

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@frankluebeck said:

> This reminds me that I already found README.md and CONTRIBUTING.md unpleasant to read as text files. It would be good if all of these files were formatted for a 80 (or 76) character wide screen.\

This cleanup sounds like a good task for someone who wants to practice with a simple pull request - if you want to pursue this further, you may submit an issue an label it "newcomer-friendly". I would be happy to merge such PR.

> Also the urls written as [visible text](http://...) are not nice to read as text. It would be nicer to have just http://... (even if it looks a little less nice when rendered as markdown).

Yes, I left all URLs untouched deliberately - not going to convert them to ` [visible text](http://...)` form by exactly the same reason.

**Comment by alex-konovalov** [comment]
Made 2nd pass - this is ready to be merged now, subject to review. If you would like to see how it looks in Markdown, please see https://github.com/alex-konovalov/gap/blob/install-markdown/INSTALL.md

**Comment by alex-konovalov** [comment]
Just to say: if anyone wants to edit INSTALL.md instead of commenting out on the PR, copy it to a page on Wiki and edit it there. I will pick up your changes from there.

**Comment by markuspf** [comment]
This looks good to me. I'll merge this, and if anyone has improvements to make they can go ahead and make a PR of their own.

As a side-note: Improving README and CONTRIBUTING files has been on my TODO list for a long time. The main reason for not touching them is the inevitable bikeshed, so I wanted to do this at one of the GAP days.

**Pull request merged**
