### PR TITLE
Make IsDirectoryPath take Directory objects, and add some simple directory tests

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This is a fairly boring patch. It makes 'IsDirectoryPath' take Directory objects, it also adds some basic tests for directory functionality.

This whole area could be improved and cleaned up, but I'm not doing that today.

### CODE REVIEW

**Comment by frankluebeck** [comment]
Looks fine, except for the naming. 

How about renaming the kernel function to `FuncIsDirectoryPathString` and exporting it to GAP level as `IsDirectoryPathString` (instead of  `STRING_DIRECTORY_PATH`)?

**Comment by ChrisJefferson** [comment]
That's fine, I took my inspiration from STRING_LIST_DIR just below, but a nicer looking name is fine too.

**Comment by frankluebeck** [comment]
The convention in GAP is that the left part of a function name indicates the type of the result and the right part the type of the input. So `STRING_LIST_DIR` gets a directory (yes, as a string) and returns a string (which is then further processed on GAP level).

**Comment by fingolfin** [comment]
Looks reasonable to me, too.

**Pull request merged**
