### PR TITLE
lib: remove lib/other.g*

### PR DESCRIPTION
**Pull request by fingolfin**
Their only content was an undocumented operation MagmaInputString which
takes a permutation group and returns a string which, when printed, can
be fed into Magma to produce the same permutation group.

While this is useful for some purposes, I don't think it belongs into
the GAP library. Perhaps a package can be created with this and related
functions? I have similar functions which take pc, pcp and fp groups
as input and would be happy to contribute them.

Alternatively, we could keep it in the library, and perhaps add my code
as additional methods, but that IMHO only makes sense if we document it.

@hulpke This is your code, what do you say?

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I agree on removing this, but will let Alexander comment. I know @hulpke has much better code than this for converting to, and from, magma.

**Comment by hulpke** [comment]
The purpose of this file was to start building functions (for different classes of groups) that produce Magma readable output. The reason for putting it into the library was my general disinclination towards packages (with their high administrative overhead), but if someone else wants to do so I have no objection. (I have no other GAP->Magma code, but significant Magma->GAP code, which is simply a standalone file.

**Comment by frankluebeck** [comment]
I agree that this does not belong to the GAP library.

But since it can be a useful function: how about moving it to the "utils" package (with short documentation, otherwise it is pointless)?

**Comment by fingolfin** [comment]
Sounds good to me. I wonder what @hulpke  and @cdwensley think about this?

For the record, here is also my function for converting pc and pcp groups to magma code. Something similar could also be done for fp groups. Then those functions (after some cleanup and tweaking, I guess) could be provided as methods for a single operation, e.g. `AsMagmaInputString` or so...

```gap
PcGroupToMagmaFormat := function(G)
    local str, g, n, r, gens, rels, i, j;
    if IsPcpGroup(G) then
        g := Pcp(G);
        r := RelativeOrders(Collector(G));
        n := Length(r);
        gens := List(g,String);
    else
        g := Pcgs(G);
        n := Length(g);
        r := RelativeOrders(g);
        gens := List(g,String);
    fi;

    str := "PolycyclicGroup< ";
    Append(str, JoinStringsWithSeparator(gens));
    Append(str, " |\n");

    rels := [];
    for i in [1..n] do
        if r[i] = 0 then continue; fi;
        if IsOne(g[i]^r[i]) then
            Add(rels, Concatenation(String(g[i]),"^",String(r[i])));
        else
            Add(rels, Concatenation(String(g[i]),"^",String(r[i])," = ",String(g[i]^r[i])));
        fi;
    od;
    for i in [2..n] do
        for j in [1..i-1] do
            if g[i]*g[j] <> g[j]*g[i] then
                Add(rels, Concatenation(String(g[i]),"^",String(g[j])," = ",String(g[i]^g[j])));
                if r[j] = 0 then
                    Add(rels, Concatenation(String(g[i]),"^",String(g[j]),"^-1 = ",String(g[i]^(g[j]^-1))));
                fi;
            fi;
        od;
    od;
    Append(str, JoinStringsWithSeparator(rels, ",\n"));
    Append(str, "\n>;\n");
    return str;
end;
```

**Comment by cdwensley** [comment]
It seems perfectly reasonable to me to extend the remit of Utils to include functions which have been in the main library and are no longer considered appropriate there.  It also seems reasonable that, if different authors have GAP<--->Magma conversion functions, then they would be better off collected into one place.
From my personal point of view the main snag with using Utils for this purpose is the question of testing.  Functions in Utils are expected to appear in one of the test files and hence in the manual.  But I have no access to Magma.  No doubt somebody else could deal with this, if they had the time, or perhaps some guest user facility for Magma is possible?

**Comment by cdwensley** [comment]
Just as a trial, I have added to Utils the functions from other.g{d,i}, renamed as PermGroupToMagmaFormat,  together with Max's PcGroupToMagmaFormat. 
These can easily be removed again if this is preferred - let me know what you think. 
There are some trivial examples added to the manual - no doubt better ones can be suggested. 
These files are available at:  https://github.com/gap-packages/utils.

**Comment by fingolfin** [comment]
@cdwensley That looks fine to me, thanks!

**Comment by cdwensley** [comment]
So what does Alexander @hulpke think about this?  He commented that "I have no other GAP->Magma code, but significant Magma->GAP code, which is simply a standalone file."  If this is a GAP file, might it be added to Utils?  If not, I could release utils-0.45 this week.

**Comment by fingolfin** [comment]
@cdwensley I think @hulpke was refering to his Magma-to-GAP converter, which is a somewhat bigger thing of its own. I somewhat doubt he'd want to include it in `utils`. So just go ahead with making a `utils` release with what is in it right now :-).

**Comment by frankluebeck** [comment]
I have a function `GAPMatricesToMagmaGroup` that prints for a given list of matrices over a finite field magma code which creates the group generated by these matrices.

If there is interest in this function contact me by email.

**Comment by cdwensley** [comment]
I will make a release of utils-0.45 tomorrow, with or without Frank's GAPMatricesToMagmaGroup.  It may turn out that other users have GAP->MAGMA code which can be added at a later stage.

**Pull request merged**
