### PR TITLE
Some kernel cleanup and refactoring

### PR DESCRIPTION
**Pull request by fingolfin**
I was looking into issue #358, and thus needed to understand how the bits in the kernel related to error handling, break loops etc. work. While I have not yet managed to attain my original goal, I think the resulting cleanups and refactoring are worthwhile on their own.

Plus, I now know what causes #358, though I have no idea how to fix it... ;-).

### CODE REVIEW

**Comment by fingolfin** [comment]
I rebased this on master, to resolve the conflicts caused by mergin #936.

To potential reviewers: I took great care to put all changes into clearly labeled, self-contained commits. So it should be possible to review this one commit at a time... I hope... :-)

**Comment by markuspf** [comment]
This looks good to me. I particularly approve of the replacement of obscure `ADDR_OBJ(something)[x]` by macros with sensible names.  

It occurred to me that I was wondering whether there is documentation of the stack layout anywhere, or even more detailed documentation on how the executor/interpreter works?

**Comment by fingolfin** [comment]
@markuspf I'd love to know that, too. I don't expect it to exist, though... would be really nice to have something, even if it just gives a rough sketch.

**Comment by ChrisJefferson** [comment]
This all looks good.

**Comment by alex-konovalov** [comment]
Two reviews from @markuspf and @ChrisJefferson - shall we rebase?

**Comment by fingolfin** [comment]
Since there isn't really much of a discussion here, I personally wouldn't mind if this was rebased (instead of merged). As long as it gets included into master in some way, I am happy :)

**Pull request merged**
