### PR TITLE
Various fixes to IsAssociate, StandardAssociate(Unit), ... and some tests

### LINKED ISSUE #3510: Fix StandardAssociateUnit for Z/nZ
Report on GAP support by Luciano Notarfrancesco:
```
gap> R := ZmodnZ(6);
(Integers mod 6)
gap> StandardAssociate(4*One(R));
ZmodnZObj( 2, 6 )
gap> StandardAssociateUnit(4*One(R));
ZmodnZObj( 2, 6 )
gap> IsUnit(StandardAssociateUnit(4*One(R)));
false
```

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #3510

### CODE REVIEW

**Comment by DominikBernhardt** [comment]
I think we could replace `for ring and two ring elements` with `for _a_ ring and two ring elements` since this would be grammatically correct.

**Comment by fingolfin** [comment]
@DominikBernhardt huh, where do you see "for ring and two ring elements"? Maybe comment on the specific lines?

**Comment by DominikBernhardt** [comment]
@fingolfin  Line `539`. I can't comment on that line because it is a line before the first line you changed. I just thought we could fix this in this PR as well.

**Comment by fingolfin** [comment]
@DominikBernhardt aha. No, let's not do that: it is an outside beyond the scope of this PR. If you spot an issue, why not submit a fix for it yourself?

**Comment by DominikBernhardt** [comment]
@fingolfin Sure, will do.

**Comment by fingolfin** [comment]
Thanks I'll update the PR ASAP

**Comment by fingolfin** [comment]
@wilfwilson commit message fixed, thanks. I also rewrote StandardAssociateUnit method for IsZmodnZObj, adding comments and simplifying it. I think it was good that you "made" me (well, very, very gently, of course :-) look at it again, because I already had forgotten the reasoning myself, and anyway, it was implemented in a needlessly complex (and obfuscated) way. I hope it is better now.

**Comment by fingolfin** [comment]
And having thorough tests rocks! Otherwise I wouldn't have dared this quick rewrite :-)

**Comment by wilfwilson** [comment]
I had a look – nice! I get it now. Good work.

**Comment by fingolfin** [comment]
@wilfwilson fixed on instance of "us" -> "use"

**Pull request merged**
