### PR TITLE
Better syntax error for an expr when expecting a statement

### LINKED ISSUE #822: Misleading error message when missing `()` from function call
### Observed behaviour

```
gap> f := function() Stabilizer; end;
Syntax error: := expected
f := function() Stabilizer; end;
```
### Expected behaviour

Perhaps `:= or () expected`? We could also expect `.`, `[]`, but I think the function call or brackets are what we want.

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #822

### CODE REVIEW

**Comment by fingolfin** [comment]
I am a bit concerned about the precise phrasing and would appreciate if a native speaker or two could take a look at this.

**Review by ChrisJefferson — APPROVED** [review]
I would say "found an expression..."(or more technically, you could say 'parsed an expression...') instead of "got an expression..."

**Review by stevelinton — APPROVED** [review]

**Review by wilfwilson — APPROVED** [review]

**Review by ruthhoffmann — APPROVED** [review]
Not a (fully) native speaker but agree with @ChrisJefferson

**Comment by fingolfin** [comment]
I've changed this to `found...` right after @ChrisJefferson pointed it out (it immediately "felt" better to me as well). So I assume everybody is happy with this now :-).

**Pull request merged**
