### PR TITLE
Move SCRSift into the kernel

### PR DESCRIPTION
**Pull request by stevelinton**
Gains about 30% in time but massively reduces the amount of memory allocated, with consequent reduction of garbage collection time

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Looks good for merging.

**Comment by fingolfin** [comment]
A few tests for this would be nice... ;-)

**Comment by frankluebeck** [comment]
Looks fine.

But is it really necessary to put the main loop in this kernel function?

How about a more generically useful kernel function `MultiplyBy(p1,p2)`  which works as "\*=", that is it changes inplace a permutation p1 to the product p1*p2?

**Comment by stevelinton** [comment]
I did think about that (and also the equivalent for large integers). 

It would involve making (or least allowing) these objects to be mutable though, with all the complexity that follows from that.  In this solution I only mutate a newly created permutation which no other object could possibly contain a reference to, so I'm safe.

The code that is in the kernel has three nested loops (down the stabchain, across the transversal and multiplying permutations). I probably could life the outer loop out of the kernel without much penalty, at least for "small base" type groups, but equally that loop doesn't add much complexity.

**Comment by stevelinton** [comment]
One possible approach occurs to me, based on the example of the way Java handles strings would be to have a separate type of PermBuffers. A PermBuffer is basically a mutable permutation, but it is NOT intended to be used in place of a permutation and permutations do not become Copyable. 

So you would do something like:

    pb := PermBuffer(p1[,options]);
    RightMultiply(pb, p2);
    .......
    TracePointThrough(pt, pb);

**Comment by stevelinton** [comment]
@fingolfin I've added some simple tests. 

@frankluebeck See issue #550. If that works, it might eventually enable this code to be removed from the kernel, but it's a relatively large project, so I would suggest this can be merged in the meantime.

**Pull request merged**
