### PR TITLE
Change TNUMs from #defines to enum, remove some unused ones, and more

### PR DESCRIPTION
**Pull request by fingolfin**
This PR changes a bunch of #defines to a big enum, which I think is easier to read and maintain.

It also reorders some TNUMs, and removes some unused ones. This revealed one placed in the library where the TNUM of booleans was hard coded (was 8, now is 12). If there is code out there which relies on specific TNUM values, it would thus be broken. Alas, that's a problem in any case, so I am tempted to ignore it, and wait for people to complain; then we can instruct them how to adjust their code to be future proof (and can still revert the relevant parts of this commit, at least temporarily).

Oh, and of course this breaks workspaces compatibility. But we have broken that constantly recently, and I think it's unrealistic to stop doing that, at least not on master (`stable` branches are something else, though even there this is tough).

I recommend reviewing the commits of this PR individually, to see the changes grouped logically.

### CODE REVIEW

**Comment by fingolfin** [comment]
Thinking about the potential for regressions some more, I can think of one caveat: This change may potentially require recompiling all package kernel extensions, as those may be using TNUMs, and compiling them of course "hard codes" those TNUMs.

So while we already made several changes recently which can force you to recompile kernel extensions, I think so far all of those are changes which will lead to link errors once on tries to load the kernel extension. This changes is different, as it could lead to silent errors, or weird crashes...

Of course this only affects people who work from `master`. Indeed, if you use `git bisect`, it can be annoying, because during bisection, all kinds of kernel packages could suddenly be broken...

So perhaps I should revert that part of the PR for now? Though note that with the bag "HPC-GAP merge" we already caused a similar break (but since we also added lots of other breaks, I guess it didn't really matter as much).

**Comment by ChrisJefferson** [comment]
We should have a way of checking kernel module's versions. I can think of a few different techniques, with a few different trade-offs.

**Comment by stevelinton** [comment]
> So while we already made several changes recently which can force you to recompile kernel extensions, I think so far all of those are changes which will lead to link errors once on tries to load the kernel extension. This changes is different, as it could lead to silent errors, or weird crashes...

As a slightly hacky defence, could we force a link error in this PR by renaming a function and then using a `#define` to  suport use of the old name.

**Comment by stevelinton** [comment]
PS Sorry about the explicit TNUMs.

**Comment by fingolfin** [comment]
@stevelinton that's a good idea

@ChrisJefferson Yeah, I can vaguely think of some, too (including a systematic variation of what @stevelinton suggests). Any more concrete discussions or *gasp* implementations would be highly welcome :-).

**Comment by ChrisJefferson** [comment]
I'm happy to do an implementation, it depends what we want to implement. Do we want "manually adjusted version", or "rebuild kernel modules on every new git commit".

**Comment by fingolfin** [comment]
I update the PR. In particular:
* `T_BODY` is now also part of the TNUM enum (I overlooked it before)
* That made me realize that our old check for `LAST_COPYING_TNUM` being <= 254 was inadequate, it must be <= 253
* also removed `T_SINGULAR` and `T_POLYMAKE`;  @sebasguts is working on adjusting PolymakeInterface, and SingularInterface already is adjusted (and not a distributed package anyway)


This leaves some meta questions (which don't need to be addressed for this PR, just wondering):
* Should the "shared" TNUMs of HPC-GAP really come after the external TNUMs? We might need to carefully look at some code that checks TNUM ranges
* should `T_BODY` perhaps be moved into the `CONSTANT_TNUM` list, alongside `T_HVARS` and `T_LVARS`, and `T_FUNCTION`? What consequences would that have?

**Comment by fingolfin** [comment]
@ChrisJefferson forcing a rebuild of all kernel etensions on each commit sounds horribly annoying. So the other solution sounds more appealing.

**Comment by markuspf** [comment]
This needs to be rebased.

**Comment by fingolfin** [comment]
Rebased, let's see whether the tests still pass.

**Pull request merged**
