### PR TITLE
Import ffdata.c/ffdata.h and finfield.c changes from HPC-GAP

### PR DESCRIPTION
**Pull request by markuspf**
This pull requests imports a change introduced to the finite fields code in HPC-GAP, but does not contain any HPC-GAP specific code. It merely changes the behaviour for the first 6635 finite fields in that their sizes, characteristics and degrees are stored in a table (which is defined in `src/ffdata.c`).

This will again lessen the differences between `master` and `hpcgap-default`

A future improvement could be generating this table.

### CODE REVIEW

**Comment by fingolfin** [comment]
Seems sensible to me, change looks good, tests pass...

**Comment by rbehrends** [comment]
> A future improvement could be generating this table.

FYI, the table is generated by `etc/ffgen.c`.

**Comment by fingolfin** [comment]
Then this PR probably should also copy `etc/ffgen.c` over?!

**Comment by markuspf** [comment]
It should, but where would these tools go? `etc` seems like a random collection of things, `ffgen.c` is more like a component of the build process.

**Comment by rbehrends** [comment]
Well, `ffgen.c` is not part of the build process, because the mathematical properties of finite fields are invariant and thus do not need to be updated. The code is there in case the file has to be reconstructed or to facilitate reformatting, but even so, using it during regular builds is at best a waste of CPU cycles and can at worst become a proximate cause for breakage.

**Comment by markuspf** [comment]
I added `ffgen.c` into the `etc/` directory as well.

**Pull request merged**
