### PR TITLE
Revert "travis: enable coverage reporting for 32bit builds"

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Reverts gap-system/gap#1065

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
reverting bad pull request. Just checking this works before merging.

**Comment by fingolfin** [comment]
or we just force-push a revert? unlikely many people pulled

**Comment by ChrisJefferson** [comment]
Bah. We could also just wait until tomorrow -- I've pushed a new profiling package release that should make this pass. @alex-konovalov - how long should it take the new package to get into bootstrap-pkg-full ?

**Comment by fingolfin** [comment]
WE should also reconsider whether we really want to use `bootstrap-pkg-full` for this anyway -- it's several hundred MBs that gt downloaded again and again and again...

**Comment by fingolfin** [comment]
Perhaps we could use the "cacche" feature Travis offers? Not sure if it is applicable and whether it would help, though

**Comment by fingolfin** [comment]
I resolved this now via force push. Too many PRs got messed up.

**Pull request closed without merging**
