### PR TITLE
Update config.guess and config.sub

### PR DESCRIPTION
**Pull request by fingolfin**
This should still work with 2.69, which is the most wide spread version. We'll see.

See also  #1478

### CODE REVIEW

**Comment by wilfwilson** [comment]
I'm happy to merge in the updated helper scripts, but I don't see why it should close #4377, because the purpose of that PR is to make the macOS GitHub Actions job pass, which this PR does not do.

**Review by wilfwilson — APPROVED** [review]
Thanks for sorting this out @fingolfin.

**Comment by fingolfin** [comment]
You are right, this was a red herring. I've updated the PR title and removed the "closes XYZ"

**Comment by fingolfin** [comment]
I still think it's useful to update these scripts, though, the last update was 2019-10-24

**Pull request merged**
