### PR TITLE
allow info string in "RedispatchOnCondition"

### PR DESCRIPTION
**Pull request by bh11**
This change allows an "info" string in RedispatchOnCondition, similar to "InstallMethod". In this way, one can provide some information about the conditions being tested, in order to make TraceMethods() easier to follow. If no "info" string is provided, the old text is used, so this should not interfere with the present code.

### CODE REVIEW

**Comment by hungaborhorvath** [comment]
This would be a very useful feature, and would help to keep code in a readable way. Do not have the means to check it, but I like the feature very much.

**Comment by alex-konovalov** [comment]
This looks good to me, but I would wait and to it after the 2nd beta of GAP 4.8

**Comment by fingolfin** [comment]
This is useful, and the code change looks sensible, too. Should be ready for merging.
@alex-konovalov If you want to delay it till after the 2nd beta, fine by me, as long as it gets merged eventually

**Comment by alex-konovalov** [comment]
Thanks @bh11 - I've cherry-picked this onto the newly created `stable-4.8` branch. This will appear in GAP 4.8.2.

**Pull request merged**
