### PR TITLE
Tilde fix

### LINKED ISSUE #1049: Strange behaviour of ~
### Observed behaviour
```
gap> a~ := 1;
Syntax error: ; expected
a~ := 1;
 ^
gap> ~a := 1;
Syntax error: ; expected
~a := 1;
 ^
gap> ~ := 1;
1
gap> l := [2, ~];
[ 2, ~ ]
gap> l = l[2];
true
```
### Expected behaviour
The assignment `~ := 1;` should lead to the same syntax error as the first examples.
### Copy and paste GAP banner (to tell us about your setup)
Seems that this has been in all version of GAP4 (and also in GAP3, where only the last line behaves differently).

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Fixes #1049 (users can assign `~`).

This is built on top of #490, so that should be merged first (if that gets rejected, or edited, I will adjust this as appropriate).

### CODE REVIEW

**Comment by fingolfin** [comment]
@ChrisJefferson there are some errors in the tests, according to Travis..

**Comment by ChrisJefferson** [comment]
Bah, this is some different, old errors. (We leave `~` with a bad value in the case we escape a setjmp/longjmp loop).

**Comment by ChrisJefferson** [comment]
Hopefully fixed after this patch filters through.

**Comment by fingolfin** [comment]
Rebased version is now in master as 51e8c0b9b05abaacc97f829a14e61bfc71336f44

**Comment by fingolfin** [comment]
I also tweaked two commit messages: One to reference issue #1049, the other for brevity

**Pull request closed without merging**
