### PR TITLE
Use ObjMap for OPERATIONS

### PR DESCRIPTION
**Pull request by fingolfin**
This implements an idea by @ChrisJefferson . It improves startup times of GAP by 10-20% for me. 

In addition, with this, if I tell GAP to not use any of the `src/c_*.c` files, its startup speed is still faster than how it was before this commit.

[ Sorry, couldn't resist working on this, took 15 minutes or so to implement ]
[ Also, if @ChrisJefferson now also has an implementation, feel free to close this one ]

### CODE REVIEW

**Comment by fingolfin** [comment]
`testmanuals` fails because we have not implemented workspace saving/loading for `OBJ_MAP` yet...
`Error, Panic: tried to save an object of unknown type '80'`

This error suggests two things:
1. It should be improved to give the name of the TNUM ;-)
2. We need to implement workspace support for OBJ_SET and OBJ_MAP. To get a head start with this, look at `src/hpc/serialize.c` and in there `DeserializeObjSet` etc.

**Comment by frankluebeck** [comment]
This is a nice idea. I was  not aware of the functions in src/objset.{h,c}. It is unfortunate that their implementation is not complete. 

Nevertheless, we have around 5000 operations and such a number can also be efficiently handled by records. The pull request "Store declaration filters of operations in record"  (#1707) shows an alternative implementation which uses a list of (just) the operations, a record and HANDLE_OBJ, and which also works with storing and restoring workspaces.

**Comment by fingolfin** [comment]
I now implement workspace support for ObjSet and ObjMap, let's see.

**Comment by fingolfin** [comment]
At this point, I really have no idea what causes the workspace failures. The manual tests crash with a segfault -- but they pass on my MacBook Pro, and also on an Ubuntu.

Looking at the Travis output, it seems as if GAP starts, and executes the first line(s) of the generated tests, and then crashes.

Unfortunately, I am unable to reproduce the crash, which makes it hard to debug :/

**Comment by fingolfin** [comment]
This is obsolete now.

**Pull request closed without merging**
