### PR TITLE
Improve Makefile.in, in particular add "make check"

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Done. I also added a rule which ensures that the `Makefile` (or rather: `Makefile-CONFIGNAME`) is regenerated if `Makefile.in` changes.

**Comment by alex-konovalov** [comment]
@fingolfin thanks - now, where to document make check? At least in the INSTALL file? (oh, and BTW, does anyone agree that INSTALL should be converted to markdown?)

**Comment by vbraun** [comment]
I checked out the branch and ran `./configure && make check`. This then builds gap but the tests fail because of missing gap packages. The first error is  
~~~~
[....]
gcc -g  -export-dynamic  -o gap ariths.o blister.o bool.o c_filt1.o c_meths1.o c_oper1.o c_random.o c_type1.o calls.o code.o compiler.o compstat.o costab.o cyclotom.o dt.o dteval.o exprs.o finfield.o funcs.o gap.o gasman.o gmpints.o gvars.o integer.o intfuncs.o intrprtr.o iostream.o listfunc.o listoper.o lists.o macfloat.o objccoll.o objcftl.o objects.o objfgelm.o objpcgel.o objscoll.o opers.o permutat.o plist.o pperm.o precord.o profile.o range.o rational.o read.o records.o saveload.o scanner.o sctable.o set.o stats.o streams.o string.o sysfiles.o system.o tietze.o trans.o vars.o vec8bit.o vecffe.o vecgf2.o vector.o weakptr.o   -lm   /tmp/gap/bin/x86_64-pc-linux-gnu-gcc-default64/extern/gmp/lib/libgmp.a -lreadline -lrt -ldl -lutil 
make[1]: Leaving directory '/tmp/gap/bin/x86_64-pc-linux-gnu-gcc-default64'
chmod +x bin/gap-default64.sh
( echo 'SetUserPreference("UseColorsInTerminal",false); \
        ReadGapRoot( "tst/testutil.g" ); \
            ReadGapRoot( "tst/testinstall.g" );' | ./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  )
#I  GAP: needed package gapdoc cannot be loaded
Error, failed to load needed package `gapdoc' (version >= 1.2) called from
func(  ); at /tmp/gap/lib/system.g:159 called from
<function "CallAndInstallPostRestore">( <arguments> )
 called from read-eval loop at line 890 of /tmp/gap/lib/init.g
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
~~~~
Only after `make bootstrap-pkg-minimal` I can run the tests.

PS: `git clean -f -d -x` deletes everything that isn't checked(!) in, so thats one way to get to a pristine repo to reproduce this issue.

PPS: The bootstrap-pkg-minimal.tar.gz tarball is not in `.gitignore` so git will list is as a change. I'd ignore it to avoid to accidentally check it in.

**Comment by vbraun** [comment]
PPPS:`.travis.yml` could run  `make check` after `make` to sure this works

**Comment by alex-konovalov** [comment]
@vbraun Thanks for testing! 

Hmm, if `make check` is supposed to be used by end users, they would have all packages there and it will make no sense to make them overwriting their GAPDoc with the one provided by `bootstrap-pkg-minimal `. So it's a matter of documenting `make check` usage for developers, rather than making `make check` depending on `bootstrap-pkg-minimal `.

**Comment by vbraun** [comment]
So `check` should download gapdoc only if it doesn't exits

**Comment by markuspf** [comment]
On Tue, Jan 19, 2016 at 10:00:05AM -0800, Volker Braun wrote:
> PPS: The bootstrap-pkg-minimal.tar.gz tarball is not in .gitignore so git will
> list is as a change. I'd ignore it to avoid to accidentally check it in.

Just added it (as well as bootstrap-pkg-full.tar.gz).

Markus

**Comment by fingolfin** [comment]
I don't think `check` (or for that matter, any other target) should automatically download anything. This is for developers, after all, and developers simply need to know that they need to make sure required packages (i.e. currently only GAPDoc) are available somewhere.

Perhaps we can add a check which warns if GAPDoc is not found before trying to start GAP -- but I am not sure how to do that; just looking whether `pkg/GAPDoc` is there is not enough, after all the user could have installed GAPDoc somewhere else and taught the local GAP where to find it.

**Comment by vbraun** [comment]
So you are saying `tst/testutil.g` should use `TestPackageAvailability("gapdoc")` to check and, if not found, print a suitable error message that tells people to run `make bootstrap-pkg-minimal`? Sounds good to me.

**Comment by ChrisJefferson** [comment]
Ignoring the gapdoc issue (which is real, but should be fixed somewhere else), I have reviewed this patch and think it is good.

**Comment by fingolfin** [comment]
@vbraun The problem is that if there is no GAPDoc, I think we won't even get to that point, as GAP will error out earlier :-/. I have now filed issue #520 on this.

**Comment by fingolfin** [comment]
@ChrisJefferson so, anything left to be done for a merge?

**Comment by dimpase** [comment]
@fingolfin : "make check" is something that is used very often in scenarios needing installation from source. Saying that it's developer-only is wishful thinking. A GAP user who for one or another reason built GAP from source would be tempted to run "make check".

It should be possible to check that GAP doesn't have GAPDoc installed by making it exit with an appropriate exit code, and analysing this exit code.

**Pull request merged**
