### PR TITLE
Rewrite ONanScottType

### PR DESCRIPTION
**Pull request by ssiccha**
This fixes one part of "ONanScottType not working for some
primitive groups of degree 3600" #852.

Some parts of the primitive groups library still need to be
fixed.

### CODE REVIEW

**Comment by ssiccha** [comment]
This should replace the fix by @hulpke in PR #1937. It is more along the lines of the original algorithm and should be more efficient than the fix in PR #1937. @hulpke could you check whether this version is correct?

I'm currently testing my code against the primitive groups library.

**Comment by hulpke** [comment]
@ssiccha 
I'm not entirely sure what we  achieve by having two different fixes.

As for runtime, my experience is that `ONanScottType` spends most of its time in the (not very well written -- my fault) `Socle` method. I was planning to look at improving this next. However, with the data that `Socle` already stores in the group I suspect a runtime comparison will come down more on what we consider as ``typical'' example than on code.

I wrote the current(=old) version of ONanScottType about 18 years ago and I was pretty sure then that is was correct. So much for ``pretty sure''. My gut feeling thus was to *not* go for a minimal change of the existing code (whose erraneous proof disappeared in my recycling bucket long ago) and in another 18 years again be stumped first how it works, but to rather go with reference to a textbook proof that still can be found then easily.

Of course the critical part for testing is only at 3600, when we have the first proper power of a simple group order.

**Comment by ssiccha** [comment]
@hulpke I tested it for degree 3600 first of course (but forgot to mention it) and it gives the same result as your new version (for the 33 groups that are small base). Also I tried to give a complete proof of the algorithm in the comments.

I must confess, since you wrote
> I'll think once more whether this can be made more efficient.

I just assumed that getting rid of the `Stabilizer` and `NormalClosure` computations would improve the runtime noticeably.

I timed the following computations with the small base groups of degree 3600, first forgetting all information via `Group(GensOfGroups(..))` and the alternative version is about 2 times faster - see below for the results.

Apparently, even with a known socle, the `ONanScottType` computation still takes a nontrivial amount of time. I think we should be able to reduce the times of both versions further by calling `OrbitsDomain` instead of `Orbits` because we know exactly which set we are acting on. Also, my feeling says figuring out the ONan-Scott Type if the socle is already known should be a lot quicker than computing the socle in the first hand. So I'm actually a bit confused why both versions are taking so long.
```
gap> smallbase := AllPrimitiveGroups( NrMovedPoints, [3600] ){[1..33]};;
gap> forget := g -> Group( GeneratorsOfGroup(g) );;
gap> 
gap> 
gap> # using alexander hulpke's version
gap> _smallbase := List( smallbase, forget );;
gap> List( _smallbase, Size );; time;
3253
gap> List( _smallbase, Socle );; time;
6082
gap> List( _smallbase, hulpke );; time;
6826
gap> 
gap> 
gap> # using alexander hulpke's version, with `NormalClosure` replaced by `Orbit`
gap> _smallbase := List( smallbase, forget );;
gap> List( _smallbase, Size );; time;
3088
gap> List( _smallbase, Socle );; time;
5620
gap> List( _smallbase, hulpke2 );; time;
3941
gap> 
gap> 
gap> # using my version
gap> _smallbase := List( smallbase, forget );;
gap> List( _smallbase, Size );; time;
3124
gap> List( _smallbase, Socle );; time;
5582
gap> List( _smallbase, ONanScottType );; time;
2434
gap> 
```

**Comment by ssiccha** [comment]
About the `Socle` algorithm: Are you planning to implement the version by Cannon & Holt? I've read in the magma manual that they extended their method to groups up to degree 2^30 and wanted to send them an email, asking how they did that.

**Comment by hulpke** [comment]
@ssiccha 
These are comparatively large groups and timings on just such a short calculation can be influenced my seemingly trivial issues (e.g. I found in `Socle' that it actually is not better to use the derived series at all and that `NormalClosure(G,Subgroup(G,[z]))` is significantly slower than `NormalClosure(G,Subgroup(G,[z,z^Random(G)]))`.
(I thus wasn't planning to reimplement Cannon & Holt but just to see if such issues came up.)

If you want to rather make it your fix and implemented related tests please go ahead, I will then remove it from my other PR.

**Comment by ssiccha** [comment]
@hulpke I have thought about your version a bit. If we take the socle point stabilizer from its stabilizer chain we don't need to compute it anew. Also, we can replace `Orbit` by `OrbitDomain` or use some random elements first to rule out the "3a/4a" cases. If we can make it run faster it's probably better to use your version since it has a proper textbook reference.

I've noticed though, that the `CompositionSeries(Socle(G))` calculation is the main bottleneck. Magma has a function `SocleFactors` which is not a kernel function. I'll have a look at it tomorrow. I need to rest my hands a little today. :(

```
gap> _smallbase := List( smallbase, forget );;
gap> List( _smallbase, Size );; time;
3118
gap> List( _smallbase, Socle );; time;
5374
gap> List( last2, CompositionSeries );; time;
1903
gap> List( _smallbase, ONanScottType );; time;
375
```

The magma version:
```
> forget := function(x) return PermutationGroup< Degree(x) | Generators(x) >; end function;
> G := forget( PrimitiveGroup(3600,1) );
> time Order(G);
648000
Time: 0.020
> time Socle(G);
Permutation group acting on a set of cardinality 3600
Order = 216000 = 2^6 * 3^3 * 5^3
Time: 0.000
> time SocleFactors(G);
[
    Permutation group acting on a set of cardinality 3600
    Order = 60 = 2^2 * 3 * 5,
    Permutation group acting on a set of cardinality 3600
    Order = 60 = 2^2 * 3 * 5,
    Permutation group acting on a set of cardinality 3600
    Order = 60 = 2^2 * 3 * 5
]
Time: 0.000
```

**Comment by hulpke** [comment]
@ssiccha 

I presume (with the 4.9 release hanging) that we should concentrate first on fixing the bug, even if we know that we could do better. I'm happy with either version, but we should make a decision which one.

Then lets look at the performance as a contribution for 4.10 (or 4.9 if it gets improved quickly and 4.9 is late). Probably this should be a new issue. Does this sounds sensible?

There are really three aspects here that could be causal for performance loss:

a) The wrong kind of routine is called, as equivalent information can be obtained cheaper from another source. (Of course it begs the question, why the routines are not more clever.)

b) Existing information is not used, maybe because another routine does not know that the information is available. (The composition series code does this well within itself, but does not document well what information it holds where, so routines building up on it do not necessarily do so.) I have seen this many times and it can give dramatic speedups with minimal information. 

c) There are genuinely new algorithmic developments. -- This is the most time expensive.

As for `SocleFactors` there is a routine `DirectFactorsFittingFreeSocle` that should do the same, but currently only has a generic implementation that dos not do the relevant case quickly. This looks to me like the most promising venue.

**Comment by ssiccha** [comment]
@hulpke 
> I presume (with the 4.9 release hanging) that we should concentrate first on fixing the bug, even if we know that we could do better. I'm happy with either version, but we should make a decision which one.
> 
> Then lets look at the performance as a contribution for 4.10 (or 4.9 if it gets improved quickly and 4.9 is late). Probably this should be a new issue. Does this sounds sensible?

I agree. Then let's open new issues like "Improve `Socle` algorithm" and "Compute SocleFactors efficiently". We could e.g. let `Socle` automatically also store its composition into direct factors, if that's doable cheaply. IMO these are the only bottlenecks here.

I prefer your fix with the textbook citation. With some minor changes I think it also runs efficiently once the `Socle` and `SocleFactors` issue is resolved. I'ld suggest the following:
- Replace [line 2147](https://github.com/hulpke/gap/blob/9d837a4198058b5833be2a8095c8ebcd6d48b954/lib/grpperm.gi#L2147) by `if not IsTransitive(m,dom) then`.
The proof that we can do this is [here](https://github.com/ssiccha/gap/blob/fec845d1261610d976b2e4f9bd1e4321d2138fa7/lib/grpperm.gi#L2079) so we could just add that to the comments.
- Replace [line 2157](https://github.com/hulpke/gap/blob/9d837a4198058b5833be2a8095c8ebcd6d48b954/lib/grpperm.gi#L2157) and line 2164 by
`if Size(Orbit(G,t))<d then` where `d := Length(cs)-1;`.

On the small base groups of degree 3600, this brings down the time needed for calculations in addition to the `Socle` and `SocleFactors` to roughly 150ms.

What do you think?

**Comment by ssiccha** [comment]
> As for SocleFactors there is a routine DirectFactorsFittingFreeSocle that should do the same, but currently only has a generic implementation that does not do the relevant case quickly. This looks to me like the most promising venue.

Then we can e.g. make `SocleFactors` a documented attribute since `DirectFactorsFittingFreeSocle` is currently undocumented.

**Comment by hulpke** [comment]
> Then we can e.g. make SocleFactors a documented attribute since DirectFactorsFittingFreeSocle is currently undocumented.

With the caveat that currently the code does not assume there are solvable socle components (and it might be worth to tell such a fact to the function call to avoid calculating those in vain.)

**Comment by hulpke** [comment]
@ssiccha I think that is fine. I have done the changes you proposed. Will rebase before merging.

**Comment by ssiccha** [comment]
Closed in favor of #1937.

**Pull request closed without merging**
