### PR TITLE
Added to ValidatePackageInfo the check for new optional components

### PR DESCRIPTION
**Pull request by alex-konovalov**
It now checks optional components for the repository, issue tracker and support email address, which, if bound, will be displayed on the package overview page on the GAP website. For an example, see the commit https://github.com/gap-system/example/commit/db37d1e63982856f8e2970f6ea92f65dd68e8d0d in the Example package. This will close issue #7.

### CODE REVIEW

**Comment by fingolfin** [comment]
I am all for adding this information to the PackageInfo.g But I am not sure whether limiting the "type" is a good idea. Already know there are other VCS in use (e.g. fossil), and it's likely there'll be more in the future. 
Could we perhaps change the type check to a warning? I.e. if the type is not one of the listed ones, print a warning?

**Comment by alex-konovalov** [comment]
Thanks, Max. I've added the warning "If you are using another VCS, please contact GAP developers to extend this list." in case someone will use another system - anyhow, we cant permit arbitrary text in this component, or even a mix of upper and lowercase. 

FYI, the previous discussion on this was at https://bitbucket.org/gap-system/gap/issues/17/new-components-in-the-packageinfog-file

**Comment by frankluebeck** [comment]
I cannot see any reason to restrict the 'Type' component of a repository. This is just informal information. If at some stage this information will be used somehow you need to distinguish the cases anyway. 

The given cases should just be examples. Also "subversion" and "mercurial" would be sensible entries.

**Comment by alex-konovalov** [comment]
@frankluebeck At the moment, we will just add a link to the package overview page, so it would be acceptable to have an arbitrary string there. But if in the future we may want to use those repository URLs in an automated setup, then some standardisation would be useful.

**Comment by alex-konovalov** [comment]
I would like to publish an update of the Example package which uses these components - may we please decide about `SourceRepository.Type` then to make me able to proceed?

**Comment by markuspf** [comment]
I'd leave it as an unrestricted field, and standardise entries for automated setup (and it's the package author's fault if they break it).

**Comment by alex-konovalov** [comment]
I had to push this directly (https://github.com/gap-system/gap/commit/9b83f219f2d0619c552830b3ecdfbf9df34fc145) since it was in the master branch of my fork. I will relax the restrictions later.

**Comment by alex-konovalov** [comment]
I've relaxed the rules for the repository type component in https://github.com/gap-system/gap/commit/433c24bc9f0a8f434293281962383630a97fbd17

**Pull request closed without merging**
