### PR TITLE
Automatically find GMP, zlib, GNU readline when installed by Homebrew, MacPorts or Fink

### LINKED ISSUE #1945: Automatically search for GMP and GNU Readline in a few additional places, if we cannot find them elsewhere
When searching for GMP and GNU Readline, if we fail to detect them w/o specific compiler flags, then we could iterate over a list of standard locations where they might be found instead. Specifically, for OS X, that could be the `include` and `lib` subdirectories of...

 * `/sw`, for a typical Fink installation;
 * `/opt/local`, for a typical MacPorts install;
 * `$(brew --prefix)` for Homebrew (and for GNU Readline, also `$(brew --prefix)/opt/readline` as it is installed keg-only by default)

I am not sure if any other operating system resp. distros would benefit from it, but I'd think it'd be worth the effort regardless of that.

### PR DESCRIPTION
**Pull request by fingolfin**
This way mac users with Homebrew, Fink or MacPorts will automatically benefit from GMP/zlib/GNU readline installed via these package managers.

Resolves #1945.

### CODE REVIEW

**Comment by fingolfin** [comment]
I've tested this on macOS with Homebrew and on Linux. @dimpase you provided the original OpenBSD compatibility patch for the readline check. If you have a way to test the new code on OpenBSD (i.e. whether it still detected `libreadline` (or rather `libereadline` there), that'd be great.

**Comment by dimpase** [comment]
@fingolfin - I will test on OpenBSD and report here.

**Comment by fingolfin** [comment]
@dimpase thank you!

@ChrisJefferson it keeps failing the `testexpect testmockpkg testspecial test-compile testlibgap testkernel - - ubuntu-latest` test, due to a timeout?!? This is totally baffling to me. Any idea what might cause this?

**Comment by dimpase** [comment]
> @fingolfin - I will test on OpenBSD and report here.

OK, it works just fine. I didn't try installing packages needing building GAP kernel extensions, should I?

**Comment by fingolfin** [comment]
@dimpase I don't see a reason why kernel extensions should be affected by this. But of course it never hurts to check, except for the effort it requires... so if it is "easy" for you, please do; but if it is inconvenient, don't worry about it (GAP doesn't seem to be in the OpenBSD ports system either, so I guess there are not many GAP users there to start with)

**Comment by dimpase** [comment]
@fingolfin I just tried `semigroups` package, and got 
```
...
make[2]: Entering directory '/home/dima/tmp/gap/pkg/semigroups'
  CXX      src/semigroups_la-bipart.lo
  CXX      src/semigroups_la-cong.lo
LLVM ERROR: out of memory
Allocation failed
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: c++ -DHAVE_CONFIG_H -I/home/dima/tmp/gap/build -I/home/dima/tmp/gap/src -I/home/dima/tmp/gap -DUSE_GASMAN=1 -I/usr/local/include -I./bin/include -I./bin/include/libsemigroups -I./gapbind14/include -DHPCOMBI_CONSTEXPR_FUN_ARGS -I./libsemigroups/extern -I./libsemigroups/extern/HPCombi/include -I./libsemigroups/extern/HPCombi/include/fallback -I./libsemigroups/extern/fmt-8.0.1/include -I./libsemigroups/include -DFMT_HEADER_ONLY -DNDEBUG -I/usr/local/include -I/usr/local/include -I./bin/include -I./bin/include/libsemigroups -std=gnu++14 -O3 -flax-vector-conversions -g -O2 -MT src/semigroups_la-cong.lo -MD -MP -MF src/.deps/semigroups_la-cong.Tpo -c src/cong.cpp -fPIC -DPIC -o src/.libs/semigroups_la-cong.o
1.      <eof> parser at end of file
2.      Code generation
c++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.1
Thread model: posix
InstalledDir: /usr/bin
c++: note: diagnostic msg:
********************
...
```

**Comment by dimpase** [comment]
cf. https://github.com/llvm/llvm-project/issues/59194

**Comment by fingolfin** [comment]
@dimpase thank you for testing! I am not concerned about that semigroups failure; as you pointed out, it's a compiler bug; but even if not, it'd be a problem specific to that package, and to be dealt with by the package authors/maintainers, not us

**Comment by dimpase** [comment]
> as you pointed out, it's a compiler bug; but even if not, it'd be a problem specific to that package

it was merely lack of my knowledge of OpenBSD `datalimit` feature - this compilation needs many gigs of RAM to finish successfully, and it was limited too much.

**Comment by dimpase** [comment]
OK, at least some packages with kernel extenstions work on OpenBSD, e.g. `io` works. `Semigroups` and `digraphs` build, but don't work, as `.so` file of `digraphs` is corrupt. I'll open an issue there.

**Review by dimpase — APPROVED** [review]
LGTM

**Comment by dimpase** [comment]
> @ChrisJefferson it keeps failing the `testexpect testmockpkg testspecial test-compile testlibgap testkernel - - ubuntu-latest` test, due to a timeout?!? This is totally baffling to me. Any idea what might cause this?

is this the same problem as in  https://github.com/gap-system/gap/pull/5196#issuecomment-1305740328 ?

**Comment by fingolfin** [comment]
@dimpase aha, interesting observation! I have no idea, but they sure look similar, and in both cases `configure.ac` was modified... I still don't understand how that can lead to a timeout in that test, but it might give a clue...?

**Comment by dimpase** [comment]
> @dimpase aha, interesting observation! I have no idea, but they sure look similar, and in both cases `configure.ac` was modified... I still don't understand how that can lead to a timeout in that test, but it might give a clue...?

We use a lot of `expect` and `pexpect` in Sage, and it's in general dodgy. Various OS distros tend to break them once in a while. :-(

**Comment by dimpase** [comment]
> GAP doesn't seem to be in the OpenBSD ports system either

Creating an OpenBSD port is a nontrivial effort, especially if it involves things like extra packages, extra dynamic libraries, etc. Once @kaashif made a draft port of GAP, but didn't complete it. (The `ereadline` PR I did was meant to help it).

**Comment by james-d-mitchell** [comment]
> @dimpase thank you for testing! I am not concerned about that semigroups failure; as you pointed out, it's a compiler bug; but even if not, it'd be a problem specific to that package, and to be dealt with by the package authors/maintainers, not us

I don't really agree with this I'm afraid @fingolfin, if this PR breaks the Semigroups package, or any other package, then shouldn't that be investigated and resolved **before** this PR is merged? Just thinking about recent similar issues with `MatrixObj` that caused a huge amount of work...

**Comment by dimpase** [comment]
> > @dimpase thank you for testing! I am not concerned about that semigroups failure; as you pointed out, it's a compiler bug; but even if not, it'd be a problem specific to that package, and to be dealt with by the package authors/maintainers, not us
> 
> I don't really agree with this I'm afraid @fingolfin, if this PR breaks the Semigroups package, or any other package, then shouldn't that be investigated and resolved **before** this PR is merged? Just thinking about recent similar issues with `MatrixObj` that caused a huge amount of work...

For the record, this PR does not break Semigroups (same error on OpenBSD with GAP 4.12.1 and Semigroups there)

**Comment by james-d-mitchell** [comment]
Thanks @dimpase, my earlier comment is now obsolete!

**Comment by fingolfin** [comment]
@james-d-mitchell yeah I think we actually agree in the end then: my comment was based on the assumption that this PR is *not* the cause for the semigroups failure on OpenBSD. Of course if this PR *did* cause it, I would want to resolve it.

**Comment by fingolfin** [comment]
Found the problem: I had forgotten to copy the code defining `HAVE_LIBREADLINE`. As a result, GAP was not using GNU readline, which broke the expect test.

**Comment by dimpase** [comment]
Would it work in a Conda environment ? There locations of /usr, etc, are not fixed in advance.

We have in Sage a bunch of autoconf macros (for the libraries you deal with here, too) which allow such a scenario.

**Comment by fingolfin** [comment]
I have no idea, I've never used Conda beyond a few short experiments several years ago

**Comment by dimpase** [comment]
One does not have to go through a list of prefixes, such as `/sw, /opt/foo`, etc, as all the sane toolchains know where to look for headers and libraries.
This is how one can support more or less arbitrary locations.

**Comment by fingolfin** [comment]
@dimpase I don't really understand what you are trying to say with your last comment?

In the meantime this PR addresses a real world paper cut issue that I have seen multiple people struggling with, often without them even knowing this (eg waiting longer for GMP to compile, not benefiting from GNU readline)

**Comment by dimpase** [comment]
I was misled by the PR description, and thought (without looking at the code) that you loop over a fixed list of prefixes in search for libraries. But you actually don't do this, right?

**Comment by fingolfin** [comment]
We do this, among other things there is no alternative that works w/o expert user knowledge. 

What it does now is this: if the user specified an explicit prefix for, say, GMP, use that. Otherwise, try to see if it "just works" (e.g. because it is in /usr, or because someone/something set CPPFLAGS etc. appropriately). Otherwise, fall back to checking if Homebrew, MacPorts or Fink provide it.

**Pull request merged**
