### PR TITLE
Check for profiling too many files / files with too many lines

### PR DESCRIPTION
**Pull request by ChrisJefferson**
The current profiling stuff can break with files > 65,535 lines, or if GAP reads more than 65,535 files in the same session, even if profiling is not used (it doesn't break GAP, just gives bad profiles).

This patch catches this case, and produces an error in this situation. The patch ended up being bigger than I would like.

The test is designed so if you are running tests with coverage, they won't break that test coverage gathering (but the test will still fail).

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@ChrisJefferson: this adds some new test files e.g. `tst/example-dir/long-files/line-65537.g.gz`, and then tries to read them with `Read(Concatenation(base, "line-65537.g"));;`  but IIRC this feature does not work on Windows. If we want to test this only in the UNIX environment, then the test may call `ARCH_IS_WINDOWS()` to run the check only if this returns `false`.

**Comment by ChrisJefferson** [comment]
New test, which uses `DirectoryTemporary` to make directories on the fly, so no gzipping or large files.

**Comment by markuspf** [comment]
@alex-konovalov is this good to go then?

**Comment by alex-konovalov** [comment]
@markuspf think so. As a side effect, also this will add an extra check of the `DirectoryTemporary`.

**Comment by alex-konovalov** [comment]
@ChrisJefferson Since this PR now merged, could you please add to [this Wiki page](https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.7-and-GAP-4.8) the text to include in the changes manual and the next minor release announcement?

**Comment by alex-konovalov** [comment]
@ChrisJefferson something wrong happening on Cygwin64:
```
testing: /proc/cygdrive/C/Users/jenkins/workspace/GAP-stable-windows-test64/GA\
P-git-stable-snapshot/tst/teststandard/prof.tst
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-stable-windows-\
test64/GAP-git-stable-snapshot/tst/teststandard/prof.tst, line 29:
# Input is:
IsLineByLineProfileActive();
# Expected output:
true
# But found:
false
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-stable-windows-\
test64/GAP-git-stable-snapshot/tst/teststandard/prof.tst, line 36:
# Input is:
IsLineByLineProfileActive();
# Expected output:
true
# But found:
false
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-stable-windows-\
test64/GAP-git-stable-snapshot/tst/teststandard/prof.tst, line 41:
# Input is:
Read(Filename(tempdir, "line-65536.g"));;
# Expected output:
#I Profiling only works on the first 65,535 lines of each file
#I (this warning will only appear once).
# But found:
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-stable-windows-\
test64/GAP-git-stable-snapshot/tst/teststandard/prof.tst, line 53:
# Input is:
for i in [1..lim] do
f := fail;
Read(Filename(tempdir, "line-65536.g"));
if f(0) <> 65536 then Print("bad"); fi;
od;
# Expected output:
#I Profiling only works for the first 65,535 read files
#I (this warning will only appear once).
# But found:
########
```
I am waiting to see what's going on in 32-bit Windows.

**Comment by ChrisJefferson** [comment]
I suspect this is being caused by the 'gz' on the end of the filenames in that file (although it works fine on my computer, where I have gzip installed in cygwin).

Chris

**Comment by alex-konovalov** [comment]
@ChrisJefferson Can we get rid of gz then? We need to be able to run this on a Cygwin-free machine.

**Comment by ChrisJefferson** [comment]
We can for now. Longer term I'd like to (a) test this code, and (b) distribute gzip with gap, so it works.

**Pull request merged**
