### PR TITLE
TestDirectory reports number of failures and failed files

### LINKED ISSUE #2861: Add summary for `TestDirectory`?
It would be nice if `TestDirectory` could (optionally?) show how many .tst files it tested, and how many of these had failures resp. passed.

(Bonus points for doing the same for `Test`, but listing how many `gap>` lines were read in total, vs. how many produced diffs; and then extra bonus points if `TestDirectory` was able to display an aggregate of this:  `Executed N tests files with M input lines in total;  X test files produced a total of Y errors` or so.)

### PR DESCRIPTION
**Pull request by fingolfin**
With this, you may get output like this, with the
relevant change in the "total" line near the end.

    gap> TestDirectory("misc");
    Architecture: x86_64-apple-darwin15.6.0-default64-kv5

    testing: misc/err.tst
           0 ms (0 ms GC) and 46.6KB allocated for err.tst
    testing: misc/foo.tst
    ########> Diff in misc/foo.tst:3
    # Input is:
    1+1;
    # Expected output:
    3
    # But found:
    2
    ########
           0 ms (0 ms GC) and 6.62KB allocated for foo.tst
    -----------------------------------
    total         1 ms (0 ms GC) and 53.8KB allocated
                  1 failures in 1 of 2 files

    #I  Errors detected while testing

    false
    gap>

Resolves #2861

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This will be useful @fingolfin - let's see how this will be seen in Travis.

**Comment by alex-konovalov** [comment]
@fingolfin The problem with building manuals is not present in the master branch. Please rebase.

**Comment by fingolfin** [comment]
What problem are you talking about? Travis and AppVeyor passed now. Also, what do you mean with "please rebase" -- this is already based on 94e61abe81904630afec720d3cddc7f6a8d614dd, the current master branch.

**Comment by fingolfin** [comment]
(There simply was a stupid XML error in the GAPDoc, which is fixed now)

**Comment by alex-konovalov** [comment]
I've been looking at the earlier test of this PR on Travis - that happened at https://travis-ci.org/gap-system/gap/builds/437551821. Indeed, fine now. Seen XML error in two separate PRs but not in the master branch, hence suggested to rebase...

**Comment by fingolfin** [comment]
Ah I see: was confused because I saw your earlier comment pointing out broken XML; but after fixing that, the comment was gone?! Anyway, tests pass now.

**Comment by fingolfin** [comment]
@alex-konovalov Done. One could next argue that `1 failures` should be `1 failure`, but I really don't want to spend more time on such minor details right now. If somebody is annoyed by that, I'll be happy to review their PR, though :-).

**Comment by alex-konovalov** [comment]
@fingolfin should this be backported to stable-4.10?

**Comment by fingolfin** [comment]
I don't see why.

**Comment by alex-konovalov** [comment]
Because it's useful and should not break things... Or, actually, because I don't want to maintain two different versions of scripts for jenkins which look up for the line with the word `total` at the end of the file with `tail -5 | head -1` and  `tail -4 | head -1`respectively :)

**Comment by fingolfin** [comment]
I don't find the first argument compelling, but the final one kinda is ;-)

**Pull request merged**
