### PR TITLE
Allow Random(<random-source>, <symmetric group>) 

### PR DESCRIPTION
**Pull request by markuspf**
This provides a nice way of making Random permutations for testing.

This is a resubmit/rebase of #573. Since I don't know whether I can rebase the original PR, but I want the tests to run.

### CODE REVIEW

**Comment by markuspf** [comment]
@james-d-mitchell The failure on the test for parital permutations is what was referred to in #573.

**Comment by ChrisJefferson** [comment]
I would prefer to wait until #810 is merged to merge this, because then you can use the test function I wrote in that to really test the code (although I suspect it is right) -- I imagine at the moment there isn't any tests for this?

**Comment by markuspf** [comment]
I'll close this since @stevelinton has rebased his PR anyway.

**Comment by stevelinton** [comment]
Sorry for the duplication. Still getting caught up

**Pull request closed without merging**
