### PR TITLE
Stop using GNU libtool for linking GAP and libgap

### LINKED ISSUE #4682: buildsys: should we drop libtool and simply use our own list of build rules?
The main reason to use libtool for us is that it provides a uniform way to generate shared libraries and loadable modules (for kernel extensions). That used to be quite complicated because every vendor had their own way of doing it, and they differed, sometimes by a lot.

But these days, things are much simpler: essentially, you have to cover Linux, macOS, Windows, *BSD.

And using libtool has its costs, too:
- create `.la` and `.lo` files and `.libs` dirs
- involves a huge complicated shell script, intransparent
- relatively slow (doesn't matter *much* for us)
- complicates installation of GAP, as `gac` currently calls into `libtool`, so we'd have to install a copy of it (and some distros frown upon that, or at least it used to be that way)

I've been using this as a replacement in GAP.jl for some time for building loadable modules: 
```julia
        if Sys.islinux() || Sys.isfreebsd()
            c_compiler = "$(CC) -fPIC -DPIC"
            cxx_compiler = "$(CXX) -fPIC -DPIC"
            c_dyn_linker = "$(CC) -shared -fPIC -DPIC"
        elseif Sys.isapple()
            c_compiler = "$(CC) -fno-common -DPIC"
            cxx_compiler = "$(CXX) -fno-common -DPIC"
            c_dyn_linker = "$(CC) -bundle"
        else
            error("OS not supported")
        end
```
Note that it lacks code for Windows, but I am sure we could overcome that. It also doesn't cover building the `libgap.so` shared library, but this requires rather similar code.

The main *downside* to dropping libtool is that we may loose support for some operating systems which someone (who??) out there might still care about. But I don't expect many (if any) of these, and adding back support for such a system generally is not much harder than the above.

Note that this would essentially return us to how we did things before the new build system was introduced in GAP 4.9, so it wouldn't be really something new either. Specifically, we had this (I've removed a bunch of useless parts dealing with NeXTStep, Irix etc.):
```sh
AC_DEFUN(GP_PROG_CC_DYNFLAGS,
[AC_CACHE_CHECK(dynamic module compile options, gp_cv_prog_cc_cdynoptions,
 [ case "$host-$CC" in
    *cygwin* )
        gp_cv_prog_cc_cdynoptions="${ABI_CFLAGS}";;
    *-apple-darwin*gcc* )
        gp_cv_prog_cc_cdynoptions="-fPIC -Wall ${ABI_CFLAGS}";;
    *-gcc* | *-egcs )
        gp_cv_prog_cc_cdynoptions="-fPIC -Wall -O2 ${ABI_CFLAGS}";;
...
    * )    dnl ## if we don't recognise this compiler, guess some flags
        gp_cv_prog_cc_cdynoptions="-fPIC -O2 ${ABI_CFLAGS}";;
   esac 
 ])
...
 AC_CACHE_CHECK(dynamic module link flags, gp_cv_prog_cc_cdynlinking,
 [ case "$host-$CC" in
    *-apple-darwin*gcc* )
        gp_cv_prog_cc_cdynlinking='-g -bundle -bundle_loader ${gap_bin}/gap -lc -lm'" ${ABI_CFLAGS}";;
    *-apple-darwin*clang )
        gp_cv_prog_cc_cdynlinking='-bundle -g -bundle_loader ${gap_bin}/gap'" ${ABI_CFLAGS}";;
    *cygwin* )
        gp_cv_prog_cc_cdynlinking='-shared ${gap_bin}/gap.dll';;
    *-gcc )
        gp_cv_prog_cc_cdynlinking="-shared -g ${ABI_CFLAGS}";;
    *-clang )
        gp_cv_prog_cc_cdynlinking="-shared -g ${ABI_CFLAGS}";;
...
   esac 
 ])
```

### LINKED ISSUE #5383: Libtool errors with recent libtool
When building with libtool 2.4.7 we saw the following error at configure time:

```
config.status: executing libtool commands
+ make
    * new C compiler flags
    * new preprocessor flags
   C       src/ariths.c => obj/src/ariths.lo
libtool: Version mismatch error.  This is libtool 2.4.7, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
libtool: and run autoconf again.
```

For the conda-forge distribution, we fixed this with [this patch](https://github.com/conda-forge/gap-feedstock/pull/66/files#diff-c2aea2d513c0db971da5166d41ba7b6e1219265f0c54a4bcf7d8efa05fa6f058), i.e., `rm aclocal.m4` and use `AC_CONFIG_MAROS_DIR` to tell autoconf where it's macros can be found instead.

What is the reason for GAP's non-standard setup here?

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #4682
Resolves #5383

TODOs include at least:
- [x] Windows support
- [x] `make install` tweaks
- [ ] testing on some *BSD variants
- ...

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
The title of this PR is missing a "t", `libool` -> `libtool`.

**Comment by dimpase** [comment]
just a note that there are packages which don't build on OpenBSD due to a libtool problem.

**Comment by fingolfin** [comment]
This seems to be working now. What's not yet tested is anything other than Linux, macOS, Windows...

**Comment by dimpase** [comment]
I'll test on OpenBSD and report.

**Review by dimpase — APPROVED** [review]
All is good on OpenBSD 7.3. GAP builds, semigroups package builds, most tests in `TestPackage("semigroups");`  pass.

**Comment by fingolfin** [comment]
Thanks @dimpase !

**Review by ChrisJefferson — APPROVED** [review]

**Comment by fingolfin** [comment]
I think this should be mentioned in the release notes as it is quite relevant for downstream packagers

**Comment by fingolfin** [comment]
(well ideally it is transparent for them, but I think it's good to make sure they are aware as it could cut down debugging time if anything breaks, and they might be able to get rid of some libtool specific adjustments etc.)

**Comment by fingolfin** [comment]
Started a run of the package distro test suite at https://github.com/gap-system/PackageDistro/actions/runs/7589464817

**Comment by fingolfin** [comment]
That package distro CI run failed due to the scripts there not being ready to deal with branches containing a slash... So I made https://github.com/gap-system/PackageDistro/pull/877 and based on that started this test run which shows that all packages still pass with this PR here, yay!

https://github.com/gap-system/PackageDistro/actions/runs/7604428542/job/20707309882

**Pull request merged**
