### PR TITLE
Neaten output filenames from TestDirectory

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This neatens the output of testdirectory (give the filename for each file at the start of the line)

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@ChrisJefferson thanks. There is now a duplicated line with `total`:
```
testing: /home/travis/build/gap-system/gap/tst/testinstall/algmat.tst
algmat.tst             10113           1144
-------------------------------------------
total                  10296           7816
total                  10296           7816
```
Furthermore, `testbugfix.g` produces an error message which does not fail the travis test (why?):
```
Error, Record Element: <rec> must be a record (not a list (string,imm)) in
  lines := SplitString( StringFile( file.name ), "\n" )
 called from 
 ; on line 566 of file /home/travis/build/gap-system/gap/lib/test.gifunc( C[i] 
 ) on line 745 of file /home/travis/build/gap-system/gap/lib/coll.gi called fr\
om
List( files, getStones 
 ) on line 664 of file /home/travis/build/gap-system/gap/lib/test.gi called fr\
om
<function "TestDirectory">( <arguments> )
 called from read-eval loop at line 45 of tst/testbugfix.g
you can replace <rec> via 'return <rec>;'
brk> 
gap> 
```

**Comment by ChrisJefferson** [comment]
Thanks, let's go through the issues :)

1) bugfix broken - fixed.

2) bugfix not failing travis -- I think we are going to have to go back to diffing the output of GAP. I don't like it, but unfortunately it seems I can't quite reliably, in all cases, get the return value of GAP set to a non-zero value on failure (although cases where this fails are bugs. I'm not sure what's happening here).

Double 'total' line -- is weird, investigating.

**Comment by ChrisJefferson** [comment]
The 'double total line' has been happening for ages it seems, and only on travis. Do you see it on your desktop, or jenkins? If not, I'm tempted to just blame travis and ignore it (I can't understand how the code could ever print the line out twice).

**Comment by markuspf** [comment]
As a naughty hack you might try and write a return value (or return json...) to a file somewhere to indicate failure. 
I don't like parsing and diffing GAP output like this, it's just so fragile  (#314 I am looking at you).

**Comment by ChrisJefferson** [comment]
Actually, I have a different, slightly horrible option. I could add a command-line option which sets gap's return value (which can then be changed by GAP code of course). This would mean if the library fails to load correctly, we still get a non-zero GAP return value.

**Comment by alex-konovalov** [comment]
@ChrisJefferson Never seen the double line elsewhere. Ok, so shall we merge it now to restore the opportunity to take timings, and address the rest on #314?

**Comment by ChrisJefferson** [comment]
Yep, sounds good.

**Pull request merged**
