### PR TITLE
Rename `string.h` to `stringobj.h`

### PR DESCRIPTION
**Pull request by markuspf**
This is to avoid clashes with a system include called `string.h` that compilers get confused about. See also #515 and #516.

This patch should not break packages, since it introduces `string.h` for backwards compatibility that just includes both `stringobj.h` and the system's `string.h`.

Thanks to @ChrisJefferson for the idea.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
While a bit of a hack, I think this patch is good to go.

**Comment by markuspf** [comment]
For consistency we should probably rename `string.c` to `stringobj.c` as well.

**Comment by markuspf** [comment]
I will merge this, since it does not change functionality. If anyone is strong opposed to this, we can still revert.

**Comment by fingolfin** [comment]
Thanks. The change by itself is indeed somewhat of a hack, but it doesn't really hurt us, but does simplify our life for now.

**Pull request merged**
