### PR TITLE
Don't strip binaries when installing them

### PR DESCRIPTION
**Pull request by fingolfin**
The stripping causes issues in various situations. Some distros
also disable it for that reason. It is also easy to strip the
libraries manually later on if so desired.

### CODE REVIEW

**Review by ChrisJefferson — APPROVED** [review]

**Comment by fingolfin** [comment]
This fails right now because our tests for `make install` verify that the build path do not show up in any installed files, which is broken if we don't strip (due to debug data referencing it).

I could adjust the test, but I am really torn on what the "right" thing here is. Perhaps downstream packagers have feedback on this? I.e., what do you prefer `make install` should do:
1. strip installed `gap` and `libgap`
2. don't strip it
3. don't care
4. something else

CC @jamesjer @isuruf @dimpase @collares @antonio-rojas @yurivict

**Comment by antonio-rojas** [comment]
Please don't strip on make install, as it breaks debug package generation. Distros usually have their own tooling to strip binaries at packaging time (after debug symbols have been extracted).

**Comment by yurivict** [comment]
No.

Both GNU tools and cmake are able to install either stripped or unstripped binaries based on the value of the ```STRIP``` environment variable.

**Comment by fingolfin** [comment]
Backported to `stable-4.12` in bbfbd2e4bd07f099f2d1966d36a45b4cb00fcc32 and 69c13035e9920728c0815c4599f85511beeb51cd

**Pull request merged**
