### PR TITLE
Add permgroup iterator

### PR DESCRIPTION
**Pull request by markuspf**
This is missing a reference in the documentation. Comments of course welcome as always.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This looks really good to me.

Chris

**Comment by markuspf** [comment]
As per Thomas Breuer's  suggestion, I will add a quick explanation as to how the algorithm works to the documentation before I will merge this.

**Comment by markuspf** [comment]
I merged this in 882a74f in a squashed form to clutter the history a little less.

**Comment by alex-konovalov** [comment]
@markuspf: so far there is only one diff reported:
```
########> Diff in [ "./language.xml", 1611, 1620 ]
# Input is:
x;
# Expected output:
(1,4,3)(2,6,5)
# But found:
(1,5,2)(3,4,6)
########
```
The example is here:
```
gap> g := Group((1,2,3,4,5),(1,2)(3,4)(5,6));
Group([ (1,2,3,4,5), (1,2)(3,4)(5,6) ])
gap> for x in g do
> if Order(x) = 3 then
> break;
> fi; od;
gap> x;
(1,4,3)(2,6,5)
```
so this is just a result of elements of the group enumerated in a different order. Perhaps the test needs to be rewritten to use another example. This also shows that this change may have an impact on packages' tests.

**Comment by markuspf** [comment]
Dear Alex,

Even though I think that I got the order wrong in the code (and corrected it
right now, plus made an adjustment to use LeftQuotient instead of x^(-1) * y,
because that is more efficient for permutations), of course we cannot rely on
orders being equal if different stabiliser chains are used.

If we want Iterators and Enumerators to work the same, I'll have to look at
how Iterators and Enumerators are implemented and sync up how they work.

Markus

**Comment by markuspf** [comment]
Ah I see what I am doing differently, I increment the base images from "right to left", whereas the enumerator code does it from "left to right". I believe the Enumerator code is correct, so I'll have to adapt my iterator, but I will do that in a separate pull request.

**Pull request closed without merging**
