### PR TITLE
Replace hpc-gap finalizer interface by existing functions

### PR DESCRIPTION
**Pull request by fingolfin**
This is a new go at the change made in PR #57

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This looks good to me.

**Comment by markuspf** [comment]
Could you rebase this?

**Comment by markuspf** [comment]
Sorry, I noticed that this is subsumed by #1471 which I believe is the better approach (and whcih I just approved)

**Comment by fingolfin** [comment]
Closing, as #1471 was merged. Thanks :-)

**Pull request closed without merging**
