### PR TITLE
Add methods for Intersection2 with empty list as parameter

### PR DESCRIPTION
**Pull request by markuspf**
This is a fix for #773.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@markuspf This looks ok, but I wouldn't a more general method for `IsListOrCollection, IsListOrCollection` with the wrong family relation be better?

**Comment by markuspf** [comment]
The empty list is *not* a collection, which is why the whole mess occurs. As @stevelinton puts it: The empty list doesn't know which type of object it doesn't contain any of. 

Hence I special case on IsEmpty (and IsListOrCollection is more general). I can add `IsNotIdenticalObj`, but I don't know whether that gains anything 

(fun fact: `IsNotIdenticalObj([],[])` returns `true` ;)).

**Comment by james-d-mitchell** [comment]
While it is true that the empty list is not a collection, it is a list, and so it belongs to `IsListOrCollection`. The `IsNotIdenticalObj` applies to the family of the objects not the objects themselves, and

    gap> IsIdenticalObj(FamilyObj([]), FamilyObj([]));
    true

So, making the change I suggested really is more general than what you proposed.

**Comment by markuspf** [comment]
The code you proposed uses `IsCollection`, not `IsListOrCollection`.

**Comment by james-d-mitchell** [comment]
Oh right, I meant:

    InstallMethod( Intersection2,
        "for two lists or collections with the wrong family relation",
        IsNotIdenticalObj,
        [ IsListOrCollection, IsListOrCollection ], 
        function(coll, list),
          return [];
        end);

or something like this.

**Comment by markuspf** [comment]
I think this will lead to unintended behaviour:

```
gap> S := FullTransformationMonoid(3);
<full transformation monoid of degree 3>
gap> Intersection(S, [1,2,IdentityTransformation]);
[  ]
```

(Incidentally this doesn't work at the moment, and I wonder whether it should return `[IdentityTransformation]` or not?)

**Comment by markuspf** [comment]
According to the documentation `Intersection` should only be applied to Collections, so the "no method found" is in accordance with the documentation (and any of the changes seem to introduce more generality than allowed)

**Comment by markuspf** [comment]
The code for `Intersection` works for lists though.

**Comment by james-d-mitchell** [comment]
Ok, the idea of adding a more general method is no good. 

I still think that `Intersection(D, []);` should be made to work, especially since if the second argument is not empty it works, and also if we do `Union(D, []);` or `Union([], D);`, then this works. 

To sum up, I think your PR is good, and should be merged.

**Comment by markuspf** [comment]
So the question is whether one would want to intersect a collection and an inhomogeneous list, in which case we'd still need to install at least the methods for that as far as I can see...

**Comment by james-d-mitchell** [comment]
I think it only makes sense to intersect a collection and an inhomogeneous list if the entries in the list can actually be compared (and sorted). Is there any way to detect this? If not, then I suggest merging this PR as it currently is.

**Comment by markuspf** [comment]
good point actually @james-d-mitchell.

**Pull request merged**
