### PR TITLE
8th HPC-GAP sync PR

### PR DESCRIPTION
**Pull request by fingolfin**
This PR once more reduces diffs between the GAP and HPC-GAP kernel.

### CODE REVIEW

**Comment by markuspf** [comment]
Is this suppsed to be reviewed/merged or should it have the "DO NOT MERGE" label for the time being?

**Comment by fingolfin** [comment]
It is supposed to be reviewed. What gives a different impression? Did I forget to remove some TODO somewhere, or is there some breakage, or ?

**Comment by markuspf** [comment]
The fact that there's no comment on the PR, and it looked to me as if you were still adding commits to it

**Comment by fingolfin** [comment]
I added a description. And yeah, when I initially opened this PR, I briefly afterwards added some more commits. But further changes will go into new PRs (see also #1282 for a preview of that).

**Pull request merged**
