### PR TITLE
Fixing some bugs in the creation of semigroups

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This pull request includes the following:

* fixes some bugs in the creation of semigroups, namely
    * if a semigroup ideal was passed as an argument to any of `Semigroup`,
`Monoid`, `InverseSemigroup`, or `InverseMonoid`, then the entire ideal was used as
a set of generators.

   * removed duplicate generators from Rees 0-matrix semigroups.

* corrects some of the documentation for partial permutations. Thanks to @cdwensley for pointing these out.

* Adds `ViewString` methods for elements of Rees matrix and 0-matrix semigroups

* Updates the `ViewString` and `PrintString` methods for Green's classes, so that they are more informative (indicating the type of the class, and the representative, not only the representative as was previously the case).

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thanks - Travis CI shows that `reesmat.tst` now works, and the manual builds. I am a bit puzzled though since I can't see yet which of the changes is responsible for that.

**Comment by james-d-mitchell** [comment]
the last two commits fix the issue. The previous ones are not related. Hopefully everything is ok now!

**Comment by alex-konovalov** [comment]
Thanks! BTW, for the stable should I just retain the previous version of Semigroups package?

**Comment by alex-konovalov** [comment]
I think this could be merged. @james-d-mitchell would you mind to edit the title and description of this PR to make it more informative, please?

**Pull request merged**
