### PR TITLE
Key dependent operation

### PR DESCRIPTION
**Pull request by bh11**
add setter and tester operations for KeyDependentOperations

This should make it easier to handle the problems raised in #412 and #511. 

In the long run, it might be a good idea to "undocument" the Computed… attribute itself, and maybe replace it by a dictionary object.

This PR also fixes a potential problem when computing a value, the Computed… attribute gets changed (because the called method computed other attribute values on the way, etc).

### CODE REVIEW

**Comment by bh11** [comment]
P.S. I might also add a binary search, somehow hurts to see a linear search in a sorted list.

**Comment by markuspf** [comment]
This seems like a prime application for the caching framework that @fingolfin was suggesting (also in view to HPC-GAP merge)

**Comment by hungaborhorvath** [comment]
Ah, so the syntax would be 
````
HasSylowSubgroup(G, 2); 
````
and 
````
SetSylowSubgroup(G, 2, subgroup);
````
Is that right?

**Comment by hungaborhorvath** [comment]
BTW, I find these as excellent and very useful functions, thank you very much for the effort. 

Have not tested it, yet, though.

**Comment by bh11** [comment]
@hungaborhorvath Yes, that's the syntax. There's an example in the manual section.

**Comment by fingolfin** [comment]
This is a very nice idea. I also agree with @bh11's remarks on the `Computed...` attributes. As to the binary search: This is implemented by `PositionSorted` resp. `PositionSet`, perhaps they can be used (or perhaps they are already? I have not yet looked at the patch here itself, sorry).

BTW, if you are willing, it would be very nice if you could add a small test case for this. Nothing fancy -- just a few lines testing the new feature briefly. They could either go into the existing manual example, or be part of a (possiblye new) `tst/testinstall/*.tst` file.

**Pull request merged**
