### PR TITLE
Change #include <src/foo.h> to #include "foo.h"

### PR DESCRIPTION
**Pull request by fingolfin**
The main reason we used the former since the HPC-GAP merge was to allow us to override GAP headers with modified headers for HPC-GAP during compilation. But now the kernel header files all have been merged, so this is no longer necessary.

We also change <gen/config.h> back to "config.h", and adjust the build system suitably.

Finally, we rename our util.h to utils.h, to avoid a conflict with the BSD system header <util.h>.

### CODE REVIEW

**Comment by fingolfin** [comment]
Unfortunately this PR is a bit messy to review, as tons of `<src/foo.h>` -> `"foo.h"` changes drown out the other stuff. I could split that commit, but then the first commit would not compile correctly, which is annoying when bisecting. So for now, here are the files which received other changes:
* `Makefile.rules`
* `cnf/gac.in`
* `src/compiler.c` (to adjust the C code generation)

**Comment by fingolfin** [comment]
Compiling `io` with HPC-GAP currently fails, because the files in `src/hpc/` cannot include files from `src`. To workaround this, we could symlink all header files into `builddir/bin/GAPRACH/` (next to `config.h`).

**Comment by fingolfin** [comment]
So, I cheated and added a commit to set CPPFLAGS, which hopefully will allow `io` to compile. 

To ensure compatibility with `io` and other packages with kernel extensions, the only option I see is adding those symlinks I mentioned above. But I am very reluctant to do that: It is very easy to mess this up; also, if we remove or rename source files, those symlinks would stay around, unless we took great care to have the build system clean them in turn. This sounds like complexity I'd rather avoid.

The only alternative I can think of right now is to gear up things a notch and finally update the build system of autoconf based packages to not require all that trickery in the first place. Ideally this would only affect `ac_find_gap.m4`, at least for now; deeper changes could still come later, but if just `ac_find_gap.m4` has to be changed, I am hopeful that we can adapt a majority of affected packages very quickly.
(Bigger changes for later: well, e.g. `ward` should be used when building HPC-GAP kernel extensions... of course there are C++ kernel extensions, and `ward` does not support those. Fun! :-(

**Comment by fingolfin** [comment]
Oh, to further complicate things, the new `ac_find_gap.m4` should of course still support GAP 4.8, so that new packages releases can be made now, before GAP 4.9 is out.

That in turn means I have to add a way for packages to reliably and cleanly detect the new build system. And all extra information they might need, including things like the correct include paths...

This could be done as in issue #275 (via pkgconfig and/or a `gap-config` script).

**Comment by fingolfin** [comment]
Another approach for solving this would be to change files in `src/hpc` to add `../` to their `#include` statements, i.e. `#include "../system.h"`, which would have the added benefit that it works correctly in many addition circumstances, e.g. also with installed headers.
Without it, we'll always have to be very careful about which include paths we specify...

Of course the drawback of this is that moving files between `src` subdirs of `src` becomes slightly more tedious. But that should be a rare event, and anyway, it'd still be quite easy to do.

**Comment by markuspf** [comment]
Do we still want to do this? If so @fingolfin would have to rebase this.

**Comment by fingolfin** [comment]
I do think we still want to change the way we do `#includes`, but given the nature of this PR, I cannot update it all the time, as virtually every change is going to break it :-).

Also, we could do something slightly different: change `#include <src/FOO.h>` to ``#include <gap/FOO.h>` -- though then we need to ensure these headers are found, say via a symlink `bin/GAPARCH/gap` -> `src`. Alas, this feels a bit hacky.

Or we do as this PR originally suggests, and use `#include "FOO.h"`. But then we need to deal with the problem of files in `src/hpc/`. I thought we could address that by changing those files to use `#include` directives with relative paths, but that doesn't work, because the relative paths are always resolved relative to the `.c` file.

This means that if we want to go back to using `#include "FOO.h"`, then we need to adjust packages to set the proper `-I` paths (at least for any package that we want to be buildable against HPC-GAP). This in turn could be done for all package using autoconf in one go by adjusting their shared `.m4` file(s).

**Comment by fingolfin** [comment]
While I still want to do this on the long run, it doesn't make sense right now to keep this PR open.

**Pull request closed without merging**
