### PR TITLE
FIX: RepresentativeAction for Sn/An on elements

### LINKED ISSUE #1515: Error when calling Irr for permutation group
The following happens in GAP 4.8.7 as well as in the current master branch,
without packages.
```
gap> GAPInfo.Version;
"4.8.7"
gap> s10:= SymmetricGroup( 10 );;
gap> Irr( Stabilizer( s10, [ 1 .. 3 ], OnSets ) );; # this works
gap> Irr( Stabilizer( s10, [ 2 .. 4 ], OnSets ) );; # this does not work
Error, List Element: <list>[2] must have an assigned value in
  img := opr( img, S.transimages[bimg[1]] )
 ; at /users/sam/gap/gap4r8/lib/ghomperm.gi:108 called from 
ImageSiftedBaseImage( S, OnTuples( BaseStabChain( S ), elm ), S.idimage, 
 OnRight ) at /users/sam/gap/gap4r8/lib/ghomperm.gi:1008 called from
ImagesRepresentative( InverseGeneralMapping( hom ), elm 
 ) at /users/sam/gap/gap4r8/lib/ghomperm.gi:1101 called from
PreImagesRepresentative( hom, conj 
 ) at /users/sam/gap/gap4r8/lib/clashom.gi:2786 called from
TFCanonicalClassRepresentative( D.group, [ el ] 
 ) at /users/sam/gap/gap4r8/lib/ctblperm.gi:62 called from
D.identification( D, el 
 ) at /users/sam/gap/gap4r8/lib/ctblgrp.gi:1647 called from
...  at line 4 of *stdin*
you can 'return;' after assigning a value
brk> 
```

### PR DESCRIPTION
**Pull request by alex-konovalov**
This backports to the stable-4.8 branch commit 8c82ee3da2f845c555f3d3012f37b4b6b072410a by @hulpke 

The code change applies straightforwardly. To add the test, I had to do this in `tst/teststandard/grpperm.tst` since there is no `tst/testinstall/grpperm.tst` in GAP 4.8.

Fixes #1515

### CODE REVIEW

**Comment by alex-konovalov** [comment]
No Travis CI tests were triggered - why?

**Comment by markuspf** [comment]
It builds here: https://travis-ci.org/markuspf/gap/builds/261276800 so you could do a minimal edit and force-push to try and restart the build

**Comment by fingolfin** [comment]
Probably because you submitted this to the wrong branch at first, and changed the target branch after creating the PR; I assume this confused Travis. Just do as @markuspf

**Comment by alex-konovalov** [comment]
Even without minimal edits: just `git commit --amend` without any changes followed by `git push --force` is enough to kick off Travis.

**Comment by fingolfin** [comment]
This looks good to me. The AppVeyor errors are unfortunately normal for the stable branch.

**Pull request merged**
