### PR TITLE
kernel: add NEW_PLIST_IMM and NEW_PLIST_MUT helpers

### PR DESCRIPTION
**Pull request by fingolfin**
This PR adds two `NEW_PLIST` wrapper functions: `NEW_PLIST_IMM` has the same signature as `NEW_PLIST`, but ensures that the resulting plist is immutable, currently by adjusting the TNUM (i.e. OR-ing it with `IMMUTABLE`), in the future it might instead set or clear a suitable object flag.

The second helper, `NEW_PLIST_MUT`, takes an additional boolean (0 or 1) as its first argument `mut`, which indicates whether the resulting plist should be mutable (`mut=1`) or immutable (`mut=0`). This is used in code where a new plist is created whose mutability depends on some external factors, e.g. it should match that of another object.

(Oh yeah: This PR contains some code from PR #1571)

One obvious bad thing about this PR is that the naming of the two helpers is somewhat in conflict: Based on the names, one could rightfully expect the second helper `NEW_PLIST_MUT` to be just like the first, except that it always forces a mutable plist, but it isn't. I don't expect us to merge the PR with this conflict, though; but there are several ways to resolve them, and I though I'd solicit some feedback before wasting time on implementing one of them:

1. We could rename the second helper to e.g. `NEW_PLIST_WITH_MUTABILITY` -- but I'd kind of prefer to keep a short name.
2. We could get rid of the first helper, and replace  `NEW_PLIST_IMM(tnum, len)` invocations by `NEW_PLIST_MUT(0, tnum, len)`. Does this have drawbacks? (perhaps that one might not immediately be able to guess that the second code is creating an immutable plist; also, one could accidentally permute the arguments, a possible source of errors -- and one of the reasons why I really would have liked to introduce a `BOOL` type, see #1883, but it seems nobody either likes or cares about this approach).
3. Rename the first helper, to... ?
4. Others?

I am kind of tempted to just go with approach 2, it is trivial to implement with a quick `sed` invocation. The main reason I did not yet do it is that reverting it again *would* be work, so I'd rather first get feedback.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I do prefer the IMM version, as making immutable lists is fairly common and nice to be able to do simply.

**Comment by ChrisJefferson** [comment]
New_plist_maybe_imm ?

**Comment by markuspf** [comment]
I don't really like the `NEW_PLIST_MUT` approach, with the first parameter being mutability, because as you say it's not very readable. One could address this by using `BOOL`, but then again what is `true` in that position supposed to mean?

I think I prefer the explicit-but-long-name variant `NEW_PLIST_WITH_MUTABILITY`

**Comment by fingolfin** [comment]
@markuspf wrote:
> I don't really like the NEW_PLIST_MUT approach, with the first parameter being mutability [...]
Could you turn this into something more constructive? First off: Is this a general objection to having a function which creates an object and sets its mutability in one go? Or just to this particular variant, so e.g.the position of the argument?

If this is just about the position of the argument, then my reply would be: well, putting it first made it by far easiest to convert the code; of course we could refactor, but I see no major gain, this feel like bike shedding.

If it is in general about having an argument for setting mutability: OK, so what alternative(s) would you prefer? The only one I can think of is to add a second like, like
```gap
  list =  NEW_PLIST( T_PLIST, len );
  SET_PLIST_MUTABILITY( list, mutable );
```
which of course would work, I guess (esp. when/if we move mutability from the TNUM into an OBJ_FLAG), but is slightly less efficient than the current code in this PR (as the new object is briefly mutable, and changing it to immutable requires touching  the tnum field, and also the region of the object in HPC-GAP.

So speaking from a purely pragmatic POV, having `NEW_PLIST_MUT` (or `NEW_PLIST_WITH_MUTABILITY`) seem both easier to do (I mean... I already did it), and also potentially more efficient. The only arguments against I understood so far seem to be purely subjective ("don't like it"), which is impossible to argue against :-(.

So right now, I see these options, but am open to concrete, constructive suggestions for furhter:
1. we merge this as-is
2. rename `NEW_PLIST_MUT` to `NEW_PLIST_WITH_MUTABILITY`, then merge
3. discard this PR, and resolve those `IMMUTABLE` flags in a different way.

I can certainly live with 3, too, but it'd be a bit sad, because I think this PR is a nice step-stone towards an (IM)MUTABLE object flag, in the sense that the main goal of this PR is to reduce the number of places that would have to be touched if / when we w replace the `tnum | IMMUTABLE` approach.

**Comment by fingolfin** [comment]
BTW, small stat: I did, `git grep -w IMMUTABLE src | wc -l`, and got:
* on master: 568 hits
* in this PR: 481 hits (i.e. 87 less)
* on master, after running the script from PR #1571: 324
* in this PR, after running the script from PR #1571: 237
* with PR #1571 (which contains this PR) plus running the script:  223

Granted, there are several dozen more lines containing `IMMUTABLE` which can be simply be deleted if we remove `IMMUTABLE`, but still, this PR is getting rid of roughly 1/5 to 1/4 of all the `IMMUTABLE` occurrences. And of course nothing stops us from further refactoring later (and replacing `NEW_PLIST_MUT` resp. `NEW_PLIST_WITH_MUTABILITY` with something better then)

**Comment by ChrisJefferson** [comment]
I think (@markuspf can disagaree) that we are all happy with the current PR, except for the naming of NEW_PLIST_MUT, which just looks too symmetric with NEW_PLIST_IMM (which I do like the name of)

**Comment by markuspf** [comment]
Yes, I agree with what @ChrisJefferson says: I am happy with the PR, *except* for the naming of `NEW_PLIST_MUT` (in conjunction with having `NEW_PLIST_IMM` *and* the "obscure" parameter).

The most constructive I came up with was renaming `NEW_PLIST_MUT` to `NEW_PLIST_WITH_MUTABILITY` (i.e. following one of your less preferred suggestions).

**Comment by fingolfin** [comment]
Rebased and changed to use `NEW_PLIST_WITH_MUTABILITY`

**Pull request merged**
