### PR TITLE
Change "make doc" to use --quitonbreak and to work on HPC-GAP

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
My only comment (and this can be for another patch) is if we should just stop using workspaces at all during building, is it worth the messing around (and it also makes running things in parallel trickier)

**Comment by fingolfin** [comment]
Yeah, I also wondered whether it is worth it. For me, it brings little gain, but then again I have new SSD in my laptop...
For `make doc’ we use he workspace 8 times, which adds up - but then again, I think running GAPDoc actually dwarves this. But I wonder if we could actually reduce this to a single GAP session, or at most two.

OTOH, the workspace is stored in `builddir/doc`, so I think there is not really a parallelization issue...

**Comment by fingolfin** [comment]
I now made PR #1448, which is probably the better alternative.

**Comment by fingolfin** [comment]
Closing this in favor of #1448

**Pull request closed without merging**
