### PR TITLE
TestPackage function and 'testpackage' make target

### PR DESCRIPTION
**Pull request by alex-konovalov**
This is in response to the issue #637 by @ChrisJefferson.

This PR adds two ways of testing a GAP package.

The first is called from the shell using
```
make testpackage PKGNAME=packagename
``` 

This is as maximally close to the setting in which we run regression tests as possible - the difference is of course in the local version of GAP and the selection of package. Otherwise, it will run the test three times, each in a new GAP session (without/default/all packages), with assertion level 2, and will produce three log files in the dev/log directory.

The second may be called from the GAP prompt via
```
TestPackage("pkgname");
```
In this case assertion level will not be changed, and the test will run only once in the current GAP session. 

I've labeled this "DO NOT MERGE" since I should also document this before merging, but I'm submitting the code to get some feedback.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Example: testing a package with .g file using 'make testpackage':

```
Mac-0c4de9c1b942:gap-fork alexk$ make testpackage PKGNAME=circle
mkdir -p dev/log
( echo 'SetAssertionLevel( 2 ); ReadGapRoot( "tst/testutil.g" ); \
            SaveWorkspace( "wsp.g" );' | ./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  )
true
( echo 'CreatePackageTestsInput( "testpackage.in", \
            "dev/log/testpackage1", \
            "./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  -L wsp.g", "false", "circle" );'\
            | ./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  -L wsp.g > /dev/null )
( chmod 777 testpackage.in; ./testpackage.in; rm testpackage.in )
Testing circle 1.5.4, test=/Users/alexk/GITREPS/gap-fork/pkg/circle/tst/testall.g, all packages=false
( rm wsp.g )
( echo 'SetAssertionLevel( 2 ); ReadGapRoot( "tst/testutil.g" ); \
            SaveWorkspace( "wsp.g" );' | ./bin/gap-default64.sh -b -m 100m -o 1g -q -x 80 -r  )
true
( echo 'CreatePackageTestsInput( "testpackage.in", \
            "dev/log/testpackageA", \
            "./bin/gap-default64.sh -b -m 100m -o 1g -q -x 80 -r  -L wsp.g", "auto", "circle" );'\
            | ./bin/gap-default64.sh -b -m 100m -o 1g -q -x 80 -r  -L wsp.g > /dev/null )
( chmod 777 testpackage.in; ./testpackage.in; rm testpackage.in )
Testing circle 1.5.4, test=/Users/alexk/GITREPS/gap-fork/pkg/circle/tst/testall.g, all packages=auto
( rm wsp.g )
( echo 'SetAssertionLevel( 2 ); ReadGapRoot( "tst/testutil.g" ); \
            SaveWorkspace( "wsp.g" );' | ./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  )
true
( echo 'CreatePackageTestsInput( "testpackage.in", \
            "dev/log/testpackage2", \
            "./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  -L wsp.g", "true", "circle" );'\
            | ./bin/gap-default64.sh -b -m 100m -o 1g -A -q -x 80 -r  -L wsp.g > /dev/null )
( chmod 777 testpackage.in; ./testpackage.in; rm testpackage.in )
Testing circle 1.5.4, test=/Users/alexk/GITREPS/gap-fork/pkg/circle/tst/testall.g, all packages=true
( rm wsp.g )
```

**Comment by alex-konovalov** [comment]
Example: testing a package with .tst file using `TestPackage`:
```
gap> TestPackage("cohomolo");
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  cohomolo 1.6.4 (Computing Cohomology groups and Schur Multipliers)
by Derek Holt (http://homepages.warwick.ac.uk/staff/D.F.Holt/).
Homepage: https://gap-packages.github.io/cohomolo
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
testall.tst
GAP4stones: 119
#I  No errors detected while testing package cohomolo version 1.6.4
#I  using the test file `/Users/alexk/GITREPS/gap-fork/pkg/cohomolo-1.6.4/tst/testall.tst'
```

**Comment by markuspf** [comment]
This looks to me.

**Comment by alex-konovalov** [comment]
Thanks @markuspf. I've now added the documentation, so I think this is ready for merge.

**Pull request merged**
