### PR TITLE
Remove unused sparse list code

### PR DESCRIPTION
**Pull request by markuspf**

### CODE REVIEW

**Comment by frankluebeck** [comment]
Actually, I have private code that uses these files (and slightly extends the functionality). And I know that other people at least know about this code (but I don't know if anyone else uses it).

If it's just me, I could make a copy of the files until proper sparse matrix code is available.

**Comment by markuspf** [comment]
I might be getting a bit overzealous here trying to re-establish modularity of the library (the goal being to make packages if possible).

But to be less disruptive, I could do the following instead

* not remove the code, (and maybe display a warning if it's used to see whether people are using it).
* copy the code into a package for (sparse) matrix functionality, which would of course then require me to document it properly
* once it is in an acceptable state in a released package, I can properly remove it from the library.

**Comment by fingolfin** [comment]
I am not sure that's worth the effort in isolation. I mean, yeah, perhaps do it eventually, but for now there are more important things to fry. For now, we could just add a note to these each of these files documenting their status; and perhaps insert warnings into some of the functions they define which tell users they may go away. Perhaps asking people using them to contact us if they want them toi stay. This way, we might learn who uses them, and how best to help them moving forward.

The warnings could also be printed upon loading the files.

**Comment by stevelinton** [comment]
It was my code from long ago. Reviewing it now, it's not terrible, and the data structures it uses were designed to be reasonably easy to manipulate from the kernel.

On the other hand, if you start with the new vector matrix interface you could do a much simpler and probably faster implementation of sparse vectors designed to implement that interface.

I feel no particular attachment to the code and I'd be happy to see it moved to a package or abandoned if that seems best.

**Comment by ChrisJefferson** [comment]
Another option would be to build a simple sparse list interface on top of the hash table in datastructures (in fact, it's almost completely there already).

**Comment by dimpase** [comment]
This code would be useful in (eventual) implementation of conversion of dense matrices into sparse ones. If it's just removed it would be easy to forget about its existence all together...

**Comment by fingolfin** [comment]
@dimpase I have known about this code for years, back then I studied it a lot, and tried using it. I've not really looked at it since then, but I also have not forgotten it. It is indeed quite keenly in my mind whenever I think about the matrix objects stuff. So I don't think there is any risk of it being forgotten. At least not a higher risk anyway: You might argue that it is already "forgotten", since it's disabled code in the GAP library which most people never knew about, and have no chance of ever learning about ;-).

@ChrisJefferson That would indeed be another option, but one with quite different performance characteristics. It would be interesting to have multiple sparse matrix implementations, to be able to benchmark them, and possibly provide them all to users (unless benchmarks clearl show one implementation to be strictly inferior to another, of course)

**Comment by markuspf** [comment]
I will close this and not merge it, I have plans for the matrices package which, time permitting, we should go over at the GAP-Sage days in January. As soon as there is sparse matrix code in that library I will redo this removal.

**Pull request closed without merging**
