### PR TITLE
Hpcgap default

### PR DESCRIPTION
**Pull request by ChrisJefferson**
(Hopefully) a successful merge of master into hpcgap (let's see what travis says).

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@ChrisJefferson : thanks! Travis test was terminated on `relation.tst` running too long without any output, two other tests passed well.

**Comment by markuspf** [comment]
On Sun, Mar 22, 2015 at 01:34:00PM -0700, Alexander Konovalov wrote:
> @ChrisJefferson : thanks! Travis test was terminated on relation.tst running
> too long without any output, two other tests passed well.
> 

The real question is: Why did this time out now? Is it a coincidence or
another regression?

I restarted the travis tests to see whether this will fail again.

**Comment by alex-konovalov** [comment]
@markuspf Thanks. Interestingly, the pattern repeats, but `relation.tst` runs fine in `testtravis` - perhaps some interaction between several tests. Hope someone will be able to fetch the PR and test locally - I can't do it at the moment.

**Comment by markuspf** [comment]
On Sun, Mar 22, 2015 at 02:07:08PM -0700, Alexander Konovalov wrote:
> @markuspf Thanks. Interestingly, the pattern repeats, but relation.tst runs
> fine in testtravis - perhaps some interaction between several tests. Hope
> someone will be able to fetch the PR and test locally - I can't do it at the
> moment.

I can't reproduce this failure on my laptop at all. the relation.tst test
returns immediately, even when run in the context of testinstall.g

**Comment by markuspf** [comment]
Running it a couple of times I can get the test to hang in random places. Looks like a deadlock of some sort.

**Comment by ChrisJefferson** [comment]
The question is (if you can get it to happen) did it used to happen before this commit? Also, can you get a backtrace on the deadlock (I'm having trouble getting it to happen).

**Comment by markuspf** [comment]
On Sun, Mar 22, 2015 at 03:29:50PM -0700, Christopher Jefferson wrote:
> The question is (if you can get it to happen) did it used to happen before this
> commit? Also, can you get a backtrace on the deadlock (I'm having trouble
> getting it to happen).

If I run hpcgap-default 100 times using 

```
# echo 'Read("tst/testinstall.g"); quit;' | sh bin/gap.sh
```
I cannot get it to hang. Running #115 i can hang it almost every time. The
main thread seems to hang in

```
#5  0x0000000800a1abd1 in _pthread_rwlock_wrlock (rwlock=rwlock@entry=0x81fdb8
<RNameLock>) at /usr/src/lib/libthread_xu/thread/thr_rwlock.c:405
#6  0x00000000004892d5 in LockNames (write=1) at gen/records.c:81
#7  LockNames (write=1) at gen/records.c:104
#8  RNamName (name=0x4ef5698 "dummy") at gen/records.c:142
#9  0x000000000048959e in RNamObj (obj=<optimized out>) at gen/records.c:246
#10 0x0000000000549c48 in ExecAssRecExpr (stat=440) at gen/vars.c:1760
```

Unfortunately debugging threads using GDB on DragonFly is broken at the
moment, so I can't look at the other threads it seems. The full backtrace is
of course a whole lot longer.

Markus

**Comment by ChrisJefferson** [comment]
Thanks Markus, that was enough to find the problem (or at least, at least one bug!)

**Comment by markuspf** [comment]
@ChrisJefferson would you mind sharing what the problem was?

**Comment by ChrisJefferson** [comment]
@markuspf There is some locking (which has to be manually locked and unlocked) in the functions which map record names to strings. I added new code to the record name to error when identifiers longer than 1023 characters occur, but didn't notice that in HPC-GAP I had to make sure to release the lock in this case.

**Pull request merged**
