### PR TITLE
Remove unused matrix recognition code

### PR DESCRIPTION
**Pull request by markuspf**
This code was commented out, and removing it does not cause any functional change. If there is still interest in this functionality we should move it into a package.

### CODE REVIEW

**Comment by fingolfin** [comment]
Interesting. This looks a bit like an early precursor to the group recognition project...

In principle, even GAP library that is not loaded by default could be in use by packages, which can e.g. use `ReadLib` to directly load certain functions. However, I checked the latest package distro, plus various other packages I have my hands on, and none does that. (I checked both by grepping for `ReadLib`, as well as the basenames of all files this PR removes).

Therefore, this PR seems fine to me. Good catch, Markus!

Next, you could investigate removing readsl.g and the releated sparse list/matrix/vector code (of course one could also consider preserving it, and makign it official, say with a MatrixObj interface; but perhaps that, too, should better be done in a package?)

**Comment by alex-konovalov** [comment]
@fingolfin Are there any other `ReadLib` calls in packages or any other files in the library that are exist but are not read by default? I know at least of `lib/demo.g` which I use time to time for running demos.

**Comment by frankluebeck** [comment]
Indeed, this experimental code should not have been commited to the GAP library but put into a package instead. Development stalled before the code became functional, and so its loading was disabled at some stage.

I think it is safe to remove this. When doing so use a sensible commit message mentioning the authors of that code. Then it is will be easy to find and to dig out that code if someone wants to look at it later.

**Comment by fingolfin** [comment]
@alex-konovalov As you say, `ReadLib` is used by three pacakges to read `lib/demo.g`. The only other `ReadLib` call is in `Browse`, which uses it to read the `conwdat*.g`, but those are also being read by `ReadLib` calls in the GAP library.

@frankluebeck Of course I agree that a good commit mesage should be used (that shold *always* be done, after all ;-). Alhough I am not sure whether one would really search that code by the name of its authors...? Anyway, even in that case, I think I thould point to the powerful `git log -G<regex>`, which can be used to find commits which add/remove lines matching the given regex. Thus e.g. `git log -G"Copperman"` will also find this commit. So, even if the commit message is not perfect, this way one can find most commits if one just knows a little bit about them.

**Comment by markuspf** [comment]
This PR now also removes the sparse list code.

It also adds a file DELETED to keep track of deleted bits of the library for the time being.

**Comment by markuspf** [comment]
I decided it would be a bit sneaky to remove unrelated chunks of the library in one PR, so I split this up into one PR  that removes the experimental code by Cooperman and Murray (#312) and one that removes Linton's the sparse list code (#323).

**Comment by fingolfin** [comment]
There is no mess here, nothing to be sorry about :). Though you can also remove your (now obsolete) comments, if you think they are distracting (and afterwards, we could remove this very comment, too ;-).

**Comment by ChrisJefferson** [comment]
This patch looks OK to me and uncontroversial -- as @fingolfin says, while technically someone could be reading this code, it's never being loaded by default. let's go for it!

**Pull request merged**
