### PR TITLE
Semigroups changes

### PR DESCRIPTION
**Pull request by mtorpey**
A few changes towards allowing the Semigroups package to run in HPC-GAP

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Please do not merge this pull request - tests are failing, we will help to investigate.

**Comment by markuspf** [comment]
This looks as if it needs some careful combing through the library for calls to FamiliesOfGeneralMappingsAndRanges and putting in the appropriate atomic read/readwrite statements.

**Comment by markuspf** [comment]
Right, actually it only needs one change it seems: https://github.com/markuspf/gap/tree/pr-45
I don't know whether this locking is a bit too generous though.

**Comment by alex-konovalov** [comment]
Thanks - the link you have just points to the branch, how to see the actual change?

**Comment by markuspf** [comment]
If I had actually pushed the changes, you'd be able to see the commit. It should now be [there](https://github.com/markuspf/gap/commit/761b6a5311abcfc3b08efe0d96995370248221c5)

**Comment by alex-konovalov** [comment]
I think locking is definitely not wrong, since `FamiliesOfGeneralMappingsAndRanges`, defined as a mutable attribute of a family, is a list that stores at the odd positions the families of general mappings with source in the family `Fam`, and at the even positions the families of ranges of the general mappings. Therefore, if e.g. one would make it an atomic list, another thread may see an inconsistent state when one of the entries is changed and another - not yet. 

There are actually two cases where `FamiliesOfGeneralMappingsAndRanges` used in the library, not just one:
* `GeneralMappingsFamily` in `mapping.gi`
* `CreateIsomorphicPcGroup` in `pcgsperm.gi`

**Comment by markuspf** [comment]
The case in mapping.gi has already been covered by @mtorpey's PR, I just added the additional case which made the tests fail.

**Pull request closed without merging**
