### PR TITLE
Hpcgap merge oct 2015

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Regular master -> hpcgap merge.

Nothing particularly eventful. Removal of some occurrences of Systrcmp and Systrncmp, and also locking the command line region in FactInt (not convinced FactInt should be digging around reading the command line history looking for possible factors, but that's a separate issue).

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Looks good to me, but bugfix.tst failed in Travis - perhaps worth to check that before merging. I haven't understood a bit regarding the FactInt package - it's not a part of the repo. Do you mean that you've tweaked your local copy of it to make tests running?

**Comment by ChrisJefferson** [comment]
FactInt is a function in GAP which factorises integers (long existing, but some other change made it get called differently, and hit a long-standing bug in hpc-gap). It does a dodgy hack where it scans the user's command line history for numbers.

**Comment by ChrisJefferson** [comment]
There was a bug which bugfix.tst was shaking out. Basically, @frankluebeck 's recent patch which special-cased iterators created from records didn't handle those records being atomic records (not unreasonably!)

For now, I have fixed this by changing ```CALL_1ARGS( STD_ITER, list ) == True``` to ```CALL_1ARGS( STD_ITER, list ) == True && IS_PREC_REP(list)``` in HPC-GAP. We could in principle also apply the optimisation when we have atomic records, but this was the easiest way to get the code working again.

**Comment by alex-konovalov** [comment]
Still can't see in diffs where is the "locking the command line region in FactInt" - could you please point me there?

**Comment by ChrisJefferson** [comment]
Woops woops!

The edit was in the 'factint' package, which I had put in my package directory. Edited it without noticing where the file was!

So, long term the factint package (like many packages) needs making hpc-gap compliant. The fact I've got many packages in my pkg directory would explain why I haven't seen this error before. Basically, just ignore that whole issue :)

**Pull request merged**
