### PR TITLE
Merge master into hpcgap-default

### PR DESCRIPTION
**Pull request by fingolfin**
This PR merges master into hpcgap-default.

This was a bit tricky to pull off, as in the past we merged some HPC-GAP changes into master, only to later revert them. This caused the backmerge to pull those reversal changes in, which then broke HPC-GAP; so I had to painstakingly revert those. Lots of other things caused pain, too.

Despite all, the resulting merge suffers from regressions. For starters, consider this:
```gap
gap> g := SL(2,5);;
gap> f := FrattiniSubgroup(g);
Error, List Element: <list>[2] must have an assigned value in
   called from
Error, <lvars> must be an lvars (not a high variables bag) in
   called from
img := opr( img, S.transimages[bimg[1]] ); at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/ghomperm.gi:108ImageSiftedBaseImage( stb, OnTuples( iter!.bimg, stb.labels[k] ), iter!.img * stb.labelimages[k], OnRight
 ) at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/ghomperm.gi:142 called from
iter!.NextIterator( iter ) at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/coll.gi:995 called from
sch <> One( sch ) at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/ghomperm.gi:986 called from
context := ParentLVars( context ); at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/error.g:57WHERE( ParentLVars( ErrorLVars ), depth, ErrorLVars ); at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/error.g:81 called from
OnBreak(  ); at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/error.g:229 called from
img := opr( img, S.transimages[bimg[1]] ); at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/ghomperm.gi:108 called from
ImageSiftedBaseImage( stb, OnTuples( iter!.bimg, stb.labels[k] ), iter!.img * stb.labelimages[k], OnRight
 ) at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/ghomperm.gi:142 called from
iter!.NextIterator( iter ) at /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/coll.gi:995 called from
...  at stream:2
#I  Options stack has been reset
```

One can see two regressions here: First, the FrattiniSubgroup computation fails. Secondly, the error backtrace contains another error message. I think I know what causes the latter, but didn't want to spend more hours of work on this today; for the former, I have absolutely no idea right now as to what went wrong... *sigh*

Another problem is that this shows up during startup:
```
 Loading the library and packages ...
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/galois.gi:503
 atomic TRANSREGION do
                     ^
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/galois.gi:562
 atomic TRANSREGION do
                     ^
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/galois.gi:664
 atomic TRANSREGION do
                     ^
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/hpcgap/gap/lib/galois.gi:819
 atomic TRANSREGION do
                     ^
 Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
```

Clearly this is caused by the recent work on factoring out the transitive groups library. It shouldn't be too hard to fix, but since it is mostly harmless, I did not yet bother.

If anybody would like to help with resolving any of these, that would be most welcome -- either describe the fix here, or feel free to directly commit to my branch.

### CODE REVIEW

**Comment by fingolfin** [comment]
Turned out the problem with the error backtrace was simpler to fix than I thought, so I just did that.

**Comment by mohamed-barakat** [comment]
Congratulations 👍

**Comment by fingolfin** [comment]
@mohamed-barakat that's a bit premature. Nothing has been merged yet :-). I just closed this PR, which was an (in retrospect failed) attempt to make one last merge before the proper integration...

But I really hope we can get the actual hpc-merg done during the SageDays in march!

**Comment by mohamed-barakat** [comment]
I wish you all the luck you need. I am already in urgent need for HPC-GAP to attack a huge enumeration problem. Reimer is kindly preparing a work-stealing environment (as a variation on the existing tasks) for me now.

**Pull request closed without merging**
