### PR TITLE
Miscellaneous changes which avoid using globals for temporary values

### PR DESCRIPTION
**Pull request by fingolfin**
This PR is motivated by issue #811.

### CODE REVIEW

**Comment by hulpke** [comment]
My understanding was that `trans' is supposed to become a package with the next release shouldn't the changes in `trans' go to 
https://github.com/hulpke/transgrp
instead? (I will merge if you make a PR).

**Comment by fingolfin** [comment]
@hulpke OK, I can make a pull request for <https://github.com/hulpke/transgrp>, too.

However, as long as `trans` remains in the main gap repository, we must update it, too, for everybody who does not have `transpkg`.

In addition, AFAIK nobody has made any attempts to make `transpkg` compatible with `trans` so far, which concerns diffs between the directories `trans` and `hpcgap/trans`.

**Comment by hulpke** [comment]
@fingolfin 
Thank you. I would suggest to remove `trans' now from the main repository and transition to the package version.

What I can see from `git log` is only two changes:
3d10dd976c672c77cd281ddde5943a561f1e7cad
and
bc7f98f5cb2567f5c84cc49dba4eaaf94c2b9d3c
(the second of which concerns whitespace only) that happened after the split into a library. None seems hpcgap related.

**Comment by fingolfin** [comment]
I am happy to track down any changes we (well, most likely *me*) made to `trans` on `master`, and submit them to you as PR.

The HPC-GAP changes are all inside `hpcgap/trans/` -- this directory contains copies of some files in `trans/` but with modifications. Some of these are quite extensive and not particularly nice. But perhaps one can do better -- I'll try to think about it, and perhaps discuss with Reimer and others, and then we can perhaps turn that in to a pull request, too.

**Pull request merged**
