### PR TITLE
Further Info classes cleanup

### PR DESCRIPTION
**Pull request by fingolfin**
This PR ...
* fixes addition of more than two info classes,
* adds support for the `InfoCheckLevel` hotpath to C code generated by the GAP compiler,
* moves INFODATA_* constants to the kernel, so that we can use them from the kernel, instead of hard coding magic constants there;
* gets rid of the global `InfoData` record;
* turns `InfoDoPrint` into a kernel function

I am torn between whether turning `InfoDoPrint` into C code is a good idea or a bad one...; if others dislike it, I am happy to drop that commit again.

My main motivation for this was to get rid of `InfoData`, because IMHO the use of this record to pass a value from `InfoDecision` to `InfoDoPrint` makes the Info code considerably harder to follow.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I haven't read this carefully, I have two broad comments.

1) your new doprint kernel method seems to lack error checking. Now it might be you can never get anything nasty into this code, but the gap version had the advantage it would just error, not go crazy if the wrong type got in.

2) I tried hard when fixing up Info to NOT break InfoData. I knew gapdoc at least was using it (although I have since got a change in there), and I have code which uses it privately. Until my recently clean up, any custom info printer had to use InfoData, as the info you needed wasn't stored anywhere else. Do we want to break any code out there using InfoData?

**Comment by fingolfin** [comment]
1. `InfoDoPrint` can only be called after `InfoDecision` which performs all required validation (it also cannot be called directly by the user, so no chance for bad input creeping in that way). But of course if somebody modified `InfoDecision` and removed all error checks from there, we'd run into problems. If we are concerned about that, we/I can indeed add error checks in. Or just drop the last commit which converts `InfoDoPrint` into a kernel function, as suggested above *shrug*

2. `InfoData` was never documented. And `GAPDoc` was the only package to ever use it. I am confident to bet that virtually nobody other than Frank and you wrote custom InfoHandlers to start with. The fact that nobody ever complained about it being unclear how to correctly use `SetInfoHandler` and `SetInfoOutput` in parallel IMHO kinda supports this. So, yeah, I am absolutely fine "breaking" this code resp. asking people who wrote it to adapt to use documented APIs instead.

By the way, to double check what the documentation says, I just had a look at the manual, where you added `InfoOutput` -- right now it says there: "Returns: nothing" ... :-)

**Comment by fingolfin** [comment]
BTW, you already removed `InfoData.CurrentLevels`, `InfoData.ClassNames`, `InfoData.Handler` and `InfoData.Output`. So I assume when you say "I tried hard when fixing up Info to NOT break InfoData." perhaps you really mean that you tried hard not to break how it is used in GAPDoc and your personal code :-).

**Comment by ChrisJefferson** [comment]
There was some justification behind the bits I kept, they were the bits both Frank and I needed to implement a custom printing function, and seem to be the only bits required.

I'm not opposed to merging this, but there was some reasoning behind it. Might want to at least be sure we document we changed this.

**Comment by fingolfin** [comment]
You mean as in " The undocumented function X was changed, now the undocumented record InfoData is not used anymore; if you are using a custom Info handler which used these undocumented features, you can now use the (documented) function Z." ?

Certainly can do. Also, I recommend we postpone this to 4.10 (i.e. till after 4.9 is branched)

**Pull request merged**
