### PR TITLE
10th HPC-GAP sync PR

### PR DESCRIPTION
**Pull request by fingolfin**
This PR gets rid of another four files in `hpcgap/src`. As always with these PRs, it is probably best to review it commit-by-commit, to see the syncing changes made to files *before* they get removed in the final commit.

Note: I add to add an HPC-GAP implementation of `AssGVarUnsafe`, but what I did there may be wrong, even nonsense. So I'd appreciate if that bit could be closely checked by people who know about it -- in particular @ChrisJefferson who added it to GAP, and perhaps also @rbehrends (as HPC-GAP expert).

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
The `AssGVarUnsafe` is fairly wrong, I'll look at it tonight (I'm not happy with it generally, but we are stuck with something horrible, due to the long-standing semantics of `~` in GAP).

**Comment by fingolfin** [comment]
@ChrisJefferson I see what you mean (at least some of it). When I wrote it, I thought "this is used to assign to `Tilde`, and `Tilde` is a TLS variable anyway". Of course that's total hogwash, so ... :-).

But it does make me wonder: We really only ever use this function to assign to `Tilde`, and that indeed should be thread local. So, before you waste time on implementing `AssGVarUnsafe` "properly" for HPC-GAP, we could also consider replacing it with a dedicated `AssignTilde` function (*if* that makes things simpler).

**Comment by fingolfin** [comment]
And while at it, we should also resolve this FIXME from `gvars.c`:
```
#if !defined(HPCGAP)
    /* stop unauthorised changes to '~'                                    */
    // FIXME: enabling this causes HPC-GAP to crash
    MakeReadOnlyGVar(Tilde);
#endif
```

**Comment by fingolfin** [comment]
Another one: Why do we use `ValAutoGVar( Tilde )`, shouldn't it be `ValGVarTL(Tilde)` ?

**Comment by ChrisJefferson** [comment]
I'm actually working on a much more hardcore fix I should have done originally -- stop pretending tilde is a global variable. Patch arriving tomorrow.

**Comment by fingolfin** [comment]
See PR ##1316 for @ChrisJefferson "hardcore fix"

**Pull request merged**
