### PR TITLE
ci: add gaplint job (trailing whitespace only)

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR adds a CI job using GitHub actions to run gaplint:

https://github.com/james-d-mitchell/gaplint

on `lib/*.gi` and `lib/*.gd` with all of the rules disabled except for the trailing whitespace one. This does not fail for trailing whitespace in manual examples contained inside comments.  The file `.gaplint.yml` is also added, if for some reason it's desirable not to add this, then the same result can be obtained by adding command line args in the `.github/workflows/lint.yml` file. 

## Text for release notes

None

### CODE REVIEW

**Comment by ThomasBreuer** [comment]
Just for curiosity: Why are the files `lib/*.g` left out?

**Comment by james-d-mitchell** [comment]
> Just for curiosity: Why are the files `lib/*.g` left out?

Good question, I just forgot them, will add that now, thanks @ThomasBreuer

**Comment by fingolfin** [comment]
Maybe also cover `hpcgap/lib/*.g*` and `grp/*.g` ?

**Comment by fingolfin** [comment]
... and `lib/hpc/*.g` and `hpcgap/lib/hpc/*.g`. Phew, quite some files :-)

**Comment by james-d-mitchell** [comment]
Added those files too, thanks for the suggestion @fingolfin

**Review by ChrisJefferson — APPROVED** [review]

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
