### PR TITLE
Simplify AppVeyor config; improve "make bootstrap*" targets

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Let's see how this build fares..

**Comment by alex-konovalov** [comment]
Can we in addition see if we can make AppVeyor builds fail in case of diffs? This build has two diffs but did not fail: https://ci.appveyor.com/project/gap-system/gap/build/job/ki8eer6853mf5q7b

**Comment by fingolfin** [comment]
@alex-konovalov that's weird... was it always broken?!? I'll look into it

**Comment by fingolfin** [comment]
There are lots of older builds with the same test failures, and all are marked as "pass" by AppVeyor :-(.

**Comment by fingolfin** [comment]
Downloading the bootstrap files is reaaally slow. However, we might be able to speed that up using their cache feature. It supposedly stores data in the same data center in which the VMs are run, and they say  it can speed up some downloads (unlike Travis, where they say it won't make a difference).

**Comment by fingolfin** [comment]
@alex-konovalov actually it's clear why the errors are not detected: because `make testinstall` and the othr test targets swallow the exit codes, so the make rule always signals success. This seems like a bug to me. But I am not going to chang those Makefile rules now; they all seem problematic to me, but this is beyond th scope of this PR. However, I will try to invoke the testinstall script directly.

**Comment by fingolfin** [comment]
I tried making use of the AppVeyor build cache now, but it doesn't seem to have any effcect. However, I also read somewhere on the AppVeyor support site that it is not populated by PR builds, so we may have to wait till this is merged to know for sure whether it works or not...

**Comment by fingolfin** [comment]
Note that right now, it seems that downloading the full package set takes 10 minutes or so, i.e. a large part of the overall build time... If using the cache does not work, we should consider switching to a minimal package set (just GAPDoc; perhaps also add in io and profiling).

**Comment by fingolfin** [comment]
So, codecov uploads seem to work now, and the whole AppVeyor setup is IMO easier to understand now. Drawback: the failing timeout test now actually leads to a test failure... So if we merge this, AppVeyor 32bit tests will always fail (of course, if we do not merge this, they also will always fail, because our current AppVeyor settings are broken, and so *all* AppVeyor builds fail.

Of course if somebody knows how to fix the timeout code on Win32, we could wait for that fix to land... @ChrisJefferson ? @stevelinton ?

**Comment by ChrisJefferson** [comment]
I tested this on a 32-bit cygwin installed on 64-bit windows 10, and all the tests pass fine, so it might be an appveyor thing (not sure what kind of thing that might be..)

**Comment by fingolfin** [comment]
@ChrisJefferson OK. Unfortunatly, it's rather difficult to debug this on AppVeyor :-/. So I am trying now to simplye disable `timeout.tst` there, let's see if that works.

**Comment by ChrisJefferson** [comment]
Merged. It's important we get back to the tests passing, and this only effects windows (apart from some small, correct, other changes)

**Pull request merged**
