### PR TITLE
Include ./autogen.sh

### PR DESCRIPTION
**Pull request by saraedum**
There is no `configure` if you clone this repository.

### CODE REVIEW

**Comment by fingolfin** [comment]
First off, thanks for your contribution!

These instructions are meant to be usable for people who get a release version of GAP, and which hence most likely should not run autogen.sh (they may not have the required tools). 

I.e. I don't think we should merge this PR as is. Instead, we'll need some text which explains when to run autogen.sh and when not. Like "if you got this from git, run autogen.sh; if you got this from a stable GAP release, do not run it".

Alternatively, we could use a modified README for the release, but that'd require a complication for the release scripts....

**Comment by saraedum** [comment]
@fingolfin Sure, I am used to tars already including the configure. But the ones in the "Releases" here at github do not seem to include this (tried with the 4.9.0 one). Is the 300MB+ download available at https://www.gap-system.org/Releases/index.html a source release?

**Comment by saraedum** [comment]
Oh, I had not seen the header. So the ones at gap-system.org do actually require `./configure; make`.

**Comment by saraedum** [comment]
I just realized that your `README.md` does contain the information necessary to build from a git clone.

**Comment by fingolfin** [comment]
Yeah, it does. So, I think this PR can be closed. However, I am now looking into improving the interaction of README.md and INSTALL.md a bit.

**Pull request closed without merging**
